Repository NervanaSystems/ngraph, pull requests merged in 2018-08, with the labels that each got.

#1285 IntelGPU backend: Convolution operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Ready to merge

#1266 move onehot and reverse op to cuda_emitter
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_emitters.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_emitters.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
Labels: GPU, Ready to merge

#1276 IntelGPU backend: Sum and redeveloped Broadcast operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.hpp
Labels: Ready to merge

#1251 More efficient sum for some cases
  src/ngraph/codegen/compiler.cpp
  src/ngraph/runtime/cpu/cpu_kernel_emitters.cpp
Labels: Ready to merge

#1256 Work around some buggy (and deprecated) rpath directives
  cmake/mkldnn.diff
Labels: Ready to merge

#1293 Minor cmake cleanup
  test/util/CMakeLists.txt
Labels: Ready to merge

#1303 convolution backprop & max pool memory primitive cacheing
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: GPU

#934 Interpreter implementation of batch norm bprop
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/get_output_element.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/batch_norm.hpp
  test/autodiff.in.cpp
  test/util/autodiff/backprop_derivative.hpp
Labels: Fully Reviewed

#1284 Fix SUSE build and run errors
  src/ngraph/codegen/compiler.cpp
  src/ngraph/codegen/compiler.hpp
  src/ngraph/file_util.cpp
  src/ngraph/file_util.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
Labels: Fully Reviewed, bug fix

#1307 Min & Max memory primitive cacheing
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: NvidiaGPU

#1289 Implement trigonometric ops for direct execution.
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/kernel/acos.hpp
  src/ngraph/runtime/cpu/kernel/asin.hpp
  src/ngraph/runtime/cpu/kernel/atan.hpp
  src/ngraph/runtime/cpu/kernel/cos.hpp
  src/ngraph/runtime/cpu/kernel/cosh.hpp
  src/ngraph/runtime/cpu/kernel/sin.hpp
  src/ngraph/runtime/cpu/kernel/sinh.hpp
  src/ngraph/runtime/cpu/kernel/tan.hpp
  src/ngraph/runtime/cpu/kernel/tanh.hpp
Labels: Fully Reviewed

#1287 gpu element op optimize
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
Labels: Fully Reviewed, NvidiaGPU

#1290 softmax & convolution memory primitive cacheing
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_kernel_emitters.cpp
  src/ngraph/runtime/gpu/gpu_kernel_emitters.hpp
Labels: Fully Reviewed, NvidiaGPU

#1292 [Py] Add convolution_backprop_data to API
  python/ngraph/__init__.py
  python/ngraph/ops.py
  python/test/ngraph/test_convolution.py
Labels: Fully Reviewed

#1291 [Py] Add __repr__ to Strides and CoordDiff
  python/pyngraph/coordinate_diff.cpp
  python/pyngraph/strides.cpp
Labels: Fully Reviewed

#1294 Fix first_iteration
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
Labels: Fully Reviewed

#1282 LRN
  src/ngraph/CMakeLists.txt
  src/ngraph/op/lrn.cpp
  src/ngraph/op/lrn.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/lrn.hpp
  src/ngraph/serializer.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1296 CPU Direct Execution: Implement product reductions
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/product.cpp
  src/ngraph/runtime/cpu/kernel/reduce_product.hpp
Labels: Fully Reviewed

#1297 DEX Group Convolution
  src/ngraph/runtime/cpu/builder/convolution.cpp
Labels: Fully Reviewed

#1299 DEX MaxPoolWithIndices
  src/ngraph/runtime/cpu/builder/max_pool.cpp
Labels: Fully Reviewed

#1304 IntelGPU backend: Slice operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1312 Propagate input buffers for passthrough kernels
  src/ngraph/graph_util.cpp
  src/ngraph/op/util/op_annotations.hpp
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
Labels: Fully Reviewed

#1302 Added DEX support for (MaxPool + AvgPool) Backprop op for CPU backend
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/kernel/avg_pool.hpp
  src/ngraph/runtime/cpu/kernel/max_pool.hpp
Labels: Fully Reviewed

#1305 Added DEX execution support for ReluBprop
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/kernel/relu.hpp
Labels: Fully Reviewed

#1309 Upstream for versioning
  doc/sphinx/source/framework-integration-guides.rst
  doc/sphinx/source/frameworks/generic.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/index.rst
Labels: Fully Reviewed

#1314 IntelGPU backend: Select operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#1316 Upstream for versioning
  doc/sphinx/source/framework-integration-guides.rst
Labels: Fully Reviewed

#1317 fix travis build...I hope
  src/ngraph/op/util/op_annotations.hpp
Labels: Fully Reviewed

#1318 IntelGPU backend: BatchNorm operation completly redeveloped
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.hpp
Labels: Fully Reviewed, IntelGPU

#1231 Preallocate intermediate buffers
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
  src/ngraph/runtime/gpu/gpu_memory_manager.cpp
  src/ngraph/runtime/gpu/gpu_memory_manager.hpp
  src/ngraph/runtime/gpu/pass/tensor_memory_reservation.cpp
  src/ngraph/runtime/gpu/pass/tensor_memory_reservation.hpp
  test/gpu_test.cpp
Labels: Fully Reviewed, NvidiaGPU

#1279 nbench: add option to run all models in a directory
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#1328 IntelGPU backend: Code refactored. No algorithms changed.
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#1321 Fix bugs in StaticInitializer and CudaContextManager
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_backend.hpp
  src/ngraph/runtime/gpu/gpu_cuda_context_manager.cpp
  src/ngraph/runtime/gpu/gpu_cuda_context_manager.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
Labels: Fully Reviewed, NvidiaGPU, bug fix

#1332 IntelGPU backend: Allow zero size Shape
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
Labels: Fully Reviewed, IntelGPU, bug fix

#1329 IntelGPU backend: Dot_2x2 operation bug fix
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
Labels: Fully Reviewed, IntelGPU, bug fix

#1331 IntelGPU backend: Greater, Less, Equal operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#1333 IntelGPU backend: Max and Min operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
Labels: Fully Reviewed, IntelGPU

#1330 IntelGPU backend: Sum operation bug fix
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
Labels: Fully Reviewed, IntelGPU, bug fix

#1334 IntelGPU backend: Product operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.hpp
Labels: Fully Reviewed, IntelGPU

#1320 CPU Direct Execution: Implement Pad
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/pad.cpp
  src/ngraph/runtime/cpu/kernel/pad.hpp
Labels: Fully Reviewed

#1322 Broadcast optimization
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
Labels: NvidiaGPU

#1324 Share GPUHostParameters with CUDNNHostParameters
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/cudnn_host_parameters.hpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.cpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.hpp
Labels: NvidiaGPU

#1278 Switch to using more expressive layout descriptors instead of numeric layout names
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/builder/reshape.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_invoke.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.hpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_shuffle_folding.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1326 Auto. gen. kernel signatures and argument expansion
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/cudnn_host_parameters.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_host_parameters.hpp
  src/ngraph/runtime/gpu/gpu_kernel_args.cpp
  src/ngraph/runtime/gpu/gpu_kernel_args.hpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.cpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.hpp
Labels: Fully Reviewed, NvidiaGPU

#1336 IntelGPU backend: AvgPool operation(partially)
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.hpp
Labels: Fully Reviewed, IntelGPU

#1310 cuda optimize softmax
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
Labels: Fully Reviewed, NvidiaGPU

#1337 IntelGPU backend: And, Or operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#1338 IntelGPU backend: Reverse operation implementation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#1339 DEX: Helper macros for subset of types and ranks
  src/ngraph/runtime/cpu/cpu_builder.hpp
Labels: Fully Reviewed

#1343 reduce fprop cache outputs
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/util.cpp
  test/util.cpp
Labels: Fully Reviewed

#1344 DEX LRN
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/lrn.cpp
Labels: Fully Reviewed

#1351 CPU Direct Execution: Implement ReduceWindow
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/reduce_function_window.cpp
  src/ngraph/runtime/cpu/kernel/reduce_function_window.hpp
Labels: Fully Reviewed

#1352 DEX Micro-optimizations: Use the mapped-value reference capture idiom…
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed

#1319 DEX BatchDot
  src/ngraph/runtime/cpu/builder/matmul_bias.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed

#1349 DEX: Reduce function
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/reduce_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.hpp
  src/ngraph/runtime/cpu/kernel/reduce_function.hpp
Labels: Fully Reviewed

#1356 CPU Direct Execution: Implement Slice
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/kernel/slice.hpp
Labels: Fully Reviewed

#1354 Revert changes to gpu shape and update
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/nvdiff.hpp
  src/ngraph/runtime/gpu/nvshape.hpp
  test/gpu_test.cpp
Labels: Fully Reviewed, NvidiaGPU

#1360 Add Softmax variant for rank-3 with 2 reduction axes
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/kernel/softmax.hpp
Labels: Fully Reviewed

#1308 Added DEX execution support for Lstm & Rnn
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
Labels: Fully Reviewed

#1366 Replace hardcoded alignment value
  src/ngraph/runtime/cpu/kernel/reduce_function_window.hpp
Labels: Fully Reviewed

#1367 Remove unused headers
  src/ngraph/runtime/cpu/cpu_builder.cpp
Labels: Fully Reviewed

#1355 Added DEX support for BoundedRelu
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
Labels: Fully Reviewed

#1368 Remove unnecessary static
  src/ngraph/runtime/cpu/builder/lrn.cpp
Labels: Fully Reviewed

#1371 disable rnn && lstm fusion pass for DEX
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#1365 Jmenon/nbench
  src/tools/nbench/benchmark.cpp
  src/tools/nbench/benchmark.hpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#1369 Make pool alignment a constexpr
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed

#1373 add missing unit tests
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1363 IntelGPU backend: Concat operation implementation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1378 Add missing override
  src/ngraph/pass/common_function_collection.hpp
Labels: Fully Reviewed

#1381 IntelGPU backend: Sin, cos, log, exp operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1375 added DEX support for BatchNormRelu
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
Labels: Fully Reviewed

#1374 CMake: Halide
  CMakeLists.txt
  cmake/external_halide.cmake
Labels: Fully Reviewed

#1346 Utilize GPUKernelArgs parameter for ew-collective, nd-conv, replace_slice.
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
Labels: Fully Reviewed, NvidiaGPU

#1383 switch pytest to use INTERPRETER backend for testing
  python/test/conftest.py
  python/test/ngraph/test_basic.py
Labels: Fully Reviewed

#1388 Remove a dynamic_cast
  src/ngraph/runtime/cpu/builder/concat.cpp
Labels: Fully Reviewed

#1379 Added MKLDNN concat in DEX
  src/ngraph/runtime/cpu/builder/concat.cpp
Labels: Fully Reviewed

#1393 IntelGPU backend: BatchNorm, Dot, Pad operations optimization
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#1386 Fix allocation size in batchnorm kernel
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
Labels: Fully Reviewed

#1384 Add cudnn host data param case for CUDNN_DATA_INT8x32
  cmake/clang_4_0_flags.cmake
  src/ngraph/runtime/gpu/cudnn_host_parameters.hpp
Labels: Fully Reviewed, HIGH PRIORITY, NvidiaGPU

#1298 Update Dockerfile
  .ci/travis/ubuntu/Dockerfile
Labels: Fully Reviewed

#1361 Backend support for static and dynamically linked backends
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/backend_manager.hpp
Labels: Fully Reviewed

#1376 Dex non-mkldnn version of clipped relu
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/kernel/relu.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1392 CPU Direct Execution: Add MKL-DNN EW Add
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/add.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
Labels: Fully Reviewed

#1377 [ONNX] Support for Split op
  .ci/travis/ubuntu/Dockerfile
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/attribute.hpp
  src/ngraph/frontend/onnx_import/graph.hpp
  src/ngraph/frontend/onnx_import/model.hpp
  src/ngraph/frontend/onnx_import/node.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
  src/ngraph/frontend/onnx_import/op/split.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/tensor.hpp
  src/ngraph/frontend/onnx_import/value_info.hpp
  test/CMakeLists.txt
  test/models/onnx/add_abc.onnx
  test/models/onnx/add_abc_initializers.onnx
  test/models/onnx/split_equal_parts_2d.onnx
  test/models/onnx/split_equal_parts_default.onnx
  test/models/onnx/split_variable_parts_2d.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1394 IntelGPU backend: Convert operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1399 don't propagate outputs inplace to constants
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#1401 change style-check target to not be predecated on unit test
  CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#1402 IntelGPU backend: Convolution workaround operations (partially)
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: IntelGPU

#1327 Remove validation checks from performance critical code paths and ski…
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  test/backend_test.in.cpp
Labels: Changes API, Fully Reviewed

#1311 Implement new CI trigger to alleviate API rate issues
  .ci/jenkins/jenkins-trigger.groovy
Labels: Fully Reviewed

#1405 Edit distr docs
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/howto/distribute-train.rst
Labels: Fully Reviewed

#1406 DEX: Propagate inputs & outputs
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/convert.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/dot.cpp
  src/ngraph/runtime/cpu/builder/function_call.cpp
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/matmul_bias.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/builder/reduce_function.cpp
  src/ngraph/runtime/cpu/builder/reduce_function_window.cpp
  src/ngraph/runtime/cpu/builder/reduction.hpp
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/builder/replace_slice.cpp
  src/ngraph/runtime/cpu/builder/reshape.cpp
  src/ngraph/runtime/cpu/builder/reverse.cpp
  src/ngraph/runtime/cpu/builder/reverse_sequence.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/builder/select.cpp
  src/ngraph/runtime/cpu/builder/select_and_scatter.cpp
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed

#1409 DEX: Add MKLDNN path for Relu
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
Labels: Fully Reviewed

#1412 IntelGPU backend: Convolution workaround operations completed
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: IntelGPU

#1413 IntelGPU backend: Softmax operation implementation
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1410 Add StopGradient to the graph serializer
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#1415 Removed unused code.
  src/ngraph/log.cpp
Labels: Fully Reviewed

#1340 Add OneHot op to direct execution.
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/one_hot.cpp
  src/ngraph/runtime/cpu/kernel/one_hot.hpp
Labels: Fully Reviewed

#1396 [ONNX] Batchnorm operation
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/exceptions.hpp
  src/ngraph/frontend/onnx_import/op/batch_norm.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/batchnorm_default.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1397 Temporary broadcast optimizations till halide support is merged
  src/ngraph/runtime/cpu/builder/broadcast.cpp
Labels: Fully Reviewed

#1347 Fold affine transformations on 4d convolution
  src/ngraph/graph_util.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/core_fusion.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1408 put ngraph and ngraph imported headers in search path before system paths
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
Labels: Fully Reviewed

#1416 Skip size one dimensions in kernel emitters
  src/ngraph/runtime/cpu/cpu_kernel_emitters.cpp
Labels: Fully Reviewed

#1418 Fix relu so it uses get_tensor_data
  src/ngraph/runtime/cpu/builder/relu.cpp
Labels: Fully Reviewed

#1421 address centos build error
  src/ngraph/util.cpp
Labels: Fully Reviewed

#1313 [Py] Wrapper for LRN
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/lrn.cpp
  python/pyngraph/ops/lrn.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_normalization.py
Labels: Fully Reviewed

#1420 Jbobba/tensor roles
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/runtime/cpu/builder/add.cpp
  src/ngraph/runtime/cpu/builder/broadcast.cpp
  src/ngraph/runtime/cpu/builder/one_hot.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed

#1427 IntelGPU backend: MaxPoolBackprop operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: IntelGPU

#1414 IntelGPU backend: Not, Minimum, OneHot operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1422 Fix broken dependencies
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#1425 DEX SGEMM batch for rank-3 rank-2 dot
  src/ngraph/runtime/cpu/builder/dot.cpp
Labels: Fully Reviewed

#1426 DEX: Support fewer ranks
  src/ngraph/runtime/cpu/cpu_builder.hpp
Labels: Fully Reviewed

#1419 [ONNX] Link nGraph statically against Protocol Buffers
  .ci/travis/ubuntu/Dockerfile
  CMakeLists.txt
  cmake/external_protobuf.cmake
  doc/sphinx/source/install.rst
  src/ngraph/frontend/onnx_import/CMakeLists.txt
Labels: Fully Reviewed

#1389 DEX Sigmoid Multiply
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/kernel/sigmoid_multiply.hpp
  src/ngraph/runtime/cpu/op/sigmoid_mul.hpp
Labels: Fully Reviewed

#1430 Allow -mtune control
  CMakeLists.txt
Labels: Fully Reviewed

#1431 DEX: Enable packetized innermost dim reducers
  src/ngraph/runtime/cpu/builder/reduction.hpp
  src/ngraph/runtime/cpu/kernel/reduce_max.hpp
  src/ngraph/runtime/cpu/kernel/reduce_min.hpp
  src/ngraph/runtime/cpu/kernel/reduce_product.hpp
  src/ngraph/runtime/cpu/kernel/reduce_sum.hpp
Labels: Fully Reviewed

#1434 IntelGPU backend: Code refactoring and optimization
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1432 Avoid using integer literal suffixes so it doesn't confuse xcode clang
  src/ngraph/runtime/cpu/builder/dot.cpp
Labels: Fully Reviewed, bug fix

#1424 Enable DEX only build of ngraph
  CMakeLists.txt
  src/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/tools/CMakeLists.txt
  src/tools/compile_benchmark/CMakeLists.txt
  src/tools/compile_benchmark/compile_benchmark.cpp
  test/CMakeLists.txt
  test/codegen.cpp
Labels: Fully Reviewed

#1428 Backend test: MaxPoolBackprop test strided and padded
  src/ngraph/runtime/cpu/unit_test.manifest
  test/autodiff.in.cpp
Labels: Fully Reviewed

#1438 Packetized Softmax variant with innermost reducers
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/kernel/softmax.hpp
Labels: Fully Reviewed

#1423 collapse dims
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.hpp
Labels: Fully Reviewed

#1440 Allow tensor[view, layout] element type and shape to be modified
  src/ngraph/descriptor/layout/tensor_view_layout.cpp
  src/ngraph/descriptor/layout/tensor_view_layout.hpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/descriptor/primary_tensor_view.cpp
  src/ngraph/descriptor/primary_tensor_view.hpp
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/descriptor/tensor_view.cpp
  src/ngraph/descriptor/tensor_view.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
Labels: Fully Reviewed

#1447 Test cent os gcc 4.8 fix of bug in std::basic_string
  src/ngraph/runtime/gpu/cuda_emitter.cpp
Labels: Fully Reviewed

#1451 [ONNX] Ops bridge refactoring
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/batch_norm.hpp
  src/ngraph/frontend/onnx_import/op/constant.cpp
  src/ngraph/frontend/onnx_import/op/constant.hpp
  src/ngraph/frontend/onnx_import/op/split.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1411 gpu replace slice optimize
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_op_annotations.hpp
  src/ngraph/runtime/gpu/pass/gpu_layout.cpp
  src/ngraph/runtime/gpu/pass/gpu_layout.hpp
Labels: Fully Reviewed, NvidiaGPU

#1435 ArgMin
  src/ngraph/CMakeLists.txt
  src/ngraph/op/argmin.cpp
  src/ngraph/op/argmin.hpp
  src/ngraph/op/util/index_reduction.cpp
  src/ngraph/op/util/index_reduction.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/argmin.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/argmin.hpp
  src/ngraph/serializer.cpp
  test/backend_test.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1370 update MKLDNN version from v0.14 -> v0.16
  cmake/external_mkldnn.cmake
  src/ngraph/descriptor/layout/tensor_view_layout.cpp
  src/ngraph/descriptor/layout/tensor_view_layout.hpp
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/descriptor/tensor_view.hpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Fully Reviewed

#1444 Statically link cpu backend into ngraph shared library
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/interpreter/CMakeLists.txt
  src/tools/nbench/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#1457 Revert "Statically link cpu backend into ngraph shared library (#1444)"
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/interpreter/CMakeLists.txt
  src/tools/nbench/CMakeLists.txt
  test/CMakeLists.txt
Labels: HIGH PRIORITY, bug fix

#1441 add EXCLUDE_FROM_ALL to codegen directory
  cmake/external_llvm.cmake
  cmake/external_llvm_prebuilt.cmake
  cmake/external_mkldnn.cmake
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
Labels: Fully Reviewed

#1452 get_default_order
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/reduce_ops.cpp
  src/ngraph/builder/tensor_mask.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/softmax.cpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
Labels: Fully Reviewed

#1449 [ONNX] Fix build for CentOS 7
  src/ngraph/frontend/onnx_import/graph.cpp
  src/ngraph/frontend/onnx_import/node.hpp
  src/ngraph/frontend/onnx_import/value_info.hpp
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1458 Public documentation version release info updated and confirmed
  .gitignore
  doc/sphinx/source/conf.py
Labels: Fully Reviewed

#1461 DEX AllReduce op
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/allreduce.cpp
Labels: Fully Reviewed

#1462 dont create mkldnn memory desc if dims == 0
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
Labels: Fully Reviewed

#1466 [ONNX] Change compiler options
  src/ngraph/frontend/onnx_import/CMakeLists.txt
Labels: Fully Reviewed, ONNX

#1468 [ONNX] Attribute helper functions
  src/ngraph/frontend/onnx_import/attribute.hpp
  src/ngraph/frontend/onnx_import/node.hpp
Labels: Fully Reviewed, ONNX

#1467 [ONNX] Refactor exceptions
  src/ngraph/frontend/onnx_import/exceptions.hpp
  src/ngraph/frontend/onnx_import/op/batch_norm.hpp
Labels: Fully Reviewed, ONNX

#1472 [ONNX] Conv operation
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/exceptions.hpp
  src/ngraph/frontend/onnx_import/op/batch_norm.hpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/conv.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.hpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
  test/models/onnx/conv_with_strides_and_assymmetric_padding.onnx
  test/models/onnx/conv_with_strides_no_padding.onnx
  test/models/onnx/conv_with_strides_padding.onnx
  test/models/onnx/conv_with_strides_padding_bias.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1470 [ONNX] Delete redundant pragma statement
  src/ngraph/frontend/onnx_import/op/constant.cpp
Labels: Fully Reviewed, ONNX

#1482 revert exclude from all on directory to get codegen library to install
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
Labels: Fully Reviewed

#1483 broadcast fix
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
Labels: Fully Reviewed, HIGH PRIORITY

#1477 Revert MKLDNN ver to 0.14
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed, HIGH PRIORITY

#1460 Move apply_permutation to util
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
Labels: Fully Reviewed

#1476 [ONNX] Code cleanup
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/exceptions.hpp
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
  src/ngraph/frontend/onnx_import/op/batch_norm.hpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/conv.hpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/op/split.hpp
  test/models/onnx/conv_with_strides_and_asymmetric_padding.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1471 Test tools - small refactoring
  test/util/test_tools.hpp
Labels: Fully Reviewed

#1481 [ONNX] Alter code layout
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/attribute.cpp
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
  src/ngraph/frontend/onnx_import/op/batch_norm.hpp
  src/ngraph/frontend/onnx_import/op/constant.cpp
  src/ngraph/frontend/onnx_import/op/constant.hpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/conv.hpp
  src/ngraph/frontend/onnx_import/op/relu.hpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/op/split.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.hpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
Labels: Fully Reviewed, ONNX

#1485 [ONNX] Ops bridge - change exception handling
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1486 [ONNX] Move Convolution and Pooling helpers to utils/convpool
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
Labels: Fully Reviewed, ONNX
