Repository NervanaSystems/ngraph, pull requests merged in 2018-12, with the labels that each got.

#2095 Minor perf tweaks
  src/ngraph/runtime/plaidml/plaidml_backend.cpp
  src/ngraph/runtime/plaidml/plaidml_compiled_function.cpp
  src/ngraph/runtime/plaidml/plaidml_compiled_function.hpp
  src/ngraph/runtime/plaidml/plaidml_tensor.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, PlaidML

#2123 Patch halide cmake files to only build X86 backend
  cmake/external_halide.cmake
  cmake/halide.patch
Labels: Fully Reviewed, IntelCPU

#2122 Support arg_reduce for int32 for nvGPU
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_arg_reduce.in.cpp
  test/backend_sum.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#2127 Additional info calculated & printed for all_close_f.
  test/all_close_f.cpp
  test/util/all_close_f.cpp
  test/util/all_close_f.hpp
Labels: Fully Reviewed

#2086 IntelGPU backend: Use clDNN BatchNorm in operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU, Merge Blocked, β

#2143 Doc for Batchnorm
  doc/sphinx/ngraph.doxyfile
  doc/sphinx/source/ops/batch_norm.rst
  doc/sphinx/source/ops/batch_norm_inference.rst
  doc/sphinx/source/ops/batch_norm_training.rst
  doc/sphinx/source/ops/batch_norm_training_backprop.rst
  doc/sphinx/source/ops/index.rst
Labels: Fully Reviewed

#2140 fix to kahan summation in ref kernel
  src/ngraph/runtime/reference/sum.hpp
Labels: Fully Reviewed

#2152 Update ABOUT.md
  ABOUT.md
Labels: Fully Reviewed, High Priority

#2078 [ONNX] Enable Pad operator and batch normalization non-spatial mode
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
  src/ngraph/frontend/onnx_import/op/pad.cpp
  src/ngraph/frontend/onnx_import/op/pad.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#2158 Fix broken link
  README.md
Labels: Fully Reviewed

#2162 Merge External PR
  src/ngraph/runtime/gpu/gpu_external_function.cpp
Labels: Bug, External, Fully Reviewed

#2170 Make MKLDNN_ENABLE_CONCURRENT_EXEC ON to use concurrent scratchpad in…
  cmake/external_mkldnn.cmake
Labels: High Priority, IntelCPU

#2055 Support for 5D batchnorm
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  test/backend_test.in.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU, β

#2157 remove reshapes on both hands of a binary op
  src/ngraph/runtime/cpu/pass/cpu_reshape_sinking.cpp
Labels: Fully Reviewed, IntelCPU

#2175 fix failing bn test
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed

#1874 Pruthvi/fix rnn precision
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/pass/cpu_concat_inputs.cpp
  src/ngraph/runtime/cpu/pass/cpu_concat_inputs.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  test/cpu_fusion.cpp
  test/gpu_fusion.cpp
  test/models/mxnet/1rnn_layer_3lstm_cell.json
  test/models/mxnet/2layer_3timestep_ic100oc100.json
Labels: Fully Reviewed, IntelCPU

#2155 Fix compiler error GCC with 7.1
  src/ngraph/partial_shape.hpp
Labels: Fully Reviewed

#2076 nvgpu cuda reduce with stable sum
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_host_parameters.hpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.cpp
  src/ngraph/runtime/gpu/type_info.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_sum.in.cpp
  test/util/all_close.hpp
  test/util/all_close_f.cpp
Labels: Fully Reviewed, NvidiaGPU, β

#2164 [Py] setup.py code style formatting.
  python/setup.py
  python/tox.ini
Labels: Fully Reviewed

#2151 [Py] Update README for PyPI
  python/BUILDING.md
  python/README.md
  python/build_wheel.sh.in
  python/setup.py
  python/test/ngraph/test_onnx_import.py
Labels: Fully Reviewed, β

#2144 Graph comparison - isolated per op testing
  test/backend_graph_comparison.in.cpp
Labels: Fully Reviewed

#2179 Abort messages in Matcher to better understand cases where we fail to match
  src/ngraph/pattern/matcher.cpp
Labels: Fully Reviewed

#2178 Give Fusions Names
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
Labels: Fully Reviewed

#2183 add a throw in lieu of a return stmt
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
Labels: Fully Reviewed, IntelCPU

#2156 DEX Loop Kernel (updated)
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/halide_generators.cpp
  src/ngraph/runtime/cpu/builder/halide_generators.hpp
  src/ngraph/runtime/cpu/builder/halide_op.cpp
  src/ngraph/runtime/cpu/builder/loop_kernel.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#2187 IntelGPU backend: Allow more cases for clDNN gemm
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2062 QCBiasAdd and QCBiasSignedAdd for mkldnn
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization_util.hpp
  src/ngraph/op/experimental/quantized_conv_bias.cpp
  src/ngraph/op/experimental/quantized_conv_bias.hpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU, Merge Blocked, β

#2154 Update TBB from 2019_U1 to 2019_U2.
  cmake/external_tbb.cmake
Labels: Fully Reviewed, IntelCPU

#2184 Support for all_close_f w/ doubles
  test/all_close_f.cpp
  test/util/all_close_f.cpp
  test/util/all_close_f.hpp
Labels: Fully Reviewed

#2192 IntelGPU backend: Fix memory copy into zero tensors
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Bug, IntelGPU

#2180 Update slice kernels
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/update_slice.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/update_slice.hpp
  src/ngraph/runtime/cpu/op/update_slice.cpp
  src/ngraph/runtime/cpu/op/update_slice.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  test/cpu_fusion.cpp
Labels: IntelCPU

#2153 make GOE extend from util::Op
  python/pyngraph/ops/get_output_element.cpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/get_output_element.hpp
Labels: Fully Reviewed

#2168 reenable mkldnn convolution for large padding
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2195 change all_close tests to return gtest AssertionResult instead of bool
  test/util/all_close.hpp
  test/util/all_close_f.cpp
  test/util/all_close_f.hpp
Labels: Fully Reviewed

#2210 Fix TF test failures on Mac.
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
Labels: High Priority

#2169 Matcher skip
  src/ngraph/pattern/matcher.cpp
Labels: Fully Reviewed

#2188 Reshape SoftMax Reshape
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/core_fusion.hpp
  test/core_fusion.cpp
Labels: Fully Reviewed

#2193 [Py]Add version to ngraph python
  python/ngraph/__init__.py
Labels: Fully Reviewed

#2201 IntelGPU backend: Fix reshape operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Bug, Fully Reviewed, IntelGPU

#2205 fix crash in ReshapeConvertLayout
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
Labels: Fully Reviewed, IntelCPU

#2101 nvgpu cuda softmax optimization
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#2177 Windows build support
  .gitignore
  CMakeLists.txt
  cmake/external_cldnn.cmake
  cmake/external_gtest.cmake
  cmake/external_llvm.cmake
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/codegen_visibility.h
  src/ngraph/file_util.cpp
  src/ngraph/ngraph_visibility.hpp
  src/ngraph/pass/manager.cpp
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/backend_manager.hpp
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/int_visibility.h
  src/ngraph/runtime/reference/min.hpp
  src/ngraph/runtime/reference/topk.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  src/ngraph/util.cpp
  src/tools/nbench/CMakeLists.txt
  test/CMakeLists.txt
  test/backend_test.in.cpp
  test/util.cpp
  test/util/autodiff/backprop_derivative.hpp
  test/util/test_tools.cpp
Labels: Fully Reviewed

#2053 Embedding fprop
  src/ngraph/CMakeLists.txt
  src/ngraph/op/embedding_lookup.cpp
  src/ngraph/op/embedding_lookup.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/embedding_lookup.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/embedding_lookup.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend_embedding_lookup.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2197 Skip Broadcast in sigmoid fusion
  src/ngraph/pass/core_fusion.cpp
  test/core_fusion.cpp
Labels: Fully Reviewed

#2212 Removing GOEE
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/get_output_element.cpp
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/builder/topk.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed

#1520 Integration of MLSL library
  CMakeLists.txt
  cmake/external_mlsl.cmake
  doc/examples/mnist_mlp/CMakeLists.txt
  doc/examples/mnist_mlp/dist_mnist_mlp.cpp
  doc/examples/mnist_mlp/mnist_loader.cpp
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/howto/distribute-train.rst
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
  src/ngraph/distributed.cpp
  src/ngraph/distributed.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/allreduce.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  src/ngraph/runtime/interpreter/CMakeLists.txt
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/allreduce.hpp
  src/tools/nbench/CMakeLists.txt
  src/tools/nbench/nbench.cpp
  test/CMakeLists.txt
  test/distributed.in.cpp
Labels: Fully Reviewed, Merge Blocked

#2189 Remove old eigen code in codegen and misc bug fixes
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed, IntelCPU

#2211 Move CPU ReshapeSinking to Core pass
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/reshape_sinking.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  test/CMakeLists.txt
  test/reshape_sinking.cpp
Labels: Fully Reviewed

#2213 Add BroadcastLike and ScalarConstantLike to op_tbl
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/op/acos.cpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/broadcast.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#2216 Fixed NGRAPH_INSTANTIATE_TEST_CASE_P use of static
  test/util/test_control.hpp
Labels: Fully Reviewed

#2218 Batchnorm autodiff test
  test/autodiff.in.cpp
  test/util/autodiff/numeric_compare.hpp
Labels: Fully Reviewed

#2200 Addressed some all_close_f loose ends
  test/all_close_f.cpp
  test/backend_graph_comparison.in.cpp
  test/util/all_close_f.cpp
  test/util/all_close_f.hpp
Labels: Fully Reviewed

#2220 fix visibility.h not being copied to install folder
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/int_visibility.hpp
Labels: Fully Reviewed

#2202 [ONNX] Expose API enabling to get supported ONNX operators set.
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
Labels: Fully Reviewed, ONNX

#2176 Fix path to nGraph licenses files in pyngraph.
  python/setup.py
Labels: Fully Reviewed

#2229 add make command to fix-mode
  CMakeLists.txt
  cmake/Modules/fix_mode.cmake
Labels: Fully Reviewed

#2215 DEX Execution plan for debugging
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed, IntelCPU

#2126 generic layout methods for elementwise kernels.
  src/ngraph/runtime/cpu/op/bounded_relu.cpp
  src/ngraph/runtime/cpu/op/bounded_relu.hpp
  src/ngraph/runtime/cpu/op/leaky_relu.cpp
  src/ngraph/runtime/cpu/op/leaky_relu.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.hpp
Labels: Fully Reviewed, IntelCPU

#2231 Cherry-pick "let convolutionbiasbackprop apply to 5D (#2230)"
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
Labels: Fully Reviewed

#2225 enable visualize graph even if graphviz is not installed
  src/ngraph/pass/visualize_tree.cpp
  test/util.cpp
Labels: Fully Reviewed

#2239 IntelGPU backend: All and Any operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.hpp
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#2235 matcher's strict mode
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  test/pattern.cpp
Labels: Fully Reviewed

#2214 Enable in place slice when slice's arg is function input.
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, IntelCPU

#2222 Refactor ReshapeSinking into individual sinkers
  src/ngraph/pass/reshape_sinking.cpp
Labels: Fully Reviewed

#2224 Make explicit compile call in unit tests
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  test/autodiff.in.cpp
  test/backend_all.in.cpp
  test/backend_any.in.cpp
  test/backend_arg_reduce.in.cpp
  test/backend_binary_elementwise.in.cpp
  test/backend_broadcast.in.cpp
  test/backend_comparison.in.cpp
  test/backend_dot.in.cpp
  test/backend_embedding_lookup.in.cpp
  test/backend_graph_comparison.in.cpp
  test/backend_one_hot.in.cpp
  test/backend_performance.cpp
  test/backend_pool.in.cpp
  test/backend_reduce.in.cpp
  test/backend_reshape.in.cpp
  test/backend_sum.in.cpp
  test/backend_test.in.cpp
  test/backend_topk.in.cpp
  test/backend_unary_elementwise.in.cpp
  test/builder.cpp
  test/builder_quantization.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/distributed.in.cpp
  test/gpu_fusion.cpp
  test/gpu_test.cpp
  test/halide.cpp
  test/hybrid_backend.cpp
Labels: Fully Reviewed

#2245 Fixed NGRAPH_TEST_F separator to be consistent with documentation of how to filter
  test/util/test_control.cpp
Labels: Fully Reviewed

#2248 Fixed the benchmark file to reflect the updated compile function usage
  src/tools/nbench/benchmark.cpp
Labels: Bug, Fully Reviewed

#2249 Fix how the bias reorder scale is passed
  src/ngraph/builder/quantization_util.hpp
Labels: Fully Reviewed

#2219 Doc 0.11
  FAQs.md
  INSTALL.md
  README.md
  doc/examples/subgraph_snippets/mxnet-gluon-example.py
  doc/sphinx/ngraph_theme/searchbox.html
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/ngraph_theme/static/favicon.ico
  doc/sphinx/ngraph_theme/static/theme.css
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/framework-integration-guides.rst
  doc/sphinx/source/frameworks/generic-configs.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/testing-latency.rst
  doc/sphinx/source/frameworks/validation.rst
  doc/sphinx/source/glossary.rst
  doc/sphinx/source/graphics/599px-Intel-ngraph-ecosystem.png
  doc/sphinx/source/graphics/favicon.xcf
  doc/sphinx/source/graphics/features-figure-latest.png
  doc/sphinx/source/graphics/ngcompiler-ecosystem.png
  doc/sphinx/source/graphics/ngcompiler-ecosystem.xcf
  doc/sphinx/source/graphics/ngraph-ecosys.png
  doc/sphinx/source/graphics/ngraph-ecosystem.png
  doc/sphinx/source/graphics/ngraph-mxnet-models.png
  doc/sphinx/source/graphics/tablengraphops.png
  doc/sphinx/source/howto/import.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/about.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/project/about.rst
  doc/sphinx/source/project/code-contributor-README.rst
  doc/sphinx/source/project/contrib.md
  doc/sphinx/source/project/index.rst
  doc/sphinx/source/python_api/index.rst
Labels: Fully Reviewed

#2252 [ONNX] Handle negative axis values in Concat op.
  python/pyngraph/onnx_import/onnx_import.cpp
  src/ngraph/frontend/onnx_import/op/concat.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
Labels: Fully Reviewed, ONNX

#2120 Implement ngraph::element::Type as a wrapper around an enum
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  test/element_type.cpp
Labels: Fully Reviewed

#2258 Graph comparison testing quiet unless problem is detected
  test/backend_graph_comparison.in.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#2171 Support dynamic scales for Qconv's and Dequantize
  src/ngraph/op/experimental/quantized_conv_relu.hpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/conv_relu.hpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU

#2253 add unit test for nbench functionality
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/tools/nbench/nbench.cpp
  test/CMakeLists.txt
  test/tools.cpp
Labels: Fully Reviewed

#2257 Remove old cudnn test
  test/CMakeLists.txt
  test/cudnn.cpp
Labels: Fully Reviewed, NvidiaGPU

#2259 fix windows build
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/type/element_type.hpp
Labels: Fully Reviewed

#2263 Add missing #include to reference/avg_pool.hpp
  src/ngraph/runtime/reference/avg_pool.hpp
Labels: Fully Reviewed

#2241 Remove code designed to support the Ninja cmake generator
  CMakeLists.txt
  cmake/external_eigen.cmake
  cmake/external_gtest.cmake
  cmake/external_halide.cmake
  cmake/external_llvm.cmake
  cmake/external_llvm_prebuilt.cmake
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed
