Repository NervanaSystems/ngraph, pull requests merged in 2018-09, with the labels that each got.

#1537 TEST: simple test with one constant to two outputs
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed, IntelGPU

#1540 Small error reporting improvement
  src/ngraph/runtime/backend_manager.cpp
Labels: Fully Reviewed

#1541 IntelGPU backend: helper function improvement
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.cpp
Labels: Fully Reviewed, IntelGPU

#1542 IntelGPU backend: Pad operation optimization
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
Labels: Fully Reviewed, IntelGPU

#1544 IntelGPU backend: Broken compilation fixed
  src/ngraph/runtime/intelgpu/intelgpu_tensor_view.cpp
  src/ngraph/runtime/intelgpu/intelgpu_tensor_view.hpp
Labels: Fully Reviewed, HIGH PRIORITY, IntelGPU

#1543 IntelGPU backend: getting clDNN convolution back with filter=1
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#1552 [ONNX] tensor add support for raw_data
  src/ngraph/frontend/onnx_import/core/tensor.hpp
Labels: ONNX

#1549 [ONNX] Numpy style binary broadcasting
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.hpp
  test/models/onnx/add_bcast.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1555 [ONNX] Fix for GEMM op
  src/ngraph/frontend/onnx_import/op/gemm.cpp
Labels: Fully Reviewed, ONNX

#1556 [ONNX] Fix for Conv op
  src/ngraph/frontend/onnx_import/op/conv.cpp
Labels: Fully Reviewed, ONNX

#1545 IntelGPU backend: Sum operation optimization
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, IntelGPU

#1539 Cmake flags update
  CMakeLists.txt
Labels: Fully Reviewed

#1536 Merge descriptor::TensorView into descriptor::Tensor
  src/ngraph/CMakeLists.txt
  src/ngraph/descriptor/layout/dense_tensor_view_layout.hpp
  src/ngraph/descriptor/layout/tensor_view_layout.cpp
  src/ngraph/descriptor/layout/tensor_view_layout.hpp
  src/ngraph/descriptor/output.cpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/descriptor/tensor_view.cpp
  src/ngraph/descriptor/tensor_view.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/node.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view_wrapper.hpp
  src/ngraph/runtime/gpu/gpu_tensor_view_wrapper.cpp
  src/ngraph/runtime/gpu/gpu_tensor_view_wrapper.hpp
  src/ngraph/runtime/tensor_view.hpp
Labels: Fully Reviewed

#1557 [ONNX] Pow operator
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/pow.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1491 nvgpu reduce to scalar optimization
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1551 add more order to Node, at least a consistent sort order...
  src/ngraph/node.hpp
Labels: Fully Reviewed

#1345 Simplify result copy elimination
  src/ngraph/CMakeLists.txt
  src/ngraph/op/result.cpp
  src/ngraph/op/result.hpp
  src/ngraph/pass/result_copy_elimination.cpp
  src/ngraph/pass/result_copy_elimination.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
  test/autodiff.in.cpp
Labels: Fully Reviewed

#1546 [ONNXIFI] implement onnxGetBackendIDs() interface function
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnxifi/CMakeLists.txt
  src/ngraph/frontend/onnxifi/backend.hpp
  src/ngraph/frontend/onnxifi/backend_manager.cpp
  src/ngraph/frontend/onnxifi/backend_manager.hpp
  src/ngraph/frontend/onnxifi/onnxifi.cpp
  test/CMakeLists.txt
  test/onnxifi.cpp
Labels: Fully Reviewed, ONNX

#1561 Fix centOS GCC 4.8 std::basic_string compiler error
  src/ngraph/runtime/gpu/cuda_emitter.cpp
Labels: Fully Reviewed, bug fix

#1568 Update doc build v and fix doc on captioning
  README.md
  doc/sphinx/ngraph_theme/layout.html
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/framework-integration-guides.rst
  doc/sphinx/source/frameworks/generic.rst
  doc/sphinx/source/howto/import.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/doc-contributor-README.rst
Labels: Fully Reviewed

#1567 [ONNX] Logical ops
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/and.hpp
  src/ngraph/frontend/onnx_import/op/equal.hpp
  src/ngraph/frontend/onnx_import/op/greater.hpp
  src/ngraph/frontend/onnx_import/op/less.hpp
  src/ngraph/frontend/onnx_import/op/not.hpp
  src/ngraph/frontend/onnx_import/op/or.hpp
  src/ngraph/frontend/onnx_import/op/xor.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1572 IntelGPU backend: Workaround for unsupported data types
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: IntelGPU

#1565 Add support for Dequantize op via mkldnn for IA backend (codegen + DEX)
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/dequantize.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/dequantize.cpp
  src/ngraph/runtime/cpu/op/dequantize.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/CMakeLists.txt
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1566 IntelGPU backend: Reshape operation optimization
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, IntelGPU

#1562 [ONNX] Reduce* operations
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/reduce.cpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
Labels: ONNX

#1579 IntelGPU backend: BatchNorm operation optimization
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
Labels: Fully Reviewed, IntelGPU

#1526 Add conv add fusion
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/conv_add.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1573 [ONNX] Refactor exceptions to asserts
  src/ngraph/assertion.hpp
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/exceptions.hpp
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/reshape.cpp
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
Labels: Fully Reviewed, ONNX

#1564 Make apply-code-format set correct permissions on source files
  maint/apply-code-format.sh
  src/ngraph/runtime/cpu/cpu_tensor_view.hpp
  src/ngraph/runtime/cpu/kernel/reduce_function.hpp
  src/ngraph/runtime/cpu/kernel/reduce_function_window.hpp
Labels: Fully Reviewed

#1538 Interpreter use switch() for main loop
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/interpreter/CMakeLists.txt
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/node_wrapper.cpp
  src/ngraph/runtime/interpreter/node_wrapper.hpp
Labels: Fully Reviewed

#1571 Add support for Quantized Pooling(Max + Avg) op via mkldnn for IA backend (codegen + DEX)
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantized_avg_pool.cpp
  src/ngraph/runtime/cpu/builder/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/op/quantized_avg_pool.cpp
  src/ngraph/runtime/cpu/op/quantized_avg_pool.hpp
  src/ngraph/runtime/cpu/op/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/op/quantized_max_pool.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1578 nbench buffer copy each iteration
  src/tools/nbench/benchmark.cpp
  src/tools/nbench/benchmark.hpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#1585 Update fusion doc and add ONNX build flag to buildlb doc
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/fusion/index.rst
  doc/sphinx/source/project/about.rst
  python/README.md
Labels: Fully Reviewed, ONNX

#1589 [ONNX] Tests for reduction ops.
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  test/models/onnx/reduce_l1.onnx
  test/models/onnx/reduce_l2.onnx
  test/models/onnx/reduce_log_sum.onnx
  test/models/onnx/reduce_log_sum_exp.onnx
  test/models/onnx/reduce_max.onnx
  test/models/onnx/reduce_mean.onnx
  test/models/onnx/reduce_min.onnx
  test/models/onnx/reduce_prod.onnx
  test/models/onnx/reduce_sum.onnx
  test/models/onnx/reduce_sum_square.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1559 Add in_place support for ReplaceSlice
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernel_emitters.cpp
  src/ngraph/runtime/cpu/cpu_kernel_emitters.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  test/backend_test.in.cpp
Labels: Broken, Fully Reviewed

#1590 Use validated call in the quantization unit test and the correct shape
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1598 Bug fix for assert
  src/ngraph/runtime/cpu/op/conv_add.cpp
Labels: Fully Reviewed

#1591 nvgpu reshape optimization: pass args instead of pointer to array
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
Labels: Fully Reviewed, NvidiaGPU

#1445 Control dependencies
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/serializer.cpp
  src/ngraph/util.cpp
  test/CMakeLists.txt
  test/control_dependencies.cpp
Labels: Fully Reviewed

#1446 Modify DEX OneHot op: use generator.
  src/ngraph/runtime/cpu/builder/one_hot.cpp
  src/ngraph/runtime/cpu/kernel/one_hot.hpp
Labels: Fully Reviewed

#1592 Disable clang optimizations on emitted functions
  src/ngraph/runtime/gpu/gpu_external_function.cpp
Labels: Fully Reviewed, NvidiaGPU

#1531 Handle unsupported op in nbench
  src/ngraph/except.hpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/conv_add.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/node_wrapper.cpp
  src/tools/nbench/nbench.cpp
  test/backend_test.in.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
Labels: Broken, Fully Reviewed

#1603 Fix some validation errors
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/broadcast.hpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/util.cpp
Labels: Fully Reviewed

#1580 [ONNX] Non-linear operators
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/elu.cpp
  src/ngraph/frontend/onnx_import/op/elu.hpp
  src/ngraph/frontend/onnx_import/op/leaky_relu.cpp
  src/ngraph/frontend/onnx_import/op/leaky_relu.hpp
  src/ngraph/frontend/onnx_import/op/prelu.cpp
  src/ngraph/frontend/onnx_import/op/prelu.hpp
  src/ngraph/frontend/onnx_import/op/selu.cpp
  src/ngraph/frontend/onnx_import/op/selu.hpp
  src/ngraph/frontend/onnx_import/op/sigmoid.hpp
  src/ngraph/frontend/onnx_import/op/tanh.hpp
  src/ngraph/frontend/onnx_import/op/thresholded_relu.cpp
  src/ngraph/frontend/onnx_import/op/thresholded_relu.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.hpp
  test/models/onnx/elu.onnx
  test/models/onnx/leaky_relu.onnx
  test/models/onnx/prelu.onnx
  test/models/onnx/selu.onnx
  test/models/onnx/sigmoid.onnx
  test/models/onnx/tanh.onnx
  test/models/onnx/thresholded_relu.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1605 [ONNX] ONNX CI on nGraph PRs
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/README.md
  .ci/onnx/jenkins/dockerfiles/ubuntu-16_04.dockerfile
  .ci/onnx/jenkins/prepare_environment.sh
  .ci/onnx/jenkins/runCI.sh
  .ci/onnx/jenkins/utils/docker.sh
  .ci/onnx/jenkins/utils/utils.groovy
Labels: Fully Reviewed, ONNX, ONNX_CI

#1602 Cyphers/layout
  src/ngraph/CMakeLists.txt
  src/ngraph/descriptor/input.cpp
  src/ngraph/descriptor/input.hpp
  src/ngraph/descriptor/layout/dense_tensor_layout.cpp
  src/ngraph/descriptor/layout/dense_tensor_layout.hpp
  src/ngraph/descriptor/layout/tensor_layout.cpp
  src/ngraph/descriptor/layout/tensor_layout.hpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/pass/assign_layout.hpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view_wrapper.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view_wrapper.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/op/convert_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_tensor_view.cpp
  src/ngraph/runtime/gpu/gpu_tensor_view_wrapper.cpp
  src/ngraph/runtime/gpu/gpu_tensor_view_wrapper.hpp
  src/ngraph/runtime/host_tensor_view.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.hpp
  src/ngraph/runtime/intelgpu/intelgpu_tensor_view.cpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/tensor_view.cpp
  src/ngraph/runtime/tensor_view.hpp
  test/cpu_fusion.cpp
  test/util/all_close.hpp
  test/util/all_close_f.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#1607 add a check that all nodes are sorted to topological sort
  src/ngraph/graph_util.hpp
Labels: Fully Reviewed

#1608 subgraph_topological_sort
  src/ngraph/graph_util.hpp
  test/util.cpp
Labels: Fully Reviewed

#1583 Remove heap allocations during execution
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
Labels: Fully Reviewed

#1534 GPU logical reshape pass-through
  src/ngraph/pass/common_function_collection.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
  src/ngraph/runtime/gpu/pass/gpu_layout.cpp
Labels: Fully Reviewed, NvidiaGPU

#1599 Move to MKLDNN v0.16. Git hash picks up some bug fixes post v0.16
  cmake/external_mkldnn.cmake
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
Labels: Fully Reviewed

#1612 Change serializer to use op_tbl
  cmake/external_llvm_prebuilt.cmake
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#1613 remove contains_key()
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/util.hpp
  test/graph_partition.cpp
  test/util/test_control.cpp
Labels: Fully Reviewed

#1595 [ONNXIFI] Test for onnxSignalEvent
  test/onnxifi.cpp
Labels: ONNX

#1594 [ONNXIFI] Unit Test for onnxWaitEvent
  test/onnxifi.cpp
Labels: ONNX

#1614 add very basic test for Coordinate
  test/CMakeLists.txt
  test/coordinate.cpp
Labels: Fully Reviewed

#1604 [ONNX] Unary ops
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/abs.hpp
  src/ngraph/frontend/onnx_import/op/cast.cpp
  src/ngraph/frontend/onnx_import/op/cast.hpp
  src/ngraph/frontend/onnx_import/op/ceil.hpp
  src/ngraph/frontend/onnx_import/op/clip.cpp
  src/ngraph/frontend/onnx_import/op/clip.hpp
  src/ngraph/frontend/onnx_import/op/exp.hpp
  src/ngraph/frontend/onnx_import/op/floor.hpp
  src/ngraph/frontend/onnx_import/op/hard_sigmoid.cpp
  src/ngraph/frontend/onnx_import/op/hard_sigmoid.hpp
  src/ngraph/frontend/onnx_import/op/identity.hpp
  src/ngraph/frontend/onnx_import/op/log.hpp
  src/ngraph/frontend/onnx_import/op/log_softmax.hpp
  src/ngraph/frontend/onnx_import/op/neg.hpp
  src/ngraph/frontend/onnx_import/op/reciprocal.cpp
  src/ngraph/frontend/onnx_import/op/reciprocal.hpp
  src/ngraph/frontend/onnx_import/op/softplus.cpp
  src/ngraph/frontend/onnx_import/op/softplus.hpp
  src/ngraph/frontend/onnx_import/op/softsign.cpp
  src/ngraph/frontend/onnx_import/op/softsign.hpp
  src/ngraph/frontend/onnx_import/op/sqrt.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1593 [ONNXIFI] Unit Tests for onnxRunGraph
  test/onnxifi.cpp
Labels: ONNX

#1596 [ONNXIFI] Test for onnxReleaseBackend and onnxReleaseBackendID
  test/onnxifi.cpp
Labels: ONNX

#1597 [ONNXIFI] Test for onnxReleaseGraph
  test/onnxifi.cpp
Labels: ONNX

#1624 IntelGPU backend: GetOutputElement operation fixed
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: IntelGPU

#1576 Add support for Quantize op via mkldnn for IA backend (codegen + DEX)
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantize.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/quantize.cpp
  src/ngraph/runtime/cpu/op/quantize.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/quantization_util.hpp
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1617 nvgpu optimize reshape v3
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1621 Disable pass through for Reshapes with shape change and transpose
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, bug fix

#1628 Bug fix for nvgpu GOE
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Fully Reviewed, bug fix

#1632 remove cmake generated op list
  src/ngraph/CMakeLists.txt
Labels: Fully Reviewed

#1619 refactor distributed code
  doc/examples/mnist_mlp/CMakeLists.txt
  doc/examples/mnist_mlp/dist_mnist_mlp.cpp
  doc/sphinx/source/howto/distribute-train.rst
  src/ngraph/CMakeLists.txt
  src/ngraph/distributed.cpp
  src/ngraph/distributed.hpp
  test/distributed.cpp
  test/main.cpp
Labels: Fully Reviewed

#1635 switch error to debug msg for bounded relu
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed

#1633 [ONNX CI] nGraph-ONNX CI Hotfix
  .ci/onnx/jenkins/Jenkinsfile
Labels: ONNX

#1615 [ONNXIFI] More tests for onnxInitGraph (using tensor descriptors).
  test/onnxifi.cpp
Labels: ONNX

#1611 [ONNX] Transpose op
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/transpose.cpp
  src/ngraph/frontend/onnx_import/op/transpose.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
Labels: Fully Reviewed, ONNX

#1625 [ONNX] Squeeze op
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1618 Change GPU backend to use op_tbl
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
Labels: Fully Reviewed, NvidiaGPU

#1640 fix Sphinx version for Jenkins and update nG versioning
  contrib/docker/Dockerfile.ngraph.centos74
  contrib/docker/Dockerfile.ngraph.ubuntu1604
  doc/sphinx/source/conf.py
Labels: Fully Reviewed, HIGH PRIORITY, enhancement

#1639 Prefer local versions over code available externally
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed, HIGH PRIORITY

#1620 Add support for Quantized Convolution op via mkldnn for IA backend (codegen + DEX)
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/quantized_conv.cpp
  src/ngraph/runtime/cpu/op/quantized_conv.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/quantization_util.cpp
  src/ngraph/runtime/cpu/quantization_util.hpp
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1638 Switch to the OpenMP threadpool
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed, blocker

#1575 Use MKLDNN for non-strided slice ops.
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.hpp
Labels: Fully Reviewed

#1643 IntelGPU backend: Atan, Ceiling, Floor, Sign, Tan operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1616 move weights conversion out of group convolution emitter to convert_l…
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Fully Reviewed

#1629 Fix output element type for selection functions
  src/ngraph/runtime/cpu/builder/select_and_scatter.cpp
Labels: Fully Reviewed

#1626 IntelGPU backend. Change Intel GPU backend to use op_tbl
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#1649 Normalize line endings
  .gitattributes
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/uuid.hpp
  test/pass_liveness.cpp
  test/pass_memory_layout.cpp
  test/uuid.cpp
Labels: Fully Reviewed

#1651 Cannot end a single line c++ commend with a backslash.
  src/ngraph/assertion.hpp
Labels: Fully Reviewed

#1653 fix a bug in get_output_element
  src/ngraph/op/get_output_element.hpp
Labels: Fully Reviewed

#1644 [ONNX] Fix bugs in unsqueeze and pooling ops
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
Labels: ONNX

#1645 [ONNX] LRN op
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/lrn.cpp
  src/ngraph/frontend/onnx_import/op/lrn.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1646 [ONNX] Dropout op
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1642 Common pass registration for codegen and Dex
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.hpp
Labels: Fully Reviewed

#1647 Testing with searchtools js from zephyr project
  doc/sphinx/ngraph_theme/static/js/jquery.ba-bbq.min.js
  doc/sphinx/ngraph_theme/static/js/jquery.slideto.min.js
  doc/sphinx/ngraph_theme/static/js/jquery.wiggle.min.js
  doc/sphinx/ngraph_theme/static/js/searchtools.js
  doc/sphinx/ngraph_theme/static/js/swagger-oauth.js
  doc/sphinx/ngraph_theme/static/js/swagger-ui.js
  doc/sphinx/ngraph_theme/static/js/swagger-ui.min.js
Labels: Fully Reviewed

#1648 IntelGPU backend. Use clDNN broadcast and fix compilation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#1652 Update clang/llvm to 5.0.2 and add macOS prebuild binary support.
  cmake/external_llvm.cmake
  cmake/external_llvm_prebuilt.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/resource/CMakeLists.txt
Labels: Fully Reviewed

#1654 IntelGPU backend: createVarianceBack initial optimization
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
Labels: Fully Reviewed, IntelGPU

#1656 Add namespace to NGRAPH_OP macro to address backend fusion ops
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/node_wrapper.cpp
  src/ngraph/runtime/interpreter/node_wrapper.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#1655 IntelGPU backend: Sum to scalar optimization
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
Labels: Fully Reviewed, IntelGPU

#1511 Extend concat elimination to fold slice + reshape
  src/ngraph/pass/algebraic_simplification.cpp
  test/algebraic_simplification.cpp
Labels: Fully Reviewed

#1515 Pruthvi/dex debug manifest
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed

#1577 Add CPU horizontal fusion pass for inception.
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1630 Disable/Enable individual transformations (needed for SPH)
  src/ngraph/pass/constant_folding.hpp
Labels: Fully Reviewed

#1660 fix assert in get_argument
  src/ngraph/node.cpp
Labels: Fully Reviewed

#1667 IntelGPU backend. Use common nGraph optimization passes
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: IntelGPU

#1668 IntelGPU backend. Fix bug in Concat and small refactoring
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: IntelGPU

#1669 GPU backend. Fix compilation on Ubuntu 18. std::iota requires <numeri…
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#1663 zero dim elem fix
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#1670 Enable building without CPU without triggering mkldnn or eigen builds
  cmake/external_tbb.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/resource/CMakeLists.txt
  src/resource/main.cpp
Labels: Fully Reviewed

#1672 Add lots more fun output to nbench
  src/ngraph/type/element_type.cpp
  src/tools/nbench/nbench.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1636 CPU Builder: Add double to the partial element type set
  src/ngraph/runtime/cpu/cpu_builder.hpp
Labels: Fully Reviewed

#1679 Don't reuse memory for non-destructive ops
  src/ngraph/pass/memory_layout.cpp
Labels: Fully Reviewed, bug fix

#1681 IntelGPU backend: Types workaround removal
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1686 Fix DEX_ONLY compile error in cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#1688 IntelGPU backend: Switch Select operation to use implementation from …
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#1676 Move GPU Call Frame into GPU Backend class
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_backend.hpp
  src/ngraph/runtime/gpu/gpu_call_frame.cpp
  src/ngraph/runtime/gpu/gpu_call_frame.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
Labels: Fully Reviewed

#1664 Add Quantized conv+relu
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/quantized_conv_relu.cpp
  src/ngraph/runtime/cpu/op/quantized_conv_relu.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/quantization_util.cpp
  src/ngraph/runtime/cpu/quantization_util.hpp
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1661 add nGraph quantize op
  src/ngraph/CMakeLists.txt
  src/ngraph/coordinate.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/quantize.cpp
  src/ngraph/op/quantize.hpp
  src/ngraph/runtime/cpu/builder/quantize.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/op/quantize.cpp
  src/ngraph/runtime/cpu/op/quantize.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/argmax.hpp
  src/ngraph/runtime/reference/argmin.hpp
  src/ngraph/runtime/reference/broadcast.hpp
  src/ngraph/runtime/reference/max.hpp
  src/ngraph/runtime/reference/min.hpp
  src/ngraph/runtime/reference/product.hpp
  src/ngraph/runtime/reference/quantize.hpp
  src/ngraph/runtime/reference/reduce.hpp
  src/ngraph/runtime/reference/softmax.hpp
  src/ngraph/runtime/reference/sum.hpp
  src/ngraph/serializer.cpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  test/backend_test.in.cpp
  test/element_type.cpp
  test/models/mxnet/10_bucket_LSTM.json
  test/models/mxnet/mnist_mlp_forward.json
  test/quantize_cpu.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1675 add DropOut op and stub to Documentation ToC
  contrib/docker/Dockerfile.ngraph
  contrib/docker/Dockerfile.ngraph.centos74
  contrib/docker/Dockerfile.ngraph.ubuntu1604
  doc/sphinx/source/ops/checklist.txt
  doc/sphinx/source/ops/drop_out.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/ops/op_stub.rst
  doc/sphinx/source/project/code-contributor-README.rst
  doc/sphinx/source/project/doc-contributor-README.rst
Labels: Fully Reviewed

#1697 IntelGPU backend: ArgMax, ArgMin, LRN operations + Add Quantize op into IntelGPU
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: IntelGPU

#1682 Major cleanup of runtime::TensorView
  doc/examples/mnist_mlp/tensor_utils.hpp
  python/pyngraph/runtime/tensor_view.cpp
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.hpp
  src/ngraph/runtime/host_tensor_view.cpp
  src/ngraph/runtime/host_tensor_view.hpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/tensor_view.cpp
  src/ngraph/runtime/tensor_view.hpp
  src/tools/nbench/benchmark.cpp
  test/util/autodiff/numeric_compare.hpp
Labels: Changes API, Fully Reviewed, blocker

#1674 [ONNX CI] CI Speedup
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/prepare_environment.sh
Labels: Fully Reviewed, ONNX

#1707 set context current during each call
  src/ngraph/runtime/gpu/gpu_backend.cpp
Labels: Fully Reviewed, NvidiaGPU, bug fix

#1711 Cherry-pick #1709 (Fix get_index_element_type to return the correct type for IndexReduction OP)
  src/ngraph/op/util/index_reduction.cpp
Labels: Fully Reviewed

#1713 nbench. Fix exception handler output.
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#1714 IntelGPU backend: Add different types into dot operation
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1715 IntelGPU backend: Avoid scalar to matrix operation in clDNN
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, IntelGPU

#1717 IntelGPU backend: Compilation fix after pr1700
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#1694 set_output_size shouldn't reset existing outputs
  src/ngraph/node.cpp
  src/ngraph/runtime/cpu/pass/cpu_loop_kernel_fusion.cpp
Labels: Fully Reviewed

#1689 Address deferred comments from PR 1676
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_backend.hpp
Labels: Fully Reviewed

#1720 initialize all int32_t with 0 or 1 to make OneHot happt
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed
