Repository NervanaSystems/ngraph, pull requests merged in 2018-11, with the labels that each got.

#1889 GraphRewrite until fixed point
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/graph_rewrite.hpp
Labels: Fully Reviewed

#1942 Dropout for CPU
  src/ngraph/CMakeLists.txt
  src/ngraph/op/experimental/generate_mask.cpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/state.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/hybrid/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/reference/generate_mask.hpp
  src/ngraph/serializer.cpp
  src/ngraph/state/rng_state.cpp
  src/ngraph/state/rng_state.hpp
  src/ngraph/state/state.hpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1957 IntelGPU backend: Change exception type for unsupported op
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: IntelGPU

#1904 Partial Shapes and Types, Part 4m: BatchNorm and backprops
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/type_prop.cpp
Labels: Changes API, Fully Reviewed

#1954 [ONNX CI] Disable email notification on aborted builds
  .ci/onnx/jenkins/Jenkinsfile.groovy
  .ci/onnx/jenkins/utils/utils.groovy
Labels: Fully Reviewed

#1955 Update "JSON for Modern C++" to a version that officially supports gc…
  cmake/Modules/patch_json.cmake
  cmake/external_json.cmake
Labels: Fully Reviewed

#1950 fix centos gpu build
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#1961 Update unhandled op tests to support late validation
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1962 Update add_delta_to_slice to tolerate dynamic shapes and element types
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
Labels: Fully Reviewed

#1964 Change GetOutputElement to use delayed validation
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/get_output_element.hpp
Labels: Fully Reviewed

#1901 remove 5arg BNTraining
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/runtime/gpu/op/batch_norm.cpp
  src/ngraph/runtime/gpu/op/batch_norm.hpp
Labels: Fully Reviewed

#1959 IntelGPU backend: Function no cache usage control
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
Labels: Fully Reviewed, IntelGPU

#1958 print ngraph cmake option settings when running cmake
  CMakeLists.txt
Labels: Fully Reviewed

#1965 Update LRN for partial shape/type stuff
  src/ngraph/op/lrn.cpp
  src/ngraph/op/lrn.hpp
Labels: Fully Reviewed

#1966 add method to get ngraph version string
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.cpp
Labels: Fully Reviewed

#1963 Update BatchNorm to set_output_size at construction time
  src/ngraph/op/batch_norm.cpp
Labels: Fully Reviewed

#1968 Fix warnings in RNGState for clang on macosx
  src/ngraph/state/rng_state.hpp
Labels: Fully Reviewed

#1977 Make debug logging threadsafe
  src/ngraph/log.cpp
Labels: Fully Reviewed

#1960 enable hybrid test with graph splits
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/result.cpp
  src/ngraph/pass/assign_placement.cpp
  src/ngraph/pass/assign_placement.hpp
  src/ngraph/placement.cpp
  src/ngraph/placement.hpp
  test/hybrid_backend.cpp
  test/hybrid_utils.cpp
  test/hybrid_utils.hpp
Labels: Fully Reviewed

#1946 TopK additional tests for nvGPU backend
  src/ngraph/runtime/gpu/pass/gpu_layout.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/backend_topk.in.cpp
  test/gpu_test.cpp
Labels: Fully Reviewed, NvidiaGPU

#1987 Misc fixes for partial shapes
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/convert.cpp
  src/ngraph/op/convolution.cpp
Labels: Fully Reviewed

#1941 [ONNX] Support for external weights to enable Caffe2 models
  python/pyngraph/onnx_import/onnx_import.cpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/core/weight.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
Labels: Fully Reviewed, ONNX

#1992 Missing header
  src/ngraph/runtime/cpu/cpu_executor.hpp
Labels: Bug, Fully Reviewed

#1981 fix regex for version splitting
  CMakeLists.txt
Labels: Fully Reviewed

#2012 remove debug statement
  CMakeLists.txt
Labels: Fully Reviewed

#1971 Jbobba/halide
  cmake/external_halide.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/halide_op.cpp
  src/ngraph/runtime/cpu/pass/halide_subgraph_extraction.cpp
  test/CMakeLists.txt
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#1998 Add a real HybridBackend
  CMakeLists.txt
  src/ngraph/pass/assign_placement.cpp
  src/ngraph/runtime/CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_backend.hpp
  src/ngraph/runtime/hybrid/hybrid_backend.cpp
  src/ngraph/runtime/hybrid/hybrid_backend.hpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/tensor.hpp
  test/hybrid_backend.cpp
Labels: Fully Reviewed, High Priority

#1928 Do not fuse nodes if one node is predecessor of another node in horiz…
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#1986 Update pattern ops to propagate partial shapes
  src/ngraph/pattern/op/any.hpp
  src/ngraph/pattern/op/label.hpp
  src/ngraph/pattern/op/skip.hpp
Labels: Fully Reviewed

#1991 IAT: Collapse dims for Dot ops
  src/ngraph/runtime/cpu/builder/dot.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/kernel/dot.hpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
Labels: Fully Reviewed, IntelCPU

#2015 Isolate mutable pass managers
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_compiler.hpp
Labels: Fully Reviewed

#2016 [ONNX CI] 15 minutes without activity timeout
  .ci/onnx/jenkins/Jenkinsfile.groovy
Labels: Fully Reviewed, ONNX

#1993 [ONNXIFI] 1. Base PR for the ONNXIFI upcoming changes
  src/ngraph/frontend/onnxifi/backend_manager.cpp
  src/ngraph/frontend/onnxifi/onnxifi.cpp
  test/onnxifi.cpp
Labels: Fully Reviewed, ONNX

#2024 [ONNX CI] ONNX CI fixes
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/Jenkinsfile.groovy
  .ci/onnx/jenkins/utils/utils.groovy
Labels: Fully Reviewed, ONNX

#1988 nvgpu cuda reduce
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#1990 Address potential bug in cudnnGetReductionWorkspaceSize
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1994 [ONNXIFI] 2. Add exceptions for statuses
  src/ngraph/frontend/onnxifi/CMakeLists.txt
  src/ngraph/frontend/onnxifi/backend_manager.cpp
  src/ngraph/frontend/onnxifi/exceptions.hpp
  src/ngraph/frontend/onnxifi/onnxifi.cpp
Labels: Fully Reviewed, ONNX

#2030 Interpreter rework
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/relu.hpp
  src/ngraph/runtime/reference/reverse_sequence.hpp
  src/ngraph/runtime/reference/sigmoid.hpp
Labels: Fully Reviewed

#2019 Fix gtest and LLVM builds with ABI flag setting
  CMakeLists.txt
  cmake/external_gtest.cmake
  cmake/external_llvm.cmake
Labels: Fully Reviewed

#2029 Dropout for INT
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
Labels: Fully Reviewed

#2027 more cpu passes to static_pointer_cast
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#2031 Don't collapse unit size dimensions for dot ops
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2034 Swim a special case of Broadcast
  src/ngraph/runtime/cpu/pass/cpu_reshape_sinking.cpp
Labels: Fully Reviewed, IntelCPU

#2036 optimization for about 2x speedup
  src/ngraph/coordinate_transform.cpp
  src/ngraph/coordinate_transform.hpp
  src/ngraph/runtime/reference/convolution.hpp
Labels: Fully Reviewed

#2040 Update l2_norm and std_dev builders to use op::Sqrt
  src/ngraph/builder/reduce_ops.cpp
Labels: Fully Reviewed

#2037 catch exceptions for convert_layout for visualize_tree
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
Labels: Fully Reviewed, IntelCPU

#2020 Heterogenous serialized graph testing across backends
  test/CMakeLists.txt
  test/backend_graph_comparison.in.cpp
  test/util/all_close.hpp
  test/util/all_close_f.cpp
  test/util/test_control.hpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#2028 add isfinite check for all_close
  test/autodiff.in.cpp
  test/cpu_fusion.cpp
  test/gpu_fusion.cpp
  test/util/all_close.hpp
  test/util/all_close_f.cpp
Labels: Bug, Fully Reviewed

#2014 nvgpu softmax cuda version
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#2032 Faster argmax/argmin kernels
  src/ngraph/runtime/cpu/builder/argmax.cpp
  src/ngraph/runtime/cpu/builder/argmin.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/kernel/argmax.hpp
  src/ngraph/runtime/cpu/kernel/argmin.hpp
Labels: Fully Reviewed

#1956 Tracing for CPU
  src/ngraph/runtime/cpu/cpu_debugger.cpp
  src/ngraph/runtime/cpu/cpu_debugger.hpp
  test/cpu_debugger.cpp
Labels: Fully Reviewed, IntelCPU

#1933 Quantize(reorder) bias to int32
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization_util.hpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/type/element_type.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU

#1983 cse for convert layout
  src/ngraph/runtime/cpu/cpu_cse.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#1984 Moved mkldnn conv availability checks to utils and use it across passes
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#1969 [ONNX] Fix MatMul op for vec @ tensor multiplication
  src/ngraph/frontend/onnx_import/op/matmul.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
  test/models/onnx/matmul_vec_ten3d.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#2033 Add cudnn sum and test that exposes tf test failure for nvGPU
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/reference/sum.hpp
  test/backend_sum.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#2041 switch more passes to static_pointer_cast
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
Labels: Fully Reviewed

#2057 Fix the error in nbench for input tensor data
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed

#2058 remove exit call
  src/ngraph/runtime/cpu/unit_test.manifest
  test/backend_sum.in.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, High Priority

#2047 remove TensorFlow rounding mode HALF_AWAY_FROM_ZERO
  src/ngraph/op/quantize.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/reference/quantize.hpp
  test/constant_folding.cpp
  test/type_prop.cpp
Labels: Changes API, Fully Reviewed

#1996 [ONNXIFI] 3. Add class Span
  src/ngraph/frontend/onnxifi/CMakeLists.txt
  src/ngraph/frontend/onnxifi/span.hpp
  test/CMakeLists.txt
  test/onnxifi_span.cpp
Labels: Fully Reviewed, ONNX

#1997 [ONNXIFI] 4. Add class Tensor
  src/ngraph/frontend/onnxifi/CMakeLists.txt
  src/ngraph/frontend/onnxifi/tensor.cpp
  src/ngraph/frontend/onnxifi/tensor.hpp
Labels: Fully Reviewed, ONNX

#2059 Add test revealing issue in current cudnn pooling implementation.
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_pool.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#2066 Replaced the git command
  cmake/Modules/git_tags.cmake
Labels: Fully Reviewed

#2051 [ONNX] Enable transposed convolution
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/frontend/onnx_import/op/conv_transpose.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#2067 [ONNX] Add operator Size.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/size.cpp
  src/ngraph/frontend/onnx_import/op/size.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#2049 Support to selectively enable/disable passes through env variable
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/manager.hpp
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/pass_config.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed, IntelCPU

#2063 When processing in place slice, do not change the offset of the slice…
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2042 Support dynamic scales for quantization in the CPU backend
  src/ngraph/runtime/cpu/builder/quantization.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU

#2081 Sigmoid layout bugfix
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2038 Architecture and feature docs2
  ABOUT.md
  CONTRIB.md
  FAQs.md
  INSTALL.md
  README.md
  doc/sphinx/source/branding-notice.rst
  doc/sphinx/source/framework-integration-guides.rst
  doc/sphinx/source/frameworks/generic.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/validation-testing.rst
  doc/sphinx/source/graphics/descriptor-of-tensor.png
  doc/sphinx/source/graphics/develop-without-lockin.png
  doc/sphinx/source/graphics/develop-without-lockin.xcf
  doc/sphinx/source/graphics/full-ngstck.png
  doc/sphinx/source/graphics/full-ngstck.xcf
  doc/sphinx/source/graphics/ngraph-compiler-stack-readme.png
  doc/sphinx/source/graphics/ngraph-compiler-stack-readme.xcf
  doc/sphinx/source/graphics/stackngrknl.png
  doc/sphinx/source/graphics/stackngrknl.xcf
  doc/sphinx/source/project/about.rst
Labels: Fully Reviewed, β

#2068 support a general case Broadcast swimming for ReshapeSinking
  src/ngraph/runtime/cpu/pass/cpu_reshape_sinking.cpp
  test/cpu_reshape_sinking.cpp
Labels: Fully Reviewed, IntelCPU, β

#2065 Add MaxPool as an explicit argument to MaxPoolBackprop
  python/pyngraph/ops/max_pool.cpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
Labels: Changes API, Fully Reviewed, High Priority, β

#2069 check if the nodes are reachable before returning the users of a node
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  test/util.cpp
Labels: Fully Reviewed, β

#2073 Update SDL
  CMakeLists.txt
  cmake/sdl.cmake
  src/ngraph/node.cpp
Labels: Fully Reviewed, β

#2088 Add more checks in horizontal fusion.
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
Labels: Bug, Fully Reviewed, β

#2071 Convert layout early to get more efficient MKLDNN kernels
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU, β

#2091 Re-enable one hot unit tests on CPU backend (non-exception cases only)
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed, β

#2075 AnyOf for nodes with a variable number of arguments
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/pattern/op/any_of.hpp
  test/pattern.cpp
Labels: Fully Reviewed, β

#2077 add license badge
  README.md
Labels: Fully Reviewed, β

#2074 Build clDNN when building IntelGPU
  CMakeLists.txt
  cmake/external_cldnn.cmake
  src/ngraph/runtime/intelgpu/CMakeLists.txt
Labels: Fully Reviewed, IntelGPU, β

#2082 bug fix, hang for compiling
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Bug, Fully Reviewed, NvidiaGPU, β

#2089 only check for prebuilt llvm and API flags if llvm is used in build
  CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
Labels: Fully Reviewed, β

#2093 Re-enable disabled INTERPRETER tests
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/unit_test.manifest
Labels: Fully Reviewed, β

#1945 [ONNX] LSTM node
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/lstm.hpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
Labels: ONNX

#2070 Use cuda_reduce for int32 & int8 input_type instead of cudnn_reduce
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/nvshape.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_sum.in.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU, β

#2084 [ONNX] Run ONNX CI on CPU and INTERPRETER
  .ci/onnx/jenkins/runCI.sh
Labels: Fully Reviewed, ONNX, β

#2099 Fix check to prevent in-tree builds
  .gitignore
  CMakeLists.txt
Labels: Fully Reviewed, β

#2098 klocwork issue
  src/ngraph/pass/memory_layout.cpp
Labels: Fully Reviewed, β

#2087 move get_ngraph_version_string() to a separate source file
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/ngraph_version.cpp
Labels: Fully Reviewed, β

#1970 Update MKLDNN v0.16 -> v0.17
  cmake/external_mkldnn.cmake
  cmake/mkldnn.diff
  cmake/mkldnn.patch
Labels: Fully Reviewed, IntelCPU, β

#2100 fix memory leak
  src/ngraph/runtime/cpu/builder/quantization.cpp
Labels: Fully Reviewed, IntelCPU, β

#2092 Architecture and feature docs3
  README.md
  doc/sphinx/cmake_install.cmake
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/frameworks/validation-testing.rst
  doc/sphinx/source/glossary.rst
  doc/sphinx/source/graphics/ngraph_wireframes_with_notice.png
  doc/sphinx/source/graphics/ngraph_wireframes_with_notice.xcf
  doc/sphinx/source/project/about.rst
  ecosystem-overview.md
Labels: Documentation, Fully Reviewed, β

#2107 Update ABOUT.md
  ABOUT.md
  doc/sphinx/source/graphics/full-ngstck.png
  doc/sphinx/source/graphics/stackngrknl.png
Labels: Documentation, High Priority, β

#2108 Removed verbose phrases
  README.md
Labels: Documentation, High Priority, β

#2109 Fix rendering issue with MXNet workloads
  doc/sphinx/source/frameworks/validation-testing.rst
Labels: Documentation, High Priority, β

#2118 disable squeeze layout optimizations for padded layouts
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Fully Reviewed, IntelCPU, β

#2103 Disable CF on CPU
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU, β

#2121 On macos,
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/tools/nbench/CMakeLists.txt
Labels: Fully Reviewed, β

#2124 Update external libraries to optionally not version label shared libraries
  cmake/external_mkldnn.cmake
  cmake/mkldnn_no_so_link.patch
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed, β

#2117 Add release notes and improve rendering of changes.md
  README.md
  contrib/docker/Dockerfile.ngraph
  contrib/docker/Dockerfile.ngraph.centos74
  contrib/docker/Dockerfile.ngraph.centos74_gpu
  contrib/docker/Dockerfile.ngraph.ubuntu1604
  contrib/docker/Dockerfile.ngraph.ubuntu1604_gpu
  doc/sphinx/source/conf.py
  doc/sphinx/source/framework-integration-guides.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed, β

#2130 [Py] Change package name to ngraph-core
  python/setup.py
Labels: Fully Reviewed, β

#2112 Add NGRAPH_PYTHON_BUILD_ENABLE option to cmake.
  CMakeLists.txt
Labels: Fully Reviewed, β

#2114 Fix uninitialized parameter tensor data in nbench
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed, β

#2131 Re-enable CPU.batchnorm_bprop_n4c3h2w2
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed, β

#2132 copy license files to install directory
  CMakeLists.txt
Labels: β

#2129 Cyphers/bnorm back
  python/ngraph/ops.py
  python/pyngraph/ops/batch_norm.cpp
  src/ngraph/descriptor/input.hpp
  src/ngraph/descriptor/layout/tensor_layout.hpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/kernel/batchnorm.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/reference/batch_norm.hpp
  src/ngraph/serializer.cpp
  test/autodiff.in.cpp
  test/backend_test.in.cpp
  test/cpu_fusion.cpp
  test/type_prop.cpp
Labels: Fully Reviewed, β

#2135 Apply NGRAPH_TARGET_ARCH to mkldnn build also.
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed, High Priority, β

#2137 Fix title
  doc/sphinx/source/branding-notice.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/about.rst
Labels: β

#2138 Add license files and cleanup compiler/linker options.
  python/setup.py
Labels: Fully Reviewed, β

#2139 Add license files for:
  licenses/eigen-license.txt
  licenses/googletest-license.txt
  licenses/json-license.txt
  licenses/llvm-license.txt
  licenses/mkl-dnn-license.txt
  licenses/mklml-license.txt
  licenses/numpy-license.txt
  licenses/tbb-license.txt
  licenses/tensorflow-license.txt
Labels: β

#2147 Add notifications file for eigen
  licenses/notifications.txt
Labels: β

#2148 Update setup.py
  python/setup.py
Labels: Fully Reviewed, High Priority, β

#2146 Architecture and feature docs5
  README.md
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/conf.py
  doc/sphinx/source/framework-integration-guides.rst
  doc/sphinx/source/frameworks/validation-testing.rst
Labels: Documentation, Fully Reviewed, High Priority
