Repository NervanaSystems/ngraph, pull requests merged in 2018-10, with the labels that each got.

#1659 Add CODEOWNERS file
  CODEOWNERS
Labels: Fully Reviewed

#1704 Sigmoid and tanh doc, edit for abs
  doc/sphinx/source/ops/sigmoid.rst
  doc/sphinx/source/ops/tanh.rst
  src/ngraph/op/tanh.hpp
Labels: Fully Reviewed

#1698 GPU External Function cleanup
  src/ngraph/runtime/gpu/cuda_error_check.hpp
  src/ngraph/runtime/gpu/cudnn_descriptors.hpp
  src/ngraph/runtime/gpu/gpu_cuda_context_manager.cpp
  src/ngraph/runtime/gpu/gpu_cuda_context_manager.hpp
  src/ngraph/runtime/gpu/gpu_cuda_function_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_function_pool.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
  src/ngraph/runtime/gpu/gpu_runtime_context.cpp
  src/ngraph/runtime/gpu/gpu_runtime_context.hpp
  src/ngraph/runtime/gpu/gpu_tensor_view.cpp
  src/ngraph/runtime/gpu/gpu_util.cpp
  src/ngraph/runtime/gpu/gpu_util.hpp
  src/ngraph/runtime/gpu/pass/tensor_memory_reservation.cpp
  src/ngraph/runtime/gpu/pass/tensor_memory_reservation.hpp
Labels: Fully Reviewed, NvidiaGPU

#1722 Rename GPU_TensorView to GPUTensor
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
  src/ngraph/runtime/gpu/gpu_kernel_emitters.cpp
  src/ngraph/runtime/gpu/gpu_kernel_emitters.hpp
  src/ngraph/runtime/gpu/gpu_tensor.cpp
  src/ngraph/runtime/gpu/gpu_tensor.hpp
  src/ngraph/runtime/gpu/gpu_tensor_wrapper.cpp
  src/ngraph/runtime/gpu/gpu_tensor_wrapper.hpp
Labels: Fully Reviewed, NvidiaGPU

#1677 Pruthvi/rnn fusion
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1692 Partial Shapes, Part 1: Classes for partially known shapes, possibly unknown dimensions
  src/ngraph/CMakeLists.txt
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/rank.hpp
  test/CMakeLists.txt
  test/partial_shape.cpp
Labels: Fully Reviewed

#1723 print the entire path of the file printing relative to the project root
  CMakeLists.txt
  src/ngraph/log.hpp
Labels: Fully Reviewed

#1729 IntelGPU backend: Datatype workaround for NCF model
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed, IntelGPU

#1736 IntelGPU backend: Operation Reduce implemented
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: IntelGPU

#1735 add doctools js from basic theme sphinx repo
  doc/sphinx/ngraph_theme/layout.html
  doc/sphinx/ngraph_theme/static/js/doctools.js
  doc/sphinx/ngraph_theme/static/js/searchtools.js
Labels: Fully Reviewed

#1745 fix resize bug in gpu memory manager.
  src/ngraph/runtime/gpu/gpu_memory_manager.cpp
Labels: Bug, Fully Reviewed, NvidiaGPU

#1749 address klocwork issue 13183
  src/ngraph/pass/visualize_tree.cpp
Labels: Fully Reviewed

#1733 Show types in VisualizeTree
  src/ngraph/pass/visualize_tree.cpp
Labels: Fully Reviewed

#1741 nvgpu maxpool bug fix
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  test/backend_test.in.cpp
Labels: Bug, Fully Reviewed, NvidiaGPU

#1734 address potential double free memory
  src/ngraph/runtime/cpu/cpu_call_frame.hpp
  src/ngraph/runtime/gpu/gpu_tensor.hpp
Labels: Fully Reviewed

#1718 Partial Shapes, Part 2: Adapt Tensor class to have partial shapes
  src/ngraph/descriptor/input.cpp
  src/ngraph/descriptor/input.hpp
  src/ngraph/descriptor/output.cpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  test/partial_shape.cpp
Labels: Fully Reviewed

#1747 address klocwork issue
  src/ngraph/runtime/cpu/cpu_layout_descriptor.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
Labels: Fully Reviewed

#1750 address klocwork issues 14714, 17248, and 18661
  doc/examples/update/update.cpp
  src/ngraph/placement.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#1751 address klocwork number overflow issue
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/pass/cpu_concat_inputs.cpp
Labels: Fully Reviewed

#1753 Properly support global stats in BN
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Bug, Fully Reviewed, NvidiaGPU

#1757 Add asserts to reference to make sure we don't overshoot iterators
  src/ngraph/runtime/reference/concat.hpp
  src/ngraph/runtime/reference/pad.hpp
  src/ngraph/runtime/reference/replace_slice.hpp
  src/ngraph/runtime/reference/reshape.hpp
  src/ngraph/runtime/reference/slice.hpp
Labels: Fully Reviewed

#1459 RNN fusion (inference)
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/cudnn_descriptors.hpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/op/op_tbl.hpp
  src/ngraph/runtime/gpu/op/rnn.cpp
  src/ngraph/runtime/gpu/op/rnn.hpp
  src/ngraph/runtime/gpu/pass/gpu_rnn_fusion.cpp
  src/ngraph/runtime/gpu/pass/gpu_rnn_fusion.hpp
  test/CMakeLists.txt
  test/gpu_fusion.cpp
Labels: Fully Reviewed, NvidiaGPU

#1739 Changes to make Klocwork a little happier
  doc/examples/mnist_mlp/mnist_loader.cpp
  doc/examples/mnist_mlp/mnist_loader.hpp
  src/ngraph/cpio.cpp
  src/ngraph/cpio.hpp
  src/ngraph/op/result_vector.hpp
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/runtime/reference/avg_pool.hpp
  src/resource/main.cpp
Labels: Fully Reviewed

#1748 address klocwork issue
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
Labels: Fully Reviewed

#1755 CPU: Make DEX mode the default
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1740 Support LRN for NVGPU Backend
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
Labels: Fully Reviewed, NvidiaGPU

#1761 Eliminated two warnings introduced in #1459
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#1712 IAT: More convolution folding optimizations
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, ONNX

#1684 IAT: Skip reshapes that are removing or adding size-1 dimensions
  src/ngraph/runtime/cpu/cpu_layout_descriptor.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#1759 Update pad on nvpgu
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1765 optimize operator==
  src/ngraph/coordinate_transform.cpp
Labels: Fully Reviewed

#1769 IAT: Add bounds check for MKLDNN layout creation
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
Labels: Fully Reviewed

#1766 enable some unit tests that were disabled.
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1776 Update nGraph version number in Sphinx to version number v0.9
  doc/sphinx/source/conf.py
Labels: Fully Reviewed

#1701 Reshape Sinking
  src/ngraph/node.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/pass/cpu_reshape_sinking.cpp
  src/ngraph/runtime/cpu/pass/cpu_reshape_sinking.hpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
  test/CMakeLists.txt
  test/cpu_reshape_sinking.cpp
  test/models/tf_conv_mnist_nhwc.json
Labels: Fully Reviewed

#1773 nvgpu one hot update
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#1785 add back missing part for find algo for build convolution.
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#1760 updated unit tests
  test/coordinate.cpp
Labels: Fully Reviewed

#1805 make sure that data/weights/add are all of the right shapes
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
Labels: Bug, Fully Reviewed, High Priority

#1788 Modify slice layout.
  src/ngraph/node.hpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/kernel/softmax.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_reshape_sinking.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, High Priority, ONNX

#1810 [ONNX]: fix compilation of ONNX Python via setup.py
  .ci/onnx/jenkins/prepare_environment.sh
  .ci/travis/ubuntu/Dockerfile
  src/ngraph/node.hpp
Labels: Fully Reviewed, ONNX

#1737 Support ArgMin and ArgMax for NVGPU Backend
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1767 validate includes
  src/ngraph/runtime/cpu/kernel/result.hpp
  src/ngraph/runtime/cpu/kernel/softmax.hpp
  src/ngraph/runtime/gpu/gpu_host_parameters.hpp
  src/ngraph/runtime/performance_counter.hpp
  test/CMakeLists.txt
  test/includes.cpp
Labels: Fully Reviewed

#1797 Handle workspace reservation when workspace size is zero
  src/ngraph/runtime/gpu/gpu_memory_manager.cpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.cpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.hpp
  test/gpu_test.cpp
Labels: Fully Reviewed, NvidiaGPU

#1806 Leona/10112018
  README.md
  doc/sphinx/source/graphics/599px-Intel-ngraph-ecosystem.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/about.rst
  doc/sphinx/source/project/doc-contributor-README.rst
  doc/sphinx/source/project/release-notes.rst
Labels: Documentation, Fully Reviewed

#1764 Handle zero sized buffer requests
  src/ngraph/runtime/aligned_buffer.cpp
  src/ngraph/runtime/aligned_buffer.hpp
Labels: Fully Reviewed

#1790 Normalize license headers
  src/ngraph/distributed.cpp
  src/ngraph/distributed.hpp
  src/ngraph/frontend/onnx_import/op/max.hpp
  src/ngraph/frontend/onnx_import/op/mean.cpp
  src/ngraph/frontend/onnx_import/op/mean.hpp
  src/ngraph/frontend/onnx_import/op/min.hpp
  src/ngraph/frontend/onnx_import/op/sum.hpp
  src/ngraph/frontend/onnx_import/utils/variadic.hpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/runtime/cpu/builder/dequantize.cpp
  src/ngraph/runtime/cpu/builder/quantize.cpp
  src/ngraph/runtime/cpu/builder/quantized_avg_pool.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/builder/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/builder/topk.cpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/conv_add.hpp
  src/ngraph/runtime/cpu/op/dequantize.cpp
  src/ngraph/runtime/cpu/op/dequantize.hpp
  src/ngraph/runtime/cpu/op/quantize.cpp
  src/ngraph/runtime/cpu/op/quantize.hpp
  src/ngraph/runtime/cpu/op/quantized_avg_pool.cpp
  src/ngraph/runtime/cpu/op/quantized_avg_pool.hpp
  src/ngraph/runtime/cpu/op/quantized_conv.cpp
  src/ngraph/runtime/cpu/op/quantized_conv.hpp
  src/ngraph/runtime/cpu/op/quantized_conv_relu.cpp
  src/ngraph/runtime/cpu/op/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/op/quantized_max_pool.hpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.hpp
  src/ngraph/runtime/cpu/quantization_util.hpp
  src/ngraph/runtime/reference/topk.hpp
  test/control_dependencies.cpp
  test/gpu_fusion.cpp
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1814 Tweak to GPUPrimitiveEmitter::lookup
  src/ngraph/runtime/gpu/gpu_primitive_emitter.cpp
  src/ngraph/runtime/gpu/gpu_primitive_emitter.hpp
Labels: Fully Reviewed, NvidiaGPU

#1719 Fold some unary and binary ops
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed, ONNX

#1771 remove the contains() funtion from util as it can lead to bad usage
  src/ngraph/codegen/compiler.cpp
  src/ngraph/pass/memory_visualize.cpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/util.hpp
  test/backend_api.cpp
  test/util.cpp
Labels: Fully Reviewed

#1813 Improved AvgPool unit test coverage. Fixed small bug that was revealed.
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1687 [ONNX] Add ENV Flag to compile onnx import
  .ci/onnx/jenkins/prepare_environment.sh
  .ci/travis/run_test.sh
  .ci/travis/ubuntu/Dockerfile
  python/ngraph/impl/onnx_import/__init__.py
  python/pyngraph/pyngraph.cpp
  python/pyngraph/pyngraph_onnx_import.cpp
  python/setup.py
  python/tox.ini
Labels: Fully Reviewed, ONNX

#1738 [ONNX] Use ONNX_ML headers
  cmake/external_onnx.cmake
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/op/cast.cpp
Labels: Fully Reviewed, ONNX

#1746 [ONNX] Update Squeeze Op to conform with doc.
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  test/models/onnx/squeeze_duplicate_axes.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, Merge Blocked, ONNX

#1770 [ONNX] Assert all op types supported
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.cpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/op/cast.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.hpp
  test/models/onnx/unsupported_op.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1802 enable code coverage flag via cmake
  CMakeLists.txt
Labels: Fully Reviewed

#1780 run Quantize / Dequantize reference kernels on CPU backend
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed

#1816 handle unsupported ops
  src/ngraph/cpio.cpp
  src/ngraph/cpio.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#1807 Type prop tests for Quantize/Dequantize
  src/ngraph/op/dequantize.cpp
  src/ngraph/op/quantize.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1808 don't optimize Add(Dot) if there's just one data node
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
Labels: Fully Reviewed

#1809 mat_fusion 4d test case
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#1824 [ONNX CI] ONNX CI Improvements
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/prepare_environment.sh
Labels: Fully Reviewed, ONNX

#1825 Cleanup grammar on documentation for tensor and backend
  doc/sphinx/source/ops/index.rst
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/tensor.hpp
Labels: Fully Reviewed

#1786 reset buffer size, use original input size for memcpy
  src/ngraph/runtime/gpu/gpu_memory_manager.cpp
  test/gpu_test.cpp
Labels: Fully Reviewed, NvidiaGPU

#1834 IntelGPU backend: ArgMin/ArgMax functionality was fixed; Tests on unsupported functionality were disabled
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#1823 [ONNX] Global Pool ops
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/op/global_average_pool.cpp
  src/ngraph/frontend/onnx_import/op/global_average_pool.hpp
  src/ngraph/frontend/onnx_import/op/global_max_pool.cpp
  src/ngraph/frontend/onnx_import/op/global_max_pool.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
Labels: Fully Reviewed, ONNX

#1826 Minor GPU code cleanup
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
Labels: Fully Reviewed

#1835 [ONNX] Fix batchnorm attribute variable type.
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
Labels: Fully Reviewed, ONNX

#1837 Doc for result and subtract.
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/ops/result.rst
  doc/sphinx/source/ops/subtract.rst
  src/ngraph/op/result.hpp
  src/ngraph/op/subtract.hpp
Labels: Fully Reviewed

#1833 Constant folding with Quantize
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#1830 Quantize and Dequantize documentation
  doc/sphinx/source/ops/dequantize.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/ops/quantize.rst
  src/ngraph/op/dequantize.hpp
  src/ngraph/op/quantize.hpp
Labels: Fully Reviewed

#1845 IntelGPU backend: GNMT training enabling: Added Negative operation functionality for i32 data type
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#906 Added the capability of directly compiling cuda and ptx to CMake.
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/nvcc/example.cu.cpp
  src/ngraph/runtime/gpu/nvcc/kernels.hpp
Labels: Fully Reviewed, NvidiaGPU

#1836 Fixed doc warning: param -> tparam
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
Labels: Fully Reviewed

#1844 Enums should be moved to public to access
  src/ngraph/pass/constant_folding.hpp
Labels: Fully Reviewed

#1847 [ONNX] remove "unlikely()" macro
  src/ngraph/frontend/onnx_import/core/attribute.hpp
Labels: Fully Reviewed, ONNX

#1846 [ONNX] flatten operators bridge
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.hpp
Labels: Fully Reviewed, ONNX

#1849 Update new docbuild requirements to python3-sphinx (new in 1.7.5)
  doc/sphinx/source/project/doc-contributor-README.rst
Labels: Fully Reviewed

#1838 CMake cleanup
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/interpreter/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#1799 Partial Shapes and Types, Part 4f: Pad
  src/ngraph/op/pad.cpp
  src/ngraph/op/pad.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1850 Quantized and Dequantize doc fixes
  doc/sphinx/source/ops/dequantize.rst
  doc/sphinx/source/ops/quantize.rst
  src/ngraph/op/dequantize.hpp
  src/ngraph/op/quantize.hpp
Labels: Fully Reviewed

#1853 Cuda < 9 compilation fix suggested by Chris Sullivan
  src/ngraph/runtime/gpu/CMakeLists.txt
Labels: Fully Reviewed

#1778 Partial Shapes and Types, Part 4b: Concat
  src/ngraph/op/concat.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1783 Partial Shapes and Types, Part 4d: Broadcast
  src/ngraph/op/broadcast.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1800 Partial Shapes and Types, Part 4g: Select
  src/ngraph/op/select.cpp
  src/ngraph/op/select.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1781 Partial Shapes and Types, Part 4c: Slice and ReplaceSlice
  src/ngraph/op/replace_slice.cpp
  src/ngraph/op/replace_slice.hpp
  src/ngraph/op/slice.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1787 Partial Shapes and Types, Part 4e: Dot
  src/ngraph/op/dot.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1851 cast to ArgMin/ArgMax based on reduce_op
  src/ngraph/runtime/gpu/gpu_emitter.cpp
Labels: Fully Reviewed, NvidiaGPU

#1831 Add support for perf counter collection in DEX
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/performance_counter.hpp
Labels: Fully Reviewed

#1857 Flush denormals to zero in nbench
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed

#1866 fix centos compile warning
  src/ngraph/runtime/interpreter/int_backend.cpp
Labels: Fully Reviewed

#1865 Move unit tests out of backend_test.in.cpp
  test/CMakeLists.txt
  test/backend_binary_elementwise.in.cpp
  test/backend_broadcast.in.cpp
  test/backend_comparison.in.cpp
  test/backend_dot.in.cpp
  test/backend_one_hot.in.cpp
  test/backend_reduce.in.cpp
  test/backend_reshape.in.cpp
  test/backend_sum.in.cpp
  test/backend_test.in.cpp
  test/backend_unary_elementwise.in.cpp
Labels: Fully Reviewed

#1842 Partial Shapes and Types, Part 4j: Quantize/Dequantize
  src/ngraph/op/dequantize.cpp
  src/ngraph/op/quantize.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1871 Partial Shapes and Types, Part 4k: AvgPool/MaxPool and backprops
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/partial_shape.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1870 Add missing include to benchmark.cpp
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed

#1873 IntelGPU backend: Fix place for the backend library
  src/ngraph/runtime/intelgpu/CMakeLists.txt
Labels: Bug, IntelGPU

#1863 IntelGPU backend: Profiling with various statistics
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
Labels: Fully Reviewed, IntelGPU

#1832 Partial Shapes and Types, Part 4i: OneHot
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/one_hot.hpp
  src/ngraph/serializer.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1875 GPU backend: Fix compilation on Ubuntu 18 gcc 7.3
  src/ngraph/runtime/gpu/gpu_runtime_context.hpp
Labels: Fully Reviewed, NvidiaGPU

#1829 Partial Shapes and Types, Part 4h: IndexReduction
  src/ngraph/op/util/index_reduction.cpp
  src/ngraph/op/util/index_reduction.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1880 move unit tests out of backend_test.in.cpp
  test/CMakeLists.txt
  test/backend_pool.in.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1881 [ONNX CI] Fix manual reproduction script
  .ci/onnx/jenkins/README.md
  .ci/onnx/jenkins/runCI.sh
Labels: Fully Reviewed, ONNX

#1828 BatchNorm splitting into ops (2nd try)
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/batch_norm.cpp
  python/pyngraph/ops/batch_norm.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.cpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/serializer.cpp
  test/autodiff.in.cpp
  test/backend_test.in.cpp
  test/cpu_fusion.cpp
  test/models/tf_conv_mnist_nhwc.json
  test/type_prop.cpp
Labels: Changes API, Fully Reviewed

#1763 IAT: Collapse dimensions around arithmetic reduction operations
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#1859 add support for Quantize round mode
  doc/sphinx/source/ops/quantize.rst
  src/ngraph/op/quantize.cpp
  src/ngraph/op/quantize.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/reference/quantize.hpp
  test/backend_test.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1886 faster topological sort
  src/ngraph/descriptor/input.hpp
  src/ngraph/graph_util.hpp
Labels: Fully Reviewed

#1891 fix compiler warnings
  cmake/clang_4_0_flags.cmake
  src/ngraph/op/batch_norm.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/op/halide_op.cpp
  src/ngraph/runtime/cpu/op/halide_op.hpp
  src/ngraph/type/bfloat16.cpp
  src/ngraph/type/bfloat16.hpp
Labels: High Priority

#1856 [ONNX] add the ability to register custom ONNX operators
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/attribute.cpp
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.cpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/core/operator_set.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.hpp
  test/models/onnx/custom_operator.onnx
  test/models/onnx/custom_operator_default_domain.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1892 IntelGPU backend: Compilation fix after pr1828
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, High Priority, IntelGPU

#1885 Preprocess input variance into BN denominator for cudnn
  src/ngraph/op/util/op_annotations.hpp
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_op_annotations.hpp
  src/ngraph/runtime/gpu/pass/gpu_batch_norm_cache.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1864 [ONNX] Non-linear ops
  src/ngraph/frontend/onnx_import/op/prelu.cpp
Labels: Fully Reviewed, ONNX

#1879 [ONNX] Enable Trigonometric ops
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/acos.hpp
  src/ngraph/frontend/onnx_import/op/asin.hpp
  src/ngraph/frontend/onnx_import/op/atan.hpp
  src/ngraph/frontend/onnx_import/op/cos.hpp
  src/ngraph/frontend/onnx_import/op/sin.hpp
  src/ngraph/frontend/onnx_import/op/tan.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#1905 [ONNX CI] Update GitHub credentials
  .ci/onnx/jenkins/Jenkinsfile
  python/test/ngraph/test_basic.py
  python/tox.ini
Labels: Fully Reviewed, ONNX

#1877 [ONNX] Gemm fix
  src/ngraph/frontend/onnx_import/op/gemm.cpp
Labels: Fully Reviewed, ONNX

#1902 fix Klockwork warnings CPU part 1
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
  src/ngraph/runtime/cpu/pass/cpu_concat_inputs.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed

#1890 Partial Shapes and Types, Part 4λ: Convolution and backprops
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1862 ArgReduce 64 bit indices
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1910 m_direct_execution is used but not defined when NGRAPH_DEX_ONLY=TRUE
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed, High Priority

#1906 update git_tags to handle the case where there are no labels in the repo
  cmake/Modules/git_tags.cmake
Labels: Fully Reviewed

#1774 Add in place concat optimization.
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.hpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#1912 Partial Shapes and Types, Part 4n: TopK
  src/ngraph/op/topk.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#1913 Fix for AllReduce partial shape/type validation
  src/ngraph/op/allreduce.cpp
Labels: Fully Reviewed

#1914 Partial Shapes and Types, Part 4o: Sigmoid/SigmoidBackprop
  src/ngraph/op/sigmoid.cpp
  src/ngraph/op/sigmoid.hpp
Labels: Fully Reviewed

#1922 ArgMin/ArgMax Interpreter fix
  src/ngraph/runtime/interpreter/int_backend.cpp
Labels: Fully Reviewed

#1915 [ONNX CI] Multibranch Pipeline Jenkinsfile
  .ci/onnx/jenkins/Jenkinsfile.groovy
Labels: Fully Reviewed, ONNX

#1918 Add a Concat case to ZeroDimensionTensor
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#1839 Add builder for {de}quantize to make API's consistent and support {de}quantize with mkldnn
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization_util.hpp
  src/ngraph/op/experimental/quantized_conv.cpp
  src/ngraph/op/experimental/quantized_conv_bias.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/CMakeLists.txt
  test/backend_test.in.cpp
  test/builder_quantization.cpp
  test/quantize_cpu.cpp
Labels: Fully Reviewed

#1903 Reenabled Chris's nvcc building
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/nvcc/example.cu.cpp
  src/ngraph/runtime/gpu/nvcc/kernels.hpp
Labels: Fully Reviewed, NvidiaGPU

#1925 IntelGPU backend: Add graph dump ability
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
  src/ngraph/runtime/intelgpu/visualize_tree.hpp
Labels: Fully Reviewed, IntelGPU

#1894 nvgpu concat split
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1917 Move to TBB2019 and bug fix to capture functor
  CMakeLists.txt
  cmake/external_tbb.cmake
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
Labels: Fully Reviewed

#1923 remove js
  doc/sphinx/ngraph_theme/static/js/searchtools.js
Labels: Fully Reviewed

#1930 always using create_gpu_buffer and free_gpu_buffer instead of cudamalloc and cudafree
  src/ngraph/runtime/gpu/gpu_tensor.cpp
Labels: Fully Reviewed, NvidiaGPU

#1935 IntelGPU backend: Improved dump graph functionality
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#1932 IntelGPU backend: Profile data improved
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#1908 Support TopK for NvidiaGPU backend
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_kernel_args.hpp
  src/ngraph/runtime/gpu/pass/gpu_layout.cpp
  src/ngraph/runtime/gpu/pass/gpu_layout.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/CMakeLists.txt
  test/backend_arg_reduce.in.cpp
  test/backend_test.in.cpp
  test/backend_topk.in.cpp
Labels: Fully Reviewed, NvidiaGPU

#1938 Hybrid transformer test
  test/CMakeLists.txt
  test/hybrid_backend.cpp
  test/hybrid_utils.cpp
  test/hybrid_utils.hpp
Labels: Fully Reviewed

#1934 IntelGPU backend: Implemented some clDNN controls
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
Labels: Fully Reviewed, IntelGPU

#1936 IntelGPU backend: Add Slice to dump
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#1937 remove platform.cmake
  CMakeLists.txt
  cmake/platform.cmake
Labels: Fully Reviewed

#1898 [ONNX] Add ArgMin/Max operators
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/argmax.cpp
  src/ngraph/frontend/onnx_import/op/argmax.hpp
  src/ngraph/frontend/onnx_import/op/argmin.cpp
  src/ngraph/frontend/onnx_import/op/argmin.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  test/models/onnx/argmin_no_keepdims.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#1924 [ONNX] Support for legacy broadcasting rules
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.hpp
Labels: Fully Reviewed, ONNX

#1939 Correct sentence-case on link and correct a typo
  doc/sphinx/source/howto/update.rst
  doc/sphinx/source/project/about.rst
Labels: Fully Reviewed

#1944 Fix call to reference quantize
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed

#1951 [ONNX] Update pybind11 git repo link
  python/README.md
Labels: Fully Reviewed, ONNX

#1948 [PlaidML] Specialize within namespaces (for Linux)
  src/ngraph/runtime/plaidml/plaidml_ops_arithmetic.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_batch_norm.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_comparison.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_concat.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_convert.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_convolution.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_dot.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_function.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_general.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_index_reduction.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_io.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_local_response_norm.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_logical.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_one_hot.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_pool.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_reduce.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_replace_slice.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_reverse.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_slice.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_softmax.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_transcendental.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, PlaidML

#1952 IntelGPU backend: Remove nodes "Result" from cldnn::topology
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU
