Repository NervanaSystems/ngraph, pull requests merged in 2019-01, with the labels that each got.

#2266 print llvm build choice and allow cmake arg to override env var
  CMakeLists.txt
Labels: Fully Reviewed

#2246 Fix numeric instability in batchnorm bprop
  src/ngraph/runtime/reference/batch_norm.hpp
Labels: Bug, Fully Reviewed

#2277 add version.hpp to ngraph install files for external backends
  src/ngraph/CMakeLists.txt
  src/ngraph/version.in.hpp
Labels: Fully Reviewed

#2278 Fix a throw in slice cpu_memory_optimization.cpp due to unsupported i64 in MKLDNN
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
Labels: Bug, Fully Reviewed, IntelCPU

#2254 [NGCORE-270] UT for Softplus ONNX operator testing edge cases.
  src/ngraph/frontend/onnx_import/op/softplus.cpp
  test/models/onnx/softplus.onnx
  test/onnx_import.cpp
Labels: ONNX

#2285 Simplified all_close_f interface and tightened default criteria
  test/all_close_f.cpp
  test/backend_graph_comparison.in.cpp
  test/backend_sum.in.cpp
  test/backend_test.in.cpp
  test/backend_topk.in.cpp
  test/gpu_test.cpp
  test/util/all_close_f.cpp
  test/util/all_close_f.hpp
Labels: Fully Reviewed

#2289 [ONNX] ConvTranspose with groups.
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  test/models/onnx/conv_transpose_w_groups.onnx
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#2286 [onnx] fix building while NGRAPH_ONNXIFI_ENABLE is off
  CMakeLists.txt
  src/ngraph/frontend/onnx_import/CMakeLists.txt
Labels: Fully Reviewed

#2290 Use plaidml cmake config
  CMakeLists.txt
  src/ngraph/runtime/CMakeLists.txt
  src/ngraph/runtime/plaidml/CMakeLists.txt
Labels: Fully Reviewed, PlaidML

#2250 any/all stop-gap CPU implementation
  src/ngraph/runtime/cpu/builder/reduce_function.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed, IntelCPU

#2256 [NGCPU-339] UT for ArgMin ArgMax with int32 input data type.
  test/models/onnx/argmax_int32.onnx
  test/models/onnx/argmin_int32.onnx
  test/onnx_import.cpp
Labels: Bug, Fully Reviewed, ONNX

#2294 IntelGPU backend: fix typo in BatchNorm handling
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Bug, Fully Reviewed, IntelGPU

#2291 Allow external mklml outside of prebuilt mkldnn install directory.
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed

#2295 Replace relu implementation with element_wise
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
Labels: Fully Reviewed, IntelCPU

#2298 Add support for negative padding in Pad Op
  src/ngraph/frontend/onnx_import/op/pad.cpp
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/kernel/pad.cpp
  src/ngraph/runtime/cpu/kernel/pad.hpp
  test/backend_test.in.cpp
Labels: IntelCPU

#2280 IntelGPU backend: Use new clDNN version 12.1
  cmake/external_cldnn.cmake
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2283 Minor PlaidML updates
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/prefix_reshape_elimination.cpp
  src/ngraph/pass/prefix_reshape_elimination.hpp
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_backend.cpp
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_config.cpp
  src/ngraph/runtime/plaidml/plaidml_config.hpp
  src/ngraph/runtime/plaidml/plaidml_impl.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_concat_elision.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_combination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_winograd.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.hpp
Labels: Fully Reviewed, PlaidML

#2300 IntelGPU backend: minor fixes in statistic
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
Labels: Fully Reviewed, IntelGPU

#2302 add GetOutputElementElimination for nvgpu backend
  src/ngraph/runtime/gpu/gpu_compiled_function.cpp
Labels: Fully Reviewed, NvidiaGPU

#2296 Add a space in one of the diag msgs
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed, IntelCPU

#2318 [ONNX] Move CPU tests to INTERPRETER
  test/onnx_import.cpp
Labels: Fully Reviewed, High Priority

#2319 changes to get hybrid not dependent on any backends
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/hybrid/hybrid_backend.cpp
  src/ngraph/runtime/hybrid/hybrid_backend.hpp
Labels: Fully Reviewed, High Priority

#2317 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#2310 Fix wheel build w/Anaconda on macOS
  python/setup.py
Labels: Fully Reviewed

#2299 [ONNX] Expose API to check whether ONNX Op is supported.
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.hpp
  test/onnx_import.cpp
Labels: Fully Reviewed, ONNX

#2316 fix parallel build of target `python_wheel`
  python/CMakeLists.txt
Labels: Fully Reviewed

#2312 [ONNX] Parametrize tests to run on multiple backends
  test/CMakeLists.txt
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2315 Add a trace when we reuse inputs in Memory Layout
  src/ngraph/pass/memory_layout.cpp
Labels: Fully Reviewed

#2330 A simple heuristic for slice sinker
  src/ngraph/pass/reshape_sinking.cpp
Labels: Fully Reviewed

#2313 Sink Concat
  src/ngraph/pass/reshape_sinking.cpp
  test/reshape_sinking.cpp
Labels: Fully Reviewed

#2337 Leona/0 12 doc
  doc/sphinx/source/conf.py
  doc/sphinx/source/frameworks/validation.rst
Labels: Documentation, Fully Reviewed

#2264 Changes toward compiling the CPU backend on Windows
  CMakeLists.txt
  cmake/external_gtest.cmake
  cmake/external_mkldnn.cmake
  cmake/external_tbb_prebuilt.cmake
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/dot.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/reference/softmax.hpp
Labels: Fully Reviewed

#2341 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#2340 Fix a CoordinateTransform corner case exposed by ONNX unit tests
  src/ngraph/coordinate_transform.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#2345 Add any/all PlaidML support
  src/ngraph/runtime/plaidml/plaidml_ops_reduce.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, PlaidML

#2328 [ONNX] bug: fix missing dependency on protobuf::libprotobuf target
  src/ngraph/frontend/onnx_import/CMakeLists.txt
Labels: Bug, Fully Reviewed, ONNX

#2342 [ONNX] DepthToSpace operator.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/depth_to_space.cpp
  src/ngraph/frontend/onnx_import/op/depth_to_space.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/depth_to_space.onnx
  test/models/onnx/depth_to_space_bad_blocksize.onnx
  test/models/onnx/depth_to_space_chw.onnx
  test/models/onnx/depth_to_space_no_blocksize.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2281 A backend property request
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
Labels: Fully Reviewed

#2333 [ONNX] Enable softmax test
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  test/onnx_import.in.cpp
Labels: Fully Reviewed

#2324 [ONNX] Add table with status of supported operators.
  src/ngraph/frontend/onnx_import/op/supported_ops.md
Labels: Fully Reviewed, ONNX

#2332 Use appropriate function to test NAN.
  src/ngraph/util.cpp
Labels: Fully Reviewed

#2339 Divert dynamic offset to reference
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2347 Check if the pointer returned by malloc is nullptr.
  src/ngraph/runtime/aligned_buffer.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/serializer.cpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
Labels: Fully Reviewed

#2306 Hybrid backend update
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/visualize_tree.hpp
  src/ngraph/runtime/hybrid/CMakeLists.txt
  src/ngraph/runtime/hybrid/hybrid_backend.cpp
  src/ngraph/runtime/hybrid/hybrid_backend.hpp
  src/ngraph/runtime/hybrid/pass/dump.cpp
  src/ngraph/runtime/hybrid/pass/dump.hpp
  src/ngraph/runtime/hybrid/pass/liveness.cpp
  src/ngraph/runtime/hybrid/pass/liveness.hpp
  src/ngraph/runtime/hybrid/pass/memory_layout.cpp
  src/ngraph/runtime/hybrid/pass/memory_layout.hpp
  test/CMakeLists.txt
  test/hybrid_backend.cpp
  test/hybrid_utils.cpp
  test/hybrid_utils.hpp
Labels: Fully Reviewed

#2362 Minor tweaks for older g++ support
  src/ngraph/runtime/plaidml/plaidml_impl.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.cpp
Labels: PlaidML

#2360 Add error check for user setting CMAKE_BUILD_TYPE
  CMakeLists.txt
Labels: Fully Reviewed

#2356 IntelGPU backend: Product operation fix
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Bug, Fully Reviewed, IntelGPU

#2367 add method to Function to get the size of a graph
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  test/CMakeLists.txt
  test/core.cpp
Labels: Fully Reviewed

#2373 Remove unused Node::validate_punt_if_dynamic function
  src/ngraph/node.cpp
  src/ngraph/node.hpp
Labels: Fully Reviewed

#2366 [ONNX] Add lacking data types to ONNX Tensor
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/op/constant.cpp
Labels: Fully Reviewed, ONNX

#2359 [ONNX] TopK operator
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/op/topk.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/top_k.onnx
  test/onnx_import.in.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed, ONNX

#2323 IntelGPU backend: fix online build
  CMakeLists.txt
Labels: Bug, Fully Reviewed, IntelGPU

#2383 Remove true user check for Slice sinker
  src/ngraph/pass/reshape_sinking.cpp
Labels: Fully Reviewed

#2371 Use pre-built tbb on macos
  CMakeLists.txt
  cmake/external_tbb_prebuilt.cmake
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed
