Repository NervanaSystems/ngraph, pull requests merged in 2019-03, with the labels that each got.

#2527 [ONNX] Add optional outputs to batch_norm op
  src/ngraph/frontend/onnx_import/op/batch_norm.cpp
Labels: Bug, Fully Reviewed, High Priority, ONNX

#2519 [ONNX] Update information on supported ops
  src/ngraph/frontend/onnx_import/op/supported_ops.md
Labels: Fully Reviewed, ONNX

#2520 [Py] Update to new pytest configuration method
  python/test/__init__.py
  python/test/conftest.py
  python/test/ngraph/test_basic.py
  python/test/ngraph/test_convolution.py
  python/test/ngraph/test_normalization.py
  python/test/ngraph/test_ops_matmul.py
  python/test/ngraph/test_ops_reshape.py
  python/test/ngraph/test_ops_unary.py
  python/test/ngraph/test_pooling.py
  python/test/ngraph/test_reduction.py
  python/test/ngraph/util.py
  python/test/test_ops.py
Labels: Fully Reviewed

#2521 [ONNX] Add support for negative calculated padding
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
Labels: Fully Reviewed, ONNX

#2524 [ONNX] Improve warning message
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#2530 Limit compile-api exposed through PyBind
  python/pyngraph/runtime/backend.cpp
Labels: Fully Reviewed

#2529 [ONNX] change [] into .at()
  src/ngraph/frontend/onnx_import/core/graph.cpp
Labels: Fully Reviewed, ONNX

#2523 Avijit/add diag 4 distributed debugging
  src/ngraph/log.cpp
  src/ngraph/log.hpp
  src/ngraph/runtime/cpu/builder/allreduce.cpp
Labels: Fully Reviewed, High Priority

#2532 Fixes on Windows
  cmake/external_mkldnn.cmake
Labels: High Priority

#2526 Fallback to default pooling kernels when mkldnn doesn't support input…
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2539 Fix files that had missing headers
  python/pyngraph/types/type.cpp
  src/ngraph/runtime/hybrid/op/op_tbl.hpp
Labels: High Priority

#2537 New macros for faster node validation checks
  src/ngraph/check.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/validation_util.cpp
  test/partial_shape.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2541 Cherry pick "Fix files that had missing headers (#2539)"
  python/pyngraph/types/type.cpp
  src/ngraph/runtime/hybrid/op/op_tbl.hpp
Labels: Fully Reviewed

#2535 Cyphers/distdebug
  src/ngraph/log.cpp
  src/ngraph/log.hpp
  src/ngraph/runtime/cpu/builder/allreduce.cpp
  test/main.cpp
Labels: Fully Reviewed

#2542 Enable cmake report CMAKE_<LANG>_COMPILER_ID AppleClang.
  CMakeLists.txt
Labels: Fully Reviewed

#2545 Fixed CentOS build issues
  src/ngraph/log.cpp
  src/ngraph/log.hpp
  test/main.cpp
Labels: Fully Reviewed, High Priority

#2547 Get backend working again
  src/ngraph/runtime/generic_cpu/CMakeLists.txt
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/generic_cpu/kernel/broadcast.hpp
Labels: Fully Reviewed

#2516 Extend compile API to take in PassConfig object
  python/pyngraph/runtime/backend.cpp
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/pass_config.hpp
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#2554 Rename CHECK macro to NGRAPH_CHECK
  src/ngraph/check.hpp
  src/ngraph/node.hpp
Labels: Fully Reviewed

#2549 Add ngraph and std namespaces to c++ files
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/cse.cpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/like_replacement.cpp
  src/ngraph/pass/liveness.cpp
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/manager_state.cpp
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/pass/memory_visualize.cpp
  src/ngraph/pass/nop_elimination.cpp
  src/ngraph/pass/pass.cpp
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/prefix_reshape_elimination.cpp
  src/ngraph/pass/propagate_cacheability.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#2534 Change behavior for bad/out-of-bounds OneHot values
  src/ngraph/runtime/cpu/kernel/one_hot.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/reference/one_hot.hpp
  test/backend_one_hot.in.cpp
Labels: Fully Reviewed

#2544 Split runtime backend and executable source files
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
  src/ngraph/runtime/hybrid/hybrid_executable.hpp
Labels: Fully Reviewed

#2546 Switch everything from NODE_VALIDATION_ASSERT to NODE_VALIDATION_CHECK; remove NODE_VALIDATION_ASSERT
  src/ngraph/node.hpp
  src/ngraph/op/allreduce.cpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/concat.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/dequantize.cpp
  src/ngraph/op/dot.cpp
  src/ngraph/op/embedding_lookup.cpp
  src/ngraph/op/experimental/generate_mask.cpp
  src/ngraph/op/experimental/quantized_avg_pool.cpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/experimental/quantized_max_pool.cpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/lrn.cpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/quantize.cpp
  src/ngraph/op/replace_slice.cpp
  src/ngraph/op/reshape.cpp
  src/ngraph/op/result.cpp
  src/ngraph/op/reverse.cpp
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/op/select.cpp
  src/ngraph/op/slice.cpp
  src/ngraph/op/softmax.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/index_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/update_slice.cpp
  test/type_prop.cpp
Labels: Changes API, Fully Reviewed

#2557 Migrate Klocwork issues
  src/ngraph/codegen/compiler.cpp
  src/ngraph/log.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/hybrid/hybrid_util.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#2550 IntelGPU backend: ReverseSequence operation implemenation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#2551 IntelGPU backend: Concat operation custom kernel implementation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#2555 Address klocwork issues
  src/ngraph/codegen/compiler.cpp
  src/ngraph/log.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/hybrid/hybrid_util.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#2563 Fix crash by correcting index (#2561)
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
Labels: Fully Reviewed, IntelCPU

#2548 Replace macro with proper function declaration
  src/ngraph/pass/like_replacement.cpp
Labels: Fully Reviewed

#2559 Move codegen tests to a separate module and add selectively
  test/CMakeLists.txt
  test/cpu_codegen.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#2531 Update build script to fix Windows build issues and add some work tow…
  cmake/external_gtest.cmake
  cmake/external_llvm.cmake
  cmake/external_mkldnn.cmake
  cmake/external_tbb_prebuilt.cmake
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/file_util.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.hpp
  src/resource/main.cpp
  src/resource/util.cpp
Labels: High Priority

#2569 fix header path finder bug in compiler.cpp
  src/ngraph/codegen/compiler.cpp
Labels: Fully Reviewed

#2566 Update friendly names to work properly in serialized graphs
  src/ngraph/serializer.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#2570 Reworked the sentence to make the reference clear
  README.md
Labels: Documentation, Fully Reviewed

#2558 Allow user override for eigen thread count
  src/ngraph/runtime/cpu/cpu_executor.cpp
Labels: Fully Reviewed, IntelCPU

#2560 Revamp repo doc
  README.md
Labels: Fully Reviewed

#2512 limit distributed user option to one flag
  CMakeLists.txt
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/core/constructing-graphs/distribute-train.rst
Labels: Fully Reviewed, distributed

#2577 make distributed logging available for all comm's libs
  src/ngraph/log.cpp
  src/ngraph/log.hpp
Labels: distributed

#2579 IntelGPU backend: Concat operation fix for single element
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
Labels: Bug, IntelGPU

#2581 [NFC] Remove dead code (worst_case_tmp_size)
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed, IntelCPU

#2580 Adding edited version of new section on Paddle doc
  doc/sphinx/source/frameworks/paddle_integ.rst
  doc/sphinx/source/graphics/paddlepaddle_design.png
  doc/sphinx/source/graphics/paddlepaddle_directory.png
  doc/sphinx/source/project/introduction.rst
Labels: Documentation, Fully Reviewed

#2536 refactor topological_sort to use Node.get_users()
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
Labels: Fully Reviewed

#2575 Silee2/fix prebuilt mkldnn
  cmake/external_mkldnn.cmake
  python/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#2576 Don't segfault trying to be informative about empty tensors
  test/util/all_close_f.cpp
Labels: Bug, Fully Reviewed

#2593 Remove _backwards from conv backprop ops.
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/kernel/convolution.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/convolution.hpp
Labels: Fully Reviewed

#2595 Add sitemap for OTC team
  doc/sphinx/source/index.rst
  doc/sphinx/source/sitemap.rst
Labels: Documentation, Fully Reviewed, High Priority

#2596 IntelGPU backend: Relu operation fix with int32_t
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Bug, IntelGPU

#2571 add QuantizedConcat varying min/max test
  src/ngraph/builder/quantization_util.hpp
  test/builder_quantization.cpp
Labels: Fully Reviewed

#2584 nvgpu backend check if the ptr pass to create_tensor is device pointer
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_tensor.cpp
  src/ngraph/runtime/gpu/gpu_util.cpp
  src/ngraph/runtime/gpu/gpu_util.hpp
Labels: Fully Reviewed, NvidiaGPU

#2598 [ONNX] Use NGRAPH_TEST in unit tests instead of TEST
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2600 Fix a bug in offset calculation.
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#2495 [ONNX] Quantization operators
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/dequantize_linear.cpp
  src/ngraph/frontend/onnx_import/op/dequantize_linear.hpp
  src/ngraph/frontend/onnx_import/op/quant_conv.cpp
  src/ngraph/frontend/onnx_import/op/quant_conv.hpp
  src/ngraph/frontend/onnx_import/op/quantize_linear.cpp
  src/ngraph/frontend/onnx_import/op/quantize_linear.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/dequant_lin.prototxt
  test/models/onnx/quant_conv_lin.prototxt
  test/models/onnx/quant_lin.prototxt
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2605 IntelGPU backend: ReluBackprop operation fix for datatypes
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Bug, Fully Reviewed, IntelGPU

#2608 Fixup README
  README.md
  doc/sphinx/source/sitemap.rst
Labels: Fully Reviewed

#2609 allow multiple setting of a node's friendly name
  src/ngraph/node.cpp
Labels: Fully Reviewed

#2591 Adds basic support for provenance
  src/ngraph/graph_util.cpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  test/op.cpp
Labels: Fully Reviewed

#2322 Add support for shape-specialization of functions
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/specialize_shapes.cpp
  src/ngraph/specialize_shapes.hpp
  test/CMakeLists.txt
  test/specialize_shapes.cpp
Labels: Fully Reviewed

#2602 Make 'use_mkldnn_kernel' properly deal with non-ops nodes
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
Labels: Fully Reviewed

#2592 QuantizedDot and QuantizedDotBias ops CPU impl
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization_util.hpp
  src/ngraph/op/experimental/quantized_dot.cpp
  src/ngraph/op/experimental/quantized_dot.hpp
  src/ngraph/op/experimental/quantized_dot_bias.cpp
  src/ngraph/op/experimental/quantized_dot_bias.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantized_dot.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed

#2525 Silee2/external project rpath
  CMakeLists.txt
  cmake/external_cldnn.cmake
  cmake/external_mkldnn.cmake
  cmake/external_mlsl.cmake
  src/ngraph/CMakeLists.txt
  src/resource/CMakeLists.txt
  src/tools/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#2607 add unit tests for the two versions of Backend create_tensor
  src/ngraph/runtime/gpu/unit_test.manifest
  test/CMakeLists.txt
  test/backend_api.in.cpp
Labels: Fully Reviewed

#2618 remove Kahan sum unit tests. There are 4 other stable sum unit tests.
  test/backend_test.in.cpp
Labels: Fully Reviewed

#2594 (Dynamic) Transpose op
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/ops/transpose.rst
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/op/experimental/transpose.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2613 Default to old caching behavior when memory reuse is disabled
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#2617 Fix missing libraries when library versioning is enabled.
  cmake/external_mkldnn.cmake
Labels: Bug, Fully Reviewed

#2533 Compiler passes section collab
  doc/sphinx/source/backend-support/cpp-api.rst
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/core/constructing-graphs/index.rst
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/core/passes/list-of-passes.rst
  doc/sphinx/source/core/passes/passes.rst
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/glossary.rst
  doc/sphinx/source/graphics/execution-interface.png
  doc/sphinx/source/graphics/simple-compiler-passes.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/doc-contributor-README.rst
Labels: Documentation, Fully Reviewed

#2622 Allow for test exclusion to include backend name
  test/util/test_control.cpp
  test/util/test_control.hpp
Labels: Fully Reviewed

#2621 Enable onnx, protobuf and onnx import on Windows.
  CMakeLists.txt
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnxifi/CMakeLists.txt
Labels: Fully Reviewed

#2624 nvgpu tensor copy_from
  src/ngraph/runtime/gpu/gpu_tensor.cpp
  src/ngraph/runtime/gpu/gpu_tensor.hpp
  test/backend_api.in.cpp
Labels: Fully Reviewed

#2615 remove unit test for integer division by zero
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/gpuh/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_binary_elementwise.in.cpp
Labels: Fully Reviewed

#2610 Added sqrt to constant folding
  src/ngraph/pass/constant_folding.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#2628 [ONNX] Add valid padding support
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
Labels: Fully Reviewed, ONNX

#2620 Change floating point comparisons from == to all_close_f
  test/backend_api.in.cpp
  test/backend_binary_elementwise.in.cpp
  test/backend_broadcast.in.cpp
  test/backend_dot.in.cpp
  test/backend_embedding_lookup.in.cpp
  test/backend_pool.in.cpp
  test/backend_reshape.in.cpp
  test/backend_sum.in.cpp
  test/backend_test.in.cpp
  test/backend_topk.in.cpp
  test/backend_unary_elementwise.in.cpp
  test/constant_folding.cpp
  test/cpu_codegen.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/distributed.in.cpp
  test/hybrid_backend.cpp
Labels: Fully Reviewed, High Priority

#2630 add method to get underlying executable
  src/ngraph/runtime/hybrid/hybrid_executable.cpp
  src/ngraph/runtime/hybrid/hybrid_executable.hpp
Labels: Fully Reviewed

#2631 Update sitemap.rst
  doc/sphinx/source/sitemap.rst
Labels: Fully Reviewed

#2633 Make convolution test generator work with python3
  test/ref_generators/generate_convolution_ref.py
Labels: Fully Reviewed

#2612 Add NodeInput and NodeOutput classes
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/node_input.cpp
  src/ngraph/node_input.hpp
  src/ngraph/node_output.cpp
  src/ngraph/node_output.hpp
  test/CMakeLists.txt
  test/node_input_output.cpp
Labels: Fully Reviewed, High Priority

#2626 Codegen bug fixes
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed, High Priority

#2625 Do not allow in place slice if the arg is in CONSTANT buffer set.
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  test/cpu_test.cpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#2635 Do not throw out of bound exception for onehot in CODEGEN mode.
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Bug, High Priority, IntelCPU

#2582 Fix debugger tests crash for CODEGEN.
  src/ngraph/runtime/cpu/cpu_debugger.cpp
  test/cpu_debugger.cpp
Labels: High Priority, IntelCPU

#2606 [ONNX] LSTM mixed length sequences.
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  test/models/onnx/lstm_fwd_mixed_seq.prototxt
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2540 add method to conditional check for mkldnn version & use conv_auto
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2590 [ONNX] Enable Pad modes for ONNX pad operator
  doc/sphinx/source/ops/pad.rst
  python/pyngraph/ops/pad.cpp
  src/ngraph/frontend/onnx_import/op/pad.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/pad.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/pad.cpp
  src/ngraph/runtime/cpu/kernel/pad.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_general.cpp
  src/ngraph/runtime/reference/pad.hpp
  src/ngraph/serializer.cpp
  src/ngraph/util.cpp
  test/backend_test.in.cpp
  test/constant_folding.cpp
  test/cpu_fusion.cpp
  test/nop_elimination.cpp
  test/reshape_sinking.cpp
  test/type_prop.cpp
  test/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed, High Priority

#2564 Dyn broadcast initial
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/dyn_broadcast.cpp
  src/ngraph/op/experimental/dyn_broadcast.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2642 INTELGPU: Fix names duplication of generated supporting primitives fo…
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2588 Revamp doc intro
  doc/sphinx/source/graphics/intro_graph_optimization.png
  doc/sphinx/source/graphics/intro_kernel_explosion.png
  doc/sphinx/source/graphics/intro_kernels.png
  doc/sphinx/source/graphics/stackngrknl.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/about.rst
  doc/sphinx/source/project/introduction.rst
  doc/sphinx/source/sitemap.rst
Labels: Fully Reviewed

#2651 Cleanup runtime context in CPU_CallFrame Destructor
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
Labels: Bug, External, Fully Reviewed

#2643 Fix visualize tracing file name on Windows.
  src/ngraph/pass/manager.hpp
Labels: Fully Reviewed

#2652 Fix accuracy issue
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#2641 Dynamic Padding Implementation
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/dyn_pad.cpp
  src/ngraph/op/experimental/dyn_pad.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2611 (Dynamic) Reshape and Slice
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_reshape.hpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/experimental/dyn_slice.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/type_prop.cpp
Labels: Fully Reviewed, Merge Blocked

#2640 Fallback to ref convolution for negative padding
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_test.cpp
Labels: IntelCPU

#2653 Added "min_signal" paramater to float testing
  test/all_close_f.cpp
  test/util/all_close_f.cpp
  test/util/all_close_f.hpp
Labels: Fully Reviewed

#2634 Concat Elimination and Self Concat Fusion pass
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/concat_fusion.hpp
  test/CMakeLists.txt
  test/concat_fusion.cpp
Labels: Fully Reviewed

#2648 Do not set num_threads_per_pool to 1 in cpu executor.
  src/ngraph/runtime/cpu/cpu_executor.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2650 Add erf op, interpreter kernel and unit tests
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/erf.cpp
  src/ngraph/op/erf.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/erf.hpp
  src/ngraph/serializer.cpp
  test/backend_test.in.cpp
  test/backend_unary_elementwise.in.cpp
Labels: Fully Reviewed

#2619 [ONNX] Fix Gemm operator by adding reshape
  src/ngraph/frontend/onnx_import/op/gemm.cpp
Labels: Fully Reviewed, ONNX

#2638 [ONNX] Change default broadcast dim value, gemm improvement
  src/ngraph/frontend/onnx_import/op/gemm.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
Labels: Fully Reviewed, ONNX

#2656 Adds extra case for conv affine folding
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#2629 [ONNX] Add documentation
  README.md
  doc/sphinx/source/frameworks/onnx_integ.rst
  doc/sphinx/source/frameworks/validated/list.rst
  doc/sphinx/source/project/doc-contributor-README.rst
Labels: Documentation, Fully Reviewed, ONNX

#2639 Update README.md
  python/README.md
Labels: Fully Reviewed

#2654 ngraph.ai theme
  doc/sphinx/Makefile
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/backend-support/index.rst
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/frameworks/generic-configs.rst
  doc/sphinx/source/frameworks/onnx_integ.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/introduction.rst
  doc/sphinx/source/tutorials/index.rst
Labels: Fully Reviewed, High Priority

#2644 Add naive int64-indexing to EmbeddingLookup
  src/ngraph/runtime/cpu/builder/embedding_lookup.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_embedding_lookup.in.cpp
Labels: Fully Reviewed

#2662 Use official Eigen repo.
  cmake/eigen.patch
  cmake/external_eigen.cmake
Labels: Fully Reviewed

#2663 header resource line by line
  src/ngraph/codegen/compiler.cpp
  src/ngraph/codegen/compiler.hpp
  src/resource/header_rewrite.cpp
  src/resource/main.cpp
Labels: Fully Reviewed

#2243 Add BroadcastDistributed op
  CODEOWNERS
  cmake/Modules/style_apply.cmake
  doc/sphinx/source/ops/broadcast_distributed.rst
  doc/sphinx/source/ops/index.rst
  python/pyngraph/ops/broadcast_distributed.cpp
  python/pyngraph/ops/broadcast_distributed.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/broadcast_distributed.cpp
  src/ngraph/op/broadcast_distributed.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/broadcast_distributed.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/broadcast_distributed.hpp
  src/ngraph/serializer.cpp
  test/distributed.in.cpp
Labels: Fully Reviewed, distributed

#2675 Reduce concat fusion test input sizes
  test/concat_fusion.cpp
Labels: Fully Reviewed

#2681 Cap the max parallelism that user can request
  src/ngraph/runtime/cpu/cpu_executor.cpp
Labels: Fully Reviewed, IntelCPU

#2659 Sarkars/bypass ngcore
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
Labels: Fully Reviewed

#2682 Small fix for compilation fail in PlaidML BE
  src/ngraph/runtime/plaidml/plaidml_ops_general.cpp
Labels: Fully Reviewed, PlaidML

#2680 Update cmake minimum version
  CMakeLists.txt
Labels: Fully Reviewed

#2674 Avijit/event traces
  src/ngraph/CMakeLists.txt
  src/ngraph/event_tracing.cpp
  src/ngraph/event_tracing.hpp
  test/CMakeLists.txt
  test/event_tracing.cpp
Labels: Fully Reviewed

#2660 gauss error function (erf) implementation through eigen for DEX and CODEGEN
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/erf.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/erf.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2683 [IntelCPU] Fix ambiguous 'op' namespace.
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/builder/leaky_relu.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#2678 [Warnings] Remove unused variable hso
  src/ngraph/codegen/compiler.cpp
Labels: Fully Reviewed

#2685 move unit test to correct file
  test/backend_api.in.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#2684 Fix broken link and update details about mxnet
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/frameworks/mxnet_integ.rst
  doc/sphinx/source/ops/broadcast_distributed.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/python_api/_autosummary/ngraph.exceptions.rst
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
Labels: Fully Reviewed

#2670 Add one hot new unit test
  test/backend_one_hot.in.cpp
Labels: Fully Reviewed

#2637 [ONNX] Fix convpool padding by max(x, 0) on pad calculation
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
Labels: Fully Reviewed, ONNX
