Repository NervanaSystems/ngraph, pull requests merged in 2019-04, with the labels that each got.

#2692 Add GetOutputElement to outputs of FunctionCall
  src/ngraph/runtime/hybrid/hybrid_util.cpp
Labels: Fully Reviewed, High Priority

#2700 Migrate klocwork fixes from r0.17
  test/all_close_f.cpp
  test/cpu_debugger.cpp
Labels: Fully Reviewed

#2668 [ONNX] Add verification of duplicate in unsqueeze axes attribute
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
Labels: Fully Reviewed, ONNX

#2679 Add support for QConvInteger
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/op/experimental/quantized_conv.cpp
  src/ngraph/op/experimental/quantized_conv.hpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU

#2697 [Standalone] Set MKLDNN kernel flag in ConvertLayout op.
  src/ngraph/runtime/cpu/op/convert_layout.cpp
Labels: Fully Reviewed, IntelCPU

#2699 [Warnings] Silence more warnings
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/host_tensor.hpp
  test/partial_shape.cpp
Labels: Fully Reviewed

#2702 IntelGPU backend: Select operation fix (clDNN doesn't support int32 data type); Switched to clDNN 14.0 drop
  cmake/external_cldnn.cmake
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
Labels: Fully Reviewed, IntelGPU

#2708 Minor change
  src/ngraph/runtime/reference/convolution.hpp
Labels: Bug, High Priority

#2669 [ONNX] Add verification of split attribute in split op
  src/ngraph/frontend/onnx_import/op/split.cpp
Labels: Fully Reviewed, ONNX

#2693 bfloat16 testing and fixes
  src/ngraph/type/bfloat16.cpp
  src/ngraph/type/bfloat16.hpp
  test/CMakeLists.txt
  test/all_close_f.cpp
  test/bfloat16.cpp
  test/util/CMakeLists.txt
  test/util/float_util.cpp
  test/util/float_util.hpp
Labels: Fully Reviewed

#2694 [ONNX] Missing optional output in MaxPool
  src/ngraph/frontend/onnx_import/op/max_pool.cpp
Labels: Fully Reviewed, ONNX

#2696 Update template for release notes and CHANGELOG with latest few summaries from ngraph releases repo
  doc/sphinx/ngraph_theme/static/theme.css
  doc/sphinx/source/conf.py
  doc/sphinx/source/core/constructing-graphs/derive-for-training.rst
  doc/sphinx/source/core/passes/list-of-passes.rst
  doc/sphinx/source/frameworks/generic-configs.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/paddle_integ.rst
  doc/sphinx/source/frameworks/validated/testing-latency.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/python_api/index.rst
  python/README.md
Labels: Fully Reviewed

#2709 sarkars/Minor change
  src/ngraph/runtime/reference/convolution.hpp
Labels: Bug, Fully Reviewed

#2712 Migrate doc to r0.17
  doc/sphinx/ngraph_theme/static/theme.css
  doc/sphinx/source/conf.py
  doc/sphinx/source/core/constructing-graphs/derive-for-training.rst
  doc/sphinx/source/core/passes/list-of-passes.rst
  doc/sphinx/source/frameworks/generic-configs.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/paddle_integ.rst
  doc/sphinx/source/frameworks/validated/testing-latency.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/python_api/index.rst
  python/README.md
Labels: Fully Reviewed

#2711 Add unit test for create_tensor passing in buffer to output tensor
  src/ngraph/runtime/gpu/unit_test.manifest
  test/backend_api.in.cpp
Labels: Fully Reviewed

#2710 TopK: return the lower index for equivalent values
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/reference/topk.hpp
  test/backend_topk.in.cpp
Labels: High Priority, ONNX, Release

#2689 Change OneHot to accept only integral types
  doc/sphinx/source/ops/one_hot.rst
  python/test/test_ops.py
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/one_hot.hpp
  src/ngraph/type/element_type.hpp
  test/backend_one_hot.in.cpp
  test/type_prop.cpp
Labels: Changes API, Fully Reviewed

#2538 Use cpu kernel for constant folding.
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/runtime/cpu/builder/broadcast.cpp
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/builder/reshape.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/util.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2690 [ONNX] Unit tests for QuantizeLinear
  src/ngraph/frontend/onnx_import/op/quantize_linear.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/quantize_linear.prototxt
  test/models/onnx/quantize_linear_axis_negative.prototxt
  test/models/onnx/quantize_linear_axis_zero.prototxt
  test/models/onnx/quantize_linear_zero_point.prototxt
  test/onnx_import.in.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed, High Priority, ONNX, Release

#2704 [ONNX] Unit tests for DequantizeLinear
  src/ngraph/frontend/onnx_import/op/dequantize_linear.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/dequantize_linear_0.prototxt
  test/models/onnx/dequantize_linear_1.prototxt
  test/models/onnx/dequantize_linear_2.prototxt
  test/models/onnx/dequantize_linear_3.prototxt
  test/models/onnx/dequantize_linear_4.prototxt
  test/models/onnx/dequantize_linear_5.prototxt
  test/onnx_import.in.cpp
Labels: Fully Reviewed, High Priority, ONNX, Release

#2695 Add windows support for event trace
  CMakeLists.txt
  src/ngraph/event_tracing.cpp
  src/ngraph/event_tracing.hpp
Labels: Fully Reviewed

#2688 Adding support for fused ops that are decomposable to core ngraph ops
  src/ngraph/CMakeLists.txt
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/prelu.cpp
  src/ngraph/op/fused/prelu.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/util/broadcasting.cpp
  src/ngraph/op/util/broadcasting.hpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/op/util/fused_op.hpp
  src/ngraph/pass/fused_op_decomposition.cpp
  src/ngraph/pass/fused_op_decomposition.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_compiled_function.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend_fusedop.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed, High Priority

#2687 Add support for QDotInteger
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization/quantized_linear_dot.cpp
  src/ngraph/builder/quantization/quantized_linear_dot.hpp
  src/ngraph/op/experimental/quantized_dot.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU

#2665 General-purpose recurrent reshape elimination pass
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/concat_fusion.hpp
  src/ngraph/pass/pass_util.cpp
  src/ngraph/pass/pass_util.hpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_elimination.hpp
  test/reshape_elimination.cpp
Labels: Fully Reviewed

#2705 [ONNX] Unit test models for QLinearConv
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/frontend/onnx_import/op/quant_conv.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/qlinear_conv_2d.prototxt
  test/models/onnx/qlinear_conv_3d.prototxt
  test/models/onnx/qlinearconv2d/w.bin
  test/models/onnx/qlinearconv2d/w_scale.bin
  test/models/onnx/qlinearconv2d/w_zero_point.bin
  test/models/onnx/qlinearconv2d/x.bin
  test/models/onnx/qlinearconv2d/x_scale.bin
  test/models/onnx/qlinearconv2d/x_zero_point.bin
  test/models/onnx/qlinearconv2d/y.bin
  test/models/onnx/qlinearconv2d/y_scale.bin
  test/models/onnx/qlinearconv2d/y_zero_point.bin
  test/models/onnx/qlinearconv3d/w.bin
  test/models/onnx/qlinearconv3d/w_scale.bin
  test/models/onnx/qlinearconv3d/w_zero_point.bin
  test/models/onnx/qlinearconv3d/x.bin
  test/models/onnx/qlinearconv3d/x_scale.bin
  test/models/onnx/qlinearconv3d/x_zero_point.bin
  test/models/onnx/qlinearconv3d/y.bin
  test/models/onnx/qlinearconv3d/y_scale.bin
  test/models/onnx/qlinearconv3d/y_zero_point.bin
  test/onnx_import.in.cpp
Labels: High Priority, ONNX, Release

#2720 Rework to try to avoid invalid klocwork warnings
  test/bfloat16.cpp
Labels: Fully Reviewed, High Priority

#2723 Fix unresolved symbol in cpu backend on Windows.
  src/ngraph/runtime/cpu/cpu_builder.hpp
Labels: High Priority

#2719 Add Min/Max support to zero dim tensor elimination pass
  src/ngraph/op/max.cpp
  src/ngraph/op/max.hpp
  src/ngraph/op/min.cpp
  src/ngraph/op/min.hpp
  test/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed, High Priority

#2721 rename files to .png since that is the format the files really are
  test/algebraic_simplification.cpp
  test/concat_fusion.cpp
  test/cpu_fusion.cpp
  test/reshape_elimination.cpp
  test/reshape_sinking.cpp
Labels: Fully Reviewed

#2725 cleaning up loose ends for QLinearConv
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  test/files/onnx/qlinearconv2d/w.bin
  test/files/onnx/qlinearconv2d/w_scale.bin
  test/files/onnx/qlinearconv2d/w_zero_point.bin
  test/files/onnx/qlinearconv2d/x.bin
  test/files/onnx/qlinearconv2d/x_scale.bin
  test/files/onnx/qlinearconv2d/x_zero_point.bin
  test/files/onnx/qlinearconv2d/y.bin
  test/files/onnx/qlinearconv2d/y_scale.bin
  test/files/onnx/qlinearconv2d/y_zero_point.bin
  test/files/onnx/qlinearconv3d/w.bin
  test/files/onnx/qlinearconv3d/w_scale.bin
  test/files/onnx/qlinearconv3d/w_zero_point.bin
  test/files/onnx/qlinearconv3d/x.bin
  test/files/onnx/qlinearconv3d/x_scale.bin
  test/files/onnx/qlinearconv3d/x_zero_point.bin
  test/files/onnx/qlinearconv3d/y.bin
  test/files/onnx/qlinearconv3d/y_scale.bin
  test/files/onnx/qlinearconv3d/y_zero_point.bin
  test/onnx_import.in.cpp
Labels: Fully Reviewed, High Priority

#2735 IntelGPU backend: Workaround for #2729 issue, regression test was added.
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  test/backend_test.in.cpp
Labels: Bug, Fully Reviewed, IntelGPU

#2737 update doc version to 0.18 and cmake req to 3.5.0
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/ops/quantize.rst
Labels: Fully Reviewed

#2734 IntelGPU backend: Code refactoring due to Node functions deprecated
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2732 Update TensorFlow version number
  README.md
Labels: Fully Reviewed

#2701 [Standalone] Decouple MKLDNN primitive build from code generation
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.hpp
Labels: Fully Reviewed, IntelCPU

#2583 Enable previously CI-failing test
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed, IntelCPU

#2739 Serializer supports new pad api
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#2736 IntelGPU backend: TopK operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#2691 [Dynamic Shape] Moving BatchDot to Core Op
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/batch_mat_mul.cpp
  src/ngraph/op/experimental/batch_mat_mul.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/matmul_bias.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/op/batch_dot.cpp
  src/ngraph/runtime/cpu/op/batch_mat_mul_transpose.cpp
  src/ngraph/runtime/cpu/op/batch_mat_mul_transpose.hpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/batch_mat_mul.hpp
  src/ngraph/serializer.cpp
  test/autodiff.in.cpp
  test/backend_test.in.cpp
  test/cpu_fusion.cpp
  test/type_prop.cpp
Labels: Comments Addressed, Fully Reviewed, High Priority

#2745 IntelGPU backend: Add cldnn library to ngraph target when CLDNN_ROOT_DIR defined
  cmake/external_cldnn.cmake
Labels: Fully Reviewed, IntelGPU

#2724 Deprecate direct access to descriptor::Input and descriptor::Output
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/deprecated.hpp
  src/ngraph/descriptor/input.cpp
  src/ngraph/function.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/node_input.cpp
  src/ngraph/node_input.hpp
  src/ngraph/node_output.cpp
  src/ngraph/node_output.hpp
  src/ngraph/op/abs.cpp
  src/ngraph/op/acos.cpp
  src/ngraph/op/asin.cpp
  src/ngraph/op/atan.cpp
  src/ngraph/op/concat.cpp
  src/ngraph/op/dot.cpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/replace_slice.cpp
  src/ngraph/op/reshape.cpp
  src/ngraph/op/select.cpp
  src/ngraph/op/slice.cpp
  src/ngraph/op/sum.cpp
  src/ngraph/pass/assign_layout.hpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/dump_sorted.cpp
  src/ngraph/pass/get_output_element_elimination.cpp
  src/ngraph/pass/liveness.cpp
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/shape_specialization.cpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/runtime/hybrid/hybrid_util.cpp
  src/ngraph/runtime/hybrid/pass/dump.cpp
  src/ngraph/runtime/hybrid/pass/liveness.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  src/tools/nbench/nbench.cpp
  test/backend_graph_comparison.in.cpp
  test/control_dependencies.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/node_input_output.cpp
  test/pattern.cpp
  test/tensor.cpp
Labels: Fully Reviewed

#2749 IntelGPU backend: Convolution operations corner cases fix
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Bug, IntelGPU

#2750 [ONNX] Update onnx opset version
  src/ngraph/frontend/onnx_import/CMakeLists.txt
Labels: Fully Reviewed, ONNX

#2676 [ONNX CI] nGraph master as docker image
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/base_image_builder/Jenkinsfile
  .ci/onnx/jenkins/dockerfiles/ubuntu_16_04.dockerfile
  .ci/onnx/jenkins/prepare_environment.sh
  .ci/onnx/jenkins/utils/docker.sh
Labels: Fully Reviewed, ONNX

#2760 Cyphers/mkldnn
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Fully Reviewed

#2733 Moves some fused convolution ops to core FusedOps
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/op/fused/conv_fused.cpp
  src/ngraph/op/fused/conv_fused.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/core_fusion.hpp
  src/ngraph/pass/fused_op_decomposition.cpp
  src/ngraph/pass/fused_op_decomposition.hpp
  src/ngraph/pass/pass.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/op/conv_bias.cpp
  src/ngraph/runtime/cpu/op/conv_relu.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/serializer.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/CMakeLists.txt
  test/backend_fused_op.in.cpp
  test/backend_fusedop.in.cpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2599 [ONNX CI] Update ONNX CI - no email notification after aborted build
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/utils/utils.groovy
Labels: Fully Reviewed, ONNX

#2756 Remove uuid since it is not used
  src/ngraph/uuid.hpp
  test/CMakeLists.txt
  test/uuid.cpp
Labels: Fully Reviewed

#2614 [ONNX] Fix default axis for legacy broadcasting
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
Labels: Fully Reviewed, ONNX

#2757 IntelGPU backend: Custom kernels refactoring
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#2740 remove ngraph::aligned_alloc and replaced with AlignedBuffer
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/runtime/aligned_buffer.cpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
Labels: Fully Reviewed

#2762 IntelGPU backend: Select operation support for double
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  test/backend_test.in.cpp
Labels: Bug, Fully Reviewed, IntelGPU

#2764 Removed double header include
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed

#2767 fix windows warnings
  test/backend_broadcast.in.cpp
  test/backend_reshape.in.cpp
  test/backend_sum.in.cpp
Labels: Fully Reviewed

#2763 [ONNX] Erf op support
  python/ngraph/runtime.py
  python/setup.py
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/erf.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/erf.prototxt
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2766 Update with latest clr info
  doc/sphinx/source/buildlb.rst
Labels: Fully Reviewed

#2742 gather, gather_nd
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/op/gather_nd.cpp
  src/ngraph/op/gather_nd.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/gather_nd.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/gather.hpp
  src/ngraph/runtime/reference/gather_nd.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend_gather.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed, High Priority

#2776 Migrate python changes from master
  python/ngraph/runtime.py
  python/setup.py
Labels: Fully Reviewed, High Priority

#2716 DeconvBias
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/op/deconv.cpp
  src/ngraph/runtime/cpu/op/deconv.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#2773 Fix Erf CPU Builder for int32
  src/ngraph/runtime/cpu/builder/erf.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2770 IntelGPU backend: Custom kernels refactoring 2
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.hpp
Labels: IntelGPU

#2778 [ONNX] Erf test for integer values
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/erf_int32.prototxt
  test/onnx_import.in.cpp
Labels: ONNX

#2552 Return 0 or 1 when converting to bool
  src/ngraph/runtime/cpu/builder/convert.cpp
  src/ngraph/runtime/cpu/kernel/convert.hpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/convert.hpp
  test/backend_test.in.cpp
Labels: Changes API, Fully Reviewed

#2771 [ONNX] Unify broadcast code in ngraph core and in ONNX bridge
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/and.hpp
  src/ngraph/frontend/onnx_import/op/clip.cpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/elu.cpp
  src/ngraph/frontend/onnx_import/op/equal.hpp
  src/ngraph/frontend/onnx_import/op/gemm.cpp
  src/ngraph/frontend/onnx_import/op/greater.hpp
  src/ngraph/frontend/onnx_import/op/hard_sigmoid.cpp
  src/ngraph/frontend/onnx_import/op/leaky_relu.cpp
  src/ngraph/frontend/onnx_import/op/less.hpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/matmul.cpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/not.hpp
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/op/or.hpp
  src/ngraph/frontend/onnx_import/op/pow.hpp
  src/ngraph/frontend/onnx_import/op/prelu.cpp
  src/ngraph/frontend/onnx_import/op/quant_conv.cpp
  src/ngraph/frontend/onnx_import/op/reciprocal.cpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/frontend/onnx_import/op/selu.cpp
  src/ngraph/frontend/onnx_import/op/softsign.cpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/frontend/onnx_import/op/thresholded_relu.cpp
  src/ngraph/frontend/onnx_import/op/where.hpp
  src/ngraph/frontend/onnx_import/op/xor.hpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.hpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/variadic.hpp
Labels: Fully Reviewed, ONNX

#2747 Adds provenance tag propagation
  src/ngraph/CMakeLists.txt
  src/ngraph/graph_util.cpp
  src/ngraph/provenance.cpp
  src/ngraph/provenance.hpp
  test/CMakeLists.txt
  test/provenance.cpp
Labels: Fully Reviewed

#2783 Remove debug from hybrid
  src/ngraph/runtime/hybrid/hybrid_util.cpp
Labels: Fully Reviewed

#2779 [ONNX] Split ONNX tests into smaller files in test/onnx subdirectory
  src/ngraph/runtime/gpu/unit_test.manifest
  test/CMakeLists.txt
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_convpool.in.cpp
  test/onnx/onnx_import_quant.in.cpp
  test/onnx/onnx_import_reshape.in.cpp
  test/onnx/onnx_import_rnn.in.cpp
  test/onnx/onnxifi.cpp
  test/onnx/onnxifi_span.cpp
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2781 add option to nbench to generate only a dot file
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/visualize_tree.hpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#2768 [Dynamic Shape] Add Properties to PassBase
  src/ngraph/pass/pass.cpp
  src/ngraph/pass/pass.hpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/util.hpp
  test/pattern.cpp
  test/util.cpp
Labels: Comments Addressed, Fully Reviewed, High Priority

#2780 Remove backslash at EOF in comment to fix warning.
  src/ngraph/check.hpp
Labels: Fully Reviewed, ONNX

#2784 Fix dll library load path on Windows.
  src/ngraph/runtime/backend_manager.cpp
Labels: Fully Reviewed

#2774 Add revert command for eigen patch to fix incremental build error.
  cmake/external_eigen.cmake
Labels: Fully Reviewed

#2753 helpers for function and node to determine the dynamic shape
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/reshape.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2775 Report error for C++ style comment ending with a backslash like
  cmake/clang_4_0_flags.cmake
Labels: Fully Reviewed

#2786 include rc version in NGRAPH_VERSION_SHORT and add NGRAPH_WHEEL_VERSION
  CMakeLists.txt
  python/build_wheel.sh.in
Labels: Fully Reviewed

#2785 macos: fix protobuf build issue on macos 10.14.4 + xcode 10.2.1
  CMakeLists.txt
  cmake/external_protobuf.cmake
Labels: Fully Reviewed

#2787 IntelGPU backend: Custom kernels refactoring 3
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#2788 More hybrid fixes
  src/ngraph/runtime/hybrid/hybrid_util.cpp
  src/ngraph/runtime/hybrid/op/function_call.cpp
  src/ngraph/runtime/hybrid/op/function_call.hpp
  test/CMakeLists.txt
  test/hybrid_backend.cpp
Labels: Fully Reviewed

#2765 Fix install path on Windows
  CMakeLists.txt
  cmake/external_mkldnn.cmake
  cmake/external_tbb.cmake
  cmake/external_tbb_prebuilt.cmake
Labels: Fully Reviewed

#2743 Adding auto pad to convolution and pooling
  src/ngraph/ngraph.hpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/op/pad.hpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/serializer.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2794 IntelGPU backend: Softmax visualization fix
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#2795 nbench statistics update
  src/ngraph/runtime/hybrid/hybrid_executable.cpp
  src/ngraph/runtime/hybrid/hybrid_executable.hpp
  src/ngraph/runtime/hybrid/pass/fix_get_output_element.cpp
  src/ngraph/runtime/hybrid/pass/fix_get_output_element.hpp
  src/ngraph/util.hpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#2791 Add OneHot to CSE to optimize PP NNP CPU fallbacks
  src/ngraph/pass/cse.cpp
  test/cse.cpp
Labels: Fully Reviewed

#2789 [Tests] Add NgraphTestCase test runner class
  test/onnx/onnx_import.in.cpp
  test/util/CMakeLists.txt
  test/util/test_case.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed

#2782 Don't create a separate .so for python onnx importer.
  python/CMakeLists.txt
  python/ngraph/impl/onnx_import/__init__.py
  python/pyngraph/axis_set.cpp
  python/pyngraph/coordinate_diff.cpp
  python/pyngraph/function.cpp
  python/pyngraph/onnx_import/onnx_import.cpp
  python/pyngraph/onnx_import/onnx_import.hpp
  python/pyngraph/ops/constant.cpp
  python/pyngraph/pyngraph.cpp
  python/pyngraph/shape.cpp
  python/pyngraph/strides.cpp
  python/requirements.txt
  python/setup.py
Labels: Fully Reviewed

#2754 Add ConstantToBroadcast pass
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/constant_to_broadcast.cpp
  src/ngraph/pass/constant_to_broadcast.hpp
  src/ngraph/serializer.cpp
  src/ngraph/serializer.hpp
  src/tools/reserialize/reserialize.cpp
  test/CMakeLists.txt
  test/pass.cpp
  test/util.cpp
Labels: Fully Reviewed

#2801 [ONNX] Extended types support for NgraphTestCase
  test/util/test_case.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed, ONNX

#2796 IntelGPU backend: Need to keep intermediate code
  src/ngraph/runtime/intelgpu/intelgpu_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#2802 Remove a no longer used file.
  python/pyngraph/pyngraph_onnx_import.cpp
Labels: Fully Reviewed

#2814 Fix broken test in shape specialization pass
  src/ngraph/pass/shape_specialization.cpp
  test/pass_shape_specialization.cpp
Labels: Fully Reviewed

#2805 Add numeric_limits for bfloat16 type
  src/ngraph/type/bfloat16.cpp
  src/ngraph/type/bfloat16.hpp
  test/bfloat16.cpp
Labels: Fully Reviewed

#2809 IntelGPU backend: Set of fusion operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#2812 Workaround for gcc 4.8.2: Suppress mkl-dnn warning manually since pra…
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed

#2819 Fix incorrect comment in partial_shape.hpp
  src/ngraph/partial_shape.hpp
Labels: Fully Reviewed

#2820 Fix Mac build error in bfloat16 tests
  test/bfloat16.cpp
Labels: Fully Reviewed, High Priority

#2798 [ONNX] Refactor quantized ops tests
  test/files/onnx/qlinearconv2d/w.bin
  test/files/onnx/qlinearconv2d/w_scale.bin
  test/files/onnx/qlinearconv2d/w_zero_point.bin
  test/files/onnx/qlinearconv2d/x_scale.bin
  test/files/onnx/qlinearconv2d/x_zero_point.bin
  test/files/onnx/qlinearconv2d/y_scale.bin
  test/files/onnx/qlinearconv2d/y_zero_point.bin
  test/files/onnx/qlinearconv3d/w.bin
  test/files/onnx/qlinearconv3d/w_scale.bin
  test/files/onnx/qlinearconv3d/w_zero_point.bin
  test/files/onnx/qlinearconv3d/x_scale.bin
  test/files/onnx/qlinearconv3d/x_zero_point.bin
  test/files/onnx/qlinearconv3d/y_scale.bin
  test/files/onnx/qlinearconv3d/y_zero_point.bin
  test/onnx/onnx_import_quant.in.cpp
  test/util/test_case.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed, ONNX

#2807 [ONNX] Simplify the get_monotonic_range helper function
  src/ngraph/frontend/onnx_import/utils/common.hpp
Labels: Fully Reviewed, ONNX

#2748 Build trigger to test TensorFlow bridge against PRs
  .ci/buildkite/test_ngtf_build.py
Labels: Fully Reviewed

#2803 Update LLVM to 8.0.0
  cmake/external_llvm.cmake
  cmake/external_llvm_prebuilt.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
Labels: Fully Reviewed

#2821 NGRAPH_JSON_ENABLE to conditionally enable JSON related features
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/serialize.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_debugger.cpp
  src/ngraph/runtime/cpu/cpu_tracing.cpp
  src/ngraph/runtime/cpu/cpu_tracing.hpp
  test/CMakeLists.txt
  test/autodiff.in.cpp
  test/backend_broadcast.in.cpp
  test/backend_test.in.cpp
  test/control_dependencies.cpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/gpu_fusion.cpp
  test/reshape_elimination.cpp
  test/reshape_sinking.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#2813 Fix MKLDNN convolution prop_kind
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
Labels: Fully Reviewed

#2790 PerformanceCounter rework
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/intelgpu/intelgpu_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/node_wrapper.hpp
  src/ngraph/runtime/performance_counter.hpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#2797 [Fused Ops] Add fused version of Elu
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/dequantize_linear.cpp
  src/ngraph/frontend/onnx_import/op/elu.cpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/prelu.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/elu.cpp
  src/ngraph/op/fused/elu.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2815 add safety checks for mkldnn-assignement for quantized inner product
  src/ngraph/runtime/cpu/builder/quantized_dot.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
Labels: Fully Reviewed

#2811 [Fused] Add DepthToSpace and SpaceToDepth fused ops
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/depth_to_space.cpp
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/matmul.cpp
  src/ngraph/frontend/onnx_import/op/reshape.cpp
  src/ngraph/frontend/onnx_import/op/space_to_depth.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/op/transpose.cpp
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/depth_to_space.hpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/util/reshape.cpp
  src/ngraph/op/util/reshape.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2829 Change nbench warmup to run full, normal iterations
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed

#2836 [ONNX] Refactoring tests to use NgraphTestCase
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2817 ShapeRelevance pass
  src/ngraph/CMakeLists.txt
  src/ngraph/op/experimental/dyn_pad.cpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/parameter.cpp
  src/ngraph/op/parameter.hpp
  src/ngraph/pass/shape_relevance.cpp
  src/ngraph/pass/shape_relevance.hpp
  test/CMakeLists.txt
  test/pass_shape_relevance.cpp
Labels: Fully Reviewed

#2830 Replace NodeMap class with an unordered map.
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.hpp
  src/ngraph/runtime/cpu/op/loop_kernel.cpp
  src/ngraph/specialize_shapes.cpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
  test/util.cpp
Labels: Fully Reviewed

#2834 IntelGPU backend: Use core fusion pass
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: IntelGPU

#2835 IntelGPU backend: GroupConvolution implementation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#2837 IntelGPU backend: Fix Convert, Pad and Pool
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Bug, Fully Reviewed, IntelGPU

#2839 [Standalone] Create mkldnn primitives in the generated file
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
Labels: IntelCPU

#2841 Support for complex ops used in object detection models
  src/ngraph/CMakeLists.txt
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box.hpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.hpp
  src/ngraph/op/experimental/layers/proposal.cpp
  src/ngraph/op/experimental/layers/proposal.hpp
  src/ngraph/op/experimental/layers/region_yolo.cpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
  src/ngraph/op/experimental/layers/reorg_yolo.cpp
  src/ngraph/op/experimental/layers/reorg_yolo.hpp
  test/CMakeLists.txt
  test/type_prop_layers.cpp
Labels: Fully Reviewed
