Repository NervanaSystems/ngraph, pull requests merged in 2019-11, with the labels that each got.

#3834 Add get_default_value in Dot op to handle the 0 sized input case
  src/ngraph/op/dot.cpp
  src/ngraph/op/dot.hpp
Labels: Fully Reviewed

#3831 Sarkars/move fn body to cpp
  src/ngraph/pass/implicit_broadcast_elimination.cpp
  src/ngraph/pass/implicit_broadcast_elimination.hpp
Labels: Fully Reviewed

#3802 Constant folding with shape inference; Updated specialize_function
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/graph_rewrite.hpp
  src/ngraph/specialize_function.cpp
  src/ngraph/specialize_function.hpp
Labels: Fully Reviewed

#3830 [SPEC] Add BinaryConvolution:v1
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/binary_convolution.cpp
  src/ngraph/op/binary_convolution.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/serialize.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3819 [SPEC] [MLIR] Adjust names of logical operators to the spec.
  src/ngraph/frontend/onnx_import/op/and.hpp
  src/ngraph/frontend/onnx_import/op/not.hpp
  src/ngraph/frontend/onnx_import/op/or.hpp
  src/ngraph/frontend/onnx_import/op/xor.hpp
  src/ngraph/node.hpp
  src/ngraph/op/and.cpp
  src/ngraph/op/and.hpp
  src/ngraph/op/less_eq.cpp
  src/ngraph/op/less_eq.hpp
  src/ngraph/op/not.cpp
  src/ngraph/op/not.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/or.cpp
  src/ngraph/op/or.hpp
  src/ngraph/op/xor.cpp
  src/ngraph/op/xor.hpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/opset_pass/logical_and_opset_pass.cpp
  test/opset_pass/logical_less_equal_opset_pass.cpp
  test/opset_pass/logical_not_opset_pass.cpp
  test/opset_pass/logical_or_opset_pass.cpp
  test/opset_pass/logical_xor_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3764 [MLIR] New Core Ops (V0) and Ops Versioning in NG dialect
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.hpp
  src/contrib/mlir/core/ngraph_dialect/ops.td
  src/contrib/mlir/core/ngraph_dialect/ops_attributes.td
  src/contrib/mlir/core/ngraph_dialect/ops_interfaces.td
  src/contrib/mlir/core/ngraph_dialect/ops_v0.td
  src/contrib/mlir/core/ngraph_dialect/ops_v1.td
  src/contrib/mlir/utils.cpp
  test/CMakeLists.txt
  test/main.cpp
  test/mlir/ops_test.cpp
Labels: Fully Reviewed

#3823 [SPEC] Rename element_type->destination_type attribute in Convert op
  src/ngraph/op/convert.cpp
  src/ngraph/op/convert.hpp
Labels: Fully Reviewed, SPEC

#3839 Allow fused ops to create outputs and set types/shapes in pre_validation
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/partial_slice.cpp
  src/ngraph/op/fused/rnn_cell.cpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/op/util/fused_op.hpp
Labels: Fully Reviewed

#3828 CMAKE: fixed gtests compilation with -Wundef compiler flag
  cmake/external_gtest.cmake
Labels: Fully Reviewed

#3840 Set Protobuf_FOUND to TRUE
  cmake/external_protobuf.cmake
Labels: Fully Reviewed

#3843 Pass Manager returns shared_ptr to each pass created.
  src/ngraph/pass/manager.hpp
  test/pass_manager.cpp
Labels: Fully Reviewed

#3711 Shape as a node in ConvBpropData/Filters (v1)
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/serializer.cpp
  test/backend/convolution.in.cpp
  test/opset_pass/convolution_opset_pass.cpp
  test/type_prop/convolution.cpp
Labels: Fully Reviewed

#3820 [Spec][FusedOp]Adjust DepthToSpace fused op to specification
  python/ngraph/ops.py
  python/pyngraph/ops/fused/depth_to_space.cpp
  python/test/ngraph/test_ops_fused.py
  src/ngraph/frontend/onnx_import/op/depth_to_space.cpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/depth_to_space.hpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/models/onnx/depth_to_space.prototxt
  test/models/onnx/depth_to_space_bad_blocksize.prototxt
  test/models/onnx/depth_to_space_chw.prototxt
  test/models/onnx/depth_to_space_no_blocksize.prototxt
  test/serialize.cpp
  test/type_prop/depth_to_space.cpp
Labels: Fully Reviewed, SPEC

#3848 Fix float16 denorm conversion, add rounding
  src/ngraph/type/float16.cpp
  test/float16.cpp
Labels: Bug, Fully Reviewed, High Priority

#3849 Sarkars/Add constant folding for Power for CPU
  src/ngraph/runtime/cpu/cpu_builder.cpp
Labels: Fully Reviewed

#3844 [FUSED] Add new Selu fused op.
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/selu.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/selu.cpp
  src/ngraph/op/fused/selu.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, SPEC

#3816 [SPEC] Numpy AutoBroadcast as default for specific ops.
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/equal.hpp
  src/ngraph/frontend/onnx_import/op/greater.hpp
  src/ngraph/frontend/onnx_import/op/leaky_relu.cpp
  src/ngraph/frontend/onnx_import/op/less.hpp
  src/ngraph/frontend/onnx_import/op/max.hpp
  src/ngraph/frontend/onnx_import/op/mean.cpp
  src/ngraph/frontend/onnx_import/op/min.hpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/pow.hpp
  src/ngraph/frontend/onnx_import/op/shrink.cpp
  src/ngraph/frontend/onnx_import/op/softplus.cpp
  src/ngraph/frontend/onnx_import/op/sum.hpp
  src/ngraph/frontend/onnx_import/op/thresholded_relu.cpp
  src/ngraph/frontend/onnx_import/utils/variadic.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/divide.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/equal.cpp
  src/ngraph/op/equal.hpp
  src/ngraph/op/greater.cpp
  src/ngraph/op/greater.hpp
  src/ngraph/op/greater_eq.cpp
  src/ngraph/op/greater_eq.hpp
  src/ngraph/op/less.cpp
  src/ngraph/op/less.hpp
  src/ngraph/op/less_eq.cpp
  src/ngraph/op/less_eq.hpp
  src/ngraph/op/maximum.cpp
  src/ngraph/op/maximum.hpp
  src/ngraph/op/minimum.cpp
  src/ngraph/op/minimum.hpp
  src/ngraph/op/multiply.cpp
  src/ngraph/op/multiply.hpp
  src/ngraph/op/not_equal.cpp
  src/ngraph/op/not_equal.hpp
  src/ngraph/op/power.cpp
  src/ngraph/op/power.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/opset_pass/binary_elementwise_opset_pass.cpp
  test/opset_pass/logical_less_equal_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3836 Remove unused variable
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
Labels: Fully Reviewed

#3841 Fixed compilation warnings to build nGraph unit tests in OV CI
  test/CMakeLists.txt
  test/algebraic_simplification.cpp
  test/build_graph.cpp
  test/concat_fusion.cpp
  test/constant_folding.cpp
  test/core_fusion.cpp
  test/cse.cpp
  test/nop_elimination.cpp
  test/reshape_elimination.cpp
  test/reshape_sinking.cpp
  test/type_prop_layers.cpp
  test/util.cpp
  test/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed, High Priority

#3038 TensorIterator
  src/ngraph/CMakeLists.txt
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/lambda.cpp
  src/ngraph/lambda.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/tensor_iterator.cpp
  src/ngraph/op/tensor_iterator.hpp
  src/ngraph/partial_shape.hpp
  src/ngraph/serializer.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#3861 Atan2 op (#3859)
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/atan2.cpp
  src/ngraph/op/atan2.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/pass/cse.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/kernel/atan2.hpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/atan2.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/atan2.in.cpp
  test/copy.cpp
Labels: Fully Reviewed

#3865 Autodiff for atan2
  src/ngraph/op/atan2.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/autodiff.in.cpp
Labels: Fully Reviewed

#3864 Fix an error in ONNXRT build
  src/ngraph/op/binary_convolution.hpp
Labels: Fully Reviewed

#3733 [SPEC] LSTMCell, RNNCell updates.
  python/ngraph/ops.py
  python/pyngraph/ops/fused/rnn_cell.cpp
  python/test/ngraph/test_ops_fused.py
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/op/fused/gru_cell.cpp
  src/ngraph/op/fused/gru_cell.hpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/lstm_cell.hpp
  src/ngraph/op/fused/lstm_sequence.cpp
  src/ngraph/op/fused/lstm_sequence.hpp
  src/ngraph/op/fused/rnn_cell.cpp
  src/ngraph/op/fused/rnn_cell.hpp
  src/ngraph/op/util/rnn_cell_base.cpp
  src/ngraph/op/util/rnn_cell_base.hpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/cpu_fusion.cpp
  test/serialize.cpp
  test/type_prop/gru_cell.cpp
  test/type_prop/lstm_cell.cpp
  test/type_prop/lstm_sequence.cpp
  test/type_prop/rnn_cell.cpp
Labels: Fully Reviewed, SPEC

#3789 [SPEC] Implement TopK:v1 downgrade
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  test/opset_pass/topk_opset_pass.cpp
  test/replace_node.cpp
Labels: Fully Reviewed, SPEC

#3853 Add folder to hold PDPD Fluid helper codes.
  CODEOWNERS
  src/ngraph/frontend/fluid/README.md
Labels: Fully Reviewed

#3835 [MLIR] Graph pass to lower ngraph to ngraph dialect
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/compiler.hpp
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.hpp
Labels: Fully Reviewed

#3845 specialize_function with shared constants
  src/ngraph/specialize_function.cpp
  src/ngraph/specialize_function.hpp
  test/specialize_function.cpp
Labels: Fully Reviewed

#3829 [ONNX] Add support for changed clip op in set 11.
  src/ngraph/frontend/onnx_import/op/clip.cpp
  src/ngraph/frontend/onnx_import/op/clip.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#3854 [SPEC] Anchors attribute for RegionYolo operator.
  src/ngraph/op/experimental/layers/region_yolo.cpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
Labels: Fully Reviewed, SPEC

#3883 Klockwork issues:
  src/ngraph/op/gather.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/softmax.cpp
  test/util.cpp
Labels: Fully Reviewed

#3880 Fix broadcast v1 reference
  src/ngraph/runtime/reference/broadcast.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed, High Priority

#3887 Force Gelu decompose on CPU
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed

#3885 Round the right bit with denorms
  src/ngraph/type/float16.cpp
  test/float16.cpp
Labels: Fully Reviewed

#3579 Attribute visitor
  src/ngraph/CMakeLists.txt
  src/ngraph/attribute_adapter.cpp
  src/ngraph/attribute_adapter.hpp
  src/ngraph/attribute_visitor.hpp
  src/ngraph/distributed.cpp
  src/ngraph/distributed.hpp
  src/ngraph/enum_names.hpp
  src/ngraph/factory.cpp
  src/ngraph/factory.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/node.hpp
  src/ngraph/op/abs.hpp
  src/ngraph/op/acos.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/all.hpp
  src/ngraph/op/allreduce.cpp
  src/ngraph/op/allreduce.hpp
  src/ngraph/op/and.cpp
  src/ngraph/op/and.hpp
  src/ngraph/op/any.hpp
  src/ngraph/op/argmax.cpp
  src/ngraph/op/argmax.hpp
  src/ngraph/op/argmin.cpp
  src/ngraph/op/argmin.hpp
  src/ngraph/op/asin.hpp
  src/ngraph/op/atan.hpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/broadcast.hpp
  src/ngraph/op/broadcast_distributed.cpp
  src/ngraph/op/broadcast_distributed.hpp
  src/ngraph/op/ceiling.hpp
  src/ngraph/op/concat.cpp
  src/ngraph/op/concat.hpp
  src/ngraph/op/parameter.cpp
  src/ngraph/op/parameter.hpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/op/util/binary_elementwise_arithmetic.cpp
  src/ngraph/op/util/binary_elementwise_arithmetic.hpp
  src/ngraph/op/util/binary_elementwise_comparison.cpp
  src/ngraph/op/util/binary_elementwise_comparison.hpp
  src/ngraph/op/util/binary_elementwise_logical.cpp
  src/ngraph/op/util/binary_elementwise_logical.hpp
  src/ngraph/op/util/index_reduction.cpp
  src/ngraph/op/util/index_reduction.hpp
  src/ngraph/type.hpp
  test/CMakeLists.txt
  test/attributes.cpp
Labels: Fully Reviewed

#3842 [ONNX] Importer should use fused op for MatMul
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/matmul.cpp
  src/ngraph/frontend/onnx_import/op/matmul.hpp
  src/ngraph/op/fused/matmul.cpp
Labels: Fully Reviewed, ONNX

#3856 [SPEC] Add auto_broadcast parameter to SquaredDifference
  src/ngraph/op/fused/squared_difference.cpp
  src/ngraph/op/fused/squared_difference.hpp
  src/ngraph/serializer.cpp
  test/type_prop/squared_difference.cpp
Labels: Fully Reviewed, SPEC

#3862 [Spec][FusedOp]Adjust SpaceToDepth fused op to specification
  python/ngraph/ops.py
  python/pyngraph/ops/fused/space_to_depth.cpp
  python/test/ngraph/test_ops_fused.py
  src/ngraph/frontend/onnx_import/op/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.hpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/serialize.cpp
  test/type_prop/space_to_depth.cpp
Labels: Fully Reviewed, SPEC

#3878 Force AutoBroadcast defaults
  src/ngraph/op/add.hpp
  src/ngraph/op/atan2.hpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/maximum.hpp
  src/ngraph/op/minimum.hpp
  src/ngraph/op/multiply.hpp
  src/ngraph/op/power.hpp
  src/ngraph/op/relu.cpp
  src/ngraph/op/sigmoid.cpp
  src/ngraph/op/sigmoid.hpp
  src/ngraph/op/subtract.hpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/op/util/binary_elementwise_arithmetic.cpp
  src/ngraph/op/util/binary_elementwise_arithmetic.hpp
  src/ngraph/runtime/cpu/op/gelu_backprop.cpp
Labels: Fully Reviewed

#3895 Added constant folding for V1 binary ops
  src/ngraph/pass/constant_folding_binary.cpp
Labels: Fully Reviewed, High Priority

#3898 Bug Fix: incorrect shape validation logic.
  src/ngraph/op/scatter_nd_add.cpp
Labels: Bug, Fully Reviewed

#3899 Add ReplaceSlice to ZeroDimTensorEliminiation pass
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#3876 Update fused ops groupconvolution, gelu and layernorm to be dynamic friendly
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/layer_norm.cpp
  src/ngraph/op/fused/layer_norm.hpp
Labels: Fully Reviewed

#3882 Add full path to gtest for build via ninja
  cmake/external_gtest.cmake
Labels: Fully Reviewed, High Priority

#3852 [SPEC] Add new v1::FloorMod operator
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/floor_mod.cpp
  src/ngraph/op/floor_mod.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, SPEC

#3896 [MLIR] Fix MLIR build on mac OS
  src/contrib/mlir/CMakeLists.txt
Labels: Fully Reviewed

#3879 [MLIR] Bump MLIR commit to c61db4bb
  cmake/external_mlir.cmake
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/compiler.hpp
  src/contrib/mlir/core/ngraph_dialect/dialect.cpp
  src/contrib/mlir/core/ngraph_dialect/dialect.hpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.hpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.hpp
  src/contrib/mlir/runtime/runtime.hpp
  test/mlir/ngraph_dialect/types.mlir
Labels: Fully Reviewed

#3901 Modify Gather constant folding to support v1 op.
  src/ngraph/pass/constant_folding_gather.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, High Priority

#3892 Deprecate runtime::Tensor::copy_from
  src/ngraph/runtime/tensor.hpp
Labels: Fully Reviewed

#3897 Bug Fix: incorrect shape validation logic.
  src/ngraph/op/scatter_nd_add.cpp
Labels: Bug, Fully Reviewed

#3900 Allow for overriding functions in visualization
  src/ngraph/pass/visualize_tree.hpp
Labels: Fully Reviewed

#3910 Add ReplaceSlice to ZeroDimTensorEliminiation pass (#3899)
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#3913 Default constructor needs to init autob
  src/ngraph/op/floor_mod.hpp
Labels: Bug, Fully Reviewed

#3818 Implementation of CrossEntropy and CrossEntropyBackprop as fused Op's
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/crossentropy.cpp
  src/ngraph/op/fused/crossentropy.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/core_fusion.cpp
Labels: Fully Reviewed

#3846 Update ToC to better match docplan spreadsheet
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/core/constructing-graphs/distribute-train.rst
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/core/quantization.rst
  doc/sphinx/source/dynamic/index.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/onnx_integ.rst
  doc/sphinx/source/frameworks/other/index.rst
  doc/sphinx/source/frameworks/overview.rst
  doc/sphinx/source/frameworks/paddle_integ.rst
  doc/sphinx/source/frameworks/tensorflow_connect.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/add.rst
  doc/sphinx/source/ops/and.rst
  doc/sphinx/source/ops/broadcast.rst
  doc/sphinx/source/ops/divide.rst
  doc/sphinx/source/ops/equal.rst
  doc/sphinx/source/ops/greater.rst
  doc/sphinx/source/ops/greater_eq.rst
  doc/sphinx/source/ops/less.rst
  doc/sphinx/source/ops/less_eq.rst
  doc/sphinx/source/ops/maximum.rst
  doc/sphinx/source/ops/minimum.rst
  doc/sphinx/source/ops/multiply.rst
  doc/sphinx/source/ops/not.rst
  doc/sphinx/source/ops/not_equal.rst
  doc/sphinx/source/ops/or.rst
  doc/sphinx/source/ops/power.rst
  doc/sphinx/source/ops/slice.rst
  doc/sphinx/source/ops/xor.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/provenance/index.rst
  doc/sphinx/source/training/data_ingest.rst
  doc/sphinx/source/training/index.rst
  doc/sphinx/source/training/overview.rst
  doc/sphinx/source/training/paddle_dist.rst
  doc/sphinx/source/training/qat.rst
  doc/sphinx/source/training/tf_dist.rst
Labels: Documentation, Fully Reviewed

#3921 Fix CSS rendering issues
  doc/sphinx/ngraph_theme/layout.html
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/frameworks/overview.rst
  doc/sphinx/source/frameworks/quickstart.rst
Labels: Bug, High Priority

#3906 Fix for the bug with as_type_ptr for TensorIterator::Input/Ouput desc
  src/ngraph/op/tensor_iterator.hpp
  test/serialize.cpp
Labels: Fully Reviewed

#3902 Force Gelu decompose on CPU
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed

#3912 Bug fix in conv v1 shape inference
  src/ngraph/op/convolution.cpp
  test/type_prop/convolution.cpp
Labels: Bug, Fully Reviewed

#3868 [SPEC] Add new v1::VariadicSplit operator
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/variadic_split.cpp
  src/ngraph/op/variadic_split.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, SPEC

#3894 Update ONNX importer to use v1 version of Softmax
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/frontend/onnx_import/op/softmax.hpp
  src/ngraph/pass/opset0_downgrade.cpp
Labels: Fully Reviewed, ONNX

#3922 Fix shape inference of TensorIterator body
  src/ngraph/op/tensor_iterator.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#3923 Resolve compiler warning - has virtual functions and accessible non-virtual destructor
  src/ngraph/attribute_adapter.hpp
Labels: Fully Reviewed

#3914 Added u1 precision for binary weights
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/ngraph/builder/make_constant.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/op/binary_convolution.cpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/max.cpp
  src/ngraph/op/min.cpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/pass/constant_folding_broadcast.cpp
  src/ngraph/pass/constant_folding_concat.cpp
  src/ngraph/pass/constant_folding_convert.cpp
  src/ngraph/pass/constant_folding_dyn_broadcast.cpp
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  src/ngraph/pass/constant_folding_dyn_slice.cpp
  src/ngraph/pass/constant_folding_gather.cpp
  src/ngraph/pass/constant_folding_pad.cpp
  src/ngraph/pass/constant_folding_range.cpp
  src/ngraph/pass/constant_folding_reshape.cpp
  src/ngraph/pass/constant_folding_reverse.cpp
  src/ngraph/pass/constant_folding_select.cpp
  src/ngraph/pass/constant_folding_slice.cpp
  src/ngraph/pass/constant_folding_squeeze.cpp
  src/ngraph/pass/constant_folding_transpose.cpp
  src/ngraph/pass/constant_folding_unary.cpp
  src/ngraph/pass/constant_folding_unsqueeze.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/runtime/cpu/builder/random_uniform.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  src/tools/nbench/benchmark_utils.cpp
  test/CMakeLists.txt
  test/convert_u1_to_string.cpp
Labels: Fully Reviewed, High Priority

#3871 Fused_op: BatchMatMulTranspose
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/batch_mat_mul_transpose.cpp
  src/ngraph/op/fused/batch_mat_mul_transpose.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/matmul_bias.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/autodiff.in.cpp
  test/backend/batch_mat_mul.in.cpp
  test/backend/fused_op.in.cpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
  test/type_prop/batch_mat_mul_transpose.cpp
Labels: Fully Reviewed

#3889 [ONNX CI] Change repositories addresses to use SSH
  .ci/onnx/jenkins/Jenkinsfile
Labels: Fully Reviewed, ONNX

#3919 Move CPU only unit tests to the cpu test file
  test/CMakeLists.txt
  test/backend/api.in.cpp
  test/backend/one_hot.in.cpp
  test/backend/tensorview_custom_mem.in.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#3903 Cyphers/uop
  src/ngraph/node.cpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/op_v0_tbl.hpp
  src/ngraph/op/op_v1_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/interpreter/CMakeLists.txt
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/node_wrapper.cpp
  src/ngraph/runtime/interpreter/node_wrapper.hpp
  src/ngraph/serializer.cpp
  src/ngraph/type.hpp
  test/opset_pass/binary_elementwise_opset_pass.cpp
  test/opset_pass/broadcast_opset_pass.cpp
  test/opset_pass/convolution_opset_pass.cpp
  test/opset_pass/dyn_reshape_opset_pass.cpp
  test/opset_pass/gather_opset_pass.cpp
  test/opset_pass/generate_mask_opset_pass.cpp
  test/opset_pass/logical_and_opset_pass.cpp
  test/opset_pass/logical_not_opset_pass.cpp
  test/opset_pass/logical_or_opset_pass.cpp
  test/opset_pass/logical_xor_opset_pass.cpp
  test/opset_pass/pad_opset_pass.cpp
  test/opset_pass/poolings_opset_pass.cpp
  test/opset_pass/product_opset_pass.cpp
  test/opset_pass/reverse_opset_pass.cpp
  test/opset_pass/slice_opset_pass.cpp
  test/opset_pass/softmax_opset_pass.cpp
  test/opset_pass/sum_opset_pass.cpp
  test/opset_pass/topk_opset_pass.cpp
Labels: Bug, Fully Reviewed, High Priority

#3924 Add default constructor to some ops missing them
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.hpp
  src/ngraph/op/experimental/layers/detection_output.hpp
  src/ngraph/op/experimental/layers/interpolate.hpp
  src/ngraph/op/experimental/layers/prior_box.hpp
  src/ngraph/op/experimental/layers/prior_box_clustered.hpp
  src/ngraph/op/experimental/layers/proposal.hpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
  src/ngraph/op/experimental/layers/reorg_yolo.hpp
  src/ngraph/op/experimental/layers/roi_pooling.hpp
  src/ngraph/op/experimental/quantized_conv_bias.hpp
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/op/fused/gru_cell.hpp
  src/ngraph/op/fused/lstm_cell.hpp
  src/ngraph/op/fused/rnn_cell.hpp
  src/ngraph/op/fused/selu.hpp
  src/ngraph/op/get_output_element.hpp
  src/ngraph/op/or.hpp
  src/ngraph/op/quantized_dot.hpp
  src/ngraph/op/relu.hpp
  src/ngraph/op/xor.hpp
Labels: Fully Reviewed

#3905 add env pass filtering to core
  src/ngraph/pass/manager.hpp
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/pass_config.hpp
Labels: Fully Reviewed

#3869 move CollpaseDims pass into core
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/collapse_dims.cpp
  src/ngraph/pass/collapse_dims.hpp
  src/ngraph/pass/pass_config.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed

#3857 [SPEC] HardSigmoid adjustments
  python/pyngraph/ops/fused/hard_sigmoid.cpp
  python/test/ngraph/test_ops_fused.py
  src/ngraph/frontend/onnx_import/op/hard_sigmoid.cpp
  src/ngraph/op/fused/hard_sigmoid.cpp
  src/ngraph/op/fused/hard_sigmoid.hpp
  src/ngraph/op/util/activation_functions.cpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/type_prop/hard_sigmoid.cpp
Labels: Fully Reviewed, SPEC

#3925 CropAndResize op (#3893)
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/crop_and_resize.cpp
  src/ngraph/op/crop_and_resize.hpp
  src/ngraph/op/op_v0_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/type_prop/crop_and_resize.cpp
Labels: Fully Reviewed

#3929 Put all the op header includes in one header file, ops.hpp
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/ops.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3928 Fix compilation issues for default constructors
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/op/relu.hpp
  src/ngraph/op/util/activation_functions.hpp
  src/ngraph/op/util/rnn_cell_base.hpp
Labels: Bug, Fully Reviewed, High Priority

#3891 Make Node's type_info mandatory
  src/ngraph/node.hpp
  test/control_dependencies.cpp
Labels: Fully Reviewed

#3934 Copy rt info
  src/ngraph/specialize_function.cpp
Labels: High Priority

#3877 Matmul float type test case for UEP
  test/models/onnx/matmul_float.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3884 [SPEC] Add OneHot:v1
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/one_hot.hpp
  src/ngraph/op/op_v1_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/CMakeLists.txt
  test/opset_pass/one_hot_opset_pass.cpp
  test/type_prop/one_hot.cpp
Labels: Fully Reviewed, SPEC

#3916 Enable pipelining in CPU Backend
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  test/backend_api.cpp
Labels: Fully Reviewed

#3909 [SPEC] Add support string as AutoBroadcastSpec
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  test/backend/auto_broadcast.in.cpp
Labels: Fully Reviewed, SPEC

#3938 Adding default ctor for Constant
  src/ngraph/op/constant.hpp
Labels: Fully Reviewed

#3873 Cumulative Sum
  src/ngraph/CMakeLists.txt
  src/ngraph/op/cum_sum.cpp
  src/ngraph/op/cum_sum.hpp
  src/ngraph/op/op_v0_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/cum_sum.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/cum_sum.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/cum_sum.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/cum_sum.in.cpp
Labels: Fully Reviewed, IntelCPU

#3946 Fix incorrect uses of `description()`
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#3949 Move non-primitive attribute adapters to adaptee's files
  src/ngraph/attribute_adapter.cpp
  src/ngraph/attribute_adapter.hpp
  src/ngraph/axis_set.cpp
  src/ngraph/axis_set.hpp
  src/ngraph/coordinate.cpp
  src/ngraph/coordinate.hpp
  src/ngraph/coordinate_diff.cpp
  src/ngraph/coordinate_diff.hpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/shape.cpp
  src/ngraph/shape.hpp
  src/ngraph/strides.cpp
  src/ngraph/strides.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
Labels: Fully Reviewed

#3927 Update ONNX importer Gemm to produce MatMul op
  src/ngraph/frontend/onnx_import/op/gemm.cpp
  src/ngraph/frontend/onnx_import/op/gemm.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#3908 [SPEC][FusedOp] Add Mod operator
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/mod.cpp
  src/ngraph/frontend/onnx_import/op/mod.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/fused/mod.cpp
  src/ngraph/op/fused/mod.hpp
  src/ngraph/op/op_v1_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/models/onnx/mod_sign.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, SPEC

#3942 Test cleanups
  test/opset_pass/binary_elementwise_opset_pass.cpp
  test/opset_pass/broadcast_opset_pass.cpp
  test/opset_pass/convolution_opset_pass.cpp
  test/opset_pass/dyn_reshape_opset_pass.cpp
  test/opset_pass/gather_opset_pass.cpp
  test/opset_pass/generate_mask_opset_pass.cpp
  test/opset_pass/logical_and_opset_pass.cpp
  test/opset_pass/logical_not_opset_pass.cpp
  test/opset_pass/logical_or_opset_pass.cpp
  test/opset_pass/logical_xor_opset_pass.cpp
  test/opset_pass/one_hot_opset_pass.cpp
  test/opset_pass/pad_opset_pass.cpp
  test/opset_pass/poolings_opset_pass.cpp
  test/opset_pass/product_opset_pass.cpp
  test/opset_pass/reverse_opset_pass.cpp
  test/opset_pass/slice_opset_pass.cpp
  test/opset_pass/softmax_opset_pass.cpp
  test/opset_pass/sum_opset_pass.cpp
  test/opset_pass/topk_opset_pass.cpp
  test/pattern.cpp
  test/serialize.cpp
  test/util/matcher.hpp
Labels: Fully Reviewed

#3930 Documentation for Dynamic Shapes and additional graph construction options
  doc/examples/dynamic_tensor/partial_shape.cpp
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/core/constructing-graphs/execute.rst
  doc/sphinx/source/core/constructing-graphs/index.rst
  doc/sphinx/source/core/passes/passes.rst
  doc/sphinx/source/dynamic/index.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/paddle_integ.rst
  doc/sphinx/source/glossary.rst
  doc/sphinx/source/graphics/ExecutionInterfaceRunGraphs.png
  doc/sphinx/source/graphics/dl-current-state.png
  doc/sphinx/source/graphics/dl-current-state.xcf
  doc/sphinx/source/graphics/execution-interface-run-graph.svg
  doc/sphinx/source/graphics/paddlepaddle_design.png
  doc/sphinx/source/graphics/paddlepaddle_design.svg
  doc/sphinx/source/graphics/scalability-matters.png
  doc/sphinx/source/graphics/scalability-matters.xcf
  doc/sphinx/source/graphics/simple-compiler-passes.png
  doc/sphinx/source/graphics/simple-compiler-passes.svg
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/ops/one_hot.rst
Labels: Documentation, Fully Reviewed

#3918 [ONNX] Add CumSum to ONNX importer
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/cum_sum.cpp
  src/ngraph/frontend/onnx_import/op/cum_sum.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/models/onnx/cum_sum_1d.prototxt
  test/models/onnx/cum_sum_2d_axis_input.prototxt
  test/models/onnx/cum_sum_2d_dynamic_axis_input.prototxt
  test/models/onnx/cum_sum_3d_exclusive_reverse.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3860 [MLIR] Fused Ops dialect declaration
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.td
  src/contrib/mlir/core/ngraph_dialect/ops_attributes.td
  src/contrib/mlir/core/ngraph_dialect/ops_v0.td
  test/mlir/ngraph_dialect/fused_ops.mlir
Labels: Fully Reviewed

#3911 [MLIR] Enable ViewOp in Affine Lowerer
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  test/mlir/affine_conversion/core_ops.mlir
Labels: Fully Reviewed

#3955 ConstantFolding for v1::StridedSlice operation
  src/ngraph/CMakeLists.txt
  src/ngraph/op/strided_slice.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_strided_slice.cpp
Labels: Fully Reviewed, High Priority

#3926 [SPEC] Add negative axes support for ReverseSequence
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/op/reverse_sequence.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend/reverse_sequence.in.cpp
  test/type_prop/reverse_sequence.cpp
Labels: Fully Reviewed, SPEC

#3935 [SPEC] Adjust ConvolutionBackpropData op.
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/serializer.cpp
  test/backend/convolution.in.cpp
  test/opset_pass/convolution_opset_pass.cpp
  test/type_prop/convolution.cpp
Labels: Fully Reviewed, SPEC

#3944 [SPEC] ConvertLike op
  src/ngraph/CMakeLists.txt
  src/ngraph/op/convert_like.cpp
  src/ngraph/op/convert_like.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, SPEC

#3966 [Spec] Add 3-input constructor to DetectionOutput
  src/ngraph/op/experimental/layers/detection_output.cpp
  src/ngraph/op/experimental/layers/detection_output.hpp
Labels: Fully Reviewed, SPEC
