Repository NervanaSystems/ngraph, pull requests merged in 2019-09, with the labels that each got.

#3541 [MLIR] Clean up MLIR related CMake files
  cmake/external_mlir.cmake
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/compiler/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#3546 Clean up and triage unit tests
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, PlaidML

#3527 [Py] Added Dequantize, Quantize, Quantized Convolution, Quantized Dot…
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  doc/sphinx/source/python_api/_autosummary/ngraph.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/dequantize.cpp
  python/pyngraph/ops/dequantize.hpp
  python/pyngraph/ops/quantize.cpp
  python/pyngraph/ops/quantize.hpp
  python/pyngraph/ops/quantized_convolution.cpp
  python/pyngraph/ops/quantized_convolution.hpp
  python/pyngraph/ops/quantized_dot.cpp
  python/pyngraph/ops/quantized_dot.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_quantized.py
Labels: Fully Reviewed

#3550 [MLIR] Enable ArgMin, ArgMax, Maximum, Minimum, Greater, and Less for non-in…
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3465 Fold Constant + ConvertLayout to reduce memory footprint.
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#3552 Performance optimize reference TopK op
  src/ngraph/op/topk.hpp
  src/ngraph/runtime/cpu/builder/topk.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/topk.hpp
  test/backend/topk.in.cpp
  test/type_prop/top_k.cpp
Labels: Fully Reviewed

#3565 Exclude CI-failing unit tests for PlaidML
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed

#3330 [FUSED] Add new MatMul fused operator
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/matmul_factory.cpp
  src/ngraph/builder/matmul_factory.hpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/matmul.cpp
  src/ngraph/frontend/onnx_import/op/matmul_integer.cpp
  src/ngraph/frontend/onnx_import/op/qlinear_matmul.cpp
  src/ngraph/frontend/onnx_import/utils/matmul_factory.hpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/matmul.cpp
  src/ngraph/op/fused/matmul.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/type_prop/matmul.cpp
Labels: Fully Reviewed

#3561 Fix CI email commit hash and commit subject.
  .ci/onnx/jenkins/Jenkinsfile
Labels: Fully Reviewed

#3468 Add replace_nodes function
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  test/CMakeLists.txt
  test/replace_node.cpp
Labels: Fully Reviewed

#3559 [MLIR] Clear SubGraph construction info
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.hpp
Labels: Fully Reviewed

#3567 Add missing includes to power.hpp
  src/ngraph/runtime/reference/power.hpp
Labels: Fully Reviewed

#3227 Use mkl-dnn v1.0 or v0.x depending on compilation flag.
  CMakeLists.txt
  cmake/external_mkldnn_v1.cmake
  cmake/mkldnn_v1.patch
  src/ngraph/codegen/compiler.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/add.cpp
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/leaky_relu.cpp
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/builder/quantized_dot.cpp
  src/ngraph/runtime/cpu/builder/quantized_matmul.cpp
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_executor.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_invoke.cpp
  src/ngraph/runtime/cpu/mkldnn_invoke.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#3524 [MLIR] Enable LIT testing in CMAKE
  test/CMakeLists.txt
  test/mlir/CMakeLists.txt
Labels: Fully Reviewed

#3566 [ONNX] Install serialize_onnx in nGraph's install dir
  src/tools/serialize_onnx/CMakeLists.txt
Labels: Fully Reviewed

#3569 Change cpu code ownership
  CODEOWNERS
Labels: Fully Reviewed

#3553 Minimize #include in op headers
  src/ngraph/op/all.cpp
  src/ngraph/op/all.hpp
  src/ngraph/op/any.cpp
  src/ngraph/op/any.hpp
  src/ngraph/op/argmax.cpp
  src/ngraph/op/argmax.hpp
  src/ngraph/op/argmin.cpp
  src/ngraph/op/argmin.hpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/op/embedding_lookup.hpp
  src/ngraph/op/erf.hpp
  src/ngraph/op/experimental/compiled_kernel.hpp
  src/ngraph/op/experimental/generate_mask.cpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/op/product.cpp
  src/ngraph/op/product.hpp
  src/ngraph/op/quantized_dot.hpp
  src/ngraph/op/relu.hpp
  src/ngraph/op/sum.cpp
  src/ngraph/op/sum.hpp
  src/ngraph/op/topk.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed

#3563 [ONNX] Fix support for float16 in ONNX frontend.
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/op/constant.cpp
Labels: Fully Reviewed

#3576 Update release notes for 0.25.1-rc.2
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#3573 Fix reshape error for onnx
  .ci/jenkins/jenkins-trigger.groovy
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/runtime/cpu/kernel/result.hpp
Labels: High Priority

#3571 [MLIR] Add install rule for libmlir_backend
  src/contrib/mlir/compiler/CMakeLists.txt
Labels: Fully Reviewed

#3562 Fixed NormalizeL2 decomposition for input shape length != 4
  src/ngraph/op/fused/normalize_l2.cpp
  src/ngraph/op/fused/normalize_l2.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend/fused_op.in.cpp
  test/type_prop/normalize.cpp
Labels: Fully Reviewed

#3577 Fix reshape error for onnx (on master)
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/runtime/cpu/kernel/result.hpp
Labels: Fully Reviewed

#3584 [MLIR] Bump commits
  cmake/external_mlir.cmake
  src/contrib/mlir/compiler/compiler.cpp
  src/contrib/mlir/compiler/lowerer.cpp
Labels: Fully Reviewed

#3329 nGraph-ONNX CI improvement
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/README.md
  .ci/onnx/jenkins/base_image_builder/Jenkinsfile
  .ci/onnx/jenkins/dockerfiles/ubuntu_16_04.dockerfile
  .ci/onnx/jenkins/prepare_environment.sh
  .ci/onnx/jenkins/utils/docker.sh
  .ci/onnx/jenkins/utils/utils.groovy
Labels: Fully Reviewed, ONNX

#3568 [MLIR] Remove Fake Instructions
  src/contrib/mlir/compiler/compiler.cpp
  src/contrib/mlir/compiler/compiler.hpp
  src/contrib/mlir/compiler/dialect/ops.td
  src/contrib/mlir/compiler/lowerer.cpp
Labels: Fully Reviewed

#3585 Fix passing of CMAKE_CXX_FLAGS to gtest
  cmake/external_gtest.cmake
Labels: Fully Reviewed

#3497 Cyphers/static
  CMakeLists.txt
  changes.md
  src/ngraph/CMakeLists.txt
  src/ngraph/component_manager.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/backend_manager.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/generic_cpu/gcpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/int_visibility.hpp
  src/ngraph/runtime/nop/nop_backend.cpp
  src/ngraph/runtime/plaidml/plaidml_backend_constructor.cpp
  test/CMakeLists.txt
  test/main.cpp
Labels: Changes API, Fully Reviewed

#3519 Leona/doc static
  doc/sphinx/source/backends/backend-api/index.rst
  doc/sphinx/source/backends/index.rst
Labels: Fully Reviewed

#3594 [ONNX CI] Add retry to clone step
  .ci/onnx/jenkins/Jenkinsfile
Labels: Fully Reviewed, ONNX

#3596 Update ReleaseNotes for 0.26
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/source/conf.py
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#3608 Enable some warnings
  cmake/clang_4_0_flags.cmake
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_internal_function.cpp
  src/ngraph/runtime/gpu/host_emitter.cpp
  src/ngraph/runtime/gpu/pass/gpu_layout.cpp
  src/resource/uncomment.cpp
  test/gpu_test.cpp
Labels: Fully Reviewed

#3620 Fix klocwork issues.
  src/ngraph/op/lrn.cpp
  src/ngraph/op/softmax.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  test/pattern.cpp
Labels: Fully Reviewed

#3618 resolve compiler warnings with clang-8
  src/ngraph/op/recv.hpp
  src/ngraph/op/send.hpp
  src/ngraph/pass/implicit_broadcast_elimination.cpp
  src/ngraph/runtime/cpu/builder/argmax.cpp
  src/ngraph/runtime/cpu/builder/argmin.cpp
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/builder/broadcast.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/convert.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/dot.cpp
  src/ngraph/runtime/cpu/builder/erf.cpp
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/leaky_relu.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/one_hot.cpp
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/builder/reduction.hpp
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/builder/replace_slice.cpp
  src/ngraph/runtime/cpu/builder/reshape.cpp
  src/ngraph/runtime/cpu/builder/reverse.cpp
  src/ngraph/runtime/cpu/builder/reverse_sequence.cpp
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/builder/select.cpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/builder/tile.cpp
  src/ngraph/runtime/cpu/builder/update_slice.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  test/cpu_debugger.cpp
Labels: Fully Reviewed

#3564 [MLIR] Fix style in compiler and lowerer files
  src/contrib/mlir/compiler/compiler.cpp
  src/contrib/mlir/compiler/compiler.hpp
  src/contrib/mlir/compiler/dialect/ops.cpp
  src/contrib/mlir/compiler/dialect/type.cpp
  src/contrib/mlir/compiler/lowerer.cpp
Labels: Fully Reviewed

#3614 [MLIR] Fix non-determ. order of nodes in MLIR sub-graphs
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.hpp
Labels: Fully Reviewed

#3622 Remove some dynamic_ptr_casts
  src/ngraph/function.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/experimental/dyn_replace_slice.cpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/experimental/layers/interpolate.cpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/experimental/tile.cpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/op/fused/matmul.cpp
  src/ngraph/op/fused/matmul.hpp
  src/ngraph/op/fused/normalize_l2.cpp
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/lrn.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/binary_elementwise_arithmetic.hpp
  src/ngraph/op/util/binary_elementwise_comparison.hpp
  src/ngraph/op/util/binary_elementwise_logical.hpp
  src/ngraph/op/util/fused_op.hpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/op/util/unary_elementwise_arithmetic.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/pass/constant_folding_dequantize.cpp
  src/ngraph/pass/constant_folding_logical_reduction.cpp
  src/ngraph/pass/constant_folding_quantize.cpp
  src/ngraph/pass/constant_folding_unary.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/fused_op_decomposition.cpp
  src/ngraph/pass/implicit_broadcast_elimination.cpp
  src/ngraph/pass/implicit_broadcast_elimination.hpp
  src/ngraph/pass/like_replacement.cpp
  src/ngraph/pass/liveness.cpp
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/pass/nop_elimination.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/validate_graph.cpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/pattern/op/any.hpp
  src/ngraph/pattern/op/any_of.hpp
  src/ngraph/pattern/op/label.hpp
  src/ngraph/pattern/op/skip.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.cpp
  src/ngraph/serializer.cpp
  src/ngraph/specialize_function.cpp
  src/ngraph/util.cpp
  test/pattern.cpp
Labels: Fully Reviewed

#3586 [MLIR] Add padding support to Convolution
  src/contrib/mlir/compiler/lowerer.cpp
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.cpp
  test/backend/convolution.in.cpp
Labels: Fully Reviewed

#3632 [ONNX] Handling of unknown domains in ONNX models [r0.26]
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/unknown_domain.prototxt
  test/models/onnx/unknown_domain_add.prototxt
  test/onnx/onnx_import.in.cpp
Labels: ONNX

#3631 [ONNX] Handling of unknown domains in ONNX models
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/unknown_domain.prototxt
  test/models/onnx/unknown_domain_add.prototxt
  test/onnx/onnx_import.in.cpp
Labels: ONNX

#3582 [SPEC] Adjust Concat to specification
  changes.md
  src/ngraph/op/concat.cpp
  src/ngraph/op/concat.hpp
Labels: Fully Reviewed, SPEC

#3624 Mmahbubu/provenance fix grpah replace
  src/ngraph/graph_util.cpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  test/provenance.cpp
Labels: Fully Reviewed

#3574 [Spec] Implement Pad:v1
  src/ngraph/op/pad.cpp
  src/ngraph/op/pad.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/opset_pass/pad_opset_pass.cpp
  test/serialize.cpp
  test/type_prop/pad.cpp
Labels: Fully Reviewed

#3600 [MLIR] Add ngraph-opt documentation
  src/contrib/mlir/tools/ngraph-opt/ngraph_opt.cpp
Labels: Fully Reviewed

#3635 [ONNX] ReverseSequence attributes validation [r0.26]
  src/ngraph/frontend/onnx_import/op/reverse_sequence.cpp
  test/models/onnx/reverse_sequence_incorrect_batch_axis.prototxt
  test/models/onnx/reverse_sequence_incorrect_time_axis.prototxt
  test/models/onnx/reverse_sequence_time_and_batch_axis_equal.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3627 resolve compiler warnings for undefined-func-template & float-conversion
  CMakeLists.txt
  cmake/clang_4_0_flags.cmake
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/runtime/cpu/kernel/gather.hpp
  test/util.cpp
Labels: Fully Reviewed

#3623 Remove debug graphviz plots
  test/concat_fusion.cpp
Labels: Fully Reviewed

#3639 Mmahbubu/provenance fix graph replace (#3624)
  src/ngraph/graph_util.cpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  test/provenance.cpp
Labels: Fully Reviewed

#3607 [MLIR] Add flag to dump jitted MLIR to object file
  src/contrib/mlir/compiler/compiler.cpp
Labels: Fully Reviewed

#3590 [Spec] Implement Gather:v1
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/opset_pass/gather_opset_pass.cpp
  test/serialize.cpp
  test/type_prop/gather.cpp
Labels: Fully Reviewed, SPEC

#3634 [ONNX] ReverseSequence attributes validation
  src/ngraph/frontend/onnx_import/op/reverse_sequence.cpp
  test/models/onnx/reverse_sequence_incorrect_batch_axis.prototxt
  test/models/onnx/reverse_sequence_incorrect_time_axis.prototxt
  test/models/onnx/reverse_sequence_time_and_batch_axis_equal.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3643 [0.26] Add support for negative axis.
  src/ngraph/frontend/onnx_import/op/concat.cpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/gather.hpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/frontend/onnx_import/op/mean_variance_normalization.cpp
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/op/reverse_sequence.cpp
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
Labels: Fully Reviewed

#3617 Latest illustrations of nG components and features
  ABOUT.md
  README.md
  doc/sphinx/source/graphics/nGraph_main.png
  doc/sphinx/source/graphics/ngraph_arch_diag.png
  doc/sphinx/source/graphics/ngraph_full_stack_diagrams.png
Labels: Fully Reviewed

#3350 Add a compile time flag to support all ET's in cpu backend
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/argmax.cpp
  src/ngraph/runtime/cpu/builder/argmin.cpp
  src/ngraph/runtime/cpu/builder/broadcast.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/dot.cpp
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/builder/reduction.hpp
  src/ngraph/runtime/cpu/builder/replace_slice.cpp
  src/ngraph/runtime/cpu/builder/reshape.cpp
  src/ngraph/runtime/cpu/builder/reverse_sequence.cpp
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/builder/tile.cpp
  src/ngraph/runtime/cpu/builder/update_slice.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/kernel/replace_slice.hpp
  src/ngraph/runtime/cpu/kernel/scatter_add.hpp
  src/ngraph/runtime/cpu/kernel/slice.hpp
  src/ngraph/runtime/cpu/kernel/softmax.hpp
  src/ngraph/runtime/cpu/kernel_selectors.hpp
Labels: Fully Reviewed, IntelCPU

#3644 Provenance for builders
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/make_constant.hpp
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/numpy_transpose.cpp
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_matmul.cpp
  src/ngraph/builder/quantization_utils.cpp
  src/ngraph/builder/quantized_conv_builder.cpp
  src/ngraph/builder/reduce_ops.cpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/split.cpp
  src/ngraph/builder/tensor_mask.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/pass/fused_op_decomposition.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#3557 [ONNX] Added support for negative axes.
  src/ngraph/frontend/onnx_import/op/concat.cpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/gather.hpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/frontend/onnx_import/op/mean_variance_normalization.cpp
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/op/reverse_sequence.cpp
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
Labels: Fully Reviewed

#3649 OSX SDK links changed
  CMakeLists.txt
Labels: High Priority

#3651 OSX SDK links changed
  CMakeLists.txt
Labels: High Priority

#3650 OSX SDK links changed
  CMakeLists.txt
Labels: High Priority

#3655 Cyphers/25convprov
  src/ngraph/node.cpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
Labels: Fully Reviewed, High Priority

#3598 Simple bf16 test case for CPU backend
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  test/backend/pool.in.cpp
  test/cpu_test.cpp
  test/util/float_util.cpp
  test/util/float_util.hpp
Labels: Fully Reviewed, IntelCPU

#3652 Allow building nGraph CPU without TBB - r0.25.1
  CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_executor.cpp
  src/ngraph/runtime/cpu/cpu_executor.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
  test/CMakeLists.txt
Labels: Fully Reviewed, High Priority

#3646 Provenance for builders 0.26 edition
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/dequantize_builder.cpp
  src/ngraph/builder/make_constant.hpp
  src/ngraph/builder/matmul_factory.cpp
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/numpy_transpose.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization_utils.cpp
  src/ngraph/builder/quantize_builder.cpp
  src/ngraph/builder/quantized_concat_builder.cpp
  src/ngraph/builder/quantized_conv_builder.cpp
  src/ngraph/builder/quantized_dot_builder.cpp
  src/ngraph/builder/reduce_ops.cpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/split.cpp
  src/ngraph/builder/tensor_mask.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/pass/fused_op_decomposition.cpp
  test/provenance.cpp
Labels: Fully Reviewed, High Priority

#3641 Update MKLDNN to v0.21
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed

#3625 [MLIR] Add `ngraph` prefix to MLIR flags
  src/contrib/mlir/compiler/compiler.cpp
Labels: Fully Reviewed

#3654 [MLIR] Add support for parsing nGraph tensor type
  src/contrib/mlir/compiler/dialect/dialect.cpp
  src/contrib/mlir/compiler/dialect/dialect.hpp
Labels: Fully Reviewed

#2160 Allow CPU build without TBB.
  CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_executor.cpp
  src/ngraph/runtime/cpu/cpu_executor.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
  test/CMakeLists.txt
Labels: Fully Reviewed, IntelCPU

#3640 Cyphers/lastwarns
  CMakeLists.txt
  cmake/clang_4_0_flags.cmake
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
  src/ngraph/check.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/node.hpp
  test/check.cpp
  test/type_prop/dyn_replace_slice.cpp
  test/type_prop/dyn_slice.cpp
  test/type_prop/range.cpp
  test/util/type_prop.hpp
Labels: High Priority

#3664 Fix NGRAPH_DOC_BUILD_ENABLE flag
  CMakeLists.txt
  doc/CMakeLists.txt
Labels: Fully Reviewed

#3645 Add PDPD style autobroadcast
  src/ngraph/CMakeLists.txt
  src/ngraph/node.cpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/op/util/broadcasting.cpp
  src/ngraph/op/util/broadcasting.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/pass/implicit_broadcast_elimination.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/autobroadcast_binop.hpp
  src/ngraph/serializer.cpp
  test/backend/auto_broadcast.in.cpp
Labels: Fully Reviewed

#3591 [Spec] Add v1::AvgPool and v1::MaxPool
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/opset_pass/poolings_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3662 New DynSlice (Strided Slice) realization
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/backend/dyn_replace_slice_reference.in.cpp
  test/ref_generators/generate_dyn_replace_slice_ref.py
  test/type_prop/dyn_replace_slice.cpp
  test/type_prop/dyn_slice.cpp
Labels: Fully Reviewed

#3666 [MLIR] Minor improvement to elementwise LIT test
  test/mlir/ngraph_dialect/elementwise_binary_ops.mlir
Labels: Fully Reviewed

#3674 [MLIR] Change LIT execution dir to build dir
  test/mlir/lit.cfg.py
  test/mlir/lit.site.cfg.py.in
Labels: Fully Reviewed

#3677 Fixed Cmake to build nGraph using MSVC 2019 compiler
  CMakeLists.txt
Labels: Fully Reviewed, High Priority

#3597 Theme updates for nGraph theme in Sphinx
  doc/sphinx/ngraph.doxyfile
  doc/sphinx/ngraph_theme/footer.html
  doc/sphinx/ngraph_theme/layout.html
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/ngraph_theme/static/fonts/NanumGothicCoding-Bold.ttf
  doc/sphinx/ngraph_theme/static/fonts/NanumGothicCoding-Regular.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel-Bold.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel-Italic.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel-Light.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel-LightItalic.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel-Medium.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel-MediumItalic.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel-Regular.ttf
  doc/sphinx/ngraph_theme/static/fonts/NeoSansIntel.ttf
  doc/sphinx/ngraph_theme/static/slack.png
  doc/sphinx/ngraph_theme/static/theme.css
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/frameworks/getting_started.rst
  doc/sphinx/source/graphics/nGraph_mask_1-1.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/pad.rst
  doc/sphinx/source/ops/product.rst
  doc/sphinx/source/ops/softmax.rst
  doc/sphinx/source/project/contribution-guide.rst
  doc/sphinx/source/project/extras/homomorphic_encryption.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/python_api/_autosummary/ngraph.rst
Labels: Fully Reviewed

#3653 Smaller set of constant folding kernels
  src/ngraph/pass/constant_folding_binary.cpp
Labels: Fully Reviewed

#3665 [MLIR] Add support for parsing nGraph element types
  src/contrib/mlir/compiler/dialect/dialect.cpp
  src/contrib/mlir/compiler/lowerer.cpp
  test/mlir/affine_conversion/types.mlir
  test/mlir/ngraph_dialect/types.mlir
Labels: Fully Reviewed

#3671 Change ownership of MLIR LIT tests directory
  CODEOWNERS
Labels: Fully Reviewed

#3678 LayerNorm
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/layer_norm.cpp
  src/ngraph/op/fused/layer_norm.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/layer_norm.in.cpp
  test/type_prop/layer_norm.cpp
Labels: Fully Reviewed

#3536 [Spec] Implementation of Reverse:v1
  src/ngraph/op/reverse.cpp
  src/ngraph/op/reverse.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/reverse.in.cpp
  test/opset_pass/reverse_opset_pass.cpp
  test/serialize.cpp
Labels: Fully Reviewed, SPEC

#3636 [SPEC] Add v1:Convolution operator
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/opset_pass/convolution_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3633 [Spec] Implement Reshape:v1
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_reshape.hpp
  src/ngraph/op/reshape.cpp
  src/ngraph/op/reshape.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/serializer.cpp
  test/opset_pass/dyn_reshape_opset_pass.cpp
  test/type_prop/dyn_reshape.cpp
Labels: Fully Reviewed, SPEC

#3667 [MLIR] Improve gather op lowering
  src/contrib/mlir/compiler/lowerer.cpp
  test/mlir/affine_conversion/core_ops.mlir
  test/mlir/ngraph_dialect/types.mlir
Labels: Fully Reviewed

#3672 Refactor, cleanup type info to make it safer to use for non-ops
  src/ngraph/node.hpp
  src/ngraph/type.hpp
Labels: Fully Reviewed
