Repository NervanaSystems/ngraph, pull requests merged in 2019-12, with the labels that each got.

#3945 v1::Reshape zero_flag renamed. Default value unset
  src/ngraph/op/reshape.cpp
  src/ngraph/op/reshape.hpp
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/serializer.cpp
  test/backend/dyn_reshape.in.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3940 Add groupconvolution bprop
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/group_convolution.in.cpp
Labels: Fully Reviewed, SPEC

#3962 Pass CMAKE_BUILD_TYPE to external gtest project
  cmake/external_gtest.cmake
  test/util/CMakeLists.txt
Labels: Fully Reviewed, High Priority

#3952 Relax check on LRN for rank requirement to be >=3
  src/ngraph/op/lrn.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/lrn.in.cpp
  test/type_prop/lrn.cpp
Labels: Fully Reviewed

#3874 [SPEC] ReduceLogicalAnd & ReduceLogicalOr
  src/ngraph/CMakeLists.txt
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/reduce_logical_and.cpp
  src/ngraph/op/reduce_logical_and.hpp
  src/ngraph/op/reduce_logical_or.cpp
  src/ngraph/op/reduce_logical_or.hpp
  src/ngraph/op/util/logical_reduction_keep_dims.cpp
  src/ngraph/op/util/logical_reduction_keep_dims.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/pass/constant_folding_logical_reduction.cpp
  src/ngraph/serializer.cpp
  test/constant_folding.cpp
  test/opset1.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3943 [SPEC] Adjust Split
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/build_graph.cpp
  test/type_prop/split.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3954 [SPEC] Add DeformablePSROIPooling v1
  src/ngraph/CMakeLists.txt
  src/ngraph/op/deformable_psroi_pooling.cpp
  src/ngraph/op/deformable_psroi_pooling.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/opset1.cpp
  test/serialize.cpp
  test/type_prop/deformable_psroi_pooling.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3957 Add v1 version of Subtract with Numpy broadcasting as default
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/subtract.cpp
  src/ngraph/op/subtract.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/serializer.cpp
  test/opset1.cpp
  test/opset_pass/binary_elementwise_opset_pass.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3961 [SPEC] Add constant folding for LogicalNot:v1
  src/ngraph/pass/constant_folding_unary.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3959 Update the tolerance on auto_broadcast_test
  test/backend/auto_broadcast.in.cpp
Labels: Fully Reviewed

#3969 Copy RT info for parameters
  src/ngraph/specialize_function.cpp
Labels: Fully Reviewed

#3967 [SPEC] Add GatherTree:v1
  src/ngraph/CMakeLists.txt
  src/ngraph/op/gather_tree.cpp
  src/ngraph/op/gather_tree.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/type_prop/gather_tree.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3975 [SPEC] Support negative axis and negative split specification in v1::VariadicSplit
  src/ngraph/op/variadic_split.cpp
  src/ngraph/validation_util.cpp
  test/CMakeLists.txt
  test/opset1.cpp
  test/type_prop/variadic_split.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3983 [SPEC] Change expected shape of end_token input for GatherTree
  src/ngraph/op/gather_tree.cpp
  test/type_prop/gather_tree.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3964 [SPEC] DeformableConvolution
  src/ngraph/CMakeLists.txt
  src/ngraph/op/deformable_convolution.cpp
  src/ngraph/op/deformable_convolution.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/serializer.cpp
  test/type_prop/convolution.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3976 Fixed Selu op decomposition
  src/ngraph/op/fused/selu.cpp
Labels: Bug, Fully Reviewed, High Priority, SPEC

#3977 Merge cumulative sum to r0.25.1 for Waymo
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/cum_sum.cpp
  src/ngraph/op/cum_sum.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/cum_sum.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/cum_sum.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/cum_sum.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/cum_sum.in.cpp
Labels: Fully Reviewed, IntelCPU

#3984 Convert slope to data type
  src/ngraph/op/fused/mod.cpp
  src/ngraph/op/fused/prelu.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3971 Enable multitple int types for OneHot 'depth' param
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/one_hot.hpp
Labels: Fully Reviewed, High Priority, SPEC

#3970 CMAKE: usage relative paths, added ngraph component
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
Labels: Fully Reviewed

#3956 [SPEC] Add new v1::GroupConvolution and v1::GroupConvolutionBackpropData operators.
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/serializer.cpp
  test/opset1.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3968 [SPEC] NonMaxSuppression
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/non_max_suppression.cpp
  src/ngraph/frontend/onnx_import/op/non_max_suppression.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/non_max_suppression.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/type_prop/non_max_suppression.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3985 Fix some opset bugs
  src/ngraph/opsets/opset.cpp
  src/ngraph/opsets/opset1.hpp
Labels: Fully Reviewed

#3931 Added reproducer for specialize_function
  src/ngraph/pass/get_output_element_elimination.cpp
  src/ngraph/pass/get_output_element_elimination.hpp
  src/ngraph/specialize_function.cpp
  test/specialize_function.cpp
Labels: Bug, Fully Reviewed

#3986 Fix random segfault when LRN cpu fallback to reference kernel
  src/ngraph/runtime/cpu/builder/lrn.cpp
Labels: Bug, Fully Reviewed

#3987 Add Fluid test.
  src/ngraph/frontend/CMakeLists.txt
  src/ngraph/frontend/fluid/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/test/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/test/main.cpp
  src/ngraph/frontend/fluid/operators/test/reduce_sum.cpp
  src/ngraph/frontend/fluid/operators/test/test.manifest
Labels: Fluid, Fully Reviewed

#3982 Add fluid pool op with support of global pooling and adaptive mode
  src/ngraph/frontend/fluid/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/pool.cpp
  src/ngraph/frontend/fluid/operators/pool.hpp
Labels: Fluid, Fully Reviewed, Merge Blocked

#3992 Fixed group convolution infer function
  src/ngraph/op/fused/group_conv.cpp
Labels: Fully Reviewed

#3991 Runtime-extensible opsets
  src/ngraph/factory.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/greater_eq.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/opsets/opset.cpp
  src/ngraph/opsets/opset.hpp
  src/ngraph/pass/like_replacement.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/opset1.cpp
Labels: Fully Reviewed, High Priority

#3996 Revert "Added reproducer for specialize_function"
  src/ngraph/pass/get_output_element_elimination.cpp
  src/ngraph/pass/get_output_element_elimination.hpp
  src/ngraph/specialize_function.cpp
  test/specialize_function.cpp
Labels: Bug, Fully Reviewed, High Priority

#3974 [SPEC] Select op with implicit broadcast
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/select.cpp
  src/ngraph/op/select.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/pass/constant_folding_select.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/reference/autobroadcast_binop.hpp
  src/ngraph/runtime/reference/select.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/select.in.cpp
  test/constant_folding.cpp
  test/opset1.cpp
  test/opset_pass/select_opset_pass.cpp
  test/type_prop/select.cpp
Labels: Fully Reviewed, High Priority, Merge Blocked, SPEC

#3989 Don't imbue locale to cout, imbue a stringstream instead so that it d…
  src/tools/nbench/benchmark.cpp
  src/tools/nbench/benchmark_pipelined.cpp
Labels: Fully Reviewed

#3993 [SPEC] v1::Split + onnx_importer adaptation
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/node.cpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/opset1.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3947 Fix compose/decompose of group_conv for CPU backend.
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed

#4009 [MLIR] Fix relative path in lit.site.cfg.py.in
  test/mlir/lit.site.cfg.py.in
Labels: Fully Reviewed

#4006 Add additional exports
  src/ngraph/attribute_visitor.hpp
  src/ngraph/node.hpp
Labels: Fully Reviewed, High Priority

#4008 Removed defunct flag
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#3950 [MLIR] Update MLIR/LLVM repos
  cmake/external_mlir.cmake
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ngraph_dialect/ops.hpp
  src/contrib/mlir/core/ngraph_dialect/ops.td
  src/contrib/mlir/core/ngraph_dialect/ops_v0.td
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.hpp
  test/mlir/ngraph_dialect/fused_ops.mlir
  test/mlir/ops_test.cpp
Labels: Fully Reviewed

#4002 Replace static functions with anonymous namespaces
  src/ngraph/frontend/onnx_import/op/slice.cpp
  src/ngraph/frontend/onnx_import/op/topk.cpp
Labels: Fully Reviewed, ONNX

#3997 [SPEC] Make offset input of DeformablePSROIPooling optional
  src/ngraph/op/deformable_psroi_pooling.cpp
  src/ngraph/op/deformable_psroi_pooling.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, High Priority, SPEC

#4001 [SPEC] Calculate output shape for NonMaxSuppression
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/non_max_suppression.hpp
  test/type_prop/non_max_suppression.cpp
Labels: Fully Reviewed, High Priority, SPEC

#4005 [SPEC] Fix output_shape input in (Group)ConvolutionBackpropData ops
  src/ngraph/op/convolution.cpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  test/backend/convolution.in.cpp
  test/opset_pass/convolution_opset_pass.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3999 Add UT to reproduce issue from PR3931
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/batch_norm.in.cpp
Labels: Bug, Fully Reviewed, High Priority

#4007 Fixed gather testing
  test/backend/gather.in.cpp
Labels: Fully Reviewed

#3963 [ONNX] Add GatherND op to ONNX importer
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/gather_nd.cpp
  src/ngraph/frontend/onnx_import/op/gather_nd.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/models/onnx/gatherND_float.prototxt
  test/models/onnx/gatherND_int32.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#4019 Fix serialization of op's type
  src/ngraph/serializer.cpp
Labels: Bug, Fully Reviewed

#4021 Fix serialization of op's type (#4019)
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4024 Update jenkins-trigger.groovy
  .ci/jenkins/jenkins-trigger.groovy
Labels: Fully Reviewed

#4030 Update jenkins-trigger.groovy
  .ci/jenkins/jenkins-trigger.groovy
Labels: Fully Reviewed

#4031 Fix layer_norm flatten issue
  src/ngraph/op/fused/layer_norm.cpp
  src/ngraph/op/fused/layer_norm.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/layer_norm.in.cpp
Labels: Fully Reviewed, High Priority

#3990 [MKLDNN] Emit dgemm for 2D DP FP Dot op
  src/ngraph/runtime/cpu/builder/matmul_bias.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#4000 Helper in Constant to allow casting values to a different type
  src/ngraph/op/constant.hpp
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/one_hot.hpp
Labels: Fully Reviewed

#4038 TensorIterator: reshape support
  src/ngraph/op/tensor_iterator.cpp
  src/ngraph/specialize_function.cpp
Labels: Fully Reviewed, High Priority

#4036 Add second decompose pass to INTERPRETER backend
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/unit_test.manifest
Labels: Fully Reviewed

#3951 Update MKLDNN to v1.0.4.
  CMakeLists.txt
  cmake/external_mkldnn_v1.cmake
  cmake/mkldnn_v1.patch
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#4014 Tested doc build for 0.27 with sitemap for ngraph.ai endpoint
  doc/sphinx/ngraph_theme/layout_old.html
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/core/passes/passes.rst
  doc/sphinx/source/frameworks/overview.rst
  doc/sphinx/source/graphics/mobilenet-group-conv.svg
  doc/sphinx/source/inspection/index.rst
  doc/sphinx/source/sitemap.rst
  doc/sphinx/source/training/index.rst
  doc/sphinx/source/training/overview.rst
Labels: Fully Reviewed

#4023 Matmul dyshape_fused_forward_fluid
  src/ngraph/frontend/fluid/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/matmul.cpp
  src/ngraph/frontend/fluid/operators/matmul.hpp
Labels: Fully Reviewed

#4044 use constructor_validate_and_infer_types() in CumSum ctor
  src/ngraph/op/cum_sum.cpp
  src/ngraph/op/cum_sum.hpp
Labels: Fully Reviewed, High Priority

#4042 Fix tolerance for all_close_f
  test/backend/layer_norm.in.cpp
Labels: Fully Reviewed, High Priority

#4037 Use v1::Gather in ONNX Importer
  src/ngraph/frontend/onnx_import/op/gather.hpp
  src/ngraph/pass/opset0_downgrade.cpp
Labels: Fully Reviewed, High Priority, ONNX

#4035 Add upgrade and downgrade pass for GroupConvolutionBackpropData ops
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  test/opset_pass/convolution_opset_pass.cpp
Labels: Fully Reviewed

#4045 Fixed constant operation for u1 format
  src/ngraph/op/constant.hpp
  src/ngraph/op/reduce_logical_and.hpp
  src/ngraph/op/reduce_logical_or.hpp
  src/ngraph/opsets/opset.hpp
  src/ngraph/specialize_function.hpp
  test/convert_u1_to_string.cpp
Labels: Fully Reviewed, High Priority

#4050 Fix broken serialize and deserialize for Sum and Product
  src/ngraph/serializer.cpp
Labels: Bug

#4046 v1::Reshape downgrade pass + onnx_importer adjustments
  src/ngraph/frontend/onnx_import/op/reshape.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  test/models/onnx/reshape_negative_dim.prototxt
  test/onnx/onnx_import_reshape.in.cpp
Labels: Fully Reviewed

#4061 Add fluid layout converter
  src/ngraph/frontend/fluid/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/layout_converter.cpp
  src/ngraph/frontend/fluid/operators/layout_converter.hpp
Labels: Fluid, Fully Reviewed, High Priority

#4057 Fix LRN for dynshape
  src/ngraph/op/lrn.cpp
Labels: Dynamic Shape

#4033 Check for partial tensor read/write
  src/ngraph/runtime/host_tensor.cpp
Labels: Fully Reviewed

#4022 [SPEC] Remove unused code from Split:v0
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
Labels: Fully Reviewed, High Priority, SPEC

#4003 [SPEC] Add ND input data support for DepthToSpace and SpaceToDepth
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/space_to_depth.cpp
  test/backend/fused_op.in.cpp
  test/type_prop/depth_to_space.cpp
  test/type_prop/space_to_depth.cpp
Labels: Fully Reviewed, High Priority, SPEC

#4049 [MLIR]Add clang flag and skip bf16 tests for MLIR.
  cmake/external_llvm.cmake
  test/cpu_test.cpp
Labels: Fully Reviewed

#4065 Add new flags to disable mkldnn test and example build
  cmake/external_mkldnn.cmake
  cmake/external_mkldnn_v1.cmake
Labels: Fully Reviewed

#4071 Set output element type for case of dynamic input
  src/ngraph/op/fused/partial_slice.cpp
  src/ngraph/op/fused/softmax_crossentropy.cpp
  src/ngraph/op/fused/softmax_crossentropy.hpp
Labels: Dynamic Shape, Fully Reviewed

#4072 Set output type for matmul
  src/ngraph/frontend/fluid/operators/matmul.cpp
  src/ngraph/frontend/fluid/operators/matmul.hpp
Labels: Dynamic Shape, Fluid, Fully Reviewed

#4041 [SPEC] Add constant folding for Split:v1 and VariadicSplit:v1
  src/ngraph/CMakeLists.txt
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/op/variadic_split.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_split.cpp
  src/ngraph/pass/constant_folding_variadic_split.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, High Priority, SPEC

#4070 [ TI ] TensorIterator m_num_iterations fix
  src/ngraph/op/tensor_iterator.cpp
  src/ngraph/op/tensor_iterator.hpp
Labels: Fully Reviewed, High Priority

#4011 [MLIR] Update MLIR/LLVM repos
  cmake/external_mlir.cmake
Labels: Fully Reviewed

#4010 [MLIR] Improve lit test config files and tools
  CMakeLists.txt
  src/contrib/mlir/tools/ngraph-opt/CMakeLists.txt
  test/mlir/lit.cfg.py
  test/mlir/lit.site.cfg.py.in
Labels: Fully Reviewed

#4018 Add ScatterND FusedOp
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/scatter_nd.cpp
  src/ngraph/frontend/onnx_import/op/scatter_nd.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/fused/scatter_nd.cpp
  src/ngraph/op/fused/scatter_nd.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/runtime/cpu/builder/scatter_nd_add.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/models/onnx/scatter_nd.prototxt
  test/onnx/onnx_import.in.cpp
  test/type_prop/scatter_nd.cpp
Labels: Fully Reviewed

#4043 Some type info cleanups/improvements
  src/ngraph/CMakeLists.txt
  src/ngraph/factory.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/pass/manager_state.hpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/visualize_tree.hpp
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
  src/ngraph/type.cpp
  src/ngraph/type.hpp
  src/ngraph/util.hpp
Labels: Fully Reviewed

#3965 Add stack fused op for pdpd use
  src/ngraph/CMakeLists.txt
  src/ngraph/op/fused/stack.cpp
  src/ngraph/op/fused/stack.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
Labels: Fully Reviewed

#4077 Fix type mismatch in softmax_with_xe
  src/ngraph/op/fused/softmax_crossentropy.cpp
Labels: Fully Reviewed

#4080 Resolve shape prop issue
  src/ngraph/frontend/fluid/operators/layout_converter.cpp
  src/ngraph/frontend/fluid/operators/layout_converter.hpp
  src/ngraph/frontend/fluid/operators/pool.cpp
  src/ngraph/frontend/fluid/operators/pool.hpp
  src/ngraph/frontend/fluid/operators/reduce_sum.cpp
  src/ngraph/frontend/fluid/operators/reduce_sum.hpp
Labels: Dynamic Shape, Fluid, Fully Reviewed

#4081 Support negative reduction axes in shape inference for reduction ops
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/op/util/logical_reduction_keep_dims.cpp
  test/type_prop/sum.cpp
Labels: Fully Reviewed, High Priority

#4047 Fallback to reference kernel for failing tests
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed

#4017 [MLIR] Use prebuilt MLIR when specified with -DNGRAPH_USE_PREBUILT_MLIR
  CMakeLists.txt
  cmake/external_mlir.cmake
Labels: Fully Reviewed

#4087 [SPEC] Add constant folding for OneHot:v1
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_one_hot.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/runtime/reference/one_hot.hpp
  test/constant_folding.cpp
  test/opset_pass/one_hot_opset_pass.cpp
Labels: Fully Reviewed, High Priority, SPEC

#4086 [MLIR]Use MLIR_DISABLE_TEST to disable bf16 tests.
  test/cpu_test.cpp
Labels: Fully Reviewed

#4091 Add fluid matmul grad op
  src/ngraph/frontend/fluid/operators/matmul.cpp
  src/ngraph/frontend/fluid/operators/matmul.hpp
Labels: Fluid, Fully Reviewed

#4074 - emit mlkddn for LRN only for normalizing acorss/within channel
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
Labels: Fully Reviewed

#4094 Set multiple outputs for matmul
  src/ngraph/frontend/fluid/operators/matmul.cpp
Labels: Bug, Fluid, Fully Reviewed

#4099 Update fluid matmul fprop
  src/ngraph/frontend/fluid/operators/matmul.cpp
Labels: Fluid, Fully Reviewed

#4066 ConstantFolding optimization
  src/ngraph/op/constant.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/pass/constant_folding_broadcast.cpp
  src/ngraph/pass/constant_folding_concat.cpp
  src/ngraph/pass/constant_folding_convert.cpp
  src/ngraph/pass/constant_folding_dequantize.cpp
  src/ngraph/pass/constant_folding_dyn_broadcast.cpp
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  src/ngraph/pass/constant_folding_dyn_slice.cpp
  src/ngraph/pass/constant_folding_gather.cpp
  src/ngraph/pass/constant_folding_logical_reduction.cpp
  src/ngraph/pass/constant_folding_pad.cpp
  src/ngraph/pass/constant_folding_quantize.cpp
  src/ngraph/pass/constant_folding_range.cpp
  src/ngraph/pass/constant_folding_reshape.cpp
  src/ngraph/pass/constant_folding_reverse.cpp
  src/ngraph/pass/constant_folding_select.cpp
  src/ngraph/pass/constant_folding_slice.cpp
  src/ngraph/pass/constant_folding_squeeze.cpp
  src/ngraph/pass/constant_folding_strided_slice.cpp
  src/ngraph/pass/constant_folding_transpose.cpp
  src/ngraph/pass/constant_folding_unary.cpp
  src/ngraph/pass/constant_folding_unsqueeze.cpp
  src/ngraph/pass/constant_to_broadcast.cpp
  src/ngraph/runtime/aligned_buffer.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4078 [MLIR] Update MLIR/LLVM repo
  cmake/external_mlir.cmake
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
Labels: Fully Reviewed
