Repository NervanaSystems/ngraph, pull requests merged in 2019-02, with the labels that each got.

#2350 [ONNX] Enable deselected supported opset domain when needed.
  src/ngraph/frontend/onnx_import/core/attribute.cpp
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.cpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.hpp
  test/models/onnx/missing_op_domain.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, High Priority, ONNX

#2384 Adding serializer support for experimental quant ops
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#2381 Pruthvi/fix input matrix fusion
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  test/cpu_fusion.cpp
  test/models/mxnet/gru_debug.json
Labels: Fully Reviewed

#2391 The General Purpose graph splitting is no longer used
  src/ngraph/CMakeLists.txt
  src/ngraph/graph_util.cpp
  src/ngraph/pass/assign_placement.cpp
  src/ngraph/pass/assign_placement.hpp
  src/ngraph/placement.cpp
  src/ngraph/placement.hpp
  src/ngraph/runtime/gpuh/gpuh_backend.cpp
  test/CMakeLists.txt
  test/graph_partition.cpp
Labels: Fully Reviewed

#2382 [Py] Revert Anaconda workaround
  python/setup.py
Labels: Fully Reviewed

#2395 Fix Klocwork issues
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/hybrid/hybrid_backend.cpp
  src/ngraph/type/element_type.hpp
  test/all_close_f.cpp
Labels: Fully Reviewed

#2404 IntelGPU backend: Visual output for many inputs fixed
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Bug, IntelGPU

#2403 IntelGPU backend: Floor operation fixed
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  test/backend_unary_elementwise.in.cpp
Labels: Bug, IntelGPU

#2357 IntelGPU backend: Min and Max operations fix
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Bug, Comments Addressed, Fully Reviewed, IntelGPU

#2402 [ONNX] Add hyperbolic functions support
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/cosh.hpp
  src/ngraph/frontend/onnx_import/op/sinh.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.hpp
  test/models/onnx/cosh.onnx
  test/models/onnx/sinh.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2405 Simplify the access of placement in Function
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/runtime/hybrid/CMakeLists.txt
  src/ngraph/runtime/hybrid/hybrid_backend.cpp
  src/ngraph/runtime/hybrid/hybrid_util.cpp
  src/ngraph/runtime/hybrid/hybrid_util.hpp
  src/ngraph/runtime/hybrid/pass/default_placement.cpp
  src/ngraph/runtime/hybrid/pass/default_placement.hpp
  test/hybrid_backend.cpp
Labels: Fully Reviewed

#2349 Fix for Qconv sum inplace
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU

#2407 IntelGPU backend: backend library version usage fixed
  src/ngraph/runtime/intelgpu/CMakeLists.txt
Labels: Bug, Fully Reviewed, IntelGPU

#2410 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#2409 Fix memory leak
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
Labels: Fully Reviewed

#2413 IntelGPU backend: ArgMax operation fix
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Bug, IntelGPU

#2415 Fix cmake TBB lib path on Windows.
  cmake/external_tbb_prebuilt.cmake
Labels: Fully Reviewed

#2406 [ONNX] Support for initializers without corresponding inputs
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  test/models/onnx/add_abc_initializers.onnx
  test/models/onnx/custom_operator.onnx
  test/models/onnx/custom_operator_default_domain.onnx
  test/models/onnx/initializer_wo_input.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2414 IntelGPU backend: Slice operation datatypes fix
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  test/backend_test.in.cpp
Labels: Bug, Fully Reviewed, IntelGPU

#2411 Clean up cmake project options
  CMakeLists.txt
Labels: Fully Reviewed

#2401 Mixed-precision fusions
  src/ngraph/builder/quantization.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#2418 Unify mkl-dnn patch.
  cmake/external_mkldnn.cmake
  cmake/mkldnn.patch
  cmake/mkldnn_no_so_link.patch
Labels: Fully Reviewed

#2419 Replace halide patch with cmake options.
  cmake/external_halide.cmake
  cmake/halide.patch
Labels: Fully Reviewed

#2400 Add ngraph plaidml extra dep
  python/setup.py
Labels: Fully Reviewed, PlaidML

#2386 [ONNX] Add null node.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/null_node.cpp
  src/ngraph/frontend/onnx_import/core/null_node.hpp
  src/ngraph/node.hpp
  test/models/onnx/missing_input.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2412 [ONNX] Sign operator support
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/sign.hpp
  src/ngraph/frontend/onnx_import/op/supported_ops.md
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/sign.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2422 IntelGPU backend: Kahan summation algorithm in Sum operation implemented
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Bug, Fully Reviewed, IntelGPU

#2425 Add doc for new backend api
  doc/sphinx/source/backend-support/cpp-api.rst
  doc/sphinx/source/backend-support/index.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/graphics/algebraic-simpl.png
  doc/sphinx/source/graphics/core-fusion.png
  doc/sphinx/source/graphics/passes-to-graph-rewrite.png
  doc/sphinx/source/graphics/recurrent-graph-rewrite.png
  doc/sphinx/source/graphics/runtime-exec.png
Labels: Documentation, Fully Reviewed

#2429 Install tbb
  cmake/external_tbb_prebuilt.cmake
Labels: Fully Reviewed

#2431 Initialize member for klocwork
  src/ngraph/function.hpp
Labels: Release

#2417 Leona/doc distr
  doc/sphinx/source/conf.py
  doc/sphinx/source/howto/distribute-train.rst
  doc/sphinx/source/project/doc-contributor-README.rst
Labels: Fully Reviewed

#2420 Silee2/subdirectories
  CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/resource/CMakeLists.txt
Labels: Fully Reviewed

#2424 cleanup from new backend api
  src/ngraph/runtime/interpreter/CMakeLists.txt
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/backend_debug_api.cpp
Labels: Fully Reviewed

#2430 Cyphers/tbb2
  cmake/external_tbb_prebuilt.cmake
Labels: Fully Reviewed

#2432 address build issues on CentOS for distributed
  test/backend_binary_elementwise.in.cpp
  test/main.cpp
Labels: Fully Reviewed, distributed

#2433 IntelGPU backend: Reshape operation 5D support implemented
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_reshape.in.cpp
Labels: Fully Reviewed, IntelGPU

#2399 Improve PlaidML concat perf
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_concat_split.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_concat_split.hpp
Labels: Fully Reviewed, PlaidML

#2435 IntelGPU backend: Double datatype workaround implemented
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#2439 Update Generic CPU backend to new Backend API
  src/ngraph/runtime/generic_cpu/CMakeLists.txt
  src/ngraph/runtime/generic_cpu/gcpu_backend.cpp
  src/ngraph/runtime/generic_cpu/gcpu_backend.hpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/generic_cpu/kernel/broadcast.hpp
Labels: Fully Reviewed

#2440 Cyphers/kloc1
  src/ngraph/function.hpp
Labels: Fully Reviewed

#2437 IntelGPU backend: Several multitype tests enabled
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#2445 Update PlaidML backend to current API
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_backend.cpp
  src/ngraph/runtime/plaidml/plaidml_backend.hpp
  src/ngraph/runtime/plaidml/plaidml_compilation_cache.cpp
  src/ngraph/runtime/plaidml/plaidml_compilation_cache.hpp
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_compiler.hpp
  src/ngraph/runtime/plaidml/plaidml_executable.cpp
  src/ngraph/runtime/plaidml/plaidml_executable.hpp
  src/tools/ngraph-to-plaidml/ngraph-to-plaidml.cpp
Labels: Fully Reviewed, PlaidML

#2443 adding quantized convolution builders for ONNX
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
Labels: Fully Reviewed

#2447 IntelGPU backend: Separate backend and executable classes
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
  src/ngraph/runtime/intelgpu/intelgpu_executable.cpp
  src/ngraph/runtime/intelgpu/intelgpu_executable.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
Labels: Fully Reviewed, IntelGPU

#2453 Leona/fix dstraining
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/howto/distribute-train.rst
Labels: Documentation, Fully Reviewed, High Priority

#2446 Inplace convert for bitcasting ops
  src/ngraph/runtime/cpu/builder/convert.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2436 [ONNX] Inverse hyperbolic trigonometric functions.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/acosh.cpp
  src/ngraph/frontend/onnx_import/op/acosh.hpp
  src/ngraph/frontend/onnx_import/op/asinh.cpp
  src/ngraph/frontend/onnx_import/op/asinh.hpp
  src/ngraph/frontend/onnx_import/op/atanh.cpp
  src/ngraph/frontend/onnx_import/op/atanh.hpp
  src/ngraph/frontend/onnx_import/op/supported_ops.md
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#2444 update examples to new backend API
  doc/examples/abc/abc.cpp
  doc/examples/abc_operator/abc_operator.cpp
  doc/examples/mnist_mlp/dist_mnist_mlp.cpp
  doc/examples/mnist_mlp/mnist_mlp.cpp
Labels: Fully Reviewed

#2452 Cleaner API doc reference for compile call
  doc/sphinx/ngraph.doxyfile
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/frameworks/validated/testing-latency.rst
  doc/sphinx/source/graphics/a-common-stack.png
  doc/sphinx/source/graphics/a-common-stack.xcf
  doc/sphinx/source/graphics/components-dl-stack.png
  doc/sphinx/source/graphics/components-dl-stack.xcf
  doc/sphinx/source/graphics/develop-without-lockin.png
  doc/sphinx/source/graphics/develop-without-lockin.xcf
  doc/sphinx/source/graphics/ngraph-compiler-stack-readme.png
  doc/sphinx/source/graphics/ngraph-compiler-stack-readme.xcf
  doc/sphinx/source/graphics/scalability-matters.png
  doc/sphinx/source/graphics/translation-flow-to-ng-fofx.xcf
  doc/sphinx/source/howto/derive-for-training.rst
  doc/sphinx/source/index.rst
Labels: Documentation, Fully Reviewed

#2454 Pass HostTensor all the way down
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
Labels: Fully Reviewed

#2455 Use uniform naming for external project prefixes
  cmake/external_halide.cmake
  cmake/external_llvm.cmake
  cmake/external_llvm_prebuilt.cmake
  cmake/external_mkldnn.cmake
  cmake/external_protobuf.cmake
  cmake/external_tbb.cmake
  cmake/external_tbb_prebuilt.cmake
  cmake/tbb_fetch.cmake.in
Labels: Fully Reviewed

#2457 onnx: Fix typo.
  cmake/external_onnx.cmake
Labels: Fully Reviewed

#2459 Ignore YouCompleteMe config file.
  .gitignore
Labels: Fully Reviewed

#2460 IntelGPU backend: Eltwise and unary operation all types support
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#2461 IntelGPU backend: Broadcast operation fix
  cmake/external_cldnn.cmake
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2458 Move TBB build out of CPU backend.
  cmake/external_tbb.cmake
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#2396 handle channelwise scale mask
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Fully Reviewed, IntelCPU

#2463 [ONNX] Update comments in supported ops status table.
  src/ngraph/frontend/onnx_import/op/supported_ops.md
Labels: Fully Reviewed, ONNX

#2462 IntelGPU backend: Convolution backprop filter operation fix
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2471 CMake: Read tbb library version on Linux.
  cmake/external_tbb.cmake
Labels: Fully Reviewed

#2450 Rename a few tensor view to tensor
  src/ngraph/node.hpp
  src/ngraph/op/all.hpp
  src/ngraph/op/any.hpp
  src/ngraph/op/max.hpp
  src/ngraph/op/min.hpp
  src/ngraph/op/parameter.hpp
  src/ngraph/op/product.hpp
  src/ngraph/op/replace_slice.hpp
  src/ngraph/op/reshape.hpp
  src/ngraph/op/reverse.hpp
  src/ngraph/op/slice.hpp
  src/ngraph/op/sum.hpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/op/update_slice.hpp
Labels: Fully Reviewed

#2467 Fix incorrect header resource.
  src/resource/CMakeLists.txt
  src/resource/main.cpp
Labels: Fully Reviewed

#2468 Improve codegen's header search path finding logic for various Linux …
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
  src/ngraph/codegen/compiler.hpp
Labels: Fully Reviewed

#2449 [ONNX] Where operator support
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/where.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.hpp
  test/models/onnx/where.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2464 [ONNX] ONNX operator status update.
  src/ngraph/frontend/onnx_import/op/supported_ops.md
Labels: Fully Reviewed, ONNX

#2448 [ONNX] Enable OneHot operation
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/op/onehot.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/one_hot_axis.onnx
  test/models/onnx/one_hot_no_axis.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2469 Use git shallow clone if CMake >= 3.6. Remove BUILD_BYPRODUCTS.
  CMakeLists.txt
  cmake/external_cldnn.cmake
  cmake/external_eigen.cmake
  cmake/external_gtest.cmake
  cmake/external_halide.cmake
  cmake/external_json.cmake
  cmake/external_llvm.cmake
  cmake/external_mkldnn.cmake
  cmake/external_mlsl.cmake
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
  cmake/tbb_fetch.cmake.in
  python/CMakeLists.txt
Labels: Fully Reviewed

#2470 Auto detect OSX_SYSROOT for macos >= 10.14
  CMakeLists.txt
Labels: Fully Reviewed

#2423 Utility function for reading binary file content.
  test/util/test_tools.hpp
Labels: Fully Reviewed

#2478 [ONNX] User friendly assert message when op is not supported
  src/ngraph/frontend/onnx_import/core/graph.cpp
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2475 [ONNX] Import functions input validation
  src/ngraph/frontend/onnx_import/onnx.cpp
  test/models/onnx/malformed.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2484 [ONNX] Update status of OneHot operator
  src/ngraph/frontend/onnx_import/op/supported_ops.md
Labels: Fully Reviewed, ONNX

#2465 IntelGPU backend: Quantize operations
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
Labels: Fully Reviewed, IntelGPU

#2488 Update external_cldnn.cmake
  cmake/external_cldnn.cmake
Labels: IntelGPU

#2477 [ONNX] Fix in overriding ops
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/override_op.onnx
  test/onnx_import.in.cpp
Labels: Bug, Fully Reviewed, ONNX

#2479 IntelGPU backend: Convolution support for double and code minor clean up
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.hpp
Labels: Bug, Fully Reviewed, IntelGPU

#2060 Add QuantizedConcat
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization_util.hpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/experimental/quantized_concat.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantized_concat.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed, IntelCPU

#2492 Don't use git shallow clone.
  CMakeLists.txt
  cmake/external_cldnn.cmake
  cmake/external_eigen.cmake
  cmake/external_gtest.cmake
  cmake/external_halide.cmake
  cmake/external_json.cmake
  cmake/external_llvm.cmake
  cmake/external_mkldnn.cmake
  cmake/external_mlsl.cmake
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
  cmake/tbb_fetch.cmake.in
  python/CMakeLists.txt
Labels: Fully Reviewed

#2494 Do not allow builder to access tensor_data map directly.
  src/ngraph/runtime/cpu/builder/argmax.cpp
  src/ngraph/runtime/cpu/builder/argmin.cpp
  src/ngraph/runtime/cpu/builder/embedding_lookup.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed, IntelCPU

#2434 [ONNX] Handle trimmed optional outputs.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/op/dropout.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#2466 Reorganize doc folders for core-related doc on fusion, graph rewrite, and compiler passes
  README.md
  doc/sphinx/source/backend-support/index.rst
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/core/constructing-graphs/derive-for-training.rst
  doc/sphinx/source/core/constructing-graphs/distribute-train.rst
  doc/sphinx/source/core/constructing-graphs/execute.rst
  doc/sphinx/source/core/constructing-graphs/import.rst
  doc/sphinx/source/core/constructing-graphs/index.rst
  doc/sphinx/source/core/constructing-graphs/operator.rst
  doc/sphinx/source/core/constructing-graphs/update.rst
  doc/sphinx/source/core/fusion/graph-rewrite.rst
  doc/sphinx/source/core/fusion/index.rst
  doc/sphinx/source/core/fusion/mg/cat.jpg
  doc/sphinx/source/core/fusion/mg/fusion_pattern.png
  doc/sphinx/source/core/fusion/mg/pr1_graph1.png
  doc/sphinx/source/core/fusion/mg/pr1_graph2.png
  doc/sphinx/source/core/fusion/mg/pr1_graph3.png
  doc/sphinx/source/core/fusion/mg/pr1_graph4.png
  doc/sphinx/source/core/fusion/mg/pr1_graph5.png
  doc/sphinx/source/core/fusion/mg/pr1_pattern.png
  doc/sphinx/source/core/fusion/mg/pr1_pattern2.png
  doc/sphinx/source/core/fusion/mg/pr2_graph1.png
  doc/sphinx/source/core/fusion/mg/pr2_graph2.png
  doc/sphinx/source/core/fusion/mg/pr2_graph3.png
  doc/sphinx/source/core/fusion/mg/pr2_pattern2.png
  doc/sphinx/source/core/fusion/mg/rp_graph1.png
  doc/sphinx/source/core/fusion/mg/rp_pattern.png
  doc/sphinx/source/core/fusion/overview.rst
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/core/passes/list-of-passes.rst
  doc/sphinx/source/core/passes/passes-that-use-matcher.rst
  doc/sphinx/source/core/passes/passes.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/fusion/index.rst
  doc/sphinx/source/graphics/nGraph-handles-complexity.png
  doc/sphinx/source/graphics/scalability-matters.xcf
  doc/sphinx/source/graphics/whole-stack.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/about.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/project/introduction.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/tutorials/index.rst
Labels: Comments Addressed, Documentation, Fully Reviewed

#2482 IntelGPU backend: Max and Avg pool fix
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Bug, Fully Reviewed, IntelGPU

#2232 Pruthvi/bi rnn
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/op/rnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.hpp
  test/cpu_fusion.cpp
  test/models/mxnet/lstm_bi_directional.json
Labels: Fully Reviewed

#2421 [Standalone] Introduce CPURuntimeContextCG for standalone codegen generation.
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
Labels: Fully Reviewed, IntelCPU

#2487 Windows: Support CPU DEX
  CMakeLists.txt
  cmake/external_mkldnn.cmake
  cmake/external_tbb.cmake
  cmake/external_tbb_prebuilt.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/generic_cpu/CMakeLists.txt
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpuh/CMakeLists.txt
  src/ngraph/runtime/hybrid/CMakeLists.txt
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/interpreter/CMakeLists.txt
  src/ngraph/runtime/nop/CMakeLists.txt
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/tools/nbench/CMakeLists.txt
  test/CMakeLists.txt
  test/backend_sum.in.cpp
  test/util/all_close.hpp
Labels: Fully Reviewed

#2474 Update of MLSL git tag
  cmake/external_mlsl.cmake
Labels: Fully Reviewed, High Priority, distributed

#2489 [Py] Change author name in Python package
  python/setup.py
Labels: Fully Reviewed, High Priority

#2497 [ONNX] Fix the global alias shadowing warning
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2493 use friendly name for serialization and DOT files
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, High Priority

#2408 [ONNX] Enhance LSTM support.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/matmul.cpp
  src/ngraph/frontend/onnx_import/op/supported_ops.md
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
  src/ngraph/frontend/onnx_import/utils/rnn/activation_functions.cpp
  src/ngraph/frontend/onnx_import/utils/rnn/activation_functions.hpp
  test/models/onnx/lstm_fwd_with_clip.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2486 Upgrades MKLDNN to V0.18-rc
  cmake/external_mkldnn.cmake
  cmake/mkldnn.patch
Labels: Fully Reviewed, High Priority

#2498 fix a bug on finalize when uninitialized bool
  src/ngraph/distributed.cpp
  src/ngraph/distributed.hpp
Labels: Fully Reviewed, High Priority, distributed

#2499 Rollback accidental change to CGO.RelocationModel
  src/ngraph/codegen/compiler.cpp
Labels: Bug, Fully Reviewed, High Priority

#2361 Convert PlaidML Tile op to generic ngraph passthrough op
  cmake/external_gtest.cmake
  python/pyngraph/ops/passthrough.cpp
  python/pyngraph/ops/passthrough.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  src/ngraph/CMakeLists.txt
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/passthrough.cpp
  src/ngraph/op/passthrough.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_ops_local_response_norm.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_passthrough.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_tile.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_tile.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/serialize.cpp
Labels: Fully Reviewed, PlaidML

#2473 Move CodeWriter out of codegen to ngraph root.
  src/ngraph/code_writer.hpp
  src/ngraph/codegen/code_writer.hpp
  src/ngraph/pass/common_function_collection.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/cpu_kernel_emitters.cpp
  src/ngraph/runtime/cpu/cpu_kernel_emitters.hpp
  src/ngraph/runtime/cpu/cpu_kernel_utils.cpp
  src/ngraph/runtime/cpu/cpu_kernel_utils.hpp
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
  src/ngraph/runtime/gpu/gpu_internal_function.cpp
  src/ngraph/runtime/gpu/gpu_internal_function.hpp
  src/ngraph/runtime/gpu/gpu_kernel_emitters.cpp
  src/ngraph/runtime/gpu/gpu_kernel_emitters.hpp
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/code_writer.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.cpp
Labels: Fully Reviewed

#2476 [ONNX] GlobalLpPool operator
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/lp_pool.hpp
  src/ngraph/frontend/onnx_import/op/reduce.cpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/frontend/onnx_import/op/supported_ops.md
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/norm.cpp
  src/ngraph/frontend/onnx_import/utils/norm.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  test/models/onnx/global_lp_pool_p0.onnx
  test/models/onnx/global_lp_pool_p1.onnx
  test/models/onnx/global_lp_pool_p2.onnx
  test/models/onnx/global_lp_pool_p3.onnx
  test/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2500 IntelGPU backend: Relu and Sigmoid datatypes support
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
Labels: Fully Reviewed, IntelGPU

#2480 More quantized fusion patterns
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2496 [ONNX] numpy broadcasting refactoring
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/and.hpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/equal.hpp
  src/ngraph/frontend/onnx_import/op/gemm.cpp
  src/ngraph/frontend/onnx_import/op/greater.hpp
  src/ngraph/frontend/onnx_import/op/less.hpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/op/or.hpp
  src/ngraph/frontend/onnx_import/op/pow.hpp
  src/ngraph/frontend/onnx_import/op/prelu.cpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/frontend/onnx_import/op/xor.hpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.cpp
  src/ngraph/frontend/onnx_import/utils/broadcasting.hpp
  src/ngraph/frontend/onnx_import/utils/variadic.hpp
Labels: Fully Reviewed, ONNX

#2505 IntelGPU backend: ConvolutionBackpropData stability fix
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Bug, Fully Reviewed, IntelGPU

#2456 Unit tests for relevant resnet50 integer ops
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/backend_binary_elementwise.in.cpp
  test/backend_comparison.in.cpp
  test/backend_sum.in.cpp
  test/backend_test.in.cpp
  test/backend_unary_elementwise.in.cpp
Labels: Fully Reviewed

#2503 Update namespace table and fix broken links
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/frameworks/mxnet_integ.rst
  doc/sphinx/source/project/about.rst
  doc/sphinx/source/project/doc-contributor-README.rst
Labels: Fully Reviewed

#2506 IntelGPU backend: Concat operation fix
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  test/backend_test.in.cpp
Labels: Bug, Fully Reviewed, IntelGPU

#2508 Add info about lib versions in an easy to find place
  cmake/external_mkldnn.cmake
  cmake/external_protobuf.cmake
  cmake/external_tbb.cmake
  cmake/external_tbb_prebuilt.cmake
  cmake/tbb_fetch.cmake.in
Labels: Fully Reviewed, High Priority

#2238 Reuse memory for CPU backend.
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/pass_config.hpp
  src/ngraph/pass/propagate_cacheability.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/cpu_debugger.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.hpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/util.hpp
  test/backend_test.in.cpp
  test/cpu_test.cpp
  test/models/mxnet/mxnet_densenet121_inference_batch1_float32.json
Labels: Fully Reviewed, IntelCPU

#2490 rename and document the node name methods
  python/pyngraph/function.cpp
  python/pyngraph/node.cpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/serializer.cpp
  test/backend_test.in.cpp
Labels: Changes API, Fully Reviewed, High Priority

#2363 Refactor to create MKLDNN primitives on the first iteration:
  src/ngraph/runtime/cpu/builder/add.cpp
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/leaky_relu.cpp
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/builder/quantized_avg_pool.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/builder/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
Labels: Fully Reviewed, IntelCPU

#2511 mkl-dnn use CMAKE_INSTALL_LIBDIR to handle lib vs lib64 directory nam…
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed, High Priority

#2507 Normalize the printing of settings of bools to ON/OFF
  CMakeLists.txt
Labels: Fully Reviewed

#2510 Add Alex to cmake owners
  CODEOWNERS
Labels: Fully Reviewed

#2501 Add all dependent libraries to mlsl linkage interface
  cmake/external_mlsl.cmake
Labels: Fully Reviewed, High Priority, distributed

#2518 Update doc version to be even with latest release
  doc/sphinx/source/conf.py
Labels: Documentation

#2514 Fix bug introduced by #2238 on master
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
Labels: Fully Reviewed
