Repository NervanaSystems/ngraph, pull requests merged in 2019-07, with the labels that each got.

#3071 Add DynReplaceSlice op; make Dimension support negatives
  src/ngraph/CMakeLists.txt
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/dyn_replace_slice.cpp
  src/ngraph/op/experimental/dyn_replace_slice.hpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/pad.cpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/dyn_elimination.hpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/CMakeLists.txt
  test/dyn_elimination.cpp
  test/dyn_replace_slice_test.in.cpp
  test/ref_generators/generate_dyn_replace_slice_ref.py
  test/type_prop.cpp
  test/update_dyn_replace_slice_reference.sh
Labels: Changes API, Fully Reviewed

#3136 Add PlaidML Quantize & Dequantize
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_builder.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_quantize.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, PlaidML

#3143 Update CONTRIB.md
  CONTRIB.md
Labels: Fully Reviewed

#3148 Decomposition of fused ops in PlaidML backend [r0.23]
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, High Priority

#3150 Improve PlaidML backend option debugging
  src/ngraph/runtime/plaidml/plaidml_config.cpp
Labels: Fully Reviewed, High Priority, PlaidML

#3118 Fix fused sigmoid overflow.
  src/ngraph/runtime/cpu/kernel/sigmoid_multiply.hpp
  test/models/onnx/lstm_fwd_large_batch_no_clip.prototxt
  test/onnx/onnx_import_rnn.in.cpp
Labels: Fully Reviewed

#3123 Enable ONNX Runtime CI check on nGraph PRs
  .ci/onnx/onnxruntime/Jenkinsfile
  .ci/onnx/onnxruntime/proxy.patch
Labels: Fully Reviewed

#3145 Add PlaidML Quantize & Dequantize
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_builder.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_quantize.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, PlaidML

#3130 Remove CPURuntimeContext mkldnn primitives and workspaces assignments…
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
Labels: Fully Reviewed, IntelCPU

#3132 Decomposition of fused ops in PlaidML backend
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, PlaidML

#3133 Remove redundant run of FusedOpDecomposition.
  src/ngraph/runtime/gpu/gpu_compiled_function.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
Labels: Fully Reviewed

#3137 [MLIR] Bump MLIR repo to commit 82d5084 Wed Jun 26.
  cmake/external_mlir.cmake
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/contrib/mlir/dialect/dialect.cpp
  src/contrib/mlir/dialect/dialect.hpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/lowerer.hpp
  src/contrib/mlir/op_lowerers.inc
Labels: Fully Reviewed

#3144 Migrate from r0.23
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#3151 Improve PlaidML backend option debugging
  src/ngraph/runtime/plaidml/plaidml_config.cpp
Labels: Fully Reviewed, PlaidML

#3154 Removed deprecated fusion type constants.
  src/ngraph/pass/pass.hpp
Labels: Fully Reviewed

#3054 Add QuantizedConvolution op to ngraph core
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/builder/quantization_utils.cpp
  src/ngraph/builder/quantization_utils.hpp
  src/ngraph/builder/quantized_conv_builder.cpp
  src/ngraph/builder/quantized_conv_builder.hpp
  src/ngraph/frontend/onnx_import/op/conv_integer.cpp
  src/ngraph/frontend/onnx_import/op/quant_conv.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/experimental/quantized_conv.cpp
  src/ngraph/op/experimental/quantized_conv.hpp
  src/ngraph/op/experimental/quantized_conv_bias.cpp
  src/ngraph/op/experimental/quantized_conv_bias.hpp
  src/ngraph/op/experimental/quantized_conv_relu.cpp
  src/ngraph/op/experimental/quantized_conv_relu.hpp
  src/ngraph/op/fused/conv_fused.cpp
  src/ngraph/op/quantized_convolution.cpp
  src/ngraph/op/quantized_convolution.hpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/kernel/convolution.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/deconv.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/convolution.hpp
  src/ngraph/serializer.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/backend_test.in.cpp
  test/builder_quantization.cpp
  test/cpu_fusion.cpp
  test/models/onnx/quant_conv_lin.prototxt
  test/type_prop.cpp
Labels: Fully Reviewed

#3134 Failing test on INTERPRETER backend.
  src/ngraph/op/fused/group_conv_transpose.cpp
  test/files/onnx/convtranspose_output_shape/w.bin
  test/files/onnx/convtranspose_output_shape/x.bin
  test/files/onnx/convtranspose_output_shape/y.bin
  test/models/onnx/convtranspose_output_shape.prototxt
  test/onnx/onnx_import_convpool.in.cpp
Labels: Fully Reviewed

#2522 memory allocator for CPU
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/aligned_buffer.cpp
  src/ngraph/runtime/aligned_buffer.hpp
  src/ngraph/runtime/allocator.cpp
  src/ngraph/runtime/allocator.hpp
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
Labels: Fully Reviewed, IntelCPU, Merge Blocked

#3160 fix spelling error
  src/ngraph/distributed.cpp
Labels: Fully Reviewed

#3124 Add initial igpu docs and other important fixes for 0.22
  doc/sphinx/conf.py
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/source/backends/backend-api/index.rst
  doc/sphinx/source/backends/cpp-api.rst
  doc/sphinx/source/backends/dynamicbackend-api/index.rst
  doc/sphinx/source/backends/executable-api/index.rst
  doc/sphinx/source/backends/hosttensor-api/index.rst
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/frameworks/generic-configs.rst
  doc/sphinx/source/frameworks/mxnet_integ.rst
  doc/sphinx/source/frameworks/onnx_integ.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/inspection/index.rst
  doc/sphinx/source/project/doc-contributor-README.rst
  doc/sphinx/source/project/release-notes.rst
  python/BUILDING.md
  python/README.md
Labels: Documentation, Fully Reviewed, IntelGPU

#3156 Remove reshape file from op/util.
  src/ngraph/CMakeLists.txt
  src/ngraph/op/util/reshape.hpp
Labels: Fully Reviewed

#3165 Leona/doc v0.23
  doc/sphinx/conf.py
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#3183 pydocstyle 4.0 breaks flake8-docstrings.
  python/test_requirements.txt
Labels: Bug

#3182 Fix Onnx CI seg fault
  src/ngraph/runtime/allocator.cpp
  src/ngraph/runtime/allocator.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
Labels: Blocker, Bug, High Priority, IntelCPU

#3173 Minor PlaidML fixes
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_config.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_replicate.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_combination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.cpp
Labels: Fully Reviewed, PlaidML

#3149 Update mkl-dnn to v0.20
  cmake/external_mkldnn.cmake
  cmake/mkldnn.patch
Labels: Fully Reviewed

#3178 Update generic CPU backend to latest ngraph API
  src/ngraph/runtime/generic_cpu/CMakeLists.txt
  src/ngraph/runtime/generic_cpu/gcpu_backend.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/generic_cpu/kernel/broadcast.hpp
  src/ngraph/runtime/generic_cpu/kernel/reshape.hpp
  src/ngraph/runtime/generic_cpu/kernel/result.hpp
  src/ngraph/runtime/generic_cpu/node_wrapper.hpp
Labels: Fully Reviewed

#3161 Add Batch Norm Inference Relu fusion.
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#3184 Stabilize node sorting and fix some bugs.
  src/ngraph/descriptor/output.cpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  test/control_dependencies.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed, Merge Blocked, WIP

#3174 Minor PlaidML fixes
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_config.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_replicate.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_combination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.cpp
Labels: Fully Reviewed, PlaidML

#3196 Added rpath setting for PlaidML backend
  CMakeLists.txt
  src/ngraph/runtime/plaidml/CMakeLists.txt
Labels: High Priority, PlaidML

#3189 Fix crash on MacOS
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
Labels: Fully Reviewed

#3171 Exclude subgraph results that are also inputs when traversing
  src/ngraph/graph_util.cpp
Labels: Fully Reviewed

#3021 [MLIR] Add ArgMin/ArgMax lowering support
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/contrib/mlir/dialect/ops.cpp
  src/contrib/mlir/dialect/type.hpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/op_lowerers.inc
  src/contrib/mlir/ops_supported.inc
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_arg_reduce.in.cpp
Labels: Fully Reviewed

#3172 Update the conf file picked up by CI
  doc/sphinx/conf.py
  doc/sphinx/source/conf.py
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#3179 normalize comments
  python/pyngraph/serializer.cpp
  src/ngraph/frontend/onnx_import/op/max_pool.hpp
  src/ngraph/frontend/onnx_import/op/shrink.hpp
  src/ngraph/frontend/onnxifi/onnxifi.cpp
  src/ngraph/pass/manager.hpp
  src/ngraph/pass/pass_config.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.hpp
  src/ngraph/runtime/cpu/kernel/dropout.hpp
  src/ngraph/runtime/cpu/kernel/sigmoid_multiply.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/util.hpp
  test/cpu_test.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3205 Implement traverse nodes with pointers
  src/ngraph/graph_util.cpp
Labels: Fully Reviewed

#3187 Enable ConstantFolding for Product, Reverse; add a couple of dynamic tests
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/runtime/reference/product.hpp
  test/constant_folding.cpp
  test/dynamic.in.cpp
Labels: Fully Reviewed

#3177 Use libc++ for macOS core python wheel
  python/setup.py
Labels: Fully Reviewed

#3197 [MLIR] Support MLIR lowering of Relu
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/contrib/mlir/dialect/ops.td
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/op_lowerers.inc
  src/contrib/mlir/ops_supported.inc
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_test.in.cpp
Labels: Fully Reviewed

#3099 Tracer of real data in ngraph-CPU for debug purpose
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_debug_tracer.cpp
  src/ngraph/runtime/cpu/cpu_debug_tracer.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  test/CMakeLists.txt
  test/cpu_debug_tracer.cpp
Labels: Fully Reviewed

#3101 [MLIR] Add sub-graph extraction support
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/pass/cpu_compiled_kernel_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_compiled_kernel_fusion.hpp
  test/CMakeLists.txt
  test/backend_binary_elementwise.in.cpp
  test/backend_mlir.in.cpp
Labels: Fully Reviewed

#3167 Update to support building with clang 6.0
  cmake/clang_4_0_flags.cmake
  src/ngraph/distributed.cpp
  src/ngraph/pass/pass.hpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  test/event_tracing.cpp
Labels: Fully Reviewed

#3211 Disable some tests
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed, High Priority

#3212 Remove prefix reshape elimination pass
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.hpp
Labels: PlaidML

#3218 Update PlaidML dep to 0.6.3
  python/setup.py
Labels: PlaidML

#3215 Update unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed

#3195 Handle negative padding
  src/ngraph/runtime/plaidml/plaidml_ops_general.cpp
Labels: PlaidML

#3219 Update PlaidML dep to 0.6.3
  python/setup.py
Labels: Fully Reviewed, PlaidML

#3217 [ONNX] Remove unnecessary result dumping in test.
  test/onnx/onnx_import_convpool.in.cpp
Labels: Fully Reviewed, ONNX

#3208 Preserve pad_mode in reshape sinking for Pad
  src/ngraph/pass/reshape_sinking.cpp
Labels: Fully Reviewed

#3168 Use bash for Linux and Apple style
  CMakeLists.txt
  maint/apply-code-format.sh
  maint/bash_lib.sh
  maint/check-code-format.sh
  maint/clang_format_lib.sh
Labels: Fully Reviewed

#3199 Cyphers/topmaster
  src/ngraph/descriptor/output.cpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  test/control_dependencies.cpp
  test/util.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#3222 Fix compiler warning
  test/distributed.in.cpp
Labels: Fully Reviewed

#3191 Handle negative padding
  src/ngraph/runtime/plaidml/plaidml_ops_general.cpp
Labels: Fully Reviewed, PlaidML

#3088 First cut at async interface for backend tensor allocation and execution
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
Labels: Fully Reviewed, High Priority

#3181 Add Gelu OP
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/gelu.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_unary_elementwise.in.cpp
Labels: Fully Reviewed

#3127 Change compiler action to EmitLLVMOnly.
  src/ngraph/codegen/compiler.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
Labels: Fully Reviewed, IntelCPU

#3230 Replace set with vector container after API changes
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3213 Remove prefix reshape elimination pass
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_prefix_reshape_elimination.hpp
Labels: Fully Reviewed, PlaidML

#3138 Maintain control_deps in replace_node
  changes.md
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/autodiff/adjoints.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/compiled_kernel.cpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/get_output_element.hpp
  src/ngraph/op/replace_slice.cpp
  src/ngraph/op/replace_slice.hpp
  src/ngraph/pass/fused_op_decomposition.cpp
  src/ngraph/pass/get_output_element_elimination.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/runtime/cpu/builder/get_output_element.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/gpu/pass/gpu_batch_norm_cache.cpp
  src/ngraph/runtime/gpu/pass/gpu_rnn_fusion.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/plaidml_impl.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_general.cpp
  src/ngraph/serializer.cpp
  src/ngraph/specialize_function.cpp
  test/backend_graph_comparison.in.cpp
  test/control_dependencies.cpp
  test/distributed.in.cpp
Labels: Changes API, Fully Reviewed, High Priority

#3194 [ONNX] Fix backward pass for bidirectional LSTM.
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/models/onnx/lstm_bdir_short_input_seq.prototxt
  test/models/onnx/lstm_mixed_seq_reverse.prototxt
  test/onnx/onnx_import_rnn.in.cpp
Labels: Fully Reviewed, ONNX

#3074 [Py] ENV variable for tox backend selection
  python/tox.ini
Labels: Fully Reviewed

#3157 [ONNX] Handle slice start past the end case.
  src/ngraph/frontend/onnx_import/op/slice.cpp
Labels: Fully Reviewed, ONNX

#3175 [ONNX] Use nGraph auto padding in ONNX operators.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/average_pool.cpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/conv_integer.cpp
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/frontend/onnx_import/op/global_average_pool.cpp
  src/ngraph/frontend/onnx_import/op/global_max_pool.cpp
  src/ngraph/frontend/onnx_import/op/max_pool.cpp
  src/ngraph/frontend/onnx_import/op/quant_conv.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
  src/ngraph/frontend/onnx_import/utils/pooling_factory.cpp
  src/ngraph/frontend/onnx_import/utils/pooling_factory.hpp
  src/ngraph/op/fused/group_conv_transpose.cpp
  src/ngraph/op/fused/group_conv_transpose.hpp
  src/ngraph/op/util/attr_types.hpp
  test/models/onnx/conv2d_dilation_assym_pads_strides.prototxt
  test/models/onnx/conv3d_bias.prototxt
  test/type_prop/group_convolution_transpose.cpp
Labels: Fully Reviewed, ONNX

#3188 [ONNX] Fix shrink operator for uint* types
  src/ngraph/frontend/onnx_import/op/shrink.cpp
Labels: Fully Reviewed, ONNX

#3202 Provenance fix for new nodes during replace
  src/ngraph/graph_util.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#3207 Re-enable -Wswitch and -Wswitch-enum
  cmake/clang_4_0_flags.cmake
  src/ngraph/op/max.cpp
  src/ngraph/op/min.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/gpu/cudnn_host_parameters.hpp
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed

#3242 Update jenkins-trigger.groovy
  .ci/jenkins/jenkins-trigger.groovy
Labels: Fully Reviewed

#3221 Replace tabs with spaces
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
Labels: Fully Reviewed

#3243 Update jenkins-trigger.groovy
  .ci/jenkins/jenkins-trigger.groovy
Labels: Fully Reviewed

#3238 Update copyright year. All files should be 2017-2019.
  cmake/external_halide.cmake
  doc/examples/onnx/onnx_example.py
  doc/examples/subgraph_snippets/mxnet-gluon-example.py
  doc/sphinx/source/conf.py
  doc/sphinx/source/index.rst
  python/examples/basic.py
  python/ngraph/__init__.py
  python/ngraph/exceptions.py
  python/ngraph/impl/onnx_import/__init__.py
  python/ngraph/ops.py
  python/ngraph/runtime.py
  python/ngraph/utils/__init__.py
  python/ngraph/utils/broadcasting.py
  python/ngraph/utils/decorators.py
  python/ngraph/utils/input_validation.py
  python/ngraph/utils/reduction.py
  python/ngraph/utils/types.py
  python/test/__init__.py
  python/test/ngraph/__init__.py
  python/test/ngraph/test_basic.py
  python/test/ngraph/test_convolution.py
  python/test/ngraph/test_normalization.py
  python/test/ngraph/test_onnx_import.py
  python/test/ngraph/test_ops_binary.py
  python/test/ngraph/test_ops_matmul.py
  python/test/ngraph/test_ops_reshape.py
  python/test/ngraph/test_ops_unary.py
  python/test/ngraph/test_pooling.py
  python/test/ngraph/test_reduction.py
  python/test/ngraph/util.py
  python/test/test_ops.py
  src/ngraph/builder/quantization_utils.cpp
  src/ngraph/builder/quantization_utils.hpp
  src/ngraph/builder/quantized_conv_builder.cpp
  src/ngraph/builder/quantized_conv_builder.hpp
  src/ngraph/op/quantized_convolution.cpp
  src/ngraph/op/quantized_convolution.hpp
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/tools/ngraph-to-plaidml/CMakeLists.txt
Labels: Fully Reviewed

#3250 A few fixes for some customer-reported build issues
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/kernel/concat.hpp
  src/ngraph/type/bfloat16.hpp
Labels: Fully Reviewed

#3233 [MLIR] Fix incorrect callback lookup
  src/contrib/mlir/lowerer.cpp
Labels: Fully Reviewed

#3206 Add instructions for building the NGRAPH_PLAIDML backend,
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/frameworks/getting_started.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/mxnet_integ.rst
  doc/sphinx/source/frameworks/validated/list.rst
  doc/sphinx/source/frameworks/validated/testing-latency.rst
Labels: Documentation, Fully Reviewed, PlaidML

#3223 - MLIR Binary ElementWise Op
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/op_lowerers.inc
  src/contrib/mlir/ops_supported.inc
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3254 Workaround to allow BEs to disable revalidation in pass manager
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/manager.hpp
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
Labels: Fully Reviewed, High Priority

#3244 Some docstrings for replace_node
  src/ngraph/graph_util.hpp
Labels: Fully Reviewed

#3146 [WIP] Fix unreachable warnings in constant_folding.cpp
  src/ngraph/check.hpp
  src/ngraph/pass/constant_folding.cpp
Labels: Fully Reviewed

#3232 [MLIR] Add llvm.noalias attribute to nGraph func args
  src/contrib/mlir/lowerer.cpp
Labels: Fully Reviewed

#3245 Dont let backend, etc. go out of scope
  test/backend_performance.cpp
Labels: Bug, Fully Reviewed

#3225 [MLIR] Concat
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/contrib/mlir/dialect/ops.cpp
  src/contrib/mlir/dialect/ops.td
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/op_lowerers.inc
  src/contrib/mlir/ops_supported.inc
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/ngraph/op/experimental/compiled_kernel.cpp
Labels: Fully Reviewed

#3258 Add fixes to broken link found by linkchecker
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/frameworks/onnx_integ.rst
Labels: Fully Reviewed

#3259 Better error checking for Argmin/Argmax
  src/ngraph/op/util/index_reduction.cpp
  test/type_prop/index_reduction.cpp
Labels: Fully Reviewed

#3192 Update README to fix broken TF link
  README.md
  doc/sphinx/source/frameworks/getting_started.rst
  doc/sphinx/source/frameworks/onnx_integ.rst
  doc/sphinx/source/frameworks/validated/list.rst
  doc/sphinx/source/graphics/kernel-problem-1.png
  doc/sphinx/source/graphics/kernel-problem-2.png
  doc/sphinx/source/graphics/kernel-problem-3.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/extras/distributed_training.rst
  doc/sphinx/source/project/extras/homomorphic_encryption.rst
  doc/sphinx/source/project/extras/index.rst
  doc/sphinx/source/project/extras/testing_latency.rst
  doc/sphinx/source/project/introduction.rst
  doc/sphinx/source/project/release-notes.rst
  src/ngraph/op/util/broadcasting.hpp
Labels: Fully Reviewed

#3075 Codegen support for Dropout
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
Labels: Fully Reviewed, IntelCPU

#3158 Fix validate_and_infer_types protection so all classes are consistent
  src/ngraph/op/experimental/dyn_replace_slice.hpp
  src/ngraph/op/experimental/dyn_slice.hpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/op/lrn.hpp
  src/ngraph/op/one_hot.hpp
  src/ngraph/op/pad.hpp
  src/ngraph/op/replace_slice.hpp
  src/ngraph/op/select.hpp
  src/ngraph/op/slice.hpp
  src/ngraph/op/util/index_reduction.hpp
  src/ngraph/runtime/cpu/op/update_slice.hpp
Labels: Bug, Fully Reviewed

#3220 Update mkl-dnn to v0.20.1
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed

#3255 Use Eigen kernel for more cases for Gather and ScatterAdd.
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  test/backend_scatter.in.cpp
Labels: High Priority, IntelCPU

#3268 Same as #3255: Use Eigen kernel for more cases for Gather and ScatterAdd.
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  test/backend_scatter.in.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#3120 Langjian/allreduce provenance tag
  src/ngraph/runtime/cpu/builder/allreduce.cpp
Labels: Fully Reviewed

#3264 update jenkins-trigger file to pass down info about target branch
  .ci/jenkins/jenkins-trigger.groovy
Labels: Fully Reviewed

#3256 Cherry-pick "Workaround to allow BEs to disable revalidation in pass manager" to master
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/manager.hpp
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
Labels: Fully Reviewed

#3239 [ONNX] Add ReverseSequence operator
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/reverse_sequence.cpp
  src/ngraph/frontend/onnx_import/op/reverse_sequence.h
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/reverse_sequence.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/models/onnx/reverse_sequence_time_0_batch_1.prototxt
  test/models/onnx/reverse_sequence_time_1_batch_0.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3253 Update Copyright year for some CI scripts.
  .ci/buildkite/test_ngtf_build.py
  .ci/onnx/jenkins/prepare_environment.sh
  .ci/onnx/jenkins/runCI.sh
  .ci/onnx/jenkins/utils/docker.sh
  .ci/onnx/onnxruntime/Jenkinsfile
Labels: Fully Reviewed

#3260 Fix perf regression in some models
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
Labels: Fully Reviewed, High Priority, IntelCPU

#3236 [Py] Added elu operator to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/elu.cpp
  python/pyngraph/ops/elu.hpp
  python/pyngraph/ops/fused/elu.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
  src/ngraph/op/fused/elu.cpp
Labels: Fully Reviewed

#3279 Typo in help
  src/ngraph/check.hpp
Labels: Bug, Fully Reviewed, High Priority

#3115 [Py] Update documentation for utility test functions.
  python/test/ngraph/util.py
Labels: Fully Reviewed

#3278 Cyphers/s barannikov
  src/ngraph/node.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/and.hpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/op/divide.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/dot.hpp
  src/ngraph/op/equal.hpp
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/op/gather_nd.cpp
  src/ngraph/op/gather_nd.hpp
  src/ngraph/op/greater.cpp
  src/ngraph/op/greater.hpp
  src/ngraph/op/greater_eq.cpp
  src/ngraph/op/greater_eq.hpp
  src/ngraph/op/less.cpp
  src/ngraph/op/less.hpp
  src/ngraph/op/less_eq.cpp
  src/ngraph/op/less_eq.hpp
  src/ngraph/op/log.cpp
  src/ngraph/op/log.hpp
  src/ngraph/op/lrn.cpp
  src/ngraph/op/lrn.hpp
  src/ngraph/op/max.cpp
  src/ngraph/op/max.hpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/op/maximum.cpp
  src/ngraph/op/maximum.hpp
  src/ngraph/op/min.cpp
  src/ngraph/op/min.hpp
  src/ngraph/op/minimum.cpp
  src/ngraph/op/minimum.hpp
  src/ngraph/op/multiply.cpp
  src/ngraph/op/multiply.hpp
  src/ngraph/op/negative.cpp
  src/ngraph/op/negative.hpp
  src/ngraph/op/not.cpp
  src/ngraph/op/not.hpp
  src/ngraph/op/not_equal.cpp
  src/ngraph/op/not_equal.hpp
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/one_hot.hpp
  src/ngraph/op/or.cpp
  src/ngraph/op/or.hpp
Labels: DO NOT SQUASH, Fully Reviewed

#3280 [MLIR] Fix warnings in MLIR code.
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3285 Cherry pick #3277
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/lrn.in.cpp
  test/backend/sigmoid.in.cpp
  test/backend/softmax.in.cpp
Labels: Fully Reviewed

#3287 PlaidML RPATH fixes
  CMakeLists.txt
  src/ngraph/runtime/plaidml/CMakeLists.txt
Labels: Fully Reviewed, PlaidML

#3286 PlaidML RPATH fixes
  CMakeLists.txt
  src/ngraph/runtime/plaidml/CMakeLists.txt
Labels: Fully Reviewed, PlaidML

#3277 Restore DEFAULT_FLOAT_TOLERANCE_BITS logic in lrn, sigmoid, softmax
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/lrn.in.cpp
  test/backend/sigmoid.in.cpp
  test/backend/softmax.in.cpp
Labels: Fully Reviewed

#3163 Make required numpy version for setup and install explicit.
  python/requirements.txt
  python/setup.py
Labels: Fully Reviewed

#3229 Pad: add pad mode SYMMETRIC
  src/ngraph/op/pad.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/pad.hpp
  test/backend/pad.in.cpp
Labels: Fully Reviewed

#3276 Python capsules support for ngraph::Function
  python/pyngraph/function.cpp
Labels: Fully Reviewed

#3282 Remove support for adjoints of nodes
  doc/examples/abc/abc.cpp
  doc/examples/abc_operator/abc_operator.cpp
  doc/examples/mnist_mlp/dist_mnist_mlp.cpp
  doc/examples/mnist_mlp/mnist_mlp.cpp
  doc/sphinx/source/core/constructing-graphs/execute.rst
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/autodiff/adjoints.hpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  test/backend/batch_norm.in.cpp
  test/backend/binary_elementwise.in.cpp
  test/cpu_fusion.cpp
  test/util/autodiff/backprop_derivative.hpp
  test/util/autodiff/backprop_function.cpp
Labels: Changes API, Fully Reviewed

#3263 [MLIR] Enable Gather Op
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/contrib/mlir/dialect/ops.cpp
  src/contrib/mlir/dialect/ops.td
  src/contrib/mlir/dialect/type.hpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/op_lowerers.inc
  src/contrib/mlir/ops_supported.inc
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3291 Leona/doc v0.24
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/project/introduction.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/sitemap.rst
Labels: Fully Reviewed

#3295 [CMAKE] Change CODEGEN error on windows to be more grammatically correct
  CMakeLists.txt
Labels: Fully Reviewed

#3305 Add fix to r0.24 branch
  src/ngraph/runtime/allocator.cpp
Labels: Fully Reviewed

#3292 [MLIR] Fix naming convention in MLIR files
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/contrib/mlir/dialect/dialect.cpp
  src/contrib/mlir/dialect/dialect.hpp
  src/contrib/mlir/dialect/ops.cpp
  src/contrib/mlir/dialect/ops.hpp
  src/contrib/mlir/dialect/ops.td
  src/contrib/mlir/dialect/type.cpp
  src/contrib/mlir/dialect/type.hpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/lowerer.hpp
  src/contrib/mlir/memory_manager.cpp
  src/contrib/mlir/memory_manager.hpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.hpp
Labels: Fully Reviewed

#3269 remove unique_ptr from allocator static allocation
  src/ngraph/runtime/allocator.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
Labels: Fully Reviewed, High Priority

#3289 [MLIR] Deallocate all temp tensors before return
  src/contrib/mlir/lowerer.cpp
Labels: Fully Reviewed

#3306 Some GetOutputElement changes to help with Output<Node>
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/get_output_element.cpp
Labels: Fully Reviewed

#3307 Convert some more ops to use Output<Node> inputs
  src/ngraph/op/experimental/quantized_avg_pool.cpp
  src/ngraph/op/experimental/quantized_avg_pool.hpp
  src/ngraph/op/experimental/quantized_conv_bias.cpp
  src/ngraph/op/experimental/quantized_conv_bias.hpp
  src/ngraph/op/experimental/quantized_conv_relu.cpp
  src/ngraph/op/experimental/quantized_conv_relu.hpp
  src/ngraph/op/experimental/quantized_dot.cpp
  src/ngraph/op/experimental/quantized_dot.hpp
  src/ngraph/op/experimental/quantized_dot_bias.cpp
  src/ngraph/op/experimental/quantized_dot_bias.hpp
  src/ngraph/op/experimental/quantized_max_pool.cpp
  src/ngraph/op/experimental/quantized_max_pool.hpp
  src/ngraph/op/quantize.cpp
  src/ngraph/op/quantize.hpp
  src/ngraph/op/quantized_convolution.cpp
  src/ngraph/op/quantized_convolution.hpp
  src/ngraph/op/select.cpp
  src/ngraph/op/select.hpp
  src/ngraph/op/subtract.cpp
  src/ngraph/op/subtract.hpp
Labels: Fully Reviewed

#3308 [MLIR] Add missing visitor for Relu in compiler.cpp
  src/contrib/mlir/compiler.cpp
Labels: Fully Reviewed

#3309 Fixed double-buffering timing
  src/tools/nbench/benchmark_pipelined.cpp
Labels: Fully Reviewed

#3314 Reshape sinking: fix issue with handling rank changing reshape.
  src/ngraph/pass/reshape_sinking.cpp
Labels: Bug, Fully Reviewed

#3313 Reshape sinking: fix issue with handling rank changing reshape.
  src/ngraph/pass/reshape_sinking.cpp
Labels: Bug, Fully Reviewed, High Priority

#3316 Quantization conversion from nodes to outputs
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/builder/quantization/quantized_linear_matmul.cpp
  src/ngraph/builder/quantization/quantized_linear_matmul.hpp
  src/ngraph/builder/quantization_util.hpp
  src/ngraph/builder/quantization_utils.cpp
  src/ngraph/builder/quantization_utils.hpp
  src/ngraph/builder/quantized_conv_builder.cpp
  src/ngraph/builder/quantized_conv_builder.hpp
Labels: Fully Reviewed

#3317 ConstantFolding for Concat
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3318 ConstantFolding for Sum
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3324 Changes to get allow NNP to pass tests
  test/backend/batch_mat_mul.in.cpp
  test/backend/computation_reuse.in.cpp
Labels: Fully Reviewed

#3298 [MLIR] Re-compile sub-graph once on first invocation
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/ngraph/runtime/cpu/builder/mlir_cpu_compiled_kernel.cpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  test/backend/mlir.in.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#3325 [MLIR] Fix bad merge on 2 MLIR changes
  src/contrib/mlir/lowerer.cpp
Labels: Fully Reviewed

#3290 [MLIR] Enable affine dialect loop fusion
  src/contrib/mlir/compiler.cpp
Labels: Fully Reviewed

#3296 Make validation a pass and add it after every pass by default
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/manager.hpp
  src/ngraph/pass/validate.cpp
  src/ngraph/pass/validate.hpp
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
Labels: Fully Reviewed

#3322 ConstantFolding for Equal, Greater, GreaterEq, Less, LessEq, NotEqual
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/reference/divide.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3328 Add tests for recently added CPU CF functors
  test/cpu_test.cpp
Labels: Fully Reviewed

#3320 ConstantFolding for Ceiling and Floor
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  test/constant_folding.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#3326 ConstantFolding for Not
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  test/constant_folding.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#3310 [MLIR] Bump MLIR repo to commit 26c683c, 07/29/2019.
  cmake/external_mlir.cmake
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
  src/contrib/mlir/lowerer.cpp
Labels: Fully Reviewed

#3315 Some more changes of nodes to outputs
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/autobroadcast.hpp
  src/ngraph/builder/numpy_transpose.cpp
  src/ngraph/builder/numpy_transpose.hpp
  src/ngraph/op/fused/clamp.cpp
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/op/fused/gemm.cpp
  src/ngraph/op/fused/prelu.cpp
  src/ngraph/op/fused/scale_shift.cpp
  src/ngraph/op/fused/squared_difference.cpp
  src/ngraph/op/util/broadcasting.cpp
  src/ngraph/op/util/broadcasting.hpp
  src/ngraph/op/util/rnn_cell_base.cpp
  src/ngraph/op/util/rnn_cell_base.hpp
Labels: Fully Reviewed

#3297 Add Output support for a number of builders
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/norm.hpp
  src/ngraph/builder/reduce_ops.cpp
  src/ngraph/builder/reduce_ops.hpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/builder/split.cpp
  src/ngraph/builder/split.hpp
  src/ngraph/op/softmax.cpp
Labels: Fully Reviewed

#3338 CF updates: Reshape, DynReshape, Transpose
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3341 remove broken link
  doc/sphinx/source/backends/index.rst
Labels: Documentation, Fully Reviewed

#3340 CF updates: Slice, DynSlice
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/slice_plan.cpp
  src/ngraph/slice_plan.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3343 Convert ONNX ops to new form
  src/ngraph/frontend/onnx_import/core/null_node.cpp
  src/ngraph/frontend/onnx_import/core/null_node.hpp
Labels: Fully Reviewed

#3342 Add ConstantFolding for Gather
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/runtime/reference/gather.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3344 Convert PlaidML ops to new form
  src/ngraph/runtime/plaidml/plaidml_ops_convolution.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_convolution.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_implicit_broadcast.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_replicate.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_replicate.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_winograd.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_winograd.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_winograd.cpp
Labels: Fully Reviewed

#3294 [Py] Added clamp operator to Python API
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/clamp.cpp
  python/pyngraph/ops/fused/clamp.hpp
  python/pyngraph/ops/fused/elu.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3345 Convert CPU ops to new form
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/op/batch_mat_mul_transpose.cpp
  src/ngraph/runtime/cpu/op/batch_mat_mul_transpose.hpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.cpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.hpp
  src/ngraph/runtime/cpu/op/bounded_relu.cpp
  src/ngraph/runtime/cpu/op/bounded_relu.hpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/conv_add.hpp
  src/ngraph/runtime/cpu/op/conv_relu.cpp
  src/ngraph/runtime/cpu/op/conv_relu.hpp
  src/ngraph/runtime/cpu/op/convert_layout.cpp
  src/ngraph/runtime/cpu/op/convert_layout.hpp
  src/ngraph/runtime/cpu/op/deconv.cpp
  src/ngraph/runtime/cpu/op/deconv.hpp
  src/ngraph/runtime/cpu/op/dropout.cpp
  src/ngraph/runtime/cpu/op/dropout.hpp
  src/ngraph/runtime/cpu/op/group_conv_bias.cpp
  src/ngraph/runtime/cpu/op/group_conv_bias.hpp
  src/ngraph/runtime/cpu/op/halide_op.cpp
  src/ngraph/runtime/cpu/op/halide_op.hpp
  src/ngraph/runtime/cpu/op/leaky_relu.cpp
  src/ngraph/runtime/cpu/op/leaky_relu.hpp
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/matmul_bias.cpp
  src/ngraph/runtime/cpu/op/matmul_bias.hpp
  src/ngraph/runtime/cpu/op/max_pool_with_indices.cpp
  src/ngraph/runtime/cpu/op/max_pool_with_indices.hpp
  src/ngraph/runtime/cpu/op/quantized_matmul.cpp
  src/ngraph/runtime/cpu/op/quantized_matmul.hpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/op/sigmoid.cpp
  src/ngraph/runtime/cpu/op/sigmoid.hpp
  src/ngraph/runtime/cpu/op/sigmoid_mul.cpp
  src/ngraph/runtime/cpu/op/sigmoid_mul.hpp
  src/ngraph/runtime/cpu/op/update_slice.cpp
  src/ngraph/runtime/cpu/op/update_slice.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#3359 ConstantFolding for Select
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed
