Repository NervanaSystems/ngraph, pull requests merged in 2019-05, with the labels that each got.

#2840 Generic Reference Convolution
  src/ngraph/op/experimental/quantized_conv.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/kernel/convolution.hpp
  src/ngraph/runtime/reference/convolution.hpp
  test/builder_quantization.cpp
Labels: Fully Reviewed

#2823 Support constant folding for reshape and broadcast bf16 data
  src/ngraph/dimension.hpp
  src/ngraph/pass/constant_folding.cpp
Labels: Fully Reviewed

#2826 Change CPU backend to use PassConfig for codegen enable
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/pass_config.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  test/cpu_codegen.cpp
Labels: Fully Reviewed

#2806 Create mkldnn primitives at first iteration for codegen - part1.
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
Labels: Fully Reviewed, IntelCPU, Merge Blocked

#2845 Cyphers/fp16
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  src/ngraph/type/float16.cpp
  src/ngraph/type/float16.hpp
  test/CMakeLists.txt
  test/float16.cpp
  test/util/float_util.cpp
  test/util/float_util.hpp
Labels: Fully Reviewed

#2818 Update documentation section on graph visualization, fix ngraph bridge link, etc.
  doc/sphinx/ngraph.doxyfile
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/diagnostics/nbench.rst
  doc/sphinx/source/diagnostics/visualize.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/onnx_integ.rst
  doc/sphinx/source/frameworks/tensorflow_connect.rst
  doc/sphinx/source/frameworks/tensorflow_integ.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/inspection/debug.rst
  doc/sphinx/source/inspection/index.rst
  doc/sphinx/source/inspection/performance-profile.rst
  doc/sphinx/source/project/extras.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/tutorials/index.rst
Labels: Fully Reviewed

#2804 dynamic shape support for algebraic_simplification pass
  src/ngraph/pass/algebraic_simplification.hpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/manager.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  test/algebraic_simplification.cpp
Labels: Comments Addressed, Fully Reviewed

#2850 [KW] static_cast where possible
  src/ngraph/pass/core_fusion.cpp
Labels: Fully Reviewed

#2847 Klocwork issues.
  src/ngraph/pass/pass.hpp
  src/ngraph/runtime/cpu/cpu_call_frame.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  test/cpio.cpp
Labels: Fully Reviewed

#2851 mklml on linux has no soname set. This will cause linking against the…
  cmake/external_mkldnn.cmake
Labels: Bug, Fully Reviewed

#2854 remove throw from dtor
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
Labels: Bug, High Priority

#2849 Adding DetectionOutput and Interpolate layers
  src/ngraph/CMakeLists.txt
  src/ngraph/op/experimental/layers/detection_output.cpp
  src/ngraph/op/experimental/layers/detection_output.hpp
  src/ngraph/op/experimental/layers/interpolate.cpp
  src/ngraph/op/experimental/layers/interpolate.hpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed

#2855 remove throw from dtor
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
Labels: Fully Reviewed

#2856 Fix convbias and 1dconv for CODEGEN.
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#2305 Move callback out of matcher
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/graph_rewrite.hpp
  src/ngraph/pass/prefix_reshape_elimination.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/pattern/op/pattern.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/gpu/pass/gpu_rnn_fusion.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_concat_elision.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_concat_split.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_combination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_winograd.cpp
  test/control_dependencies.cpp
  test/pattern.cpp
Labels: Changes API, Comments Addressed, Fully Reviewed, High Priority

#2861 Fix the cpu thread_safe_calls test on Windows.
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2866 Migrate from master.
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  test/cpu_test.cpp
Labels: Bug, High Priority

#2868 Add build option NGRAPH_ENABLE_CPU_CONV_AUTO to enable/disable mkldnn…
  CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
Labels: Bug, IntelCPU

#2871 Some edits to help message for nbench
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#2860 [Dynamic Shape] GraphRewrite refactor with constant folding pass
  src/ngraph/pass/algebraic_simplification.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/graph_rewrite.hpp
  src/ngraph/pass/manager.cpp
Labels: Fully Reviewed

#2878 Fix a bug in mkldnn emitter.
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#2853 [Fused Op] Move Gemm operator from onnx import to ngraph fused ops
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/gemm.cpp
  src/ngraph/frontend/onnx_import/op/gemm.hpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/transpose.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/gemm.cpp
  src/ngraph/op/fused/gemm.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/util/reshape.cpp
  src/ngraph/op/util/reshape.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2793 Create backend as shared_ptr
  python/pyngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/backend_manager.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/generic_cpu/gcpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpuh/gpuh_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/nop/nop_backend.cpp
  test/backend_test.in.cpp
  test/builder_quantization.cpp
  test/hybrid_backend.cpp
  test/util/test_case.hpp
Labels: Changes API, Fully Reviewed

#2865 Add Tile op
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/tile.cpp
  src/ngraph/op/experimental/tile.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2876 Use pragma clang only if compiler is Clang.
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/reference/equal.hpp
  src/ngraph/runtime/reference/not_equal.hpp
  src/ngraph/runtime/reference/topk.hpp
  src/ngraph/type/bfloat16.cpp
  src/ngraph/type/float16.cpp
Labels: Fully Reviewed

#2885 Fix data type for conv builder
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#2889 Provenance without post-dominated
  src/ngraph/graph_util.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#2891 Migrate #2889 from master
  src/ngraph/graph_util.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#2867 [Standalone] Create mkldnn primitives in the generated file
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
Labels: Fully Reviewed, IntelCPU

#2873 Quantization API cleanup (non breaking)
  doc/sphinx/source/ops/dequantize.rst
  doc/sphinx/source/ops/quantize.rst
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/op/dequantize.cpp
  src/ngraph/op/dequantize.hpp
  src/ngraph/op/experimental/quantized_conv.cpp
  src/ngraph/op/experimental/quantized_conv.hpp
  src/ngraph/op/experimental/quantized_conv_bias.cpp
  src/ngraph/op/experimental/quantized_conv_bias.hpp
  src/ngraph/op/experimental/quantized_conv_relu.cpp
  src/ngraph/op/experimental/quantized_conv_relu.hpp
  src/ngraph/op/quantize.cpp
  src/ngraph/op/quantize.hpp
  src/ngraph/runtime/reference/dequantize.hpp
  src/ngraph/runtime/reference/quantize.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2877 IntelGPU backend: change code owner
  CODEOWNERS
Labels: Fully Reviewed, IntelGPU

#2879 Update section on Homomorphic Encryption transformer
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/project/extras.rst
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#2827 [ONNX] Refactor LSTM tests to use NgraphTestCase
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/onnx/onnx_import_rnn.in.cpp
  test/util/test_case.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed, ONNX

#2890 Migrate from r0.19
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
Labels: Fully Reviewed, High Priority

#2869 [ONNX] Hardmax support in ONNX importer
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/runtime/cpu/builder/embedding_lookup.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/hardmax.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#2880 Store Constant arrays where data is constant as a single value
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/pass/constant_to_broadcast.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/serializer.cpp
  test/all_close_f.cpp
  test/serialize.cpp
  test/util/all_close_f.cpp
Labels: Fully Reviewed

#2897 Migrate from #2884
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/open_mpi.hpp
Labels: Fully Reviewed, High Priority

#2884 Langjian/mpi finalize
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/open_mpi.hpp
Labels: Fully Reviewed

#2864 Tweaks to VisualizeTree to make it tractable to render complex training graphs
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/visualize_tree.cpp
Labels: Fully Reviewed

#2824 Add HardSigmoid to fused ops.
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/hard_sigmoid.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/hard_sigmoid.cpp
  src/ngraph/op/fused/hard_sigmoid.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2825 [ONNX] Add interpret_as_scalar helper
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
Labels: Fully Reviewed, ONNX

#2844 Dynamic-shape backend API change, with prototype implementation
  CODEOWNERS
  python/pyngraph/runtime/backend.cpp
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.hpp
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/tensor.cpp
  src/ngraph/runtime/tensor.hpp
  test/CMakeLists.txt
  test/dynamic.in.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#2894 Add more info to error messages
  src/ngraph/runtime/backend_manager.cpp
Labels: Fully Reviewed, High Priority

#2886 [FusedOps] Clamp
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/clip.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/clamp.cpp
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2902 [ONNX] Add support for negative axis attribute in Gather op.
  src/ngraph/frontend/onnx_import/op/gather.hpp
Labels: Fully Reviewed, High Priority, ONNX

#2842 [ONNX] Activation functions parameters for LSTM.
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/utils/rnn/activation_functions.cpp
  src/ngraph/frontend/onnx_import/utils/rnn/activation_functions.hpp
  test/models/onnx/lstm_fwd_hardsigmoid_activation.prototxt
  test/onnx/onnx_import_rnn.in.cpp
Labels: Fully Reviewed, ONNX

#2862 Added extra attributes to DynSlice
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/experimental/dyn_slice.hpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/experimental/layers/proposal.cpp
  src/ngraph/validation_util.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2875 Enable non-constructor use of shape inference
  src/ngraph/function.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/result.cpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/runtime/gpu/op/batch_norm.cpp
  src/ngraph/runtime/gpu/op/batch_norm.hpp
  test/type_prop.cpp
Labels: Changes API, Fully Reviewed

#2881 Move ONNX lp-norm utility functions to core op/util.
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/norm.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/reduce.cpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/frontend/onnx_import/utils/norm.cpp
  src/ngraph/frontend/onnx_import/utils/norm.hpp
Labels: Fully Reviewed

#2909 Ayzhuang/fix tf maxpool segfault migrate
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
Labels: Bug, Fully Reviewed, High Priority

#2887 [Fused Op] Add new fused operator: MVN(Mean Variance Normalization)
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2888 [Fused op] Normalize
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/normalize.cpp
  src/ngraph/op/fused/normalize.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2910 Cherry-pick #2906 to r0.19
  src/ngraph/pass/propagate_cacheability.cpp
  src/ngraph/runtime/backend.cpp
  test/autodiff.in.cpp
  test/control_dependencies.cpp
  test/hybrid_backend.cpp
  test/pattern.cpp
Labels: Fully Reviewed, High Priority

#2893 NgraphTestCase - dump expected and computed data to the console
  test/util/test_case.cpp
  test/util/test_case.hpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#2899 Adding ROI pooling layers
  src/ngraph/CMakeLists.txt
  src/ngraph/op/experimental/layers/psroi_pooling.cpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  src/ngraph/op/experimental/layers/roi_pooling.cpp
  src/ngraph/op/experimental/layers/roi_pooling.hpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed

#2900 Normalize CPUTensorRole to TensorRole for use in multiple backends
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.hpp
  src/ngraph/runtime/gpu/gpu_call_frame.cpp
  src/ngraph/runtime/gpu/gpu_call_frame.hpp
  src/ngraph/runtime/gpu/gpu_internal_function.cpp
  src/ngraph/runtime/gpu/gpu_internal_function.hpp
  src/ngraph/runtime/gpu/gpu_tensor_wrapper.cpp
  src/ngraph/runtime/gpu/gpu_tensor_wrapper.hpp
  src/ngraph/util.hpp
Labels: Fully Reviewed

#2904 IntelGPU backend: Gemm operation
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#2906 Remove runtime/cpu includes from things outside runtime/cpu
  src/ngraph/pass/propagate_cacheability.cpp
  src/ngraph/runtime/backend.cpp
  test/autodiff.in.cpp
  test/control_dependencies.cpp
  test/hybrid_backend.cpp
  test/pattern.cpp
Labels: Fully Reviewed

#2920 Fix incorrect clang header path.
  src/resource/CMakeLists.txt
Labels: Bug, Fully Reviewed

#2921 Fix incorrect clang header path.
  src/resource/CMakeLists.txt
Labels: Bug, Fully Reviewed

#2892 [Fused Op] Add ScaleShift operator
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/scale_shift.cpp
  src/ngraph/op/fused/scale_shift.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2911 IntelGPU backend: Switch to the latest clDNN
  cmake/external_cldnn.cmake
Labels: Fully Reviewed, IntelGPU

#2913 Fix building on centos with gcc 4.8.5
  src/ngraph/op/fused/normalize.cpp
  src/ngraph/op/util/broadcasting.hpp
Labels: Fully Reviewed

#2914 Address Klocwork issue
  src/ngraph/pass/graph_rewrite.cpp
Labels: Fully Reviewed

#2898 Fix clang compiler warnings
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/op/result.cpp
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/runtime/cpu/builder/get_output_element.cpp
  src/ngraph/runtime/cpu/cpu_op_annotations.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/reference/topk.hpp
  src/ngraph/serializer.cpp
  src/ngraph/type/element_type.cpp
  src/tools/nbench/nbench.cpp
  test/control_dependencies.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#2874 scatter_add and scatter_nd_add
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/scatter_add.cpp
  src/ngraph/op/scatter_add.hpp
  src/ngraph/op/scatter_nd_add.cpp
  src/ngraph/op/scatter_nd_add.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/builder/scatter_nd_add.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/scatter_add.hpp
  src/ngraph/runtime/reference/scatter_nd_add.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend_scatter.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2915 Address Klocwork issue. Fix bug?
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
Labels: Fully Reviewed

#2922 Edit CODEOWNERS for runtime/dynamic
  CODEOWNERS
Labels: Fully Reviewed

#2925 Remove remaining osx compiler warnings
  test/autodiff.in.cpp
  test/cpu_debugger.cpp
Labels: Fully Reviewed

#2938 IntelGPU backend: More cases of MaxPool op to be executed via clDNN
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: IntelGPU

#2933 Add some assignment tests for [b]float16
  test/bfloat16.cpp
  test/float16.cpp
Labels: Fully Reviewed

#2939 IntelGPU backend: Change clDNN mode of Relu op to allow ConvolutionBiasAdd fusing inside clDNN
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2937 [ONNX] Remove return-std-move-in-c++11 warning
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
Labels: Fully Reviewed, ONNX

#2940 IntelGPU backend: Make ScaleShift op as not supported in callback of FusedOpDecomposition pass
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
Labels: Fully Reviewed, IntelGPU

#2905 [Fused Op] GRN
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/grn.cpp
  src/ngraph/op/fused/grn.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2935 [Dynamic Shape] Added Pass Properties to Core Passes
  src/ngraph/pass/algebraic_simplification.hpp
  src/ngraph/pass/batch_fusion.hpp
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/concat_fusion.hpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/cse.hpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/graph_rewrite.hpp
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/nop_elimination.hpp
  src/ngraph/pass/pass.cpp
  src/ngraph/pass/pass.hpp
  src/ngraph/pass/prefix_reshape_elimination.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_sinking.hpp
  src/ngraph/pass/shape_specialization.hpp
  src/ngraph/pass/zero_dim_tensor_elimination.hpp
  src/ngraph/util.hpp
  test/algebraic_simplification.cpp
  test/concat_fusion.cpp
  test/constant_folding.cpp
  test/core_fusion.cpp
  test/cse.cpp
  test/nop_elimination.cpp
  test/pass_shape_specialization.cpp
  test/reshape_elimination.cpp
  test/reshape_sinking.cpp
  test/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#2908 Supports more cases for Convolution Bias fusion
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  test/core_fusion.cpp
Labels: Fully Reviewed

#2930 Let dist interface control logging output
  src/ngraph/distributed.hpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/null.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/log.cpp
Labels: Fully Reviewed, High Priority

#2918 [FusedOps] SquaredDifference
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/squared_difference.cpp
  src/ngraph/op/fused/squared_difference.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2948 Remove ShapeSpecialization pass and attendant as_constants machinery
  src/ngraph/CMakeLists.txt
  src/ngraph/node.hpp
  src/ngraph/op/concat.cpp
  src/ngraph/op/concat.hpp
  src/ngraph/op/experimental/shape_of.cpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/pass/shape_specialization.cpp
  src/ngraph/pass/shape_specialization.hpp
  test/CMakeLists.txt
  test/pass_shape_specialization.cpp
Labels: Fully Reviewed

#2945 Workaround for #pragma GCC diagnostic error. (Another version)
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#2941 Update mkl-dnn: v0.19
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed

#2950 Fixes incorrect and extra provenance tags
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  test/provenance.cpp
Labels: Fully Reviewed

#2883 nbench special handle op name for "NNP_XXX"
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#2923 Remove parent from PlaidML tensor initializer
  src/ngraph/runtime/plaidml/plaidml_backend.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.hpp
Labels: Fully Reviewed

#2960 Remove parent from PlaidML tensor initializer
  src/ngraph/runtime/plaidml/plaidml_backend.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.hpp
Labels: Fully Reviewed, High Priority

#2956 Add support for move semantics to AlignedBuffer
  src/ngraph/runtime/aligned_buffer.cpp
  src/ngraph/runtime/aligned_buffer.hpp
  test/CMakeLists.txt
  test/aligned_buffer.cpp
Labels: Fully Reviewed

#2859 Create mkldnn primitives at first iteration for codegen - part2
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/max_pool_with_indices.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#2951 [FusedOps] Split
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/split.cpp
  src/ngraph/builder/split.hpp
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2949 Add more infrastructure for specialization of cloned graphs
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/dyn_elimination.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.hpp
  src/ngraph/runtime/tensor.hpp
  src/ngraph/specialize_function.cpp
  src/ngraph/specialize_function.hpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
  test/CMakeLists.txt
  test/constant_folding.cpp
  test/dyn_elimination.cpp
  test/dynamic.in.cpp
  test/specialize_function.cpp
  test/type_prop.cpp
  test/util.cpp
Labels: Fully Reviewed

#2957 Change FusionType to enum class and use EnumMask
  changes.md
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/pass/batch_fusion.hpp
  src/ngraph/pass/core_fusion.hpp
  src/ngraph/pass/pass.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
Labels: Changes API, Comments Addressed, Fully Reviewed

#2954 update visualize tree file extenstions and output formats
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/visualize_tree.hpp
  src/tools/nbench/nbench.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#2947 Update version, clean up ToC, add more detail to section on inspectin…
  doc/sphinx/conf.py
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/core/constructing-graphs/import.rst
  doc/sphinx/source/distr/index.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/inspection/index.rst
  doc/sphinx/source/project/contribution-guide.rst
  doc/sphinx/source/project/extras.rst
  doc/sphinx/source/project/governance.rst
  doc/sphinx/source/project/index.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/tutorials/index.rst
Labels: Fully Reviewed

#2959 Allow NGRAPH_VISUALIZE_TREE_OUTPUT_SHAPES to output partial shapes
  src/ngraph/pass/visualize_tree.cpp
Labels: Fully Reviewed

#2962 Remove functions from cpu which were moved to core
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
Labels: Fully Reviewed, High Priority

#2969 Move zero padded conv fusions from CPUFusion to CoreFusion.
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/core_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#2958 Fix Convert for boolean output type in CODEGEN.
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed, IntelCPU

#2973 Add environment variable to explicitly enable f->is_dynamic()
  src/ngraph/pass/graph_rewrite.cpp
Labels: High Priority

#2970 create tensor for the primary backend
  src/ngraph/runtime/hybrid/hybrid_backend.cpp
  src/ngraph/runtime/hybrid/hybrid_backend.hpp
Labels: Fully Reviewed, High Priority

#2975 Make private members protected in hybrid classes
  src/ngraph/runtime/hybrid/hybrid_executable.cpp
  src/ngraph/runtime/hybrid/hybrid_executable.hpp
  src/ngraph/runtime/hybrid/hybrid_tensor.hpp
Labels: Fully Reviewed, High Priority

#2706 [ONNX] Unit tests for QLinearMatMul
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/qlinear_matmul.prototxt
  test/models/onnx/qlinear_matmul_3d.prototxt
  test/onnx/onnx_import_quant.in.cpp
Labels: Fully Reviewed, ONNX

#2961 IntelGPU backend: Switch to clDNN which is compatible with gcc4.8
  cmake/external_cldnn.cmake
Labels: Bug, Fully Reviewed, IntelGPU

#2964 Added accessor methods for layer op attributes
  src/ngraph/op/experimental/layers/detection_output.hpp
  src/ngraph/op/experimental/layers/interpolate.hpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box.hpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.hpp
  src/ngraph/op/experimental/layers/proposal.cpp
  src/ngraph/op/experimental/layers/proposal.hpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
  src/ngraph/op/experimental/layers/reorg_yolo.cpp
  src/ngraph/op/experimental/layers/reorg_yolo.hpp
  src/ngraph/op/experimental/layers/roi_pooling.hpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed

#2955 Add save/load API to runtime
  src/ngraph/cpio.cpp
  src/ngraph/cpio.hpp
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/backend_api.cpp
Labels: Fully Reviewed, High Priority

#2976 Backport v0.19.1 fix from #2973
  src/ngraph/pass/graph_rewrite.cpp
Labels: Fully Reviewed, High Priority

#2965 CTCGreedyDecoder layer op
  src/ngraph/CMakeLists.txt
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.cpp
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.hpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed

#2968 Switch some get_inputs uses to use the newer inputs
  src/ngraph/builder/quantization/quantized_linear_matmul.cpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
  src/ngraph/runtime/cpu/op/batch_mat_mul_transpose.cpp
  src/ngraph/runtime/cpu/op/group_conv_bias.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed

#2974 update a few files to build on windows
  test/backend_fused_op.in.cpp
  test/backend_gather.in.cpp
  test/cpu_test.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#2971 Leona/doc v0.20
  doc/sphinx/source/backend-support/backend-api/index.rst
  doc/sphinx/source/backend-support/cpp-api.rst
  doc/sphinx/source/backend-support/executable-api/index.rst
  doc/sphinx/source/backend-support/hosttensor-api/index.rst
  doc/sphinx/source/backend-support/index.rst
  doc/sphinx/source/backend-support/plaidml-ng-api/index.rst
  doc/sphinx/source/backend-support/tensor-api/index.rst
  doc/sphinx/source/core/fusion/index.rst
  doc/sphinx/source/glossary.rst
  doc/sphinx/source/graphics/classngraph_patternmatcher.png
  doc/sphinx/source/graphics/classngraph_tensor_descriptor.png
  doc/sphinx/source/graphics/descriptor-of-tensor.png
  doc/sphinx/source/graphics/recurrent-graph-rewrite.png
  doc/sphinx/source/graphics/runtime-exec.png
  doc/sphinx/source/graphics/runtime.png
Labels: Fully Reviewed

#2980 Switch off the failing unit tests for iGPU
  src/ngraph/runtime/intelgpu/unit_test.manifest
Labels: Fully Reviewed, IntelGPU

#2982 Switch to clDNN version with conformance fix for 3 ONNX models (DenseNet-121, Inception-v2, ResNet-50)
  cmake/external_cldnn.cmake
Labels: Bug, Fully Reviewed, IntelGPU

#2927 [FusedOps] ShuffleChannels
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/shuffle_channels.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2981 fix broken doc strings
  src/ngraph/deprecated.hpp
  src/ngraph/op/argmax.hpp
  src/ngraph/op/argmin.hpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/op/embedding_lookup.hpp
  src/ngraph/op/gather.hpp
  src/ngraph/op/gather_nd.hpp
  src/ngraph/op/scatter_add.hpp
  src/ngraph/op/scatter_nd_add.hpp
  src/ngraph/runtime/backend.hpp
Labels: Fully Reviewed

#2988 Removed unnecessary write from autodiff::get_autodiff
  test/util/autodiff/backprop_derivative.hpp
Labels: Fully Reviewed

#2984 Move reshape functions from utils to builder.
  changes.md
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/matmul.cpp
  src/ngraph/frontend/onnx_import/op/reshape.cpp
  src/ngraph/frontend/onnx_import/op/transpose.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/gemm.cpp
  src/ngraph/op/fused/grn.cpp
  src/ngraph/op/fused/normalize.cpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.hpp
  src/ngraph/op/util/reshape.hpp
Labels: Fully Reviewed

#2989 Added option in order to build nGraph core static library
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
Labels: Fully Reviewed

#2928 [Fused] FakeQuantize operation.
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/fake_quantize.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2993 Much faster serialize/deserialize of broadcast constants
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#2936 Initial implementation of implicit broadcasting for eltwise ops
  src/ngraph/CMakeLists.txt
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/and.cpp
  src/ngraph/op/and.hpp
  src/ngraph/op/divide.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/equal.cpp
  src/ngraph/op/equal.hpp
  src/ngraph/op/greater.cpp
  src/ngraph/op/greater.hpp
  src/ngraph/op/greater_eq.cpp
  src/ngraph/op/greater_eq.hpp
  src/ngraph/op/less.cpp
  src/ngraph/op/less.hpp
  src/ngraph/op/less_eq.cpp
  src/ngraph/op/less_eq.hpp
  src/ngraph/op/maximum.cpp
  src/ngraph/op/maximum.hpp
  src/ngraph/op/minimum.cpp
  src/ngraph/op/minimum.hpp
  src/ngraph/op/multiply.cpp
  src/ngraph/op/multiply.hpp
  src/ngraph/op/not_equal.cpp
  src/ngraph/op/not_equal.hpp
  src/ngraph/op/or.cpp
  src/ngraph/op/or.hpp
  src/ngraph/op/power.cpp
  src/ngraph/op/power.hpp
  src/ngraph/op/subtract.cpp
  src/ngraph/op/subtract.hpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/op/util/binary_elementwise_arithmetic.cpp
  src/ngraph/op/util/binary_elementwise_arithmetic.hpp
  src/ngraph/op/util/binary_elementwise_comparison.cpp
  src/ngraph/op/util/binary_elementwise_comparison.hpp
  src/ngraph/op/util/binary_elementwise_logical.cpp
  src/ngraph/op/util/binary_elementwise_logical.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/pass/implicit_broadcast_elimination.cpp
  src/ngraph/pass/implicit_broadcast_elimination.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_compiled_function.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/serializer.cpp
  test/backend_binary_elementwise.in.cpp
  test/partial_shape.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#2997 Remove unused .gitmodule
  .gitmodules
Labels: Fully Reviewed

#3000 Tweak backend constructor for gcc 4.8.5
  src/ngraph/runtime/plaidml/plaidml_backend.cpp
Labels: Fully Reviewed, High Priority, PlaidML

#3001 Tweak backend constructor for gcc 4.8.5
  src/ngraph/runtime/plaidml/plaidml_backend.cpp
Labels: Fully Reviewed, High Priority, PlaidML

#2998 Add runtime check to HybridExecutable::get_as<T>()
  src/ngraph/runtime/hybrid/hybrid_executable.hpp
Labels: Fully Reviewed

#2942 Cleanup how compile flags are set and used by nGraph and external projects.
  CMakeLists.txt
  cmake/clang_4_0_flags.cmake
  cmake/external_cldnn.cmake
  cmake/external_gtest.cmake
  cmake/external_halide.cmake
  cmake/external_llvm.cmake
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
  cmake/external_tbb.cmake
  cmake/sdl.cmake
  src/CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/generic_cpu/CMakeLists.txt
  src/ngraph/runtime/gpu/nvcc/example.cu.cpp
  test/CMakeLists.txt
  test/files/CMakeLists.txt
  test/models/CMakeLists.txt
Labels: Fully Reviewed

#3005 Bob/hybrid multi
  src/ngraph/runtime/hybrid/hybrid_util.cpp
Labels: Fully Reviewed, High Priority
