Repository NervanaSystems/ngraph, pull requests merged in 2019-10, with the labels that each got.

#3681 Call ngraph_malloc instead of malloc so it throws if out of memory
  src/ngraph/runtime/aligned_buffer.cpp
Labels: Fully Reviewed

#3690 Cyphers/25headers
  src/ngraph/runtime/reference/range.hpp
  src/ngraph/runtime/reference/sum.hpp
Labels: Fully Reviewed

#3588 [SPEC] TopK::v1 implementation
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/topk.in.cpp
  test/opset_pass/topk_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3686 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#3621 Support for RandomUniformOp in CPU
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/random_uniform.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#3699 Add missing input (#3691)
  src/ngraph/node.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#3647 Master edition of Provenance for builders
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/dequantize_builder.cpp
  src/ngraph/builder/make_constant.hpp
  src/ngraph/builder/matmul_factory.cpp
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/numpy_transpose.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization_utils.cpp
  src/ngraph/builder/quantize_builder.cpp
  src/ngraph/builder/quantized_concat_builder.cpp
  src/ngraph/builder/quantized_conv_builder.cpp
  src/ngraph/builder/quantized_dot_builder.cpp
  src/ngraph/builder/reduce_ops.cpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/split.cpp
  src/ngraph/builder/tensor_mask.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/experimental/generate_mask.cpp
  src/ngraph/op/lrn.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/pass/fused_op_decomposition.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#3696 Add missing headers (#3690)
  src/ngraph/runtime/reference/range.hpp
  src/ngraph/runtime/reference/sum.hpp
Labels: Fully Reviewed

#3697 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#3698 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#3543 [Spec] Update fused operator GroupConvolution to new specification
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/fused_op.in.cpp
Labels: Fully Reviewed, SPEC

#3688 Support non-mkldnn fallback for Batchnorm training bprop in CPU backend
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/kernel/batchnorm.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/autodiff.in.cpp
Labels: Fully Reviewed

#3700 Fix ops, cleanup ToC, add latest illustrations
  doc/sphinx/ngraph_theme/layout.html
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/features.rst
  doc/sphinx/source/frameworks/generic_configs.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/overview.rst
  doc/sphinx/source/frameworks/validated/list.rst
  doc/sphinx/source/graphics/a-common-stack.png
  doc/sphinx/source/graphics/about_fullstack.png
  doc/sphinx/source/graphics/backend-dgm.png
  doc/sphinx/source/graphics/backend-dgm.xcf
  doc/sphinx/source/graphics/overview-framework-bridges.svg
  doc/sphinx/source/graphics/overview-translation-flow.svg
  doc/sphinx/source/graphics/slack.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/introduction.rst
  doc/sphinx/source/ops/avg_pool.rst
  doc/sphinx/source/ops/avg_pool_backprop.rst
  doc/sphinx/source/ops/convolution.rst
  doc/sphinx/source/ops/max_pool.rst
  doc/sphinx/source/project/about.rst
  doc/sphinx/source/project/contribution-guide.rst
  doc/sphinx/source/project/doc-contributor-README.rst
  doc/sphinx/source/project/index.rst
Labels: Comments Addressed, Fully Reviewed

#3705 Hotfix for negative axes in unsqueeze op
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
Labels: ONNX

#3703 [MLIR] Pass optimization level to MLIR ExecutionEngine
  src/contrib/mlir/compiler/compiler.cpp
  src/contrib/mlir/compiler/compiler.hpp
Labels: Fully Reviewed

#3660 [ONNX] Remove broadcasting from ONNX importer.
  src/ngraph/frontend/onnx_import/op/add.hpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/equal.hpp
  src/ngraph/frontend/onnx_import/op/greater.hpp
  src/ngraph/frontend/onnx_import/op/less.hpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/or.hpp
  src/ngraph/frontend/onnx_import/op/pow.hpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/frontend/onnx_import/op/xor.hpp
Labels: Fully Reviewed, ONNX

#3695 [SPEC] Fixed NormalizeL2
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/norm.hpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/op/fused/normalize_l2.cpp
  test/backend/fused_op.in.cpp
  test/ref_generators/generate_normalize_l2_ref.py
  test/type_prop/normalize.cpp
Labels: Fully Reviewed, SPEC

#3685 [MLIR] Remove warning (unused var)
  src/contrib/mlir/compiler/dialect/ops.cpp
Labels: Fully Reviewed, Merge Blocked

#3701 Enable Gather with negative indices.
  src/ngraph/runtime/cpu/kernel/gather.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/gather_nd.hpp
  test/backend/gather.in.cpp
Labels: IntelCPU

#3710 Fix a bug in rotate_blocked_md.
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Fully Reviewed

#3723 More expressive error messages
  src/ngraph/node.cpp
Labels: Fully Reviewed

#3587 Changed main cmake script
  CMakeLists.txt
  cmake/Modules/git_tags.cmake
  src/ngraph/CMakeLists.txt
Labels: Fully Reviewed, High Priority

#3726 Don't use get_argument in ops.
  src/ngraph/op/experimental/layers/interpolate.cpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/quantized_convolution.hpp
  src/ngraph/op/quantized_dot.hpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
Labels: Fully Reviewed, High Priority

#3716 Cyphers/26mig [MLIR]
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  src/ngraph/runtime/cpu/kernel/gather.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/gather_nd.hpp
  test/backend/gather.in.cpp
Labels: Fully Reviewed

#3729 Cyphers/26mlir [MLIR]
  test/backend/gather.in.cpp
Labels: Fully Reviewed

#3717 Fix description of path_join functions
  src/ngraph/file_util.hpp
Labels: Fully Reviewed

#3725 Added power constant folding
  src/ngraph/pass/constant_folding_binary.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3558 Remove Intel GPU backend
  CMakeLists.txt
  cmake/external_cldnn.cmake
  src/ngraph/runtime/CMakeLists.txt
  src/ngraph/runtime/intelgpu/CMakeLists.txt
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend_visibility.hpp
  src/ngraph/runtime/intelgpu/intelgpu_executable.cpp
  src/ngraph/runtime/intelgpu/intelgpu_executable.hpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_broadcast.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_convolution.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_func_call.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.hpp
  src/ngraph/runtime/intelgpu/intelgpu_op_softmax.cpp
  src/ngraph/runtime/intelgpu/intelgpu_tensor_view.cpp
  src/ngraph/runtime/intelgpu/intelgpu_tensor_view.hpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/visualize_tree.cpp
  src/ngraph/runtime/intelgpu/visualize_tree.hpp
  src/tools/nbench/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#3713 DynSlice op: fix for JIRA: NGRAPH-3437 bug
  src/ngraph/validation_util.cpp
  test/type_prop/dyn_slice.cpp
Labels: Fully Reviewed

#3734 Migrate PR#3710 from master.
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: Fully Reviewed

#3670 [SPEC] Implement Pad:v1 downgrade pass
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/pad.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset0_downgrade.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  test/opset_pass/pad_opset_pass.cpp
  test/type_prop/pad.cpp
Labels: Fully Reviewed, SPEC

#3709 Switch op dynamic casts that crept back in
  src/ngraph/op/gather.cpp
  src/ngraph/op/reshape.hpp
  src/ngraph/op/reverse.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
Labels: Fully Reviewed

#3735 Migrate PR#3638 from master.
  src/ngraph/runtime/cpu/builder/add.cpp
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/leaky_relu.cpp
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/builder/quantized_dot.cpp
  src/ngraph/runtime/cpu/builder/quantized_matmul.cpp
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_invoke.cpp
  src/ngraph/runtime/cpu/mkldnn_invoke.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
Labels: Fully Reviewed

#3739 Fixed typo in v1::AvgPool constructor
  src/ngraph/op/avg_pool.cpp
Labels: Fully Reviewed

#3687 add get_preferred_pipeline_depth to executable
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
Labels: Fully Reviewed

#3747 add get_preferred_pipeline_depth to executable
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
Labels: Fully Reviewed

#3750 [r0.26] Add Softmax::validate_and_infer_types
  src/ngraph/op/softmax.cpp
  src/ngraph/op/softmax.hpp
Labels: Bug, Fully Reviewed, High Priority

#3743 Fix a bug in Gather Eigen kernel.
  src/ngraph/runtime/cpu/kernel/gather.hpp
Labels: Bug, Fully Reviewed, High Priority, IntelCPU

#3689 Modify convert op to convert from bf16 to float and vice-versa
  src/ngraph/runtime/cpu/builder/convert.cpp
  src/ngraph/runtime/cpu/kernel/convert.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/convert.in.cpp
  test/cpu_test.cpp
  test/util/float_util.cpp
  test/util/float_util.hpp
Labels: Fully Reviewed

#3752 Make Constant an op
  src/ngraph/op/constant.hpp
Labels: Fully Reviewed

#3738 Move annotations from Op to Node
  src/ngraph/node.hpp
  src/ngraph/op/op.hpp
Labels: Fully Reviewed

#3707 [SPEC] Implement Reverse:v1 downgrade pass
  src/ngraph/op/reverse.cpp
  src/ngraph/op/reverse.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  test/opset_pass/reverse_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3746 Use static casts for ops in serializer since type is known.
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3714 Fix version module and add latest release notes; update some doc indexes and menus
  doc/sphinx/ngraph_theme/layout.html
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/core/constructing-graphs/index.rst
  doc/sphinx/source/core/fusion/index.rst
  doc/sphinx/source/core/fusion/overview.rst
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/core/passes/passes-that-use-matcher.rst
  doc/sphinx/source/core/passes/passes.rst
  doc/sphinx/source/frameworks/fw_overview.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/onnx_integ.rst
  doc/sphinx/source/frameworks/other.rst
  doc/sphinx/source/frameworks/overview.rst
  doc/sphinx/source/frameworks/paddle_integ.rst
  doc/sphinx/source/frameworks/quickstart.rst
  doc/sphinx/source/frameworks/tensorflow_connect.rst
  doc/sphinx/source/frameworks/validated/list.rst
  doc/sphinx/source/graphics/ExecutionInterfaceRunGraphs.png
  doc/sphinx/source/graphics/PaddlePaddleDir.svg
  doc/sphinx/source/graphics/execution-interface.png
  doc/sphinx/source/graphics/nGraphCompilerstack.png
  doc/sphinx/source/index.rst
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/ops/max.rst
  doc/sphinx/source/ops/min.rst
  doc/sphinx/source/project/contribution-guide.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/sitemap.rst
Labels: Documentation, Fully Reviewed

#3754 Change shared_ptr<Node> to Output<Node> for AvgPoolBackprop
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
Labels: Fully Reviewed, High Priority

#3744 Migrate #3743 from r0.26.
  src/ngraph/runtime/cpu/kernel/gather.hpp
Labels: Fully Reviewed, IntelCPU

#3745 Migrate #3736 from master.
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/pad.cpp
  src/ngraph/runtime/cpu/kernel/pad.hpp
Labels: Fully Reviewed, IntelCPU

#3742 Implements proveance tag propagation for reshape sinking pass
  src/ngraph/pass/reshape_sinking.cpp
Labels: Fully Reviewed

#3749 Add Softmax::validate_and_infer_types
  src/ngraph/op/softmax.cpp
  src/ngraph/op/softmax.hpp
Labels: Bug, Fully Reviewed

#3748 [MLIR] Change order of dot operation loop nest
  src/contrib/mlir/compiler/lowerer.cpp
  test/mlir/affine_conversion/core_ops.mlir
Labels: Fully Reviewed

#3753 Bump MLIR version
  cmake/external_mlir.cmake
  src/contrib/mlir/compiler/compiler.cpp
  src/contrib/mlir/tools/ngraph-opt/ngraph_opt.cpp
  test/backend/dot.in.cpp
Labels: Fully Reviewed

#3676 [SPEC] Implement ReduceSum:v1 and ReduceProd:v1 downgrade pass
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/norm.hpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/op/fused/normalize_l2.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/fused_op.in.cpp
  test/opset_pass/product_opset_pass.cpp
  test/opset_pass/sum_opset_pass.cpp
  test/ref_generators/generate_normalize_l2_ref.py
  test/type_prop/normalize.cpp
Labels: Fully Reviewed, SPEC

#3601 Make softmax axes dynamic
  src/ngraph/op/softmax.cpp
  src/ngraph/op/softmax.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/serializer.cpp
  test/backend/softmax.in.cpp
Labels: Fully Reviewed

#3425 [Py] Added operators GroupConvolution and RNNCell to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/group_conv.cpp
  python/pyngraph/ops/fused/group_conv.hpp
  python/pyngraph/ops/fused/rnn_cell.cpp
  python/pyngraph/ops/fused/rnn_cell.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3692 [ONNX] Add Expand op to ONNX importer.
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/expand.cpp
  src/ngraph/frontend/onnx_import/op/expand.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  test/models/onnx/expand_static_shape.prototxt
  test/onnx/onnx_import_reshape.in.cpp
Labels: Fully Reviewed, ONNX

#3755 Unify test names for opset transformation passes
  test/opset_pass/convolution_opset_pass.cpp
  test/opset_pass/dyn_reshape_opset_pass.cpp
  test/opset_pass/gather_opset_pass.cpp
  test/opset_pass/pad_opset_pass.cpp
  test/opset_pass/poolings_opset_pass.cpp
  test/opset_pass/reverse_opset_pass.cpp
  test/opset_pass/softmax_opset_pass.cpp
  test/opset_pass/topk_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3758 NullNode isn't part of npgraph core library
  src/ngraph/frontend/onnx_import/core/null_node.hpp
Labels: Fully Reviewed

#3736 Use Eigen kernel for REFLECT mode Pad.
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/pad.cpp
  src/ngraph/runtime/cpu/kernel/pad.hpp
Labels: Fully Reviewed, IntelCPU

#3765 Set the bigobj compilation flag for MSVC
  CMakeLists.txt
Labels: Fully Reviewed, High Priority

#3580 [Py] Changed argument type in fake_quantize op.
  python/pyngraph/ops/fused/fake_quantize.cpp
Labels: Fully Reviewed

#3684 Add support for ONNX 1.5 version of TopK
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/op/topk.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/models/onnx/top_k_opset_10.prototxt
  test/models/onnx/top_k_opset_10_const_k.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3770 Support construction of fused ops with partial shapes
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/util/fused_op.cpp
  test/build_graph.cpp
Labels: Fully Reviewed

#3702 Create a variant schema and allow nodes to have a rt info
  src/ngraph/CMakeLists.txt
  src/ngraph/node.hpp
  src/ngraph/variant.cpp
  src/ngraph/variant.hpp
  test/op.cpp
Labels: Fully Reviewed

#3769 Callback for writing events
  src/ngraph/event_tracing.cpp
  src/ngraph/event_tracing.hpp
  test/event_tracing.cpp
Labels: Fully Reviewed

#3773 Added op annotations to cloned function
  src/ngraph/graph_util.cpp
  test/util.cpp
Labels: Fully Reviewed

#3737 [SPEC] Added support for v1 Broadcast op specification
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/broadcast.hpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/dyn_broadcast.in.cpp
  test/opset_pass/broadcast_opset_pass.cpp
  test/type_prop/broadcast.cpp
Labels: Fully Reviewed, High Priority, SPEC

#3771 [ONNX] Add support for ONNX 1.6 TopK
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/op/topk.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/models/onnx/top_k_opset_11_const_k_smallest.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3782 Check for element-wise equality at construction and simplify zero/one…
  src/ngraph/graph_util.cpp
  src/ngraph/op/constant.hpp
Labels: Fully Reviewed

#3785 Check for element-wise equality at construction and simplify zero/one…
  src/ngraph/graph_util.cpp
  src/ngraph/op/constant.hpp
Labels: Fully Reviewed

#3526 Make axis for TopK dynamic
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3760 [SPEC] Support auto broadcast in FakeQuantize op
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/fake_quantize.hpp
  src/ngraph/op/util/broadcasting.cpp
  src/ngraph/op/util/broadcasting.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/fused_op.in.cpp
  test/type_prop/fake_quantize.cpp
Labels: Fully Reviewed, SPEC

#3784 Add support for Fused ops to transformation passes
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
Labels: Fully Reviewed

#3792 Add provenance for const in softmax
  src/ngraph/op/softmax.cpp
Labels: Fully Reviewed

#3721 Remove check in get_argument because function uses new method to get Node
  src/ngraph/node.cpp
Labels: Fully Reviewed

#3774 AvgPoolBprop dynamic shape support
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/pool.in.cpp
  test/opset_pass/avg_pool_opset_pass.cpp
Labels: Fully Reviewed

#3638 Check size of scratchpad before allocating memory and creating scratchpad.
  src/ngraph/runtime/cpu/builder/add.cpp
  src/ngraph/runtime/cpu/builder/avg_pool.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/bounded_relu.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/leaky_relu.cpp
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/builder/quantized_conv.cpp
  src/ngraph/runtime/cpu/builder/quantized_dot.cpp
  src/ngraph/runtime/cpu/builder/quantized_matmul.cpp
  src/ngraph/runtime/cpu/builder/relu.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/builder/sigmoid.cpp
  src/ngraph/runtime/cpu/builder/slice.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_invoke.cpp
  src/ngraph/runtime/cpu/mkldnn_invoke.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
Labels: Fully Reviewed, IntelCPU

#3776 [Spec] Donwgrade for Convolution op
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/op/convolution.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  test/opset_pass/convolution_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3795 add serialize_types and deserialize_types API
  src/ngraph/serializer.cpp
  src/ngraph/serializer.hpp
  test/serialize.cpp
Labels: Fully Reviewed

#3595 [FUSED] Add lstm sequence operator
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/lstm_sequence.cpp
  src/ngraph/op/fused/lstm_sequence.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/type_prop/lstm_sequence.cpp
Labels: Fully Reviewed, SPEC

#3793 Debug cleanup when running unit tests
  test/algebraic_simplification.cpp
  test/backend_api.cpp
  test/cpu_fusion.cpp
  test/pass.cpp
  test/pass_memory_layout.cpp
  test/reshape_sinking.cpp
  test/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#3675 [MLIR] Modify mlir subgraph extraction pass.
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.hpp
Labels: Fully Reviewed

#3798 [PY] Add check if pointer in capsule contains a nullptr
  python/pyngraph/function.cpp
Labels: Fully Reviewed

#3788 [SPEC] Implement MaxPool:v1 and AvgPool:v1 downgrade pass
  src/ngraph/frontend/onnx_import/op/average_pool.cpp
  src/ngraph/frontend/onnx_import/op/global_average_pool.cpp
  src/ngraph/frontend/onnx_import/op/global_max_pool.cpp
  src/ngraph/frontend/onnx_import/op/max_pool.cpp
  src/ngraph/frontend/onnx_import/utils/pooling_factory.cpp
  src/ngraph/frontend/onnx_import/utils/pooling_factory.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  test/CMakeLists.txt
  test/backend/pool.in.cpp
  test/opset_pass/avg_pool_opset_pass.cpp
  test/opset_pass/poolings_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3797 Fixed paths for python build
  python/CMakeLists.txt
  python/build_wheel.sh.in
Labels: Fully Reviewed

#3779 Support for v1 GenerateMask op ( dynamic shape )
  src/ngraph/op/experimental/generate_mask.cpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/generate_mask.in.cpp
  test/opset_pass/generate_mask_opset_pass.cpp
Labels: Fully Reviewed

#3756 Updated nGraph backend unit tests to be compatible with OpenVINO plugins
  test/CMakeLists.txt
  test/util/CMakeLists.txt
  test/util/backend_utils.cpp
  test/util/backend_utils.hpp
  test/util/test_control.hpp
Labels: Fully Reviewed

#3806 Fix mac clang compiler error
  src/ngraph/op/fused/lstm_sequence.hpp
Labels: Bug, Fully Reviewed

#3759 Add partial slice fused op for pdpd use
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/partial_slice.cpp
  src/ngraph/op/fused/partial_slice.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/executable.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/partial_slice.in.cpp
Labels: Fully Reviewed

#3805 Fix some copyright dates
  src/ngraph/op/reduce_mean.cpp
  src/ngraph/op/reduce_mean.hpp
  src/ngraph/runtime/chrome_trace.cpp
  src/ngraph/runtime/chrome_trace.hpp
Labels: Fully Reviewed

#3794 Add constant folding for Squeeze and Unsqueeze.
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_squeeze.cpp
  src/ngraph/pass/constant_folding_unsqueeze.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, IntelCPU

#3791 Add constant folding for v1 reduce ops.
  src/ngraph/ngraph.hpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/runtime/reference/mean.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3790 Added auto generated configs for nGraph
  CMakeLists.txt
  cmake/share/ngraphConfig.cmake.in
  src/ngraph/CMakeLists.txt
Labels: Fully Reviewed

#3708 Concat operator, negative indexing support
  src/ngraph/op/concat.cpp
  src/ngraph/op/concat.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/runtime/cpu/kernel/concat.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/reference/concat.hpp
  test/backend/concat.in.cpp
Labels: Fully Reviewed

#3669 Softmax + cross Entropy fusion for numerical Stabilization
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/softmax_crossentropy.cpp
  src/ngraph/op/fused/softmax_crossentropy.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/core_fusion.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/serializer.cpp
  test/core_fusion.cpp
  test/models/paddlepaddle/ngraph-paddlepaddle-bprop0.json
  test/models/paddlepaddle/ngraph-paddlepaddle-bprop1.json
  test/models/paddlepaddle/ngraph-paddlepaddle-function1.json
  test/models/paddlepaddle/ngraph-paddlepaddle-function3.json
Labels: Fully Reviewed

#3807 Don't add nodes we've already seen to the to-do list
  src/ngraph/node.cpp
  test/provenance.cpp
Labels: Bug, Fully Reviewed

#3781 Stubs for Provenance documentation
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/features.rst
  doc/sphinx/source/glossary.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/introduction.rst
  doc/sphinx/source/provenance/index.rst
  doc/sphinx/source/provenance/overview.rst
Labels: Documentation, Fully Reviewed

#3722 [SPEC] Implement StridedSlice:v1
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/slice.hpp
  src/ngraph/op/strided_slice.cpp
  src/ngraph/op/strided_slice.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/strided_slice.in.cpp
  test/opset_pass/slice_opset_pass.cpp
  test/serialize.cpp
  test/type_prop/strided_slice.cpp
Labels: Fully Reviewed, SPEC

#3786 [MLIR] MLIR Compiler refactoring
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/backend/backend.hpp
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/cpu/cpu_backend.hpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.hpp
  src/contrib/mlir/backend/pass/memory_optimization.cpp
  src/contrib/mlir/backend/pass/memory_optimization.hpp
  src/contrib/mlir/backend/pass/op_lowerers.inc
  src/contrib/mlir/compiler/CMakeLists.txt
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/compiler.hpp
  src/contrib/mlir/core/ngraph_dialect/dialect.cpp
  src/contrib/mlir/core/ngraph_dialect/dialect.hpp
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.hpp
  src/contrib/mlir/core/ngraph_dialect/ops.td
  src/contrib/mlir/core/ngraph_dialect/type.cpp
  src/contrib/mlir/core/ngraph_dialect/type.hpp
  src/contrib/mlir/core/ops_supported.inc
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.hpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.hpp
  src/contrib/mlir/runtime/cpu/memory_manager.cpp
  src/contrib/mlir/runtime/cpu/memory_manager.hpp
  src/contrib/mlir/runtime/runtime.hpp
  src/contrib/mlir/tools/ngraph-opt/ngraph_opt.cpp
  src/contrib/mlir/utils.cpp
  src/contrib/mlir/utils.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/mlir_cpu_compiled_kernel.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
Labels: Fully Reviewed

#3800 [SPEC] Adjust Tile op to the new specification
  src/ngraph/op/experimental/tile.cpp
  src/ngraph/op/experimental/tile.hpp
  src/ngraph/runtime/cpu/builder/tile.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/CMakeLists.txt
  test/backend/tile.in.cpp
  test/type_prop/tile.cpp
Labels: Fully Reviewed, SPEC

#3814 Support constant folding on V1 broadcast ops
  src/ngraph/pass/constant_folding_broadcast.cpp
  test/constant_folding.cpp
Labels: High Priority

#3751 [SPEC] Implement Reshape downgrade pass
  src/ngraph/op/reshape.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  test/CMakeLists.txt
  test/backend/dyn_reshape.in.cpp
  test/opset_pass/dyn_reshape_opset_pass.cpp
Labels: Fully Reviewed, SPEC

#3804 [Spec] Adjust PriorBoxClustered to specification
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.hpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed, SPEC

#3810 [MLIR] Graph pass to lower standardDialect to llvm module
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/cpu/cpu_backend.hpp
Labels: Fully Reviewed

#3817 Show more info in convert type error
  src/ngraph/runtime/cpu/builder/convert.cpp
Labels: Fully Reviewed

#3825 Missing forward declaration
  src/ngraph/partial_shape.hpp
Labels: Fully Reviewed

#3815 Fixed python build for some debug configurations
  python/CMakeLists.txt
  python/setup.py
Labels: Fully Reviewed

#3821 [ONNX] Add optional input C in gemm op.
  src/ngraph/frontend/onnx_import/op/gemm.cpp
Labels: Fully Reviewed, ONNX

#3787 CPU implementation of Gelu op
  python/test/ngraph/test_ops_fused.py
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/gelu.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_invoke.cpp
  src/ngraph/runtime/cpu/mkldnn_invoke.hpp
  src/ngraph/runtime/cpu/op/gelu_backprop.cpp
  src/ngraph/runtime/cpu/op/gelu_backprop.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  test/backend/gelu.in.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#3833 Constant folding support for V1 Reshape
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  test/constant_folding.cpp
Labels: High Priority
