Repository NervanaSystems/ngraph, pull requests merged in 2019-06, with the labels that each got.

#3004 [nbench] Avoid negative values in int64 initialization
  src/tools/nbench/benchmark.cpp
Labels: Fully Reviewed

#2967 Cyphers/noarg1
  src/ngraph/descriptor/input.cpp
  src/ngraph/descriptor/input.hpp
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/abs.cpp
  src/ngraph/op/abs.hpp
  src/ngraph/op/acos.cpp
  src/ngraph/op/acos.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/all.cpp
  src/ngraph/op/all.hpp
  src/ngraph/op/allreduce.cpp
  src/ngraph/op/allreduce.hpp
  src/ngraph/op/and.cpp
  src/ngraph/op/and.hpp
  src/ngraph/op/any.cpp
  src/ngraph/op/any.hpp
  src/ngraph/op/argmax.cpp
  src/ngraph/op/argmax.hpp
  src/ngraph/op/argmin.cpp
  src/ngraph/op/argmin.hpp
  src/ngraph/op/asin.cpp
  src/ngraph/op/asin.hpp
  src/ngraph/op/atan.cpp
  src/ngraph/op/atan.hpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/op.cpp
  src/ngraph/op/op.hpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/arithmetic_reduction.hpp
  src/ngraph/op/util/binary_elementwise_arithmetic.cpp
  src/ngraph/op/util/binary_elementwise_arithmetic.hpp
  src/ngraph/op/util/binary_elementwise_comparison.cpp
  src/ngraph/op/util/binary_elementwise_comparison.hpp
  src/ngraph/op/util/binary_elementwise_logical.cpp
  src/ngraph/op/util/binary_elementwise_logical.hpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/op/util/fused_op.hpp
  src/ngraph/op/util/index_reduction.cpp
  src/ngraph/op/util/index_reduction.hpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/op/util/logical_reduction.hpp
  src/ngraph/op/util/unary_elementwise_arithmetic.cpp
  src/ngraph/op/util/unary_elementwise_arithmetic.hpp
  test/build_graph.cpp
  test/util.cpp
Labels: Fully Reviewed

#2995 [Doc] Fix doc for reshape utility functions.
  src/ngraph/builder/reshape.hpp
  src/ngraph/op/util/reshape.hpp
Labels: Documentation, Fully Reviewed

#2999 Handle 0 and -1 in shape inputs for dynamic reshape op
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_reshape.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3016 Reshape elimination optimization
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
  test/reshape_elimination.cpp
Labels: Fully Reviewed

#3019 Added getters for dynslice
  src/ngraph/op/experimental/dyn_slice.hpp
Labels: Fully Reviewed

#3002 Use Eigen kernel for ScatterAdd.
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/scatter_add.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_scatter.in.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed, High Priority, IntelCPU

#3020 Fix klocwork issues
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/util/index_reduction.hpp
  src/ngraph/pass/implicit_broadcast_elimination.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/reference/scatter_add.hpp
  src/ngraph/runtime/reference/scatter_nd_add.hpp
Labels: Fully Reviewed, High Priority

#3003 Fix so you can build with NGRAPH_JSON_ENABLE=OFF
  python/test/ngraph/test_basic.py
  src/ngraph/serializer.hpp
  test/backend_api.cpp
Labels: Fully Reviewed, High Priority

#2996 Add BatchMatMul unit test to all builds
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  test/autodiff.in.cpp
  test/backend_test.in.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, Merge Blocked

#2979 Remove tensor offset from tensor read/write calls because it was never used
  changes.md
  python/ngraph/runtime.py
  python/pyngraph/runtime/tensor.cpp
  python/test/test_ops.py
  src/ngraph/frontend/onnxifi/tensor.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.hpp
  src/ngraph/runtime/gpu/gpu_tensor.cpp
  src/ngraph/runtime/gpu/gpu_tensor.hpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/host_tensor.hpp
  src/ngraph/runtime/hybrid/hybrid_tensor.cpp
  src/ngraph/runtime/hybrid/hybrid_tensor.hpp
  src/ngraph/runtime/intelgpu/intelgpu_executable.cpp
  src/ngraph/runtime/intelgpu/intelgpu_tensor_view.cpp
  src/ngraph/runtime/intelgpu/intelgpu_tensor_view.hpp
  src/ngraph/runtime/plaidml/plaidml_tensor.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.hpp
  src/ngraph/runtime/tensor.cpp
  src/ngraph/runtime/tensor.hpp
  src/tools/nbench/benchmark.cpp
  test/backend_graph_comparison.in.cpp
  test/tensor.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Changes API, Fully Reviewed

#3022 Add support for ArgMin and ArgMax to ZeroDimTensorElimination
  src/ngraph/op/argmax.cpp
  src/ngraph/op/argmax.hpp
  src/ngraph/op/argmin.cpp
  src/ngraph/op/argmin.hpp
  src/ngraph/op/util/index_reduction.cpp
  test/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#3023 Use updated reduced-size clDNN
  cmake/external_cldnn.cmake
Labels: High Priority

#3014 Use Eigen kernel for Gather when axis is 0.
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/gather.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_gather.in.cpp
Labels: Fully Reviewed, IntelCPU

#3017 Unified interpolate layer op
  src/ngraph/op/experimental/layers/detection_output.cpp
  src/ngraph/op/experimental/layers/detection_output.hpp
  src/ngraph/op/experimental/layers/interpolate.cpp
  src/ngraph/op/experimental/layers/interpolate.hpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box.hpp
  src/ngraph/op/experimental/layers/proposal.hpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed

#3028 Use convolution_direct algo
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
Labels: High Priority

#3026 Fix bug with serialization of zero-element constants
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#2991 layout aware "copy_from" for cpu tensor
  src/ngraph/runtime/cpu/cpu_tensor_view.cpp
  src/ngraph/runtime/cpu/cpu_tensor_view.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#3033 Change for better user experience with json option
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/serialize.cpp
  src/ngraph/runtime/cpu/cpu_tracing.cpp
  src/ngraph/runtime/cpu/cpu_tracing.hpp
  src/ngraph/serializer.hpp
  test/backend_api.cpp
  test/backend_broadcast.in.cpp
  test/backend_test.in.cpp
  test/control_dependencies.cpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
  test/gpu_fusion.cpp
  test/reshape_elimination.cpp
  test/reshape_sinking.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#3039 Added float16 support for constant op
  src/ngraph/builder/make_constant.hpp
Labels: Fully Reviewed

#2822 Build option to disable fast math
  CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#3046 Minor change to proposal op validation and change to codeowners
  CODEOWNERS
  src/ngraph/op/experimental/layers/proposal.cpp
Labels: Fully Reviewed

#2977 Add CPU backend support for Tile op using Eigen kernel.
  src/ngraph/op/experimental/tile.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/tile.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/tile.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed, IntelCPU

#3041 Friendlier graph visualization
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pass/visualize_tree.hpp
  src/ngraph/serializer.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#3018 Test messages improvements
  test/util/all_close.hpp
  test/util/all_close_f.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#3035 add dynamic state check for node_pass to skip optimization
  src/ngraph/pass/manager.cpp
Labels: Fully Reviewed

#3029 GenerateMask correction
  CMakeLists.txt
  src/ngraph/op/experimental/generate_mask.cpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/runtime/cpu/builder/state.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/generate_mask.hpp
  src/ngraph/serializer.cpp
  test/backend_test.in.cpp
Labels: Fully Reviewed

#3030 Update PlaidML backend for current nGraph
  src/ngraph/pass/prefix_reshape_elimination.cpp
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_executable.cpp
  src/ngraph/runtime/plaidml/plaidml_executable.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_convolution.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_implicit_broadcast.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_tensor.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/tools/ngraph-to-plaidml/ngraph-to-plaidml.cpp
Labels: Fully Reviewed, PlaidML

#3034 Change behavior of elementwise divide for integral type to match Python.
  src/ngraph/op/divide.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/kernel/divide.hpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/divide.hpp
  src/ngraph/serializer.cpp
  test/backend_binary_elementwise.in.cpp
Labels: Bug, Fully Reviewed

#3049 IntelGPU backend: Switch to new clDNN: Fixed _GLIBCXX_USE_CXX11_ABI redifinition error during ngraph-bridge build
  cmake/external_cldnn.cmake
Labels: Bug, Fully Reviewed, High Priority, IntelGPU, Release

#3012 [ONNX] Add ConvInteger op
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/conv_integer.cpp
  src/ngraph/frontend/onnx_import/op/conv_integer.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/conv_integer.prototxt
  test/models/onnx/conv_integer_no_zero_point.prototxt
  test/models/onnx/conv_integer_pads.prototxt
  test/onnx/onnx_import_quant.in.cpp
Labels: Fully Reviewed, ONNX

#3027 Added support for ceil mode in AvgPool
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/serializer.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3057 Backward compatibility for GenerateMask deserialize
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3059 [ONNX CI] Disable incremental building
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/prepare_environment.sh
Labels: Bug, Fully Reviewed, High Priority, ONNX

#2972 Change reduction operations to 2-input dynamic variants
  src/ngraph/axis_set.hpp
  src/ngraph/op/all.cpp
  src/ngraph/op/all.hpp
  src/ngraph/op/any.cpp
  src/ngraph/op/any.hpp
  src/ngraph/op/max.cpp
  src/ngraph/op/max.hpp
  src/ngraph/op/min.cpp
  src/ngraph/op/min.hpp
  src/ngraph/op/product.cpp
  src/ngraph/op/product.hpp
  src/ngraph/op/sum.cpp
  src/ngraph/op/sum.hpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/arithmetic_reduction.hpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/op/util/logical_reduction.hpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/hybrid/hybrid_util.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  test/backend_all.in.cpp
  test/copy.cpp
Labels: High Priority

#3051 Change hybrid to static library
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/hybrid/hybrid_backend.cpp
  src/ngraph/runtime/hybrid/hybrid_backend.hpp
  src/ngraph/runtime/hybrid/hybrid_executable.cpp
  src/ngraph/runtime/hybrid/hybrid_executable.hpp
  src/ngraph/runtime/hybrid/hybrid_tensor.cpp
  src/ngraph/runtime/hybrid/hybrid_tensor.hpp
  src/ngraph/runtime/hybrid/hybrid_util.cpp
  src/ngraph/runtime/hybrid/hybrid_util.hpp
  src/ngraph/runtime/hybrid/op/function_call.cpp
  src/ngraph/runtime/hybrid/op/function_call.hpp
  src/ngraph/runtime/hybrid/op/op_tbl.hpp
  src/ngraph/runtime/hybrid/pass/default_placement.cpp
  src/ngraph/runtime/hybrid/pass/default_placement.hpp
  src/ngraph/runtime/hybrid/pass/dump.cpp
  src/ngraph/runtime/hybrid/pass/dump.hpp
  src/ngraph/runtime/hybrid/pass/fix_get_output_element.cpp
  src/ngraph/runtime/hybrid/pass/fix_get_output_element.hpp
  src/ngraph/runtime/hybrid/pass/liveness.cpp
  src/ngraph/runtime/hybrid/pass/liveness.hpp
  src/ngraph/runtime/hybrid/pass/memory_layout.cpp
  src/ngraph/runtime/hybrid/pass/memory_layout.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/node_wrapper.cpp
  src/ngraph/runtime/interpreter/node_wrapper.hpp
  test/CMakeLists.txt
Labels: Fully Reviewed

#3047 Add copy of friendly name to ngraph::copy_function
  src/ngraph/graph_util.cpp
  test/util.cpp
Labels: Fully Reviewed

#3066 Reduce all avijits from codeowners
  CODEOWNERS
Labels: Fully Reviewed

#3067 Klocwork
  src/ngraph/op/topk.hpp
Labels: Fully Reviewed, High Priority

#3006 Fuse Dropout
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/dropout.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_executor.cpp
  src/ngraph/runtime/cpu/cpu_executor.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/dropout.hpp
  src/ngraph/runtime/cpu/op/dropout.cpp
  src/ngraph/runtime/cpu/op/dropout.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, High Priority

#3063 IntelGPU backend: Change clDNN hash version to release tag
  cmake/external_cldnn.cmake
Labels: Fully Reviewed, High Priority, IntelGPU, Release

#3061 Add execution tests for dynamic reduction ops; fix validation logic
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/arithmetic_reduction.hpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/op/util/logical_reduction.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/dynamic.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3058 Fix of the CI reproduction script
  .ci/onnx/jenkins/README.md
  .ci/onnx/jenkins/runCI.sh
Labels: Fully Reviewed, High Priority

#3025 Use Eigen kernel for Gather for any axis value.
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_kernels.hpp
  src/ngraph/runtime/cpu/kernel/gather.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend_gather.in.cpp
Labels: Fully Reviewed, IntelCPU

#3062 Add DynElimination for DynBroadcast
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/dyn_elimination.hpp
  test/dynamic.in.cpp
Labels: Fully Reviewed

#3024 [ONNX] Shrink op support
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/shrink.cpp
  src/ngraph/frontend/onnx_import/op/shrink.hpp
  src/ngraph/frontend/onnx_import/op/supported_ops.md
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/shrink_float.prototxt
  test/models/onnx/shrink_int.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#3037 Added missing attribute to Result serialization
  src/ngraph/op/result.cpp
  src/ngraph/op/result.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3069 Use all args for dropout
  src/ngraph/runtime/cpu/builder/dropout.cpp
  src/ngraph/runtime/cpu/op/dropout.cpp
  src/ngraph/runtime/cpu/op/dropout.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed

#3070 Set CMAKE_INSTALL_RPATH_USE_LINK_PATH
  CMakeLists.txt
Labels: Fully Reviewed, PlaidML

#3072 add tests to plaidml unit test manifest -- to triage
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed

#3040 [FUSED] Group Transpose Convolution
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/group_conv_transpose.cpp
  src/ngraph/op/fused/group_conv_transpose.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3064 Test Case: use expected shape, not computed output shape
  test/util/test_case.hpp
Labels: Fully Reviewed

#3078 [Py] Fix of the 'test_sum' test for the CPU backend
  python/test/test_ops.py
Labels: Fully Reviewed

#2966 [Fused Op] LSTMCell
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/utils/rnn/activation_functions.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/lstm_cell.hpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/util/activation_functions.cpp
  src/ngraph/op/util/activation_functions.hpp
  src/ngraph/op/util/rnn_cell_base.cpp
  src/ngraph/op/util/rnn_cell_base.hpp
  src/ngraph/runtime/gpu/gpu_compiled_function.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/serializer.cpp
  test/backend_fused_op.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3089 Backport #3080 from r0.22
  cmake/external_mkldnn.cmake
Labels: Fully Reviewed

#3092 Migrate PR#3090 from master.
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#3096 This gets all compile-time flag use into cpp files rather than headers
  src/ngraph/CMakeLists.txt
  src/ngraph/serializer.hpp
  src/ngraph/serializer_stub.cpp
Labels: Fully Reviewed

#3083 Move GroupConv and Slice op to output-handle based constructors
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/slice.cpp
  src/ngraph/op/slice.hpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/op/util/fused_op.hpp
  test/build_graph.cpp
Labels: Fully Reviewed

#3097 Cyphers/mergeser
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, High Priority

#3094 Enable Gather and ScatterAdd to use Eigen kernel for int8 type.
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/kernel/gather.hpp
  test/backend_scatter.in.cpp
Labels: Fully Reviewed, IntelCPU

#3048 Support arbitrary reduction op
  src/ngraph/distributed.cpp
  src/ngraph/distributed.hpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/null.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/op/allreduce.cpp
  src/ngraph/op/allreduce.hpp
  src/ngraph/runtime/cpu/builder/allreduce.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/allreduce.hpp
  test/distributed.in.cpp
Labels: Fully Reviewed

#3095 Modify check_inputs for unit tests with PlaidML backend
  src/ngraph/runtime/plaidml/plaidml_impl.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed

#3086 [Py] Fix of the failing tests: test_unary_op_array & test_unary_op_scalar
  python/test/ngraph/test_ops_unary.py
Labels: Fully Reviewed

#3085 [Py] Enable INTELGPU backend for python tests
  python/test/conftest.py
  python/test/test_ops.py
Labels: Fully Reviewed, IntelGPU, Merge Blocked

#3090 Modify QuantizedConvolutionBias(Signed)Add fusion.
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#3102 Serialization/deserialization of node inputs connected directly to a non-zero node output
  src/ngraph/serializer.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#3081 Normalize license header
  .ci/onnx/jenkins/Jenkinsfile
  .ci/onnx/jenkins/utils/utils.groovy
  src/ngraph/builder/quantization/quantized_linear_matmul.cpp
  src/ngraph/builder/quantization/quantized_linear_matmul.hpp
  src/ngraph/event_tracing.cpp
  src/ngraph/event_tracing.hpp
  src/ngraph/frontend/onnx_import/op/concat.cpp
  src/ngraph/frontend/onnx_import/op/concat.hpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/flatten.hpp
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/op/onehot.hpp
  src/ngraph/frontend/onnx_import/op/reshape.cpp
  src/ngraph/frontend/onnx_import/op/reshape.hpp
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.hpp
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  src/ngraph/frontend/onnx_import/op/unsqueeze.hpp
  src/ngraph/frontend/onnx_import/utils/matmul_factory.cpp
  src/ngraph/frontend/onnx_import/utils/matmul_factory.hpp
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/op/gather_nd.cpp
  src/ngraph/op/gather_nd.hpp
  src/ngraph/op/scatter_add.cpp
  src/ngraph/op/scatter_add.hpp
  src/ngraph/op/scatter_nd_add.cpp
  src/ngraph/op/scatter_nd_add.hpp
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/gather_nd.cpp
  src/ngraph/runtime/cpu/builder/halide_op.cpp
  src/ngraph/runtime/cpu/builder/loop_kernel.cpp
  src/ngraph/runtime/cpu/builder/scatter_add.cpp
  src/ngraph/runtime/cpu/builder/scatter_nd_add.cpp
  src/ngraph/runtime/cpu/op/halide_op.cpp
  src/ngraph/runtime/cpu/op/halide_op.hpp
  src/ngraph/runtime/cpu/op/quantized_matmul.cpp
  src/ngraph/runtime/cpu/op/quantized_matmul.hpp
  src/ngraph/runtime/cpu/pass/halide_subgraph_extraction.cpp
  src/ngraph/runtime/cpu/pass/halide_subgraph_extraction.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
  src/ngraph/runtime/gpu/op/rnn.cpp
  src/ngraph/runtime/gpu/op/rnn.hpp
  src/ngraph/runtime/reference/gather.hpp
  src/ngraph/runtime/reference/gather_nd.hpp
  src/ngraph/runtime/reference/scatter_add.hpp
  src/ngraph/runtime/reference/scatter_nd_add.hpp
  test/backend_gather.in.cpp
  test/backend_graph_comparison.in.cpp
  test/backend_scatter.in.cpp
  test/event_tracing.cpp
  test/halide.cpp
Labels: Fully Reviewed

#3093 Added mode attributes to DynPad and TopK
  src/ngraph/op/experimental/dyn_pad.cpp
  src/ngraph/op/experimental/dyn_pad.hpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/runtime/reference/pad.hpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3010 Documentation updates for 0.21.0
  CODEOWNERS
  doc/sphinx/conf.py
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/ngraph_theme/static/theme.css
  doc/sphinx/source/_templates/format_release_notes.rst
  doc/sphinx/source/backend-support/tensor-api/index.rst
  doc/sphinx/source/backends/backend-api/index.rst
  doc/sphinx/source/backends/cpp-api.rst
  doc/sphinx/source/backends/executable-api/index.rst
  doc/sphinx/source/backends/hosttensor-api/index.rst
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/backends/plaidml-ng-api/index.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/core/constructing-graphs/derive-for-training.rst
  doc/sphinx/source/core/constructing-graphs/execute.rst
  doc/sphinx/source/core/constructing-graphs/import.rst
  doc/sphinx/source/core/fusion/index.rst
  doc/sphinx/source/core/fusion/overview.rst
  doc/sphinx/source/core/overview.rst
  doc/sphinx/source/frameworks/generic-configs.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/project/doc-contributor-README.rst
  doc/sphinx/source/project/introduction.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/replacements.txt
  doc/sphinx/source/sitemap.rst
  python/BUILDING.md
Labels: Fully Reviewed

#3098 Add (dynamic) Range op
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/experimental/range.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/dyn_elimination.hpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/dyn_elimination.cpp
  test/dynamic.in.cpp
  test/type_prop.cpp
Labels: Fully Reviewed

#3108 Fix unit-test failure in debug mode
  cmake/mkldnn.patch
Labels: Fully Reviewed

#3065 [ONNX] Add support for onnx MeanVarianceNormalization op
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/mean_variance_normalization.cpp
  src/ngraph/frontend/onnx_import/op/mean_variance_normalization.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, ONNX

#3116 [ONNX] Missing validation of the split param for the Split op
  src/ngraph/op/fused/split.cpp
Labels: Fully Reviewed, ONNX

#3105 Use node IDs for comparison when sorting in pattern match.
  src/ngraph/pattern/matcher.cpp
  test/pattern.cpp
Labels: Fully Reviewed

#3110 Initial implementation of backend config
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  test/backend_api.cpp
Labels: Fully Reviewed

#3109 Switch Output to use a shared_ptr to prevent nodes from disappearing early
  src/ngraph/node.hpp
Labels: Fully Reviewed

#3106 Read provenance tags from serialized graph
  src/ngraph/graph_util.cpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3117 Remove static cache in unit test
  test/util/autodiff/backprop_derivative.hpp
Labels: Fully Reviewed

#3111 Eliminate wrapped enum
  src/ngraph/distributed.cpp
  src/ngraph/distributed.hpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/op/allreduce.cpp
  src/ngraph/op/allreduce.hpp
  test/distributed.in.cpp
Labels: Fully Reviewed

#3114 Alphabetize ops
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/op_tbl.hpp
Labels: Fully Reviewed

#3073 Recursive FusedOpDecomposition pass.
  src/ngraph/pass/fused_op_decomposition.cpp
  src/ngraph/pass/fused_op_decomposition.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#3119 More serialization preparation for iteration ops
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3043 Disable caching when node has state.
  src/ngraph/node.hpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed, IntelCPU

#3125 Fix klocwork issues
  src/ngraph/op/fused/group_conv.hpp
Labels: Fully Reviewed

#3126 fix license header again
  cmake/external_tbb_prebuilt.cmake
  doc/sphinx/source/project/doc-contributor-README.rst
  python/pyngraph/ops/broadcast_distributed.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/op/broadcast_distributed.cpp
  src/ngraph/op/broadcast_distributed.hpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/experimental/quantized_concat.hpp
  src/ngraph/pass/prefix_reshape_elimination.cpp
  src/ngraph/runtime/cpu/builder/quantized_concat.cpp
  src/ngraph/runtime/generic_cpu/CMakeLists.txt
  src/ngraph/runtime/generic_cpu/kernel/broadcast.hpp
  src/ngraph/runtime/generic_cpu/kernel/dot.hpp
  src/ngraph/runtime/generic_cpu/kernel/reshape.hpp
  src/ngraph/runtime/generic_cpu/kernel/result.hpp
  src/ngraph/runtime/generic_cpu/node_wrapper.cpp
  src/ngraph/runtime/generic_cpu/node_wrapper.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_convolution.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_replicate.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_replicate.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_winograd.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_winograd.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_concat_elision.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_concat_elision.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_lower_convolutions.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_combination.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_combination.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_replicate_elision.hpp
  src/ngraph/runtime/plaidml/plaidml_pass_winograd.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_winograd.hpp
Labels: Fully Reviewed

#3122 [Fused] Remove redundant conditions.
  src/ngraph/pass/fused_op_decomposition.cpp
Labels: Fully Reviewed

#3107 add send recv op
  src/ngraph/CMakeLists.txt
  src/ngraph/distributed.hpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/null.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/recv.cpp
  src/ngraph/op/recv.hpp
  src/ngraph/op/send.cpp
  src/ngraph/op/send.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/gpuh/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/recv.hpp
  src/ngraph/runtime/reference/send.hpp
  src/ngraph/serializer.cpp
  test/distributed.in.cpp
Labels: High Priority, distributed

#3131 Temporary change to CPU code ownership
  CODEOWNERS
Labels: Fully Reviewed

#3113 Adjust PlaidML test tolerances
  src/ngraph/runtime/gpu/unit_test.manifest
  test/CMakeLists.txt
  test/backend_binary_elementwise.in.cpp
  test/backend_test.in.cpp
  test/backend_unary_elementwise.in.cpp
Labels: Fully Reviewed, High Priority, PlaidML

#3100 use lock_guard to protect the access to m_exec_map in cpu_backend
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
Labels: Fully Reviewed

#3103 Add DynElimination for DynReshape
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/dyn_elimination.hpp
  test/dyn_elimination.cpp
  test/dynamic.in.cpp
Labels: Fully Reviewed

#3140 PlaidML: Disable UT's that require RNN or GRU cell.
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Blocker, Bug, Fully Reviewed, High Priority, PlaidML

#3142 Added a missing guard that is breaking the build
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed, High Priority
