Repository NervanaSystems/ngraph, pull requests merged in 2019-08, with the labels that each got.

#3351 [MLIR] Fix issue with non-affine loads/stores in argmin/armax/gather ops
  src/contrib/mlir/lowerer.cpp
Labels: Fully Reviewed

#3356 ConstantFolding for Range
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/runtime/reference/range.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3357 Switch core ops to type_name description.
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/batch_norm.hpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/pad.hpp
  src/ngraph/op/parameter.cpp
  src/ngraph/op/parameter.hpp
  src/ngraph/op/passthrough.cpp
  src/ngraph/op/passthrough.hpp
  src/ngraph/op/power.cpp
  src/ngraph/op/power.hpp
  src/ngraph/op/relu.cpp
  src/ngraph/op/relu.hpp
  src/ngraph/op/reverse.cpp
  src/ngraph/op/reverse.hpp
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/op/reverse_sequence.hpp
  src/ngraph/op/scatter_add.cpp
  src/ngraph/op/scatter_add.hpp
  src/ngraph/op/scatter_nd_add.cpp
  src/ngraph/op/scatter_nd_add.hpp
  src/ngraph/op/sigmoid.cpp
  src/ngraph/op/sigmoid.hpp
  src/ngraph/op/sign.cpp
  src/ngraph/op/sign.hpp
  src/ngraph/op/sin.cpp
  src/ngraph/op/sin.hpp
  src/ngraph/op/sinh.cpp
  src/ngraph/op/sinh.hpp
  src/ngraph/op/softmax.cpp
  src/ngraph/op/softmax.hpp
  src/ngraph/op/sqrt.cpp
  src/ngraph/op/sqrt.hpp
  src/ngraph/op/stop_gradient.cpp
  src/ngraph/op/stop_gradient.hpp
  src/ngraph/op/tan.cpp
  src/ngraph/op/tan.hpp
  src/ngraph/op/tanh.cpp
  src/ngraph/op/tanh.hpp
Labels: Fully Reviewed

#3358 Convert op/experimental to type_name descriptions
  src/ngraph/op/experimental/batch_mat_mul.cpp
  src/ngraph/op/experimental/batch_mat_mul.hpp
  src/ngraph/op/experimental/compiled_kernel.cpp
  src/ngraph/op/experimental/compiled_kernel.hpp
  src/ngraph/op/experimental/dyn_broadcast.cpp
  src/ngraph/op/experimental/dyn_broadcast.hpp
  src/ngraph/op/experimental/dyn_pad.cpp
  src/ngraph/op/experimental/dyn_pad.hpp
  src/ngraph/op/experimental/dyn_replace_slice.cpp
  src/ngraph/op/experimental/dyn_replace_slice.hpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_reshape.hpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/experimental/dyn_slice.hpp
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.cpp
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.hpp
  src/ngraph/op/experimental/layers/detection_output.cpp
  src/ngraph/op/experimental/layers/detection_output.hpp
  src/ngraph/op/experimental/layers/interpolate.cpp
  src/ngraph/op/experimental/layers/interpolate.hpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box.hpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.hpp
  src/ngraph/op/experimental/layers/proposal.cpp
  src/ngraph/op/experimental/layers/proposal.hpp
  src/ngraph/op/experimental/layers/psroi_pooling.cpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  src/ngraph/op/experimental/layers/region_yolo.cpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
  src/ngraph/op/experimental/layers/reorg_yolo.cpp
  src/ngraph/op/experimental/layers/reorg_yolo.hpp
  src/ngraph/op/experimental/layers/roi_pooling.cpp
  src/ngraph/op/experimental/layers/roi_pooling.hpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/experimental/quantized_concat.hpp
  src/ngraph/op/experimental/shape_of.cpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/op/experimental/tile.cpp
  src/ngraph/op/experimental/tile.hpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/op/experimental/transpose.hpp
Labels: Fully Reviewed

#3360 Transformers don't need to export symbols.
  src/ngraph/runtime/cpu/op/batch_mat_mul_transpose.hpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.hpp
  src/ngraph/runtime/cpu/op/bounded_relu.hpp
  src/ngraph/runtime/cpu/op/conv_add.hpp
  src/ngraph/runtime/cpu/op/conv_relu.hpp
  src/ngraph/runtime/cpu/op/convert_layout.hpp
  src/ngraph/runtime/cpu/op/deconv.hpp
  src/ngraph/runtime/cpu/op/dropout.hpp
  src/ngraph/runtime/cpu/op/group_conv_bias.hpp
  src/ngraph/runtime/cpu/op/halide_op.hpp
  src/ngraph/runtime/cpu/op/leaky_relu.hpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/matmul_bias.hpp
  src/ngraph/runtime/cpu/op/max_pool_with_indices.hpp
  src/ngraph/runtime/cpu/op/quantized_matmul.hpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/op/sigmoid_mul.hpp
  src/ngraph/runtime/cpu/op/update_slice.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_convolution.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_implicit_broadcast.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_replicate.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_winograd.hpp
Labels: Fully Reviewed

#3257 [ONNX] Update ONNX version to 1.5.0
  cmake/external_onnx.cmake
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.cpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnxifi/backend_manager.cpp
  src/ngraph/frontend/onnxifi/backend_manager.hpp
  src/ngraph/frontend/onnxifi/exceptions.hpp
  src/ngraph/frontend/onnxifi/onnxifi.cpp
  src/ngraph/frontend/onnxifi/tensor.hpp
  test/onnx/onnxifi.cpp
Labels: Fully Reviewed, ONNX

#3302 [Py] Added gelu operator to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/gelu.cpp
  python/pyngraph/ops/fused/gelu.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3348 Allow override of default tolerance for NgraphTestCase
  test/backend/fused_op.in.cpp
  test/onnx/onnx_import_rnn.in.cpp
  test/util/test_case.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed

#3361 ConstantFolding for remaining arithmetic/logical reductions
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/runtime/reference/max.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3366 ConstantFolding: Complete element type coverage, and misc cleanup/fixes
  src/ngraph/pass/constant_folding.cpp
Labels: Fully Reviewed

#3367 ConstantFolding for DynBroadcast
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3368 Convert fused ops to description format
  src/ngraph/op/fused/conv_fused.cpp
  src/ngraph/op/fused/conv_fused.hpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/depth_to_space.hpp
  src/ngraph/op/fused/elu.cpp
  src/ngraph/op/fused/elu.hpp
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/fake_quantize.hpp
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/gelu.hpp
  src/ngraph/op/fused/gemm.cpp
  src/ngraph/op/fused/gemm.hpp
  src/ngraph/op/fused/grn.cpp
  src/ngraph/op/fused/grn.hpp
  src/ngraph/op/fused/group_conv_transpose.cpp
  src/ngraph/op/fused/group_conv_transpose.hpp
  src/ngraph/op/fused/gru_cell.cpp
  src/ngraph/op/fused/gru_cell.hpp
  src/ngraph/op/fused/hard_sigmoid.cpp
  src/ngraph/op/fused/hard_sigmoid.hpp
  src/ngraph/op/fused/leaky_relu.cpp
  src/ngraph/op/fused/leaky_relu.hpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/lstm_cell.hpp
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/op/fused/normalize.cpp
  src/ngraph/op/fused/normalize.hpp
  src/ngraph/op/fused/prelu.cpp
  src/ngraph/op/fused/prelu.hpp
  src/ngraph/op/fused/rnn_cell.cpp
  src/ngraph/op/fused/rnn_cell.hpp
  src/ngraph/op/fused/scale_shift.cpp
  src/ngraph/op/fused/scale_shift.hpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/shuffle_channels.hpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.hpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/op/fused/squared_difference.cpp
  src/ngraph/op/fused/squared_difference.hpp
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/squeeze.hpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/fused/unsqueeze.hpp
Labels: Fully Reviewed

#3354 Improve pragma usage.
  src/contrib/mlir/compiler.cpp
  src/ngraph/distributed.cpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/log.cpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/equal.hpp
  src/ngraph/runtime/reference/not_equal.hpp
  src/ngraph/runtime/reference/topk.hpp
  src/ngraph/serializer.cpp
  src/ngraph/type/bfloat16.cpp
  src/ngraph/type/float16.cpp
  src/tools/nbench/benchmark_utils.cpp
  test/backend/distributed.in.cpp
Labels: Fully Reviewed, High Priority

#3352 Add windows symbol export support
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_backend_visibility.hpp
Labels: Fully Reviewed

#3337 NGCORE-526
  CMakeLists.txt
  cmake/Modules/git_tags.cmake
  maint/create_release.py
Labels: Fully Reviewed

#3369 Fix deprecation messages
  src/ngraph/op/util/broadcasting.hpp
Labels: Fully Reviewed

#3370 Remove some get_arguments() uses
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/op/concat.cpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/cse.cpp
  src/ngraph/pass/propagate_cacheability.cpp
Labels: Fully Reviewed

#3363 Add logical xor op
  doc/sphinx/source/ops/index.rst
  doc/sphinx/source/ops/xor.rst
  src/ngraph/CMakeLists.txt
  src/ngraph/ngraph.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/op/xor.cpp
  src/ngraph/op/xor.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/kernel/xor.hpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_logical.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.cpp
  src/ngraph/runtime/reference/xor.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/logical_xor.in.cpp
  test/constant_folding.cpp
  test/cpu_test.cpp
  test/type_prop/binary_elementwise.cpp
Labels: Fully Reviewed

#3371 Convert pattern ops to type_name
  src/ngraph/pattern/op/any.hpp
  src/ngraph/pattern/op/any_of.hpp
  src/ngraph/pattern/op/label.hpp
  src/ngraph/pattern/op/pattern.hpp
  src/ngraph/pattern/op/skip.hpp
Labels: Fully Reviewed

#3331 [Py] Added gemm operator to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/gemm.cpp
  python/pyngraph/ops/fused/gemm.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed, Merge Blocked

#3365 [Py] Added GRN operator to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/grn.cpp
  python/pyngraph/ops/fused/grn.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3372 Make ConstantFolding work even when shapes are not originally static
  src/ngraph/op/experimental/dyn_broadcast.cpp
  src/ngraph/pass/constant_folding.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#3353 [ONNX] Remove unused includes
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/op/cast.cpp
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/frontend/onnx_import/op/dequantize_linear.cpp
  src/ngraph/frontend/onnx_import/op/instance_norm.cpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/lrn.cpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/frontend/onnx_import/op/prelu.cpp
  src/ngraph/frontend/onnx_import/op/quant_conv.cpp
  src/ngraph/frontend/onnx_import/op/quantize_linear.cpp
  src/ngraph/frontend/onnx_import/op/selu.cpp
  src/ngraph/frontend/onnx_import/op/slice.cpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/op/thresholded_relu.cpp
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/op/transpose.cpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
  src/ngraph/frontend/onnx_import/utils/matmul_factory.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
Labels: Fully Reviewed, ONNX

#3355 Improve pragma usage.
  src/ngraph/log.cpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/equal.hpp
  src/ngraph/runtime/reference/not_equal.hpp
  src/ngraph/runtime/reference/topk.hpp
  src/ngraph/serializer.cpp
  src/ngraph/type/bfloat16.cpp
  src/ngraph/type/float16.cpp
Labels: Fully Reviewed

#3381 Export get_backend_constructor_pointer from IATransformer
  src/ngraph/runtime/cpu/cpu_backend.cpp
Labels: Fully Reviewed

#3377 Export backend function on windows
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/plaidml/plaidml_backend_constructor.cpp
Labels: Fully Reviewed

#3379 private function to static initialize all the backend for static library builds
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/backend_manager.hpp
Labels: Fully Reviewed

#3383 Klocwork unitialized variables
  src/ngraph/runtime/chrome_trace.hpp
Labels: Fully Reviewed

#3346 Adjust op ROIPooling
  src/ngraph/op/experimental/layers/roi_pooling.cpp
  src/ngraph/op/experimental/layers/roi_pooling.hpp
Labels: Fully Reviewed

#3388 Leona/doc 0.25
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/source/conf.py
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#3373 Convert remaining op/ ops to Output<Node> constructors
  src/ngraph/op/pad.cpp
  src/ngraph/op/pad.hpp
  src/ngraph/op/parameter.hpp
  src/ngraph/op/passthrough.cpp
  src/ngraph/op/passthrough.hpp
  src/ngraph/op/power.cpp
  src/ngraph/op/power.hpp
  src/ngraph/op/product.cpp
  src/ngraph/op/product.hpp
  src/ngraph/op/quantize.hpp
  src/ngraph/op/quantized_convolution.hpp
  src/ngraph/op/relu.cpp
  src/ngraph/op/relu.hpp
  src/ngraph/op/replace_slice.hpp
  src/ngraph/op/reverse.cpp
  src/ngraph/op/reverse.hpp
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/op/reverse_sequence.hpp
  src/ngraph/op/scatter_add.hpp
  src/ngraph/op/scatter_nd_add.hpp
  src/ngraph/op/select.cpp
  src/ngraph/op/sigmoid.cpp
  src/ngraph/op/sigmoid.hpp
  src/ngraph/op/sign.cpp
  src/ngraph/op/sign.hpp
  src/ngraph/op/sin.cpp
  src/ngraph/op/sin.hpp
  src/ngraph/op/sinh.cpp
  src/ngraph/op/sinh.hpp
  src/ngraph/op/slice.cpp
  src/ngraph/op/slice.hpp
  src/ngraph/op/softmax.cpp
  src/ngraph/op/softmax.hpp
  src/ngraph/op/sqrt.cpp
  src/ngraph/op/sqrt.hpp
  src/ngraph/op/stop_gradient.cpp
  src/ngraph/op/stop_gradient.hpp
  src/ngraph/op/subtract.cpp
  src/ngraph/op/sum.cpp
  src/ngraph/op/sum.hpp
  src/ngraph/op/tan.cpp
  src/ngraph/op/tan.hpp
  src/ngraph/op/tanh.cpp
  src/ngraph/op/tanh.hpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3382 Update reference kernels, constant folding to support auto-broadcast directly
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/add.hpp
  src/ngraph/runtime/reference/and.hpp
  src/ngraph/runtime/reference/autobroadcast_binop.hpp
  src/ngraph/runtime/reference/divide.hpp
  src/ngraph/runtime/reference/equal.hpp
  src/ngraph/runtime/reference/greater.hpp
  src/ngraph/runtime/reference/greater_eq.hpp
  src/ngraph/runtime/reference/less.hpp
  src/ngraph/runtime/reference/less_eq.hpp
  src/ngraph/runtime/reference/maximum.hpp
  src/ngraph/runtime/reference/minimum.hpp
  src/ngraph/runtime/reference/multiply.hpp
  src/ngraph/runtime/reference/not_equal.hpp
  src/ngraph/runtime/reference/or.hpp
  src/ngraph/runtime/reference/power.hpp
  src/ngraph/runtime/reference/subtract.hpp
  src/ngraph/runtime/reference/xor.hpp
  test/constant_folding.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#3385 Convert fused ops to value-based constructors
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/fused/clamp.cpp
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/op/fused/conv_fused.cpp
  src/ngraph/op/fused/conv_fused.hpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/depth_to_space.hpp
  src/ngraph/op/fused/elu.cpp
  src/ngraph/op/fused/elu.hpp
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/fake_quantize.hpp
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/gelu.hpp
  src/ngraph/op/fused/gemm.cpp
  src/ngraph/op/fused/gemm.hpp
  src/ngraph/op/fused/grn.cpp
  src/ngraph/op/fused/grn.hpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/fused/group_conv_transpose.cpp
  src/ngraph/op/fused/group_conv_transpose.hpp
  src/ngraph/op/fused/gru_cell.cpp
  src/ngraph/op/fused/gru_cell.hpp
  src/ngraph/op/fused/hard_sigmoid.cpp
  src/ngraph/op/fused/hard_sigmoid.hpp
  src/ngraph/op/fused/leaky_relu.cpp
  src/ngraph/op/fused/leaky_relu.hpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/lstm_cell.hpp
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/op/fused/normalize.cpp
  src/ngraph/op/fused/normalize.hpp
  src/ngraph/op/fused/prelu.cpp
  src/ngraph/op/fused/prelu.hpp
  src/ngraph/op/fused/rnn_cell.cpp
  src/ngraph/op/fused/rnn_cell.hpp
  src/ngraph/op/fused/scale_shift.cpp
  src/ngraph/op/fused/scale_shift.hpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/shuffle_channels.hpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.hpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/op/fused/squared_difference.cpp
  src/ngraph/op/fused/squared_difference.hpp
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/squeeze.hpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/fused/unsqueeze.hpp
Labels: Fully Reviewed

#3387 Move binary and unary element op tests to individual files
  test/CMakeLists.txt
  test/backend/abs.in.cpp
  test/backend/acos.in.cpp
  test/backend/add.in.cpp
  test/backend/asin.in.cpp
  test/backend/atan.in.cpp
  test/backend/auto_broadcast.in.cpp
  test/backend/binary_elementwise.in.cpp
  test/backend/ceiling.in.cpp
  test/backend/cos.in.cpp
  test/backend/cosh.in.cpp
  test/backend/divide.in.cpp
  test/backend/erf.in.cpp
  test/backend/exp.in.cpp
  test/backend/floor.in.cpp
  test/backend/gelu.in.cpp
  test/backend/log.in.cpp
  test/backend/maximum.in.cpp
  test/backend/minimum.in.cpp
  test/backend/multiply.in.cpp
  test/backend/negative.in.cpp
  test/backend/not.in.cpp
  test/backend/power.in.cpp
  test/backend/sign.in.cpp
  test/backend/sin.in.cpp
  test/backend/sinh.in.cpp
  test/backend/sqrt.in.cpp
  test/backend/subtract.in.cpp
  test/backend/tan.in.cpp
  test/backend/tanh.in.cpp
  test/backend/unary_elementwise.in.cpp
Labels: Fully Reviewed

#3386 Add method so that element::Type can be cast into enum
  src/contrib/mlir/compiler.cpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/max.cpp
  src/ngraph/op/min.cpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/runtime/cpu/builder/allreduce.cpp
  src/ngraph/runtime/cpu/builder/broadcast_distributed.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/intelgpu/intelgpu_layout.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_custom_kernels.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/type/element_type.hpp
  src/tools/nbench/benchmark_utils.cpp
  test/util/test_case.cpp
Labels: Fully Reviewed

#3333 [Fused] Remove fused LeakyRelu
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/leaky_relu.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/leaky_relu.cpp
  src/ngraph/op/fused/leaky_relu.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/fused_op.in.cpp
  test/type_prop/leaky_relu.cpp
Labels: Changes API, Fully Reviewed

#3334 [Py] Added depth_to_space operator to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/depth_to_space.cpp
  python/pyngraph/ops/fused/depth_to_space.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3347 [Spec] Adjust op PSROIPooling
  src/ngraph/op/experimental/layers/psroi_pooling.cpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed

#3384 [MLIR] Enable compilation of MLIR examples (toy, linalg, ...)
  cmake/mlir_fetch.cmake.in
Labels: Fully Reviewed

#3396 Update CODEOWNERS for cpu/builder/allreduce.*pp
  CODEOWNERS
Labels: Fully Reviewed

#3394 Don't enable dl use in static builds for r0.25
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/cpu/builder/quantized_concat.cpp
  src/ngraph/runtime/cpu/builder/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
Labels: Fully Reviewed

#3395 PlaidML Grouped Convolution Implementation
  CODEOWNERS
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/plaidml/CMakeLists.txt
  src/ngraph/runtime/plaidml/plaidml_compiler.cpp
  src/ngraph/runtime/plaidml/plaidml_ops_group_convolution.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/fused_op.in.cpp
Labels: PlaidML

#3389 Add missing initialization of pad mode in DynPad constructor
  src/ngraph/op/experimental/dyn_pad.cpp
Labels: External, Fully Reviewed

#3402 Fix crash when NGRAPH_ENABLE_{VISUALIZE,SERIALIZE}_TRACING=1
  src/ngraph/pass/manager.hpp
  test/pass_manager.cpp
Labels: Fully Reviewed

#3403 Cherry-pick "Fix crash when NGRAPH_ENABLE_{VISUALIZE,SERIALIZE}_TRACING=1" to r0.25
  src/ngraph/pass/manager.hpp
  test/pass_manager.cpp
Labels: Fully Reviewed

#3401 Cyphers/s barannikov initialize dyn pad mode
  src/ngraph/op/experimental/dyn_pad.cpp
Labels: DO NOT SQUASH, External, Fully Reviewed

#3364 [Py] Added fake_quantize operator to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/fake_quantize.cpp
  python/pyngraph/ops/fused/fake_quantize.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3404 Convert remaining experimental op dir to output args
  src/ngraph/op/experimental/batch_mat_mul.cpp
  src/ngraph/op/experimental/batch_mat_mul.hpp
  src/ngraph/op/experimental/compiled_kernel.cpp
  src/ngraph/op/experimental/compiled_kernel.hpp
  src/ngraph/op/experimental/dyn_broadcast.cpp
  src/ngraph/op/experimental/dyn_broadcast.hpp
  src/ngraph/op/experimental/dyn_pad.cpp
  src/ngraph/op/experimental/dyn_pad.hpp
  src/ngraph/op/experimental/dyn_replace_slice.cpp
  src/ngraph/op/experimental/dyn_replace_slice.hpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_reshape.hpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/experimental/dyn_slice.hpp
  src/ngraph/op/experimental/generate_mask.cpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/experimental/quantized_concat.hpp
  src/ngraph/op/experimental/quantized_conv_bias.hpp
  src/ngraph/op/experimental/quantized_conv_relu.hpp
  src/ngraph/op/experimental/quantized_dot.hpp
  src/ngraph/op/experimental/quantized_dot_bias.hpp
  src/ngraph/op/experimental/quantized_max_pool.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/experimental/range.hpp
  src/ngraph/op/experimental/shape_of.cpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/op/experimental/tile.cpp
  src/ngraph/op/experimental/tile.hpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/op/experimental/transpose.hpp
Labels: Fully Reviewed

#3409 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#3400 Cyphers/25tomaster
  CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/cpu/builder/quantized_concat.cpp
  src/ngraph/runtime/cpu/builder/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
Labels: Fully Reviewed

#3408 Disable test for unimplemented op
  src/ngraph/runtime/plaidml/unit_test.manifest
Labels: Fully Reviewed

#3413 Initialization for kw
  src/ngraph/op/topk.hpp
Labels: Fully Reviewed

#3414 #3413 for master
  src/ngraph/op/topk.hpp
Labels: Fully Reviewed

#3416 Remove not-directly-used includes
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/op/acos.cpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/dot.cpp
  src/ngraph/op/experimental/batch_mat_mul.cpp
  src/ngraph/op/experimental/compiled_kernel.cpp
  src/ngraph/op/experimental/dyn_broadcast.cpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/layers/detection_output.cpp
  src/ngraph/op/experimental/layers/reorg_yolo.cpp
  src/ngraph/op/experimental/quantized_avg_pool.cpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/experimental/quantized_conv_bias.cpp
  src/ngraph/op/experimental/quantized_conv_relu.cpp
  src/ngraph/op/experimental/quantized_dot.cpp
  src/ngraph/op/experimental/quantized_dot_bias.cpp
  src/ngraph/op/experimental/quantized_max_pool.cpp
  src/ngraph/op/experimental/shape_of.cpp
  src/ngraph/op/fused/conv_fused.cpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/elu.cpp
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv_transpose.cpp
  src/ngraph/op/fused/gru_cell.cpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/prelu.cpp
  src/ngraph/op/fused/rnn_cell.cpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/lrn.cpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/quantized_convolution.cpp
  src/ngraph/op/reshape.cpp
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/op/select.cpp
  src/ngraph/op/softmax.cpp
  src/ngraph/op/stop_gradient.cpp
  src/ngraph/op/util/activation_functions.cpp
  src/ngraph/op/util/rnn_cell_base.cpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
Labels: DO NOT SQUASH, Fully Reviewed

#3412 Fix sum reference to handle corner cases with +-inf
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/reference/sum.hpp
  test/backend/sum.in.cpp
Labels: Fully Reviewed

#3410 Add a more reasonable function to query ngraph version info
  src/ngraph/ngraph.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
  test/CMakeLists.txt
  test/ngraph_api.cpp
Labels: Fully Reviewed

#3375 [Py] Added unsqueeze operator to Python API
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/unsqueeze.cpp
  python/pyngraph/ops/fused/unsqueeze.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3418 Split constant folding constructors to separate files
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/pass/constant_folding_broadcast.cpp
  src/ngraph/pass/constant_folding_concat.cpp
  src/ngraph/pass/constant_folding_convert.cpp
  src/ngraph/pass/constant_folding_dequantize.cpp
  src/ngraph/pass/constant_folding_dyn_broadcast.cpp
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  src/ngraph/pass/constant_folding_dyn_slice.cpp
  src/ngraph/pass/constant_folding_gather.cpp
  src/ngraph/pass/constant_folding_logical_reduction.cpp
  src/ngraph/pass/constant_folding_pad.cpp
  src/ngraph/pass/constant_folding_quantize.cpp
  src/ngraph/pass/constant_folding_range.cpp
  src/ngraph/pass/constant_folding_reshape.cpp
  src/ngraph/pass/constant_folding_reverse.cpp
  src/ngraph/pass/constant_folding_select.cpp
  src/ngraph/pass/constant_folding_shape_of.cpp
  src/ngraph/pass/constant_folding_slice.cpp
  src/ngraph/pass/constant_folding_transpose.cpp
  src/ngraph/pass/constant_folding_unary.cpp
  src/ngraph/runtime/reference/quantize.hpp
Labels: Fully Reviewed

#3417 Cherry-pick #3412 to master (+- inf sum issue)
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/reference/sum.hpp
  test/backend/sum.in.cpp
Labels: Fully Reviewed

#3397 [MLIR] Enable affine loop tiling
  src/contrib/mlir/compiler.cpp
Labels: Fully Reviewed

#3421 Parameter attribute getters
  src/ngraph/op/parameter.cpp
  src/ngraph/op/parameter.hpp
Labels: Fully Reviewed

#3391 [MLIR] Add unary op -- Negative
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/op_lowerers.inc
  src/contrib/mlir/ops_supported.inc
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  test/backend/negative.in.cpp
Labels: Fully Reviewed

#3422 [MLIR] Bump MLIR repo to commit c636f12, 08/09/2019
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/lowerer.hpp
Labels: Fully Reviewed

#3407 [Py] Added operators HardSigmoid, MVN, PRelu, ScaleShift and SpaceToDepth to Python API.
  doc/sphinx/source/python_api/_autosummary/ngraph.ops.rst
  python/ngraph/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/ops.py
  python/pyngraph/ops/fused/hard_sigmoid.cpp
  python/pyngraph/ops/fused/hard_sigmoid.hpp
  python/pyngraph/ops/fused/mvn.cpp
  python/pyngraph/ops/fused/mvn.hpp
  python/pyngraph/ops/fused/prelu.cpp
  python/pyngraph/ops/fused/prelu.hpp
  python/pyngraph/ops/fused/scale_shift.cpp
  python/pyngraph/ops/fused/scale_shift.hpp
  python/pyngraph/ops/fused/space_to_depth.cpp
  python/pyngraph/ops/fused/space_to_depth.hpp
  python/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/setup.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed

#3427 [MLIR] Update MLIR and LLVM commit ids
  cmake/external_mlir.cmake
Labels: Fully Reviewed

#3415 Update cpu backend to support i32 with topk
  src/ngraph/runtime/cpu/builder/topk.cpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/topk.in.cpp
Labels: Fully Reviewed

#3428 Update jenkins-trigger.groovy
  .ci/jenkins/jenkins-trigger.groovy
Labels: Fully Reviewed

#3423 [MLIR] Set optimization level for LLVM optimizer and codegen
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
Labels: Fully Reviewed

#3398 Fix version label
  cmake/Modules/git_tags.cmake
Labels: Fully Reviewed

#3429 Remove deprecated methods
  src/ngraph/runtime/tensor.hpp
Labels: Changes API, Fully Reviewed

#3374 [Spec] Add axes input to LRN
  src/ngraph/op/lrn.cpp
  src/ngraph/op/lrn.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/type_prop/lrn.cpp
Labels: Fully Reviewed

#3424 [MLIR] Enable LLVM vectorization by initializing TTI
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/compiler.hpp
Labels: Fully Reviewed

#3433 Change fused op unit tests to use f32 instead of f64
  test/backend/fused_op.in.cpp
Labels: Fully Reviewed

#3438 Add method to check if an Executable can create tensors
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  test/CMakeLists.txt
  test/backend_api.cpp
Labels: Fully Reviewed

#3442 [MLIR] Disable CPU fusion tests in MLIR
  test/cpu_debug_tracer.cpp
  test/cpu_fusion.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#3447 GeluBackpropFactor
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/gelu.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend/gelu.in.cpp
Labels: Fully Reviewed

#3440 [MLIR] Disable python rounding Divide op in MLIR
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3332 [FUSED] Change alpha attribute in Elu from dynamic to static
  python/ngraph/ops.py
  python/pyngraph/ops/fused/elu.cpp
  python/test/ngraph/test_ops_fused.py
  src/ngraph/frontend/onnx_import/op/elu.cpp
  src/ngraph/op/fused/elu.cpp
  src/ngraph/op/fused/elu.hpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/type_prop/elu.cpp
Labels: Changes API, Fully Reviewed

#3327 LSTM MKLDNN integration for ONNX LSTM op
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed, IntelCPU

#3435 [MLIR] Fix cycle detection during sub-graph construction
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.hpp
Labels: Fully Reviewed

#3449 fix typo
  src/ngraph/runtime/executable.cpp
Labels: Fully Reviewed

#3452 Cleanup dead file
  test/hybrid_backend.cpp
Labels: Fully Reviewed

#3446 Copy outputs only if the use is outside the sub-graph
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3450 Stage README for review pre-release
  README.md
  doc/sphinx/source/graphics/ngpipelines.png
Labels: Fully Reviewed

#3451 Disable debugger tests
  test/cpu_debugger.cpp
Labels: Fully Reviewed

#3455 Release notes with PlaidML detail added
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#3434 [MLIR] Disable support for boolean type in MLIR
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
Labels: Fully Reviewed

#3445 Cyphers/exec can create tensors
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend.hpp
  test/CMakeLists.txt
  test/backend_api.cpp
Labels: Do-not-merge-yet

#3456 Separate dynamic loading from static linking
  CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend_manager.cpp
Labels: Fully Reviewed

#3453 [MLIR] Use f64 APFloat
  src/contrib/mlir/lowerer.cpp
Labels: Fully Reviewed

#3460 [MLIR] Enable clang-format on comments in contrib folder
  src/contrib/.clang-format
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.hpp
Labels: Fully Reviewed

#3462 Cyphers/exec can create tensors (#3445)
  src/ngraph/runtime/backend.cpp
Labels: Fully Reviewed

#3463 Cyphers/mdynamic
  CMakeLists.txt
  src/ngraph/runtime/backend.cpp
  src/ngraph/runtime/backend_manager.cpp
Labels: Fully Reviewed

#3419 [Spec] Adjust op Proposal
  src/ngraph/op/experimental/layers/proposal.cpp
  test/CMakeLists.txt
  test/type_prop/proposal.cpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed

#3464 Enable clang-format on comments in runtime/cpu folder
  src/ngraph/runtime/cpu/.clang-format
  src/ngraph/runtime/cpu/builder/allreduce.cpp
  src/ngraph/runtime/cpu/builder/compiled_kernel.cpp
  src/ngraph/runtime/cpu/builder/concat.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/builder/quantized_concat.cpp
  src/ngraph/runtime/cpu/builder/state.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_debugger.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/cpu_kernel_emitters.cpp
  src/ngraph/runtime/cpu/kernel/gather.hpp
  src/ngraph/runtime/cpu/kernel/scatter_add.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/op/deconv.cpp
  src/ngraph/runtime/cpu/op/deconv.hpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/max_pool_with_indices.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/op/sigmoid_mul.hpp
  src/ngraph/runtime/cpu/op/update_slice.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/halide_subgraph_extraction.cpp
Labels: Fully Reviewed

#3459 [MLIR] Fix crash when checking bool types and bprop tests
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  test/util/autodiff/backprop_derivative.hpp
Labels: Fully Reviewed

#3461 Add .clang-format with comment wrap to src/ngraph
  src/ngraph/.clang-format
  src/ngraph/autodiff/adjoints.cpp
  src/ngraph/builder/.clang-format
  src/ngraph/codegen/compiler.cpp
  src/ngraph/coordinate_transform.cpp
  src/ngraph/descriptor/.clang-format
  src/ngraph/frontend/.clang-format
  src/ngraph/function.hpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/.clang-format
  src/ngraph/pass/.clang-format
  src/ngraph/pattern/.clang-format
  src/ngraph/runtime/.clang-format
  src/ngraph/shape_util.hpp
  src/ngraph/state/.clang-format
  src/ngraph/validation_util.cpp
Labels: Fully Reviewed

#3406 [Spec][Fused] Adjust op Normalize
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/norm.hpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/fused/normalize.cpp
  src/ngraph/op/fused/normalize_l2.cpp
  src/ngraph/op/fused/normalize_l2.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/ref_generators/generate_normalize_l2_ref.py
  test/type_prop/normalize.cpp
Labels: Changes API, Fully Reviewed

#3469 clang-format comments: /src/ngraph/state
  src/ngraph/state/.clang-format
  src/ngraph/state/rng_state.hpp
  src/ngraph/state/state.hpp
Labels: Fully Reviewed

#3444 GeluBackpropFactor for 0.25
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/gelu.hpp
  src/ngraph/op/fused_op_tbl.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/backend/gelu.in.cpp
Labels: Do-not-merge-yet, Fully Reviewed

#3471 clang-format comments: /src/ngraph/pattern
  src/ngraph/pattern/.clang-format
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/pattern/op/any.hpp
  src/ngraph/pattern/op/any_of.hpp
  src/ngraph/pattern/op/label.hpp
Labels: Fully Reviewed

#3472 clang-format comments: /src/ngraph/builder
  src/ngraph/builder/.clang-format
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/autobroadcast.hpp
  src/ngraph/builder/numpy_transpose.hpp
  src/ngraph/builder/reduce_ops.hpp
  src/ngraph/builder/reshape.cpp
Labels: Fully Reviewed

#3470 clang-format comments: /src/ngraph/descriptor
  src/ngraph/descriptor/.clang-format
  src/ngraph/descriptor/input.hpp
  src/ngraph/descriptor/layout/dense_tensor_layout.hpp
  src/ngraph/descriptor/layout/tensor_layout.hpp
Labels: Fully Reviewed

#3473 clang-format comments: /src/ngraph/pass
  src/ngraph/pass/.clang-format
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_unary.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/like_replacement.cpp
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/nop_elimination.cpp
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
Labels: Fully Reviewed

#3448 Dynamic "flatten" builder
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/ngraph.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  test/CMakeLists.txt
  test/backend/builder_flatten.in.cpp
Labels: Fully Reviewed

#3439 Did a batch normalization of the BatchNorm unit test names
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/backend/batch_norm.in.cpp
  test/onnx/onnx_import.in.cpp
  test/type_prop/batch_norm.cpp
Labels: Fully Reviewed

#3458 Remove quantized pool {avg and max}
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/op/experimental/quantized_avg_pool.cpp
  src/ngraph/op/experimental/quantized_avg_pool.hpp
  src/ngraph/op/experimental/quantized_max_pool.cpp
  src/ngraph/op/experimental/quantized_max_pool.hpp
  src/ngraph/op/op_tbl.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantized_avg_pool.cpp
  src/ngraph/runtime/cpu/builder/quantized_max_pool.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/avg_pool.hpp
  src/ngraph/serializer.cpp
  test/backend/pool.in.cpp
  test/builder_quantization.cpp
Labels: Fully Reviewed

#3477 clang-format comments: /doc/examples
  doc/examples/.clang-format
  doc/examples/mnist_mlp/dist_mnist_mlp.cpp
  doc/examples/mnist_mlp/mnist_mlp.cpp
  doc/examples/mnist_mlp/tensor_utils.hpp
  doc/sphinx/source/core/constructing-graphs/derive-for-training.rst
  maint/apply-code-format.sh
  maint/check-code-format.sh
Labels: Fully Reviewed

#3478 clang-format comments: /test
  test/.clang-format
  test/algebraic_simplification.cpp
  test/backend/arg_reduce.in.cpp
  test/backend/autodiff.in.cpp
  test/backend/comparison.in.cpp
  test/backend/distributed.in.cpp
  test/backend/dot.in.cpp
  test/backend/embedding_lookup.in.cpp
  test/backend/fused_op.in.cpp
  test/backend/graph_comparison.in.cpp
  test/backend/max.in.cpp
  test/backend/min.in.cpp
  test/backend/pool.in.cpp
  test/backend/product.in.cpp
  test/backend/reshape.in.cpp
  test/backend/sum.in.cpp
  test/constant_folding.cpp
  test/cpu_debug_tracer.cpp
  test/cpu_debugger.cpp
  test/cpu_test.cpp
  test/gpu_fusion.cpp
  test/input_output_assign.cpp
  test/onnx/onnx_import_quant.in.cpp
  test/op.cpp
  test/reshape_sinking.cpp
  test/type_prop/split.cpp
  test/util/all_close_f.cpp
  test/util/all_close_f.hpp
  test/util/matcher.hpp
  test/util/test_case.hpp
Labels: Fully Reviewed

#3235 Add QuantizedDot to ngraph core
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantized_dot_builder.cpp
  src/ngraph/builder/quantized_dot_builder.hpp
  src/ngraph/frontend/onnx_import/utils/matmul_factory.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/op/quantized_dot.cpp
  src/ngraph/op/quantized_dot.hpp
  src/ngraph/runtime/cpu/builder/dot.cpp
  src/ngraph/runtime/cpu/builder/quantized_dot.cpp
  src/ngraph/runtime/cpu/builder/quantized_matmul.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/kernel/dot.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/quantized_matmul.cpp
  src/ngraph/runtime/cpu/op/quantized_matmul.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/dot.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/quantized_dot.in.cpp
  test/builder_quantization.cpp
  test/type_prop/quantized_dot.cpp
Labels: Fully Reviewed

#3479 clang-format comments: /src/ngraph/runtime/reference
  src/ngraph/runtime/reference/.clang-format
  src/ngraph/runtime/reference/avg_pool.hpp
  src/ngraph/runtime/reference/concat.hpp
  src/ngraph/runtime/reference/convolution.hpp
  src/ngraph/runtime/reference/divide.hpp
  src/ngraph/runtime/reference/dot.hpp
  src/ngraph/runtime/reference/gather.hpp
  src/ngraph/runtime/reference/gather_nd.hpp
  src/ngraph/runtime/reference/max_pool.hpp
  src/ngraph/runtime/reference/one_hot.hpp
  src/ngraph/runtime/reference/pad.hpp
  src/ngraph/runtime/reference/reshape.hpp
  src/ngraph/runtime/reference/reverse.hpp
  src/ngraph/runtime/reference/scatter_nd_add.hpp
Labels: Fully Reviewed

#3488 clang-format: Combine several already-approved PRs
  src/ngraph/runtime/dynamic/.clang-format
  src/ngraph/runtime/generic_cpu/.clang-format
  src/ngraph/runtime/generic_cpu/kernel/dot.hpp
  src/ngraph/runtime/gpu/.clang-format
  src/ngraph/runtime/gpu/cuda_emitter.cpp
  src/ngraph/runtime/gpu/cuda_emitter.hpp
  src/ngraph/runtime/gpu/cuda_error_check.hpp
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.cpp
  src/ngraph/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_internal_function.cpp
  src/ngraph/runtime/gpu/gpu_kernel_args.hpp
  src/ngraph/runtime/gpu/op/rnn.hpp
  src/ngraph/runtime/gpu/pass/gpu_batch_norm_cache.cpp
  src/ngraph/runtime/gpu/pass/gpu_rnn_fusion.cpp
  src/ngraph/runtime/gpuh/.clang-format
  src/ngraph/runtime/intelgpu/.clang-format
  src/ngraph/runtime/intelgpu/intelgpu_backend.cpp
  src/ngraph/runtime/intelgpu/intelgpu_op_batchnorm.cpp
  src/ngraph/runtime/interpreter/.clang-format
  src/ngraph/runtime/interpreter/int_visibility.hpp
  src/ngraph/runtime/nop/.clang-format
  src/ngraph/runtime/plaidml/.clang-format
  src/ngraph/runtime/plaidml/plaidml_backend_visibility.hpp
  src/ngraph/runtime/plaidml/plaidml_compilation_cache.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_implicit_broadcast.hpp
  src/ngraph/runtime/plaidml/plaidml_ops_index_reduction.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_implicit_broadcast.cpp
Labels: Fully Reviewed

#3486 Leona/doc v0.25.1
  README.md
  doc/sphinx/ngraph_theme/ngversions.html
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/conf.py
  doc/sphinx/source/frameworks/getting_started.rst
  doc/sphinx/source/frameworks/validated/list.rst
  doc/sphinx/source/project/contribution-guide.rst
  doc/sphinx/source/project/extras/testing_latency.rst
  doc/sphinx/source/project/release-notes.rst
Labels: Fully Reviewed

#3485 add virtual method to get version number from Backend
  src/ngraph/runtime/backend.hpp
Labels: Fully Reviewed

#3475 clang-format comments: /python
  python/.clang-format
  python/pyngraph/ops/util/arithmetic_reduction.cpp
  python/pyngraph/types/element_type.hpp
Labels: Fully Reviewed

#3474 mkl-dnn: patch update 0.20.2
  cmake/external_mkldnn.cmake
  cmake/mkldnn.patch
Labels: Fully Reviewed

#3467 Remove quantized concat
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/op/experimental/quantized_concat.cpp
  src/ngraph/op/experimental/quantized_concat.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/quantized_concat.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.cpp
  src/ngraph/runtime/cpu/cpu_builder_registry.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#3490 Redundant files
  src/ngraph/builder/quantization/quantized_linear_matmul.cpp
  src/ngraph/builder/quantization/quantized_linear_matmul.hpp
  src/ngraph/op/experimental/quantized_dot.cpp
  src/ngraph/op/experimental/quantized_dot.hpp
Labels: Fully Reviewed

#3498 clang-format comments: /src/ngraph/op/util
  .clang-format
  src/.clang-format
  src/ngraph/op/util/.clang-format
  src/ngraph/op/util/arithmetic_reduction.hpp
  src/ngraph/op/util/binary_elementwise_arithmetic.hpp
  src/ngraph/op/util/binary_elementwise_comparison.hpp
  src/ngraph/op/util/binary_elementwise_logical.hpp
  src/ngraph/op/util/broadcasting.cpp
  src/ngraph/op/util/broadcasting.hpp
  src/ngraph/op/util/fused_op.hpp
  src/ngraph/op/util/logical_reduction.hpp
  src/ngraph/op/util/rnn_cell_base.hpp
  src/ngraph/op/util/unary_elementwise_arithmetic.hpp
  test/.clang-format
Labels: Fully Reviewed

#3494 clang-format comments: /src/ngraph/runtime
  src/ngraph/runtime/.clang-format
  src/ngraph/runtime/allocator.hpp
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/cpu/.clang-format
  src/ngraph/runtime/dynamic/.clang-format
  src/ngraph/runtime/executable.hpp
  src/ngraph/runtime/generic_cpu/.clang-format
  src/ngraph/runtime/gpu/.clang-format
  src/ngraph/runtime/gpuh/.clang-format
  src/ngraph/runtime/intelgpu/.clang-format
  src/ngraph/runtime/interpreter/.clang-format
  src/ngraph/runtime/nop/.clang-format
  src/ngraph/runtime/plaidml/.clang-format
  src/ngraph/runtime/reference/.clang-format
Labels: Fully Reviewed

#3499 clang-format comments: /src/ngraph/op/fused
  src/ngraph/op/fused/.clang-format
  src/ngraph/op/fused/conv_fused.cpp
  src/ngraph/op/fused/depth_to_space.hpp
  src/ngraph/op/fused/fake_quantize.hpp
  src/ngraph/op/fused/gemm.hpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv_transpose.hpp
  src/ngraph/op/fused/gru_cell.cpp
  src/ngraph/op/fused/gru_cell.hpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/lstm_cell.hpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/op/fused/normalize_l2.hpp
  src/ngraph/op/fused/rnn_cell.cpp
  src/ngraph/op/fused/rnn_cell.hpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/shuffle_channels.hpp
  src/ngraph/op/fused/split.hpp
Labels: Fully Reviewed

#3500 clang-format comments: /src/ngraph/op/experimental
  src/ngraph/op/experimental/.clang-format
  src/ngraph/op/experimental/dyn_broadcast.cpp
  src/ngraph/op/experimental/dyn_broadcast.hpp
  src/ngraph/op/experimental/dyn_pad.cpp
  src/ngraph/op/experimental/dyn_replace_slice.hpp
  src/ngraph/op/experimental/dyn_reshape.hpp
  src/ngraph/op/experimental/dyn_slice.hpp
Labels: Fully Reviewed

#3492 Avoid static initialization issues
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
Labels: Fully Reviewed

#3501 Segregate the quant builders op wise
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/dequantize_builder.cpp
  src/ngraph/builder/dequantize_builder.hpp
  src/ngraph/builder/quantization.cpp
  src/ngraph/builder/quantization.hpp
  src/ngraph/builder/quantization/quantized_linear_convolution.cpp
  src/ngraph/builder/quantization_util.hpp
  src/ngraph/builder/quantization_utils.cpp
  src/ngraph/builder/quantization_utils.hpp
  src/ngraph/builder/quantize_builder.cpp
  src/ngraph/builder/quantize_builder.hpp
  src/ngraph/builder/quantized_concat_builder.cpp
  src/ngraph/builder/quantized_concat_builder.hpp
  src/ngraph/builder/quantized_conv_builder.cpp
  src/ngraph/builder/quantized_conv_builder.hpp
  src/ngraph/builder/quantized_dot_builder.cpp
  src/ngraph/builder/quantized_dot_builder.hpp
  src/ngraph/ngraph.hpp
  test/builder_quantization.cpp
Labels: Fully Reviewed

#3493 [mlir] Bump mlir repo 8/20/2019
  CMakeLists.txt
  cmake/external_mlir.cmake
  cmake/mlir_fetch.cmake.in
  src/contrib/mlir/compiler.cpp
  src/contrib/mlir/lowerer.cpp
  src/contrib/mlir/lowerer.hpp
Labels: Fully Reviewed

#3523 [MLIR] Add config files for LIT testing
  cmake/external_mlir.cmake
  test/mlir/affine_lowering/lit_test.mlir
  test/mlir/lit.cfg.py
  test/mlir/lit.site.cfg.py.in
Labels: Fully Reviewed

#3539 Convert missed ops to accept Output<Node>
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.cpp
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.hpp
  src/ngraph/op/experimental/layers/detection_output.cpp
  src/ngraph/op/experimental/layers/detection_output.hpp
  src/ngraph/op/experimental/layers/interpolate.cpp
  src/ngraph/op/experimental/layers/interpolate.hpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box.hpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.hpp
  src/ngraph/op/experimental/layers/proposal.cpp
  src/ngraph/op/experimental/layers/proposal.hpp
  src/ngraph/op/experimental/layers/psroi_pooling.cpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  src/ngraph/op/experimental/layers/region_yolo.cpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
  src/ngraph/op/experimental/layers/reorg_yolo.cpp
  src/ngraph/op/experimental/layers/reorg_yolo.hpp
  src/ngraph/op/experimental/layers/roi_pooling.cpp
  src/ngraph/op/experimental/layers/roi_pooling.hpp
Labels: Fully Reviewed

#3511 [MLIR] Fixes for cpu_fusion.validate_fuse_gru_inputs
  src/contrib/mlir/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/pass/mlir_subgraph_extraction.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#3542 no_fork: Performance issue vector of string to T
  src/ngraph/util.hpp
Labels: Fully Reviewed

#3544 no_fork : Remove allocation for empty vector
  src/ngraph/op/constant.hpp
Labels: Fully Reviewed

#3545 Cyphers/from25
  src/ngraph/event_tracing.cpp
Labels: Fully Reviewed

#3528 Update documentation for ngraph_onnx building
  doc/sphinx/source/core/constructing-graphs/import.rst
Labels: Fully Reviewed

#3530 [MLIR] Move MLIR compiler files to contrib/mlir/compiler
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/compiler/CMakeLists.txt
  src/contrib/mlir/compiler/compiler.cpp
  src/contrib/mlir/compiler/compiler.hpp
  src/contrib/mlir/compiler/dialect/dialect.cpp
  src/contrib/mlir/compiler/dialect/dialect.hpp
  src/contrib/mlir/compiler/dialect/ops.cpp
  src/contrib/mlir/compiler/dialect/ops.hpp
  src/contrib/mlir/compiler/dialect/ops.td
  src/contrib/mlir/compiler/dialect/type.cpp
  src/contrib/mlir/compiler/dialect/type.hpp
  src/contrib/mlir/compiler/lowerer.cpp
  src/contrib/mlir/compiler/lowerer.hpp
  src/contrib/mlir/compiler/memory_manager.cpp
  src/contrib/mlir/compiler/memory_manager.hpp
  src/contrib/mlir/compiler/op_lowerers.inc
  src/contrib/mlir/compiler/ops_supported.inc
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.hpp
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/mlir_cpu_compiled_kernel.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
Labels: Fully Reviewed

#3547 Show more info in error to help debugging
  src/ngraph/descriptor/tensor.cpp
Labels: Fully Reviewed

#3437 Rename auto broadcast parameter name in constructors
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/and.cpp
  src/ngraph/op/and.hpp
  src/ngraph/op/divide.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/equal.cpp
  src/ngraph/op/equal.hpp
  src/ngraph/op/greater.cpp
  src/ngraph/op/greater.hpp
  src/ngraph/op/greater_eq.cpp
  src/ngraph/op/greater_eq.hpp
  src/ngraph/op/less.cpp
  src/ngraph/op/less.hpp
  src/ngraph/op/less_eq.cpp
  src/ngraph/op/less_eq.hpp
  src/ngraph/op/maximum.cpp
  src/ngraph/op/maximum.hpp
  src/ngraph/op/minimum.cpp
  src/ngraph/op/minimum.hpp
  src/ngraph/op/multiply.cpp
  src/ngraph/op/multiply.hpp
  src/ngraph/op/not_equal.cpp
  src/ngraph/op/not_equal.hpp
  src/ngraph/op/or.cpp
  src/ngraph/op/or.hpp
  src/ngraph/op/power.cpp
  src/ngraph/op/power.hpp
  src/ngraph/op/subtract.cpp
  src/ngraph/op/subtract.hpp
  src/ngraph/op/xor.cpp
  src/ngraph/op/xor.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#3454 [Spec] Implement support for axes input of LRN op in reference implementation
  src/ngraph/op/lrn.cpp
  src/ngraph/op/lrn.hpp
  src/ngraph/runtime/cpu/builder/lrn.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/gpuh/unit_test.manifest
  src/ngraph/runtime/intelgpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/lrn.hpp
  test/backend/lrn.in.cpp
  test/ref_generators/generate_lrn_across_axes.py
  test/type_prop/lrn.cpp
Labels: Fully Reviewed

#3538 Fixed Proposal output type infer
  src/ngraph/op/experimental/layers/proposal.cpp
Labels: Fully Reviewed

#3531 make sure regex read all the way to the end of line
  cmake/Modules/git_tags.cmake
Labels: Fully Reviewed

#3540 [MLIR] Add support for Convolution Op without Padding
  src/contrib/mlir/compiler/compiler.cpp
  src/contrib/mlir/compiler/compiler.hpp
  src/contrib/mlir/compiler/dialect/ops.cpp
  src/contrib/mlir/compiler/dialect/ops.td
  src/contrib/mlir/compiler/lowerer.cpp
  src/contrib/mlir/compiler/op_lowerers.inc
  src/contrib/mlir/compiler/ops_supported.inc
  src/contrib/mlir/compiler/pass/mlir_subgraph_extraction.cpp
  test/backend/convolution.in.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed
