Repository NervanaSystems/ngraph, pull requests merged in 2020-05, with the labels that each got.

#4624 Add visitor and default axis to CumSum for opset3
  src/ngraph/op/cum_sum.cpp
  src/ngraph/op/cum_sum.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/attributes.cpp
  test/backend/cum_sum.in.cpp
Labels: Fully Reviewed, OV

#4627 Add build rules to find OpenVINO inference engine
  src/ngraph/runtime/ie/CMakeLists.txt
Labels: Fully Reviewed, OV

#4628 Bucketize op shell implementation
  src/ngraph/CMakeLists.txt
  src/ngraph/op/bucketize.cpp
  src/ngraph/op/bucketize.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/CMakeLists.txt
  test/attributes.cpp
  test/type_prop/bucketize.cpp
Labels: Fully Reviewed

#4643 Add reference kernel for non-zero
  src/ngraph/pass/constant_folding_non_zero.cpp
  src/ngraph/runtime/reference/non_zero.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed, OV

#4652 Convert remaining binary elementwise ops to use evaluate
  src/ngraph/CMakeLists.txt
  src/ngraph/op/and.cpp
  src/ngraph/op/and.hpp
  src/ngraph/op/equal.cpp
  src/ngraph/op/equal.hpp
  src/ngraph/op/greater.cpp
  src/ngraph/op/greater.hpp
  src/ngraph/op/greater_eq.cpp
  src/ngraph/op/greater_eq.hpp
  src/ngraph/op/less.cpp
  src/ngraph/op/less.hpp
  src/ngraph/op/less_eq.cpp
  src/ngraph/op/less_eq.hpp
  src/ngraph/op/not_equal.cpp
  src/ngraph/op/not_equal.hpp
  src/ngraph/op/or.cpp
  src/ngraph/op/or.hpp
  src/ngraph/op/xor.cpp
  src/ngraph/op/xor.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/host_tensor.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/equal.hpp
  src/ngraph/runtime/reference/greater.hpp
  src/ngraph/runtime/reference/greater_eq.hpp
  src/ngraph/runtime/reference/less.hpp
  src/ngraph/runtime/reference/less_eq.hpp
  src/ngraph/runtime/reference/not_equal.hpp
  src/ngraph/runtime/reference/or.hpp
  src/ngraph/runtime/reference/xor.hpp
Labels: Fully Reviewed, OV

#4661 Provide case-insensitive access to opset
  src/ngraph/opsets/opset.cpp
  src/ngraph/opsets/opset.hpp
  test/opset1.cpp
Labels: Fully Reviewed, OV

#4682 [Py] Support for different opsets ver from ops.py
  python/src/ngraph/ops.py
  python/src/pyngraph/node_factory.cpp
Labels: Fully Reviewed

#4654 NonZero evaluate support
  src/ngraph/CMakeLists.txt
  src/ngraph/op/non_zero.cpp
  src/ngraph/op/non_zero.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_non_zero.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/ie/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/opset_int_tbl.hpp
  test/CMakeLists.txt
  test/backend/non_zero.in.cpp
  test/eval.cpp
  test/op_eval/non_zero.cpp
  test/type_prop/non_zero.cpp
Labels: DO NOT SQUASH, Fully Reviewed, OV

#4680 Fix get_broadcast_axes() for Broadcast v3 bidirectional
  src/ngraph/op/broadcast.cpp
Labels: Fully Reviewed

#4685 Add method to create a backend dynamic tensor
  src/ngraph/runtime/backend.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.hpp
  src/ngraph/runtime/gcpu/gcpu_backend.cpp
  src/ngraph/runtime/gcpu/gcpu_backend.hpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/runtime/gpu/gpu_backend.cpp
  src/runtime/gpu/gpu_backend.hpp
  src/runtime/nop/nop_backend.cpp
  src/runtime/nop/nop_backend.hpp
  test/eval.cpp
Labels: Fully Reviewed

#4651 Cyphers/constant
  src/ngraph/attribute_visitor.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/host_tensor.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/tensor.cpp
  test/attributes.cpp
Labels: Fully Reviewed, High Priority, OV

#4691 Add option to enable Address Sanitizer
  CMakeLists.txt
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/pass/nop_elimination.cpp
  src/ngraph/validation_util.cpp
  test/backend/dyn_slice_reference.in.cpp
  test/cpio.cpp
  test/ref_generators/generate_dyn_slice_ref.py
Labels: Fully Reviewed

#4693 Get an error when a node doesn't evaluate
  src/ngraph/validation_util.cpp
Labels: Fully Reviewed, OV

#4694 Revert #4627
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/non_zero.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/opsets/opset.cpp
  src/ngraph/opsets/opset.hpp
  src/ngraph/runtime/ie/CMakeLists.txt
  src/ngraph/runtime/ie/ie_backend.cpp
  src/ngraph/runtime/ie/ie_backend.hpp
  src/ngraph/runtime/ie/ie_executable.cpp
  src/ngraph/runtime/ie/unit_test.manifest
  test/backend/non_zero.in.cpp
  test/constant_folding.cpp
  test/op_eval/non_zero.cpp
  test/type_prop/non_zero.cpp
Labels: Fully Reviewed

#4700 use cast_vector in op infer
  src/ngraph/op/constant.cpp
  src/ngraph/op/experimental/dyn_replace_slice.cpp
  src/ngraph/op/experimental/dyn_slice.cpp
  src/ngraph/op/split.cpp
  src/ngraph/op/tile.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/util/logical_reduction.cpp
Labels: Fully Reviewed, High Priority, OV

#4686 Visitor API for misc ops
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/op/reorg_yolo.cpp
  src/ngraph/op/reorg_yolo.hpp
  src/ngraph/op/roi_pooling.cpp
  src/ngraph/op/roi_pooling.hpp
  src/ngraph/serializer.cpp
  test/attributes.cpp
Labels: Fully Reviewed, Passed OV CI

#4646 Update nGraph PythonAPI
  python/src/ngraph/__init__.py
  python/src/ngraph/ops.py
  python/src/ngraph/utils/node_factory.py
  python/src/ngraph/utils/types.py
  python/test/ngraph/test_basic.py
  python/test/ngraph/test_create_op.py
  python/test/ngraph/test_data_movement.py
  python/test/ngraph/test_normalization.py
  python/test/ngraph/test_ops_binary.py
  python/test/ngraph/test_ops_fused.py
  python/test/ngraph/test_ops_reshape.py
  python/test/ngraph/test_ops_scatter.py
  python/test/ngraph/test_ops_unary.py
  python/test/ngraph/test_reduction.py
  python/tox.ini
  src/ngraph/op/cum_sum.cpp
  src/ngraph/op/cum_sum.hpp
  src/ngraph/op/fused/space_to_batch.hpp
  src/ngraph/op/reverse_sequence.hpp
  src/ngraph/op/roi_pooling.hpp
  src/ngraph/opsets/opset.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
Labels: Fully Reviewed, Passed OV CI

#4690 Fix out of bounds access bug.
  src/ngraph/util.cpp
Labels: Bug, Fully Reviewed

#4695 Cyphers/opsetcheck
  src/ngraph/opsets/opset.hpp
  src/ngraph/runtime/ie/ie_executable.cpp
Labels: Fully Reviewed

#4709 Make address sanitizer work on mac
  CMakeLists.txt
  cmake/sdl.cmake
Labels: Fully Reviewed

#4711 Fixed compilation with Intel compiler 19.1.1.217 20200306
  src/ngraph/variant.cpp
  src/ngraph/variant.hpp
  test/attributes.cpp
Labels: Fully Reviewed, OV

#4705 add evaluate for Concat
  src/ngraph/CMakeLists.txt
  src/ngraph/op/concat.cpp
  src/ngraph/op/concat.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_concat.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/eval.cpp
Labels: Fully Reviewed

#4719 Cyphers/python
  python/src/ngraph/ops.py
  src/ngraph/runtime/ie/ie_executable.cpp
Labels: Fully Reviewed, High Priority

#4708 Reimplemented Transpose->Reshape optimization
  src/ngraph/pass/algebraic_simplification.cpp
  test/algebraic_simplification.cpp
Labels: Fully Reviewed, High Priority, Passed OV CI

#4704 Cyphers/moremax
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/eval.cpp
Labels: Fully Reviewed, High Priority, OV

#4707 Add evaluate for gather
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_gather.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/eval.cpp
Labels: Fully Reviewed, High Priority, OV

#4727 Fix element_type_traits for bool
  src/ngraph/type/element_type_traits.hpp
Labels: Bug, Fully Reviewed, High Priority, OV

#4625 Add Interpolate v3 Shell Op
  src/ngraph/attribute_adapter.cpp
  src/ngraph/attribute_adapter.hpp
  src/ngraph/frontend/onnx_import/op/resize.cpp
  src/ngraph/op/interpolate.cpp
  src/ngraph/op/interpolate.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  src/ngraph/serializer.cpp
  test/serialize.cpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed, OV

#4630 Add evaluate to convert
  src/ngraph/op/convert.cpp
  src/ngraph/op/convert.hpp
  src/ngraph/runtime/reference/add.hpp
  test/eval.cpp
Labels: Fully Reviewed, OV

#4663 add Clamp reference kernel
  src/ngraph/op/fused/clamp.cpp
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/clamp.hpp
  src/ngraph/util.hpp
  test/backend/fused_op.in.cpp
  test/util.cpp
Labels: Fully Reviewed, OV

#4665 Constant Folding using Evaluate method for reshape::v0/v1
  src/ngraph/CMakeLists.txt
  src/ngraph/op/reshape.cpp
  src/ngraph/op/reshape.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_reshape.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/constant_folding.cpp
  test/eval.cpp
Labels: Fully Reviewed, OV

#4697 [Py] Add PartialShape and Dimension to Python API
  python/setup.py
  python/src/ngraph/impl/__init__.py
  python/src/pyngraph/dimension.cpp
  python/src/pyngraph/dimension.hpp
  python/src/pyngraph/partial_shape.cpp
  python/src/pyngraph/partial_shape.hpp
  python/src/pyngraph/pyngraph.cpp
  python/src/pyngraph/shape.cpp
  python/test/ngraph/test_core.py
Labels: Fully Reviewed, High Priority, PyAPI

#4733 Add identity for integer types for ceil and floor
  src/ngraph/op/ceiling.cpp
  src/ngraph/op/floor.cpp
Labels: High Priority

#4716 [Py] Add BatchNormInference op to Python API
  python/src/ngraph/__init__.py
  python/src/ngraph/ops.py
  python/test/ngraph/test_create_op.py
  python/test/ngraph/test_normalization.py
Labels: Fully Reviewed, High Priority, PyAPI

#4689 Upgrade v0::reshape to v1::reshape in opset1 upgrade.
  src/ngraph/pass/opset1_upgrade.cpp
Labels: Fully Reviewed

#4723 [Py] Update Python API - RNN ops
  python/src/ngraph/__init__.py
  python/src/ngraph/ops.py
  python/test/ngraph/test_create_op.py
  python/test/ngraph/test_ops_fused.py
Labels: Fully Reviewed, High Priority, Merge Blocked, PyAPI

#4640 [Py API] small refactor of NodeFactory + Py helpers
  python/src/ngraph/ops.py
  python/src/pyngraph/node_factory.cpp
Labels: Fully Reviewed, High Priority, OV, Passed OV CI, PyAPI

#4668 EmbeddingBagOffsetsSums op shell
  src/ngraph/CMakeLists.txt
  src/ngraph/op/embeddingbag_offsets_sum.cpp
  src/ngraph/op/embeddingbag_offsets_sum.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/util/embeddingbag_offsets_base.cpp
  src/ngraph/op/util/embeddingbag_offsets_base.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/CMakeLists.txt
  test/type_prop/embeddingbag_offsetssum.cpp
Labels: Fully Reviewed, OV

#4664 add more squeeze unsqueeze optimizations and check gather usecase
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/nop_elimination.cpp
  test/algebraic_simplification.cpp
  test/eval.cpp
  test/nop_elimination.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed, OV

#4677 EmbeddingSegmentsSum op shell
  src/ngraph/CMakeLists.txt
  src/ngraph/op/embedding_segments_sum.cpp
  src/ngraph/op/embedding_segments_sum.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/CMakeLists.txt
  test/type_prop/embedding_segments_sum.cpp
Labels: Fully Reviewed, OV

#4714 ONNX Softmax adjustments
  python/test/ngraph/test_ops_unary.py
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  test/models/onnx/softmax_0D.prototxt
  test/models/onnx/softmax_1D.prototxt
  test/models/onnx/softmax_axis_0.prototxt
  test/models/onnx/softmax_axis_1.prototxt
  test/models/onnx/softmax_axis_2.prototxt
  test/models/onnx/softmax_invalid_axis_1D.prototxt
  test/models/onnx/softmax_invalid_axis_3D.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed

#4732 Update basic VariantWrappers with NGRAPH_API
  src/ngraph/variant.hpp
Labels: Fully Reviewed, OV

#4676 EmbeddingBagPackedSum op shell
  src/ngraph/CMakeLists.txt
  src/ngraph/op/embeddingbag_packedsum.cpp
  src/ngraph/op/embeddingbag_packedsum.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/util/embeddingbag_packed_base.cpp
  src/ngraph/op/util/embeddingbag_packed_base.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/CMakeLists.txt
  test/type_prop/embeddingbag_packedsum.cpp
Labels: Fully Reviewed, OV

#4702 Fix some Undefined Behavior errors
  src/ngraph/op/binary_convolution.cpp
  src/ngraph/op/binary_convolution.hpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/util.cpp
  test/serialize.cpp
  test/util/test_tools.hpp
Labels: Bug, Fully Reviewed, OV

#4730 Add reference kernel for matmul
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/autobroadcast.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/matmul.hpp
  test/backend/matmul.in.cpp
Labels: Fully Reviewed, OV

#4729 adding reference kernels for arithmetic reduction ops
  src/ngraph/op/max.cpp
  src/ngraph/op/max.hpp
  src/ngraph/op/min.cpp
  src/ngraph/op/min.hpp
  src/ngraph/op/product.cpp
  src/ngraph/op/product.hpp
  src/ngraph/op/reduce_mean.cpp
  src/ngraph/op/reduce_mean.hpp
  src/ngraph/op/reduce_prod.cpp
  src/ngraph/op/reduce_prod.hpp
  src/ngraph/op/reduce_sum.cpp
  src/ngraph/op/reduce_sum.hpp
  src/ngraph/op/sum.cpp
  src/ngraph/op/sum.hpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/runtime/cpu/kernel/reduce_max.hpp
  src/ngraph/runtime/cpu/kernel/reduce_min.hpp
  src/ngraph/runtime/cpu/kernel/reduce_product.hpp
  src/ngraph/runtime/cpu/kernel/reduce_sum.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/max.hpp
  src/ngraph/runtime/reference/mean.hpp
  src/ngraph/runtime/reference/min.hpp
  src/ngraph/runtime/reference/product.hpp
  src/ngraph/runtime/reference/softmax.hpp
  src/ngraph/runtime/reference/sum.hpp
  test/CMakeLists.txt
  test/backend/reduce_max.in.cpp
  test/backend/reduce_mean.in.cpp
  test/backend/reduce_min.in.cpp
  test/backend/reduce_prod.in.cpp
  test/backend/reduce_sum.in.cpp
Labels: Fully Reviewed, OV

#4623 [ONNX] ONNX Importer as shared library.
  cmake/external_onnx.cmake
  python/setup.py
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/matmul_factory.hpp
  src/ngraph/builder/quantization/quantized_linear_convolution.hpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/builder/split.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/onnx.hpp
  src/ngraph/frontend/onnx_import/onnx_utils.hpp
  src/ngraph/frontend/onnx_import/utils/onnx_importer_visibility.hpp
  src/ngraph/op/interpolate.cpp
  src/ngraph/runtime/ie/unit_test.manifest
  src/ngraph/util.hpp
  src/tools/run_onnx_model/CMakeLists.txt
  src/tools/serialize_onnx/CMakeLists.txt
  test/CMakeLists.txt
Labels: Changes API, Fully Reviewed, ONNX, OV, Passed OV CI

#4748 Some random fixes that broke OV CI
  src/ngraph/op/binary_convolution.cpp
  src/ngraph/op/binary_convolution.hpp
  src/ngraph/runtime/ie/unit_test.manifest
Labels: Fully Reviewed, High Priority

#4737 Fix Ninja build on mac.
  cmake/external_protobuf.cmake
Labels: Fully Reviewed

#4696 Dynamic backend support ngraph-onnx, enabled tests for dynamic flatten
  python/src/ngraph/impl/__init__.py
  python/src/ngraph/runtime.py
  python/src/pyngraph/function.cpp
  python/src/pyngraph/node.cpp
  python/src/pyngraph/runtime/backend.cpp
  python/src/pyngraph/runtime/executable.cpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/flatten.prototxt
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/onnx/onnx_import_reshape.in.cpp
  test/util/test_case.cpp
Labels: Fully Reviewed

#4766 Revert "Dynamic backend support ngraph-onnx, enabled tests for dynamic flatten"
  python/src/ngraph/impl/__init__.py
  python/src/ngraph/runtime.py
  python/src/pyngraph/function.cpp
  python/src/pyngraph/node.cpp
  python/src/pyngraph/runtime/backend.cpp
  python/src/pyngraph/runtime/executable.cpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/flatten.prototxt
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/onnx/onnx_import_reshape.in.cpp
  test/util/test_case.cpp
Labels: Fully Reviewed, High Priority

#4759 Disable IE backend testing
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/CMakeLists.txt
Labels: Fully Reviewed, High Priority

#4718 Create inverse hyperbolic ops
  src/ngraph/CMakeLists.txt
  src/ngraph/op/acosh.cpp
  src/ngraph/op/acosh.hpp
  src/ngraph/op/asinh.cpp
  src/ngraph/op/asinh.hpp
  src/ngraph/op/atanh.cpp
  src/ngraph/op/atanh.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/reference/acosh.hpp
  src/ngraph/runtime/reference/asinh.hpp
  src/ngraph/runtime/reference/atanh.hpp
  test/CMakeLists.txt
  test/backend/acosh.in.cpp
  test/backend/asinh.in.cpp
  test/backend/atanh.in.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, OV

#4731 [Py] More ops exposed to python API
  python/src/ngraph/__init__.py
  python/src/ngraph/ops.py
  python/src/pyngraph/node.cpp
  python/test/ngraph/test_create_op.py
  python/test/ngraph/test_ops_fused.py
  python/test/ngraph/test_ops_scatter.py
  src/ngraph/op/embedding_segments_sum.hpp
  src/ngraph/op/embeddingbag_offsets_sum.hpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/mvn.hpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.hpp
  src/ngraph/op/region_yolo.cpp
  src/ngraph/op/region_yolo.hpp
  src/ngraph/op/reorg_yolo.cpp
  test/attributes.cpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed, High Priority, PyAPI

#4734 Add an identity kernel for use with integer floor, ceiling, and round
  src/ngraph/op/ceiling.cpp
  src/ngraph/op/floor.cpp
  src/ngraph/op/round.cpp
  src/ngraph/op/util/eval_copy.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  test/backend/ceiling.in.cpp
  test/backend/floor.in.cpp
  test/backend/round.in.cpp
Labels: Fully Reviewed, OV

#4752 Add eval and test for transpose
  src/ngraph/op/transpose.cpp
  src/ngraph/op/transpose.hpp
  test/eval.cpp
Labels: Fully Reviewed

#4754 Add codeowners for IE backend
  CODEOWNERS
Labels: Fully Reviewed

#4745 Cyphers/prior
  src/ngraph/op/prior_box.cpp
  src/ngraph/op/prior_box.hpp
Labels: Fully Reviewed, OV

#4703 Add evaluate for broadcast v3, v1, v0
  src/ngraph/CMakeLists.txt
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/broadcast.hpp
  src/ngraph/op/util/broadcast_base.cpp
  src/ngraph/op/util/broadcast_base.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_broadcast.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/eval.cpp
Labels: Fully Reviewed, High Priority, OV

#4675 nGraph v3 op ExtractImagePatches
  src/ngraph/CMakeLists.txt
  src/ngraph/op/extractimagepatches.cpp
  src/ngraph/op/extractimagepatches.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/CMakeLists.txt
  test/attributes.cpp
  test/type_prop/extractimagepatches.cpp
Labels: Fully Reviewed

#4742 Add Evaluate to scatter_elements_update
  src/ngraph/op/scatter_elements_update.cpp
  src/ngraph/op/scatter_elements_update.hpp
  test/eval.cpp
Labels: Fully Reviewed

#4749 evaluate and dynamic evaluate for maxpool
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/eval.cpp
Labels: Fully Reviewed

#4756 Fix function multiple results
  python/test/ngraph/test_ops_multioutput.py
  src/ngraph/function.cpp
Labels: Fully Reviewed, OV, PyAPI

#4771 Swapna/eval transpose
  src/ngraph/op/transpose.cpp
  src/ngraph/op/transpose.hpp
  test/eval.cpp
Labels: Fully Reviewed

#4753 Add evaluate support for MatMul op
  src/ngraph/op/fused/matmul.cpp
  src/ngraph/op/fused/matmul.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/dot.hpp
  src/ngraph/runtime/reference/matmul.hpp
  test/CMakeLists.txt
  test/op_eval/matmul.cpp
Labels: Fully Reviewed, OV

#4769 Remove the RTLD_GLOBAL flag from python API
  python/src/ngraph/impl/__init__.py
  python/src/ngraph/impl/onnx_import/__init__.py
  python/src/ngraph/impl/op/__init__.py
  python/src/ngraph/impl/op/util/__init__.py
  python/src/ngraph/impl/passes/__init__.py
  python/src/ngraph/impl/runtime/__init__.py
  python/src/pyngraph/util.py
Labels: High Priority, PyAPI

#4774 Revert API change introduced in #4731
  python/src/ngraph/ops.py
  python/test/ngraph/test_create_op.py
  src/ngraph/op/region_yolo.cpp
  src/ngraph/op/region_yolo.hpp
  test/attributes.cpp
  test/type_prop_layers.cpp
Labels: Fully Reviewed, High Priority, PyAPI

#4775 Fix validation of Range op
  src/ngraph/op/range.cpp
Labels: Fully Reviewed

#4782 Description fix
  src/ngraph/node.cpp
Labels: Fully Reviewed, OV

#4755 Python API - finishing touches
  python/examples/basic.py
  python/requirements.txt
  python/setup.py
  python/src/ngraph/__init__.py
  python/src/ngraph/impl/__init__.py
  python/src/ngraph/impl/op/__init__.py
  python/src/ngraph/ops.py
  python/src/ngraph/runtime.py
  python/src/ngraph/utils/broadcasting.py
  python/src/ngraph/utils/decorators.py
  python/src/ngraph/utils/input_validation.py
  python/src/ngraph/utils/node_factory.py
  python/src/ngraph/utils/reduction.py
  python/src/ngraph/utils/types.py
  python/src/pyngraph/ops/fused/depth_to_space.cpp
  python/src/pyngraph/ops/fused/depth_to_space.hpp
  python/src/pyngraph/ops/fused/gelu.cpp
  python/src/pyngraph/ops/fused/gelu.hpp
  python/src/pyngraph/ops/fused/grn.cpp
  python/src/pyngraph/ops/fused/grn.hpp
  python/src/pyngraph/ops/fused/hard_sigmoid.cpp
  python/src/pyngraph/ops/fused/hard_sigmoid.hpp
  python/src/pyngraph/ops/fused/mvn.cpp
  python/src/pyngraph/ops/fused/mvn.hpp
  python/src/pyngraph/ops/fused/shuffle_channels.cpp
  python/src/pyngraph/ops/fused/shuffle_channels.hpp
  python/src/pyngraph/ops/fused/space_to_depth.cpp
  python/src/pyngraph/ops/fused/space_to_depth.hpp
  python/src/pyngraph/ops/regmodule_pyngraph_op.cpp
  python/src/pyngraph/ops/regmodule_pyngraph_op.hpp
  python/test/conftest.py
  python/test/ngraph/test_basic.py
  python/test/ngraph/test_convolution.py
  python/test/ngraph/test_core.py
  python/test/ngraph/test_create_op.py
  python/test/ngraph/test_data_movement.py
  python/test/ngraph/test_node_factory.py
  python/test/ngraph/test_normalization.py
  python/test/ngraph/test_onnx_import.py
  python/test/ngraph/test_ops_binary.py
  python/test/ngraph/test_ops_fused.py
  python/test/ngraph/test_ops_matmul.py
  python/test/ngraph/test_ops_multioutput.py
  python/test/ngraph/test_ops_reshape.py
  python/test/ngraph/test_ops_scatter.py
  python/test/ngraph/test_ops_unary.py
  python/test/ngraph/test_pooling.py
  python/test/ngraph/test_reduction.py
  python/test/test_ops.py
  python/test_requirements.txt
  python/tox.ini
  src/ngraph/opsets/opset3_tbl.hpp
Labels: Fully Reviewed, High Priority, PyAPI

#4761 add clamp reference kernel with f16 and bf16 support
  src/ngraph/op/fused/clamp.cpp
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/clamp.hpp
  src/ngraph/util.hpp
  test/backend/fused_op.in.cpp
  test/util.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed

#4783 [Py] Python API for ops with struct unpacked manually
  python/src/ngraph/__init__.py
  python/src/ngraph/ops.py
  python/src/ngraph/utils/input_validation.py
  python/src/pyngraph/node_factory.cpp
  python/test/ngraph/test_basic.py
  python/test/ngraph/test_create_op.py
  python/test/ngraph/test_data_movement.py
  python/test/ngraph/test_input_validation.py
  python/test/ngraph/test_sequence_processing.py
  src/ngraph/op/detection_output.cpp
  src/ngraph/op/detection_output.hpp
  src/ngraph/op/prior_box.cpp
  src/ngraph/op/prior_box.hpp
  src/ngraph/op/prior_box_clustered.cpp
  src/ngraph/op/prior_box_clustered.hpp
  src/ngraph/op/proposal.cpp
  src/ngraph/op/proposal.hpp
  test/attributes.cpp
Labels: Fully Reviewed, OV, PyAPI

#4684 Strided Slice op - evaluate and constant_fold
  src/ngraph/CMakeLists.txt
  src/ngraph/op/strided_slice.cpp
  src/ngraph/op/strided_slice.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_strided_slice.cpp
  src/ngraph/runtime/reference/strided_slice.hpp
  test/CMakeLists.txt
  test/op_eval/strided_slice.cpp
Labels: Fully Reviewed

#4801 Merge dynamic to master
  python/src/ngraph/runtime.py
  python/src/pyngraph/function.cpp
  python/src/pyngraph/node.cpp
  python/src/pyngraph/runtime/backend.cpp
  python/src/pyngraph/runtime/executable.cpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/flatten.prototxt
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/onnx/onnx_import_reshape.in.cpp
  test/util/test_case.cpp
Labels: Fully Reviewed

#4471 remove Dimension operator size_t
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/op/group_conv.cpp
Labels: Fully Reviewed, OV

#4508 add reshape_elimination_v1 pass
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/reshape_elimination_v1.cpp
  src/ngraph/pass/reshape_elimination_v1.hpp
  test/CMakeLists.txt
  test/reshape_elimination_v1.cpp
Labels: Fully Reviewed, OV

#4631 Remove GOE, mostly from unit tests
  src/ngraph/runtime/cpu/op/sigmoid_mul.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  test/backend/autodiff.in.cpp
  test/backend/batch_norm.in.cpp
  test/backend/fused_op.in.cpp
  test/backend/scatter.in.cpp
  test/backend/topk.in.cpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/gpu_fusion.cpp
  test/gpu_test.cpp
  test/replace_node.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#4666 Attribute visitor doc, simplification
  python/src/pyngraph/node_factory.cpp
  src/ngraph/CMakeLists.txt
  src/ngraph/attribute_adapter.cpp
  src/ngraph/attribute_adapter.hpp
  src/ngraph/attribute_visitor.cpp
  src/ngraph/attribute_visitor.hpp
  src/ngraph/axis_set.cpp
  src/ngraph/axis_set.hpp
  src/ngraph/axis_vector.cpp
  src/ngraph/axis_vector.hpp
  src/ngraph/coordinate.cpp
  src/ngraph/coordinate.hpp
  src/ngraph/coordinate_diff.cpp
  src/ngraph/coordinate_diff.hpp
  src/ngraph/factory.hpp
  src/ngraph/factory_adapter.hpp
  src/ngraph/lambda.cpp
  src/ngraph/lambda.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/shuffle_channels.hpp
  src/ngraph/op/parameter.cpp
  src/ngraph/op/parameter.hpp
  src/ngraph/op/reshape.cpp
  src/ngraph/op/reshape.hpp
  src/ngraph/op/result.cpp
  src/ngraph/op/result.hpp
  src/ngraph/op/tensor_iterator.cpp
  src/ngraph/op/tensor_iterator.hpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/runtime/aligned_buffer.cpp
  src/ngraph/runtime/aligned_buffer.hpp
  src/ngraph/serializer.cpp
  src/ngraph/shape.cpp
  src/ngraph/shape.hpp
  src/ngraph/strides.cpp
  src/ngraph/strides.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  test/attributes.cpp
  test/serialize.cpp
  test/type_prop/shuffle_channels.cpp
  test/util/CMakeLists.txt
  test/util/visitor.hpp
Labels: Fully Reviewed

#4712 Remove Travis badge from readme
  README.md
Labels: Fully Reviewed

#4738 Fix clamp test so it reports which test failed
  test/backend/fused_op.in.cpp
  test/util/test_case.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed, OV

#4776 Fix a reshape builder when data is reshaped to scalar.
  src/ngraph/builder/reshape.cpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/op/reshape.cpp
  src/ngraph/pass/nop_elimination.cpp
  src/ngraph/runtime/opt_kernel/broadcast.hpp
  test/backend/reshape.in.cpp
Labels: Fully Reviewed

#4777 Use op::v0::Interpolate in opset3
  src/ngraph/frontend/onnx_import/op/resize.cpp
  src/ngraph/opsets/opset3_tbl.hpp
Labels: Fully Reviewed, High Priority, OV

#4778 Fix building python wheel by cmake and failing pythons tests on Windows
  cmake/external_onnx.cmake
  python/build_wheel.py.in
  python/setup.py
  python/test/ngraph/test_basic.py
  python/test/ngraph/test_ops_reshape.py
  src/ngraph/runtime/interpreter/CMakeLists.txt
Labels: Fully Reviewed

#4781 ShuffleChannels - rename attribute groups->group
  src/ngraph/op/fused/shuffle_channels.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4679 Add CODEGEN support to the CPU backend
  environment_variables.md
  src/contrib/mlir/core/ngraph_dialect/ops_v0.td
  src/ngraph/codegen/compiler.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_executable.cpp
  src/ngraph/runtime/cpu/cpu_executable.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/ie/unit_test.manifest
  src/ngraph/runtime/reference/topk.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/attributes.cpp
  test/backend/partial_slice.in.cpp
  test/backend/topk.in.cpp
  test/cpu_debugger.cpp
  test/cpu_test.cpp
  test/opset_pass/topk_opset_pass.cpp
  test/provenance.cpp
  test/replace_node.cpp
  test/type_prop/top_k.cpp
Labels: Fully Reviewed

#4786 ExtractImagePatches bug fix for input data type..
  src/ngraph/op/extractimagepatches.cpp
Labels: Fully Reviewed

#4789 Removed Acosh, Asinh, Atanh and ScatterNDUpdate from opset3_tbl
  python/src/ngraph/__init__.py
  python/src/ngraph/ops.py
  python/test/ngraph/test_ops_scatter.py
  src/ngraph/opsets/opset3_tbl.hpp
Labels: Fully Reviewed, OV

#4792 Use system wide or user provided clang if available.
  cmake/external_llvm.cmake
Labels: Fully Reviewed

#4797 More info in visualized graphs
  src/ngraph/pass/visualize_tree.cpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#4795 topk
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  test/eval.cpp
Labels: Fully Reviewed

#4798 Remove debug code from unit tests
  test/cpu_fusion.cpp
  test/serialize.cpp
Labels: Fully Reviewed

#4800 Add backend test cases for Mod op
  test/CMakeLists.txt
  test/backend/mod.in.cpp
Labels: Fully Reviewed

#4802 switch to MLIR IntegerType
  cmake/external_mlir.cmake
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/core/ngraph_dialect/dialect.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.hpp
  src/contrib/mlir/core/ngraph_dialect/ops.td
  src/contrib/mlir/core/ngraph_dialect/type.cpp
  src/contrib/mlir/core/ngraph_dialect/type.hpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.hpp
  src/contrib/mlir/core/pass/ng_dialect_fused_ops.cpp
  src/contrib/mlir/tools/ngraph-opt/ngraph_opt.cpp
  src/contrib/mlir/utils.cpp
  test/mlir/ngraph_dialect/elementwise_binary_ops.mlir
  test/mlir/ngraph_dialect/fused_ops.mlir
  test/mlir/ngraph_dialect/types.mlir
Labels: Fully Reviewed, MLIR

#4660 Don't simplify add/multiply with broadcasts
  src/ngraph/pass/algebraic_simplification.cpp
  test/algebraic_simplification.cpp
Labels: Fully Reviewed

#4803 codeowners cleanup
  .ci/travis/centos/Dockerfile
  .ci/travis/run_test.sh
  .ci/travis/ubuntu/Dockerfile
  .travis.yml
  CODEOWNERS
Labels: Fully Reviewed

#4804 Rename Node get_inputs and get_outputs
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/group_conv.cpp
  src/ngraph/pass/fused_op_decomposition.cpp
  src/ngraph/runtime/cpu/cpu_debugger.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
Labels: Fully Reviewed

#4659 Make get_registry_mutex protected and not exported
  src/ngraph/factory.cpp
  src/ngraph/factory.hpp
Labels: Fully Reviewed

#4809 Some minor GOE removal
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed

#4808 A little more node method cleanup
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/group_conv.cpp
  src/ngraph/runtime/cpu/cpu_debugger.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
Labels: Fully Reviewed

#4812 Get GPU backend to compile
  src/runtime/gpu/cuda_emitter.cpp
  src/runtime/gpu/cuda_emitter.hpp
  src/runtime/gpu/cudnn_emitter.cpp
  src/runtime/gpu/cudnn_emitter.hpp
  src/runtime/gpu/gpu_cuda_kernel_builder.hpp
  src/runtime/gpu/gpu_cuda_kernel_ops.hpp
  src/runtime/gpu/gpu_emitter.cpp
  src/runtime/gpu/gpu_executable.hpp
  src/runtime/gpu/gpu_internal_function.cpp
  src/runtime/gpu/gpu_kernel_emitters.cpp
  src/runtime/gpu/pass/gpu_batch_norm_cache.cpp
  src/runtime/gpu/pass/gpu_layout.cpp
  src/runtime/gpu/pass/gpu_rnn_fusion.cpp
  src/runtime/gpu/pass/tensor_memory_reservation.cpp
  test/gpu_fusion.cpp
Labels: Fully Reviewed

#4815 Use PROJECT_*_DIR instead of CMAKE_*_DIR or CMAKE_CURRENT_*_DIR in to…
  CMakeLists.txt
Labels: Fully Reviewed

#4817 Update codeowners for cmake
  CODEOWNERS
Labels: Fully Reviewed

#4810 [MLIR] fix GDBRegistrationListener assert when running MLIR unit tests
  cmake/external_mlir.cmake
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/backend/analysis/memory_analysis.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/core/ngraph_dialect/dialect.cpp
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ngraph_dialect/ops_v0.td
  test/mlir/ops_test.cpp
Labels: Fully Reviewed, MLIR

#4819 GOE cleanup in serializer
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4465 Embed python interpreter in unit-test
  CMakeLists.txt
  cmake/external_pybind11.cmake
  python/CMakeLists.txt
  python/build_wheel.py.in
  python/build_wheel.sh.in
  test/CMakeLists.txt
  test/backend/numpy.in.cpp
  test/main.cpp
Labels: Fully Reviewed

#4821 Remove broken function in serializer
  src/ngraph/serializer.cpp
  src/ngraph/serializer.hpp
  src/ngraph/serializer_stub.cpp
  test/serialize.cpp
Labels: Fully Reviewed
