Repository NervanaSystems/ngraph, pull requests merged in 2020-01, with the labels that each got.

#4063 Enable self-concat to broadcast replacement for a single concat
  src/ngraph/pass/concat_fusion.cpp
  test/concat_fusion.cpp
Labels: Fully Reviewed

#4068 [ONNX] Use v1::Minimum and v1::Maximum in Clip and LeakyRelu
  src/ngraph/frontend/onnx_import/op/clip.cpp
  src/ngraph/frontend/onnx_import/op/leaky_relu.cpp
Labels: Fully Reviewed

#4075 Move functions from header to source file
  src/ngraph/node.cpp
  src/ngraph/node.hpp
Labels: Fully Reviewed

#4090 [ONNX] Use v1::Reshape in GlobalLpPool
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
Labels: Fully Reviewed

#4096 [ONNX] Use v1 ops in ThresholdedRelu
  src/ngraph/frontend/onnx_import/op/thresholded_relu.cpp
Labels: Fully Reviewed

#4106 Remove conditional compile
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/ngraph/builder/make_constant.hpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/pass/constant_folding_convert.cpp
  src/ngraph/pass/constant_folding_reverse.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/runtime/cpu/builder/random_uniform.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  src/tools/nbench/benchmark_utils.cpp
  test/backend/distributed.in.cpp
Labels: Fully Reviewed

#4110 Remove redundant using definitions for NodeVector and OutputVector
  src/ngraph/autodiff/adjoints.hpp
  src/ngraph/node.hpp
  src/ngraph/output_vector.hpp
Labels: Fully Reviewed

#4122 Fix maxpoolbprop layout pass
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#4126 Move Constant non-templated constructor implementation to the source file
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
Labels: Fully Reviewed

#4051 Update MKLDNN to v1.1.1.
  cmake/external_mkldnn_v1.cmake
  cmake/mkldnn_v1.patch
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
Labels: Fully Reviewed

#4089 [ONNX] Use v1 ops in Shrink
  src/ngraph/frontend/onnx_import/op/shrink.cpp
Labels: Fully Reviewed

#4083 [ONNX] Use v1::Broadcast in ONNX LpNorm
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
Labels: Fully Reviewed

#4092 [ONNX] Use v1 ops in Softplus
  src/ngraph/frontend/onnx_import/op/softplus.cpp
Labels: Fully Reviewed

#4135 Migrate PR#4122 from master.
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/max_pool.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pregenerated_src/cpu_cg_runtime_context.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#4127 Fix serializer so it can serialize PP BERT large
  src/ngraph/serializer.cpp
Labels: Bug, Fully Reviewed, High Priority

#4084 [ONNX] Update Reduction ops to use v1 operators.
  src/ngraph/builder/norm.hpp
  src/ngraph/frontend/onnx_import/op/reduce.cpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  test/CMakeLists.txt
  test/opset_pass/product_opset_pass.cpp
  test/opset_pass/reduction_opset_pass.cpp
  test/opset_pass/sum_opset_pass.cpp
Labels: Fully Reviewed, ONNX

#4137 Fix serializer so it can serialize PP BERT large (#4127)
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4067 CSE optimizations
  src/ngraph/pass/cse.cpp
Labels: Fully Reviewed

#4136 Add unit test to check that every v0 op properly implements the is_* methods in Node
  test/CMakeLists.txt
  test/op_is.cpp
Labels: Fully Reviewed

#4132 Remove ScalarConstantLikeBase
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/pass/like_replacement.cpp
  src/ngraph/pass/nop_elimination.cpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4079 [MLIR] Add option NGRAPH_EXPORT_TARGETS_ENABLE
  CMakeLists.txt
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#4131 Greatly simplify the GCPU backend
  src/ngraph/runtime/generic_cpu/gcpu_executable.cpp
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
  src/ngraph/runtime/generic_cpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
Labels: Fully Reviewed

#4130 Call generic CPU kernels for Broadcast and Reshape
  src/ngraph/pass/constant_folding_broadcast.cpp
  src/ngraph/pass/constant_folding_reshape.cpp
  src/ngraph/runtime/generic_cpu/kernel/broadcast.hpp
  src/ngraph/runtime/generic_cpu/kernel/reshape.hpp
  src/ngraph/runtime/opt_kernel/broadcast.hpp
  src/ngraph/runtime/opt_kernel/reshape.hpp
Labels: Fully Reviewed

#4117 [MLIR] Remove dead code in sub-graph extraction
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.hpp
Labels: Fully Reviewed, MLIR

#4148 Fix klocwork issues
  src/ngraph/pass/constant_folding_select.cpp
Labels: Fully Reviewed

#4098 Use ngraph::normalize in onnx_importer
  src/ngraph/frontend/onnx_import/op/concat.cpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/gather.hpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/frontend/onnx_import/op/mean_variance_normalization.cpp
  src/ngraph/frontend/onnx_import/op/reverse_sequence.cpp
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
Labels: Fully Reviewed

#4069 Upgrade Add, Sub, Mul and Div ops to v1 in set_1
  src/ngraph/frontend/onnx_import/op/add.cpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
Labels: Fully Reviewed

#4108 Add provenance tags to ONNX importer
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/serializer.cpp
  test/models/onnx/provenance_tag_add.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#4138 Move some ops into v0
  src/ngraph/graph_util.hpp
  src/ngraph/node.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/parameter.hpp
  src/ngraph/op/result.hpp
  src/ngraph/op/topk.hpp
  src/ngraph/opsets/opset1_tbl.hpp
Labels: Fully Reviewed

#4140 [ONNX] Change Slice and Where to produce v1 ops
  src/ngraph/frontend/onnx_import/op/slice.cpp
  src/ngraph/frontend/onnx_import/op/where.hpp
Labels: Fully Reviewed, ONNX

#4151 [MLIR] Add missing installation of mlir core lib
  src/contrib/mlir/core/CMakeLists.txt
Labels: Fully Reviewed, MLIR

#4055 Modernize a pass
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.hpp
Labels: Fully Reviewed

#4153 Patch for ngraph.ai documentation: Update sitemap to not use a page title
  doc/sphinx/source/sitemap.rst
Labels: Fully Reviewed, High Priority

#4155 [ONNX] Remove Reciprocal FusedOp and move definition to ONNX importer.
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/reciprocal.cpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/backend/fused_op.in.cpp
  test/models/onnx/reciprocal.prototxt
  test/onnx/onnx_import.in.cpp
  test/op_is.cpp
  test/type_prop/unary_elementwise.cpp
Labels: Fully Reviewed, ONNX

#4082 [ONNX] Upgrade Pad op to version 11
  src/ngraph/frontend/onnx_import/op/pad.cpp
  src/ngraph/frontend/onnx_import/op/pad.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/pad_constant.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#4076 [SPEC] Add using Reshape:v1
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/gemm.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/transpose.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/op/experimental/transpose.hpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/opsets/opset1_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/op_is.cpp
  test/opset1.cpp
  test/opset_pass/transpose_opset_pass.cpp
Labels: Fully Reviewed, High Priority, SPEC

#4105 Add testing for serializing and deserializing graphs
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/serializer.cpp
  src/ngraph/type/element_type.cpp
  test/onnx/onnx_import_convpool.in.cpp
Labels: Bug, Fully Reviewed

#4161 [MLIR] Revert MLIR core lib creation
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/core/CMakeLists.txt
  src/contrib/mlir/tools/ngraph-opt/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Bug, Fully Reviewed, MLIR

#4119 Fixed creation NonMaxSuppression op with dynamic shapes
  src/ngraph/op/non_max_suppression.cpp
Labels: Dynamic Shape, Fully Reviewed

#4123 [ONNX] Use v1 ops in Convolution operator.
  src/ngraph/frontend/onnx_import/op/conv.cpp
  test/opset_pass/reduction_opset_pass.cpp
Labels: Fully Reviewed, ONNX

#4162 Fix klocwork issues
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/op/util/logical_reduction_keep_dims.cpp
  src/ngraph/pass/constant_folding_one_hot.cpp
  src/ngraph/runtime/reference/one_hot.hpp
Labels: Fully Reviewed, High Priority

#4124 Add Round op
  src/ngraph/CMakeLists.txt
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/round.cpp
  src/ngraph/op/round.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/pass/constant_folding_unary.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/kernel/round.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/runtime/reference/round.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/round.in.cpp
  test/op_is.cpp
Labels: Fully Reviewed

#4139 Change LogSoftmax to produce v1 and remove FusedOp
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/log_softmax.cpp
  src/ngraph/op/fused/log_softmax.cpp
  src/ngraph/op/fused/log_softmax.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/op_is.cpp
  test/type_prop/log_softmax.cpp
Labels: Fully Reviewed

#4150 Move GCPU to runtime/gcpu so that unit test manifest works
  CMakeLists.txt
  src/ngraph/runtime/CMakeLists.txt
  src/ngraph/runtime/gcpu/CMakeLists.txt
  src/ngraph/runtime/gcpu/gcpu_backend.cpp
  src/ngraph/runtime/gcpu/gcpu_backend.hpp
  src/ngraph/runtime/gcpu/gcpu_backend_visibility.hpp
  src/ngraph/runtime/gcpu/gcpu_executable.cpp
  src/ngraph/runtime/gcpu/gcpu_executable.hpp
  src/ngraph/runtime/gcpu/kernel/dot.hpp
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/generic_cpu/gcpu_executable.hpp
Labels: Fully Reviewed

#4164 Restore constant folding for DynReshape until users are converted to …
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  test/dyn_elimination.cpp
  test/models/paddlepaddle/transpose.json
Labels: Bug, Fully Reviewed

#4171 Fix topk deserialize to be backwards compatible
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4173 Fix op::Pad::set_padding_above to set m_padding_above
  src/ngraph/op/pad.hpp
Labels: Fully Reviewed

#4166 Update doc to 0.28
  doc/sphinx/source/conf.py
  doc/sphinx/source/ops/constant.rst
  doc/sphinx/source/ops/parameter.rst
  doc/sphinx/source/ops/result.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/training/index.rst
  doc/sphinx/source/training/overview.rst
Labels: Fully Reviewed

#4156 Added FP32 to FP16 conversion transformation
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/convert_fp32_to_fp16.cpp
  src/ngraph/pass/convert_fp32_to_fp16.hpp
Labels: Fully Reviewed, ROV4

#4159 Do direct FakeQuantize type propagation
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/fake_quantize.hpp
Labels: Fully Reviewed, ROV4

#4160 Direct shape inference for MVN
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
Labels: Fully Reviewed, ROV4

#4169 Fix op::Pad::set_padding_above to set m_padding_above
  src/ngraph/op/pad.hpp
Labels: Fully Reviewed

#4172 Fix topk deserialize to be backwards compatible v0.28
  src/ngraph/serializer.cpp
Labels: Fully Reviewed, High Priority

#3832 [MLIR] In-place memory optimization for elt-wise and concat ops.
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/backend/analysis/memory_analysis.cpp
  src/contrib/mlir/backend/analysis/memory_analysis.hpp
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/backend/pass/memory_optimization.cpp
  src/contrib/mlir/backend/pass/memory_optimization.hpp
  src/contrib/mlir/backend/pass/op_lowerers.inc
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.hpp
  test/backend/concat.in.cpp
  test/mlir/affine_conversion/memory_opt.mlir
Labels: Fully Reviewed, MLIR

#4170 Fix op::Pad::set_padding_above to set m_padding_above
  src/ngraph/op/pad.hpp
Labels: Fully Reviewed

#4052 [PY] Add flag to compile python API in debug mode
  python/setup.py
Labels: Fully Reviewed

#4154 [ONNX] Extended support for provenance tags
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  test/CMakeLists.txt
  test/models/onnx/provenance_input_tags.prototxt
  test/models/onnx/provenance_multiple_outputs_op.prototxt
  test/models/onnx/provenance_node_name_and_outputs.prototxt
  test/models/onnx/provenance_only_outputs.prototxt
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_provenance.in.cpp
Labels: Fully Reviewed, ONNX

#4053 [ONNX] Remove unnecesary Mean in opset 8
  src/ngraph/frontend/onnx_import/op/mean.cpp
  src/ngraph/frontend/onnx_import/op/mean.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
Labels: Fully Reviewed, ONNX

#4165 [ LSTMCell ] Setting number of outputs for LSTMCell op
  src/ngraph/op/fused/lstm_cell.cpp
Labels: Fully Reviewed, High Priority, ROV4

#4178 Revert "Remove conditional compile (#4106)"
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/ngraph/builder/make_constant.hpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/open_mpi.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/topk.cpp
  src/ngraph/pass/constant_folding_convert.cpp
  src/ngraph/pass/constant_folding_reverse.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/runtime/cpu/builder/random_uniform.cpp
  src/ngraph/runtime/gcpu/gcpu_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  src/tools/nbench/benchmark_utils.cpp
  test/backend/distributed.in.cpp
Labels: Fully Reviewed

#4180 Fixed bug in from_float_vector
  src/ngraph/type/bfloat16.cpp
Labels: Fully Reviewed

#4181 Support for bf16 & f16 for test utility read_float_vector
  src/ngraph/util.cpp
Labels: Fully Reviewed

#4184 Added NGRAPH_API for fp32 to fp16 conversion
  src/ngraph/pass/convert_fp32_to_fp16.hpp
Labels: High Priority

#4185 Add fluid lookup_table_v2 op
  src/ngraph/frontend/fluid/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/lookup_table.cpp
  src/ngraph/frontend/fluid/operators/lookup_table.hpp
  src/ngraph/frontend/fluid/operators/test/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/test/lookup_table.cpp
Labels: Dynamic Shape, Fluid, Fully Reviewed

#3838 [MLIR] Use call back for MatMul.
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/backend/pass/op_lowerers.inc
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops_v0.td
  src/contrib/mlir/core/ops_supported.inc
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/contrib/mlir/runtime/cpu/callback_utils.hpp
  src/contrib/mlir/runtime/cpu/cpu_callbacks.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.hpp
  src/contrib/mlir/runtime/runtime.hpp
  src/ngraph/op/fused/gemm.cpp
  src/ngraph/runtime/cpu/builder/mlir_cpu_compiled_kernel.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  test/CMakeLists.txt
  test/backend/fused_op.in.cpp
  test/backend/matmul.in.cpp
  test/mlir/affine_conversion/callback_ops.mlir
Labels: Fully Reviewed, IntelCPU, MLIR

#4144 Build LLVM at CMake configure time and use CMake config file.
  CMakeLists.txt
  cmake/clang_4_0_flags.cmake
  cmake/external_gtest.cmake
  cmake/external_llvm.cmake
  cmake/external_llvm_prebuilt.cmake
  cmake/llvm.patch
  cmake/llvm_fetch.cmake.in
  cmake/sdl.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/resource/CMakeLists.txt
Labels: Fully Reviewed

#4147 [MLIR] Use more threads when building mlir+llvm
  cmake/external_mlir.cmake
  cmake/mlir_fetch.cmake.in
Labels: Fully Reviewed, MLIR

#4182 [MLIR] Remove halide.
  CMakeLists.txt
  cmake/external_halide.cmake
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/broadcast.cpp
  src/ngraph/runtime/cpu/builder/compiled_kernel.cpp
  src/ngraph/runtime/cpu/builder/halide_generators.cpp
  src/ngraph/runtime/cpu/builder/halide_generators.hpp
  src/ngraph/runtime/cpu/builder/halide_op.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/op/halide_op.cpp
  src/ngraph/runtime/cpu/op/halide_op.hpp
  src/ngraph/runtime/cpu/pass/halide_subgraph_extraction.cpp
  src/ngraph/runtime/cpu/pass/halide_subgraph_extraction.hpp
  test/CMakeLists.txt
  test/cpu_test.cpp
  test/halide.cpp
Labels: Fully Reviewed

#4193 Fix memopt tests
  test/mlir/affine_conversion/memory_opt.mlir
Labels: MLIR

#4102 [MLIR] Enable lowering of GroupConv in MLIR CPU backend
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/backend/pass/op_lowerers.inc
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ops_supported.inc
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  test/mlir/affine_conversion/core_ops.mlir
Labels: Fully Reviewed, MLIR

#4060 Robust debugging docs
  doc/sphinx/ngraph_theme/static/css/theme.css
  doc/sphinx/source/core/passes/passes.rst
  doc/sphinx/source/frameworks/index.rst
  doc/sphinx/source/frameworks/other/index.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/inspection/debug_core.rst
  doc/sphinx/source/inspection/debug_onnx.rst
  doc/sphinx/source/inspection/debug_paddle.rst
  doc/sphinx/source/inspection/debug_tf.rst
  doc/sphinx/source/inspection/index.rst
  doc/sphinx/source/inspection/profiling.rst
  doc/sphinx/source/inspection/viz_tools.rst
  doc/sphinx/source/ops/transpose.rst
  doc/sphinx/source/project/release-notes.rst
  doc/sphinx/source/sitemap.rst
Labels: Documentation, Fully Reviewed

#4101 Ninja build
  CMakeLists.txt
  cmake/external_gtest.cmake
  cmake/external_mkldnn.cmake
  cmake/external_mkldnn_v1.cmake
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
  cmake/external_tbb_prebuilt.cmake
  src/ngraph/frontend/fluid/operators/test/CMakeLists.txt
  test/util/CMakeLists.txt
Labels: Fully Reviewed

#4201 Update copyright year.
  src/ngraph/output_vector.hpp
  src/ngraph/runtime/opt_kernel/broadcast.hpp
Labels: Fully Reviewed

#4199 Simplify constant folding for dynamic reshape (v1::Reshape)
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
Labels: ROV4

#4188 [MLIR] Update build system to use LLVM mono-repo for MLIR
  cmake/external_mlir.cmake
  cmake/mlir_fetch.cmake.in
  src/contrib/mlir/backend/analysis/memory_analysis.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/core/ngraph_dialect/dialect.cpp
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.td
  src/contrib/mlir/core/ngraph_dialect/ops_v0.td
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  test/mlir/CMakeLists.txt
  test/mlir/affine_conversion/core_ops.mlir
  test/mlir/affine_conversion/memory_opt.mlir
  test/mlir/lit.site.cfg.py.in
  test/mlir/ops_test.cpp
Labels: Fully Reviewed, MLIR

#4204 [MLIR] Suppress warning from usage of C99 flexible array members on AppleClang.
  cmake/clang_4_0_flags.cmake
Labels: Fully Reviewed, MLIR

#4175 [ONNX] Use v1 in ArgMax, ArgMin, Hardmax ops
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/argmax.cpp
  src/ngraph/frontend/onnx_import/op/argmin.cpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.cpp
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.hpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
Labels: Fully Reviewed, ONNX

#4191 [SPEC] Too restrictive data type
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/experimental/layers/interpolate.cpp
  src/ngraph/op/experimental/layers/prior_box.cpp
  src/ngraph/op/experimental/layers/prior_box_clustered.cpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/gather.cpp
  src/ngraph/op/lrn.cpp
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/reshape.cpp
  src/ngraph/op/strided_slice.cpp
  src/ngraph/op/util/logical_reduction_keep_dims.cpp
  src/ngraph/op/variadic_split.cpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  test/type_prop/broadcast.cpp
  test/type_prop/pad.cpp
  test/type_prop/strided_slice.cpp
Labels: Fully Reviewed, SPEC

#4212 [MLIR] Fix MLIR pre-build paths
  cmake/external_mlir.cmake
Labels: Fully Reviewed

#4211 Leona/pipversion patch
  README.md
  doc/sphinx/source/frameworks/quickstart.rst
Labels: Fully Reviewed

#4208 Optimize Constant for deserialization
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
  src/tools/nbench/nbench.cpp
  test/CMakeLists.txt
  test/constant.cpp
Labels: Fully Reviewed

#4190 [ONNX] Remove support for ONNXIFI
  CMakeLists.txt
  CODEOWNERS
  ecosystem-overview.md
  src/ngraph/frontend/CMakeLists.txt
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/core/weight.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
  test/CMakeLists.txt
  test/onnx/onnxifi.cpp
  test/onnx/onnxifi_span.cpp
Labels: Fully Reviewed, ONNX

#4200 [MLIR] Enable MLIR ninja build
  CMakeLists.txt
  cmake/external_llvm.cmake
  cmake/external_mlir.cmake
  cmake/llvm_fetch.cmake.in
  cmake/mlir_fetch.cmake.in
Labels: Fully Reviewed, MLIR

#4219 Port PR 4156 and 4184 to master
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/convert_fp32_to_fp16.cpp
  src/ngraph/pass/convert_fp32_to_fp16.hpp
Labels: Fully Reviewed

#4220 Port PR 4159 to master
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/fake_quantize.hpp
Labels: Fully Reviewed

#4221 Port PR 4160 to master
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/mvn.hpp
Labels: Fully Reviewed

#4229 Copy PR 4227
  CMakeLists.txt
Labels: Fully Reviewed

#4168 add set_parameters, set_results and serialize types
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
  src/ngraph/serializer.cpp
  src/ngraph/serializer.hpp
  test/serialize.cpp
Labels: Fully Reviewed

#4224 Add some detail to internal Pad doc.
  src/ngraph/op/pad.hpp
Labels: Fully Reviewed

#3827 LRU cache for dynamic shapes
  src/ngraph/CMakeLists.txt
  src/ngraph/op/convolution.cpp
  src/ngraph/runtime/cache.cpp
  src/ngraph/runtime/cache.hpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.hpp
  test/backend/pool.in.cpp
Labels: Dynamic Shape, Fully Reviewed

#4214 Faster constant folding for v1::Reshape, v1::Transpose and v0::DynRes…
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  src/ngraph/pass/constant_folding_transpose.cpp
Labels: Fully Reviewed

#4186 Added API to get input node@index for current node
  src/ngraph/function.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/fused/batch_mat_mul_transpose.cpp
  src/ngraph/pass/constant_folding_quantize.cpp
  src/ngraph/pass/memory_layout.cpp
  src/ngraph/pass/shape_relevance.cpp
  src/ngraph/runtime/cpu/op/dropout.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
Labels: Fully Reviewed

#4233 A couple new attribute visitors
  src/ngraph/op/atan2.cpp
  src/ngraph/op/atan2.hpp
  src/ngraph/op/binary_convolution.cpp
  src/ngraph/op/binary_convolution.hpp
Labels: Fully Reviewed

#4236 Fix compilation warnings
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.hpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
Labels: Fully Reviewed

#4235 TensorIterator: align the number of inputs.
  src/ngraph/op/tensor_iterator.cpp
Labels: Fully Reviewed

#4103 [MLIR] Add some sane utilities for environment variable handling
  environment_variables.md
  src/ngraph/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
  src/ngraph/descriptor/input.cpp
  src/ngraph/env_util.cpp
  src/ngraph/env_util.hpp
  src/ngraph/event_tracing.cpp
  src/ngraph/file_util.cpp
  src/ngraph/log.cpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/manager.cpp
  src/ngraph/pass/pass_config.cpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/provenance.hpp
  src/ngraph/runtime/chrome_trace.cpp
  src/ngraph/serializer.cpp
  test/all_close_f.cpp
  test/backend_performance.cpp
  test/cpu_debugger.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/util/all_close_f.cpp
Labels: Fully Reviewed, MLIR, Merge Blocked

#4238 [MLIR] Use enum class for broadcast hint.
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/runtime/cpu/callback_utils.hpp
  src/contrib/mlir/runtime/cpu/cpu_callbacks.cpp
Labels: Fully Reviewed, MLIR

#4163 extend executable create tensor APIs
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
  src/ngraph/runtime/tensor.hpp
Labels: Fully Reviewed

#4246 Doc Release Notes for 0.29
  doc/sphinx/source/conf.py
  doc/sphinx/source/project/release-notes.rst
Labels: Documentation, Fully Reviewed

#4241 [ONNX] Remove ONNXIFI importer
  src/ngraph/frontend/onnxifi/CMakeLists.txt
  src/ngraph/frontend/onnxifi/backend.hpp
  src/ngraph/frontend/onnxifi/backend_manager.cpp
  src/ngraph/frontend/onnxifi/backend_manager.hpp
  src/ngraph/frontend/onnxifi/exceptions.hpp
  src/ngraph/frontend/onnxifi/executable.hpp
  src/ngraph/frontend/onnxifi/onnxifi.cpp
  src/ngraph/frontend/onnxifi/span.hpp
  src/ngraph/frontend/onnxifi/tensor.cpp
  src/ngraph/frontend/onnxifi/tensor.hpp
Labels: Fully Reviewed

#4252 v1 Subtract Constant Folding
  src/ngraph/pass/constant_folding_binary.cpp
Labels: Fully Reviewed

#4244 [ONNX] Upgrade ONNX to 1.6 version
  cmake/external_onnx.cmake
Labels: Fully Reviewed, ONNX

#4254 Add folder to keep helper classes for PyTorch.
  CODEOWNERS
  src/ngraph/frontend/ATen/README.md
Labels: Fully Reviewed, High Priority, PyTorch

#4213 Add provenance tags to decompose ops pass
  src/ngraph/pass/fused_op_decomposition.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#4198 Add provenance tags to opset transformation passes
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  test/models/onnx/provenance_downgrade_topk.prototxt
  test/onnx/onnx_import_provenance.in.cpp
  test/provenance.cpp
Labels: Fully Reviewed

#4255 Add basic build files for ATen helpers
  src/ngraph/frontend/ATen/CMakeLists.txt
  src/ngraph/frontend/ATen/operators/test/CMakeLists.txt
  src/ngraph/frontend/ATen/operators/test/dummy.cpp
  src/ngraph/frontend/ATen/operators/test/main.cpp
  src/ngraph/frontend/ATen/operators/test/test.manifest
  src/ngraph/frontend/CMakeLists.txt
Labels: Fully Reviewed, PyTorch

#4216 Allow Constant ops to share internal buffer
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  test/constant.cpp
Labels: Fully Reviewed

#4234 Extend NgraphTestCase to support dynamic backends
  src/ngraph/op/fused/fake_quantize.cpp
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/util/test_case.cpp
  test/util/test_case.hpp
Labels: Dynamic Shape, Fully Reviewed

#4256 Setting outputs for dynamic v1::Split
  src/ngraph/op/fused/split.cpp
Labels: Fully Reviewed

#4223 Printing cleanup
  doc/sphinx/source/inspection/debug_core.rst
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/type/element_type.cpp
  test/type_prop/dequantize.cpp
  test/type_prop/quantize.cpp
  test/type_prop/quantized_convolution.cpp
  test/type_prop/quantized_dot.cpp
  test/type_prop/top_k.cpp
Labels: Fully Reviewed

#4257 [ONNX] Remove missed files
  src/ngraph/op/fused/reciprocal.cpp
  src/ngraph/op/fused/reciprocal.hpp
Labels: Fully Reviewed, ONNX

#4261 Update C++ JSON to 3.7.3
  cmake/external_json.cmake
Labels: Fully Reviewed
