Repository NervanaSystems/ngraph, pull requests merged in 2020-03, with the labels that each got.

#4346 Add attribute visitor for ops E-L
  src/ngraph/attribute_adapter.cpp
  src/ngraph/attribute_adapter.hpp
  src/ngraph/attribute_visitor.hpp
  src/ngraph/coordinate_diff.cpp
  src/ngraph/op/erf.cpp
  src/ngraph/op/erf.hpp
  src/ngraph/op/exp.cpp
  src/ngraph/op/exp.hpp
  src/ngraph/op/floor.cpp
  src/ngraph/op/floor.hpp
  src/ngraph/op/fused/elu.cpp
  src/ngraph/op/fused/elu.hpp
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/fake_quantize.hpp
  src/ngraph/op/fused/grn.cpp
  src/ngraph/op/fused/grn.hpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/fused/hard_sigmoid.cpp
  src/ngraph/op/fused/hard_sigmoid.hpp
  src/ngraph/op/fused/lstm_cell.cpp
  src/ngraph/op/fused/lstm_cell.hpp
  src/ngraph/op/fused/lstm_sequence.cpp
  src/ngraph/op/fused/lstm_sequence.hpp
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/op/gather_tree.cpp
  src/ngraph/op/gather_tree.hpp
  src/ngraph/op/log.cpp
  src/ngraph/op/log.hpp
  src/ngraph/op/lrn.cpp
  src/ngraph/op/lrn.hpp
  src/ngraph/op/not.cpp
  src/ngraph/op/not.hpp
  test/attributes.cpp
Labels: Fully Reviewed

#4288 add missing space, otherwise "error: corrupt patch at line 12"
  cmake/mkldnn_v1.patch
Labels: DO NOT SQUASH, External, Fully Reviewed

#4391 Allow for opset extensions
  src/ngraph/factory.hpp
  src/ngraph/opsets/opset.cpp
  src/ngraph/opsets/opset.hpp
  test/opset1.cpp
Labels: Fully Reviewed

#4406 fix output replacement in split constant folding
  src/ngraph/pass/constant_folding_split.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, High Priority

#4325 Add attribute visitor for ops S-X
  src/ngraph/op/experimental/shape_of.cpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/op/experimental/tile.cpp
  src/ngraph/op/experimental/tile.hpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/op/experimental/transpose.hpp
  src/ngraph/op/fused/selu.cpp
  src/ngraph/op/fused/selu.hpp
  src/ngraph/op/fused/shuffle_channels.cpp
  src/ngraph/op/fused/shuffle_channels.hpp
  src/ngraph/op/fused/space_to_depth.cpp
  src/ngraph/op/fused/space_to_depth.hpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/op/fused/squared_difference.cpp
  src/ngraph/op/fused/squared_difference.hpp
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/squeeze.hpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/fused/unsqueeze.hpp
  src/ngraph/op/sign.cpp
  src/ngraph/op/sign.hpp
  src/ngraph/op/sin.cpp
  src/ngraph/op/sin.hpp
  src/ngraph/op/sinh.cpp
  src/ngraph/op/sinh.hpp
  src/ngraph/op/softmax.cpp
  src/ngraph/op/softmax.hpp
  src/ngraph/op/sqrt.cpp
  src/ngraph/op/sqrt.hpp
  src/ngraph/op/strided_slice.cpp
  src/ngraph/op/strided_slice.hpp
  src/ngraph/op/tan.cpp
  src/ngraph/op/tan.hpp
  src/ngraph/op/tanh.cpp
  src/ngraph/op/tanh.hpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/binary_elementwise_arithmetic.cpp
  src/ngraph/op/util/binary_elementwise_logical.cpp
  src/ngraph/op/variadic_split.cpp
  src/ngraph/op/variadic_split.hpp
  src/ngraph/op/xor.cpp
  src/ngraph/op/xor.hpp
  test/attributes.cpp
Labels: Fully Reviewed

#4340 Add attribute visitor for ops R
  src/ngraph/op/experimental/layers/region_yolo.cpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
  src/ngraph/op/experimental/range.cpp
  src/ngraph/op/experimental/range.hpp
  src/ngraph/op/fused/rnn_cell.cpp
  src/ngraph/op/fused/rnn_cell.hpp
  src/ngraph/op/reshape.cpp
  src/ngraph/op/reshape.hpp
  src/ngraph/op/result.cpp
  src/ngraph/op/result.hpp
  src/ngraph/op/reverse.cpp
  src/ngraph/op/reverse.hpp
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/op/reverse_sequence.hpp
  src/ngraph/op/util/arithmetic_reductions_keep_dims.cpp
  src/ngraph/op/util/arithmetic_reductions_keep_dims.hpp
  src/ngraph/op/util/logical_reduction_keep_dims.cpp
  src/ngraph/op/util/logical_reduction_keep_dims.hpp
  src/ngraph/op/util/rnn_cell_base.cpp
  src/ngraph/op/util/rnn_cell_base.hpp
  src/ngraph/op/util/unary_elementwise_arithmetic.cpp
  src/ngraph/op/util/unary_elementwise_arithmetic.hpp
  test/attributes.cpp
Labels: Fully Reviewed

#4344 Add attribute visitor for ops M-P
  src/ngraph/op/experimental/layers/psroi_pooling.cpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  src/ngraph/op/fused/matmul.cpp
  src/ngraph/op/fused/matmul.hpp
  src/ngraph/op/fused/mod.cpp
  src/ngraph/op/fused/mod.hpp
  src/ngraph/op/fused/normalize_l2.cpp
  src/ngraph/op/fused/normalize_l2.hpp
  src/ngraph/op/fused/prelu.cpp
  src/ngraph/op/fused/prelu.hpp
  src/ngraph/op/max_pool.cpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/op/negative.cpp
  src/ngraph/op/negative.hpp
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/non_max_suppression.hpp
  src/ngraph/op/one_hot.cpp
  src/ngraph/op/one_hot.hpp
  src/ngraph/op/pad.cpp
  src/ngraph/op/pad.hpp
  test/attributes.cpp
Labels: Fully Reviewed

#4389 Add axis normalization to Squeeze and Unsqueeze fused ops
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/unsqueeze.cpp
Labels: Fully Reviewed

#4377 Move ops in ngraph::op namespace to ngraph::op::v0
  src/contrib/mlir/core/compiler.hpp
  src/ngraph/op/any.hpp
  src/ngraph/op/crop_and_resize.hpp
  src/ngraph/op/dequantize.hpp
  src/ngraph/op/experimental/batch_mat_mul.cpp
  src/ngraph/op/experimental/batch_mat_mul.hpp
  src/ngraph/op/experimental/compiled_kernel.hpp
  src/ngraph/op/experimental/dyn_broadcast.hpp
  src/ngraph/op/experimental/dyn_pad.hpp
  src/ngraph/op/experimental/dyn_replace_slice.hpp
  src/ngraph/op/experimental/dyn_slice.hpp
  src/ngraph/op/experimental/quantized_conv_bias.hpp
  src/ngraph/op/experimental/quantized_conv_relu.hpp
  src/ngraph/op/experimental/quantized_dot_bias.hpp
  src/ngraph/op/experimental/random_uniform.hpp
  src/ngraph/op/fused/batch_mat_mul_transpose.hpp
  src/ngraph/op/fused/crossentropy.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
Labels: Fully Reviewed

#4407 Fixed auto_brodcast in visit_attributes
  src/ngraph/op/util/binary_elementwise_comparison.cpp
Labels: Fully Reviewed

#4397 [ONNX] Instance normalization with v1 ops
  src/ngraph/frontend/onnx_import/op/instance_norm.cpp
Labels: Fully Reviewed, ONNX, SPEC

#4414 Update CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#4412 Fixed GEMM conversion
  src/ngraph/frontend/onnx_import/op/gemm.cpp
Labels: Fully Reviewed, High Priority

#4399 Change chrome trace to use string concat instead of streams
  src/ngraph/chrome_trace.cpp
Labels: Fully Reviewed

#4400 Move chrome trace to proper namespace
  src/ngraph/chrome_trace.cpp
  src/ngraph/chrome_trace.hpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
Labels: Changes API, Fully Reviewed

#4402 Cleanup null distributed device
  src/ngraph/CMakeLists.txt
  src/ngraph/distributed.cpp
  src/ngraph/distributed/null.cpp
  src/ngraph/distributed/null.hpp
Labels: Fully Reviewed

#4408 Rename tensor view to tensor in CPU backend
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/builder/batch_norm.cpp
  src/ngraph/runtime/cpu/builder/gather.cpp
  src/ngraph/runtime/cpu/builder/matmul_bias.cpp
  src/ngraph/runtime/cpu/builder/mlir_cpu_compiled_kernel.cpp
  src/ngraph/runtime/cpu/builder/random_uniform.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_builder.hpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_debugger.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_emitter.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/cpu_tensor.cpp
  src/ngraph/runtime/cpu/cpu_tensor.hpp
  src/ngraph/runtime/cpu/cpu_tensor_wrapper.cpp
  src/ngraph/runtime/cpu/cpu_tensor_wrapper.hpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  test/cpu_debugger.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#4409 Move CPU executable to a separate file
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_backend.hpp
  src/ngraph/runtime/cpu/cpu_executable.cpp
  src/ngraph/runtime/cpu/cpu_executable.hpp
Labels: Fully Reviewed

#4403 Distributed debug print cleanup
  src/ngraph/distributed.hpp
  src/ngraph/distributed/null.cpp
  src/ngraph/distributed/null.hpp
  src/ngraph/frontend/ATen/operators/test/main.cpp
  src/ngraph/log.cpp
  src/ngraph/log.hpp
  src/ngraph/runtime/cpu/builder/allreduce.cpp
  test/main.cpp
Labels: Fully Reviewed

#4421 Added virtual dtor for RNNCellBase
  src/ngraph/op/util/rnn_cell_base.hpp
Labels: Fully Reviewed

#4429 Disable warnings while building LLVM to make the log files cleaner
  cmake/llvm_fetch.cmake.in
Labels: Fully Reviewed

#4418 Fixed python build
  python/build_wheel.sh.in
Labels: Fully Reviewed

#4427 Update README.md
  README.md
Labels: Fully Reviewed

#4434 [MLIR] Fix overwriting of value
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
Labels: Fully Reviewed, MLIR

#4435 CMAKE: component per directory
  src/ngraph/CMakeLists.txt
Labels: Fully Reviewed

#4443 Fix u1 allocation size
  src/ngraph/op/constant.cpp
Labels: Fully Reviewed, High Priority

#4442 Klocwork issues
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/constant.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed, High Priority

#4275 LLVM 9.0.1
  cmake/llvm_fetch.cmake.in
Labels: Fully Reviewed, Merge Blocked

#4448 Change reserializer to not indent output making files smaller
  src/tools/reserialize/reserialize.cpp
Labels: Fully Reviewed

#4410 Produce v1::ReduceMean in ONNX ReduceMean
  src/ngraph/frontend/onnx_import/op/reduce.cpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/op/reshape.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  test/models/onnx/reduce_mean.prototxt
  test/onnx/onnx_import.in.cpp
  test/util/test_case.hpp
Labels: Fully Reviewed, ONNX

#4404 float16 round halves to even
  src/ngraph/type/float16.cpp
  src/ngraph/type/float16.hpp
  test/float16.cpp
  test/util/float_util.cpp
  test/util/float_util.hpp
Labels: Fully Reviewed, High Priority

#4452 Update calls to copy_with_new_args to clone_with_new_inputs
  src/ngraph/descriptor/input.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.hpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
  test/constant.cpp
  test/copy.cpp
Labels: Fully Reviewed

#4453 [ONNX] Require the rank only if any value of axes is negative in Unsqueeze and Concat ops.
  src/ngraph/frontend/onnx_import/op/concat.cpp
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  test/models/onnx/concat_negative_axis.prototxt
  test/models/onnx/unsqueeze_negative_axes.prototxt
  test/onnx/onnx_import_reshape.in.cpp
Labels: Fully Reviewed, ONNX

#4423 Use Add (input+0) for ONNX Identity op
  src/ngraph/frontend/onnx_import/op/identity.hpp
Labels: Fully Reviewed, High Priority

#4350 Stricter checks on padding attributes for v1::Convolution
  src/ngraph/op/convolution.cpp
  test/type_prop/convolution.cpp
Labels: Fully Reviewed, Merge Blocked

#4473 Cleanup doc cmake files
  doc/CMakeLists.txt
  doc/doxygen/CMakeLists.txt
Labels: Fully Reviewed

#4450 [ONNX] Enable cross-compiling and ninja build for onnx_importer
  CMakeLists.txt
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
  src/ngraph/builder/reshape.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/exceptions.hpp
  test/CMakeLists.txt
Labels: Fully Reviewed, High Priority, ONNX

#4472 Remove some warning disables and add more strict checking
  CMakeLists.txt
  cmake/clang_4_0_flags.cmake
Labels: Fully Reviewed

#2990 [ONNX] Add Tile op
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/tile.cpp
  src/ngraph/frontend/onnx_import/op/tile.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/tile.prototxt
  test/models/onnx/tile_static.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
Labels: Fully Reviewed, ONNX

#4477 Revert "GetOutputElement removal preparation"
  .gitignore
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/ngraph/CMakeLists.txt
  src/ngraph/descriptor/output.cpp
  src/ngraph/descriptor/output.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/node_output.cpp
  src/ngraph/node_output.hpp
  src/ngraph/op/fused/lstm_sequence.hpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/get_output_element.hpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/variadic_split.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/constant_folding_shape_of.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/pattern/op/any.cpp
  src/ngraph/pattern/op/any_of.hpp
  src/ngraph/pattern/op/any_output.cpp
  src/ngraph/pattern/op/any_output.hpp
  src/ngraph/pattern/op/skip.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/op/convert_layout.cpp
  src/ngraph/runtime/cpu/op/convert_layout.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/algebraic_simplification.cpp
  test/backend/fused_op.in.cpp
  test/build_graph.cpp
  test/cpu_fusion.cpp
  test/opset_pass/topk_opset_pass.cpp
  test/provenance.cpp
  test/type_prop/top_k.cpp
  test/util/matcher.hpp
  test/util/test_tools.hpp
Labels: Do-not-merge-yet, Fully Reviewed

#4478 Revert "Stricter checks on padding attributes for v1::Convolution"
  src/ngraph/op/convolution.cpp
  test/type_prop/convolution.cpp
Labels: Do-not-merge-yet, Fully Reviewed

#4205 [MLIR] Use mkldnn callback for ConvBias.
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/backend/pass/op_lowerers.inc
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/ops_supported.inc
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/contrib/mlir/runtime/cpu/callback_utils.hpp
  src/contrib/mlir/runtime/cpu/cpu_callbacks.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.hpp
  src/contrib/mlir/runtime/runtime.hpp
  src/ngraph/runtime/cpu/builder/mlir_cpu_compiled_kernel.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  test/cpu_fusion.cpp
  test/cpu_test.cpp
  test/mlir/affine_conversion/callback_ops.mlir
  test/mlir/ngraph_dialect/fused_ops.mlir
Labels: Fully Reviewed, MLIR

#4479 Fix klocwork issues
  src/ngraph/node_output.cpp
  test/type_prop/top_k.cpp
Labels: Fully Reviewed

#4203 Remove dynreshape use v1:Reshape instead
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/reshape.cpp
  src/ngraph/op/experimental/dyn_reshape.cpp
  src/ngraph/op/experimental/dyn_reshape.hpp
  src/ngraph/op/fused/batch_mat_mul_transpose.cpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/dyn_elimination.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/pass/shape_relevance.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/dyn_reshape.in.cpp
  test/backend/dynamic.in.cpp
  test/build_graph.cpp
  test/dyn_elimination.cpp
  test/models/paddlepaddle/transpose.json
  test/op_is.cpp
  test/opset_pass/dyn_reshape_opset_pass.cpp
  test/pass_shape_relevance.cpp
  test/type_prop/dyn_reshape.cpp
Labels: Changes API, Dynamic Shape, Fully Reviewed

#4483 Fix unsafe opset singleton object
  src/ngraph/opsets/opset.cpp
Labels: Fully Reviewed, High Priority

#4482 Removed CMakeFindDependencyMacro to support CMake 2.8
  cmake/share/ngraphConfig.cmake.in
Labels: Fully Reviewed, rov2020.2

#4484 Fix unsafe opset singleton
  src/ngraph/opsets/opset.cpp
Labels: Fully Reviewed, rov2020.2

#4486 Add value_type to Dimension, deprecate int64_t cast
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/op/concat.cpp
  src/ngraph/op/crop_and_resize.cpp
  src/ngraph/op/fused/layer_norm.cpp
  src/ngraph/op/fused/matmul.cpp
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/pad.cpp
  src/ngraph/partial_shape.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/validation_util.cpp
Labels: Fully Reviewed

#4462 [ VariadicSplit ] Dynamic shape inference
  src/ngraph/op/variadic_split.cpp
  test/type_prop/variadic_split.cpp
Labels: Dynamic Shape, Fully Reviewed, MaskRCNN

#4495 Eliminate mismatch between opset1/opset2 and our real intentions
  src/ngraph/opsets/opset2_tbl.hpp
Labels: Fully Reviewed, SPEC, rov2020.2

#4464 Update includes in reference runtime headers
  src/ngraph/runtime/reference/and.hpp
  src/ngraph/runtime/reference/batch_norm.hpp
  src/ngraph/runtime/reference/cum_sum.hpp
  src/ngraph/runtime/reference/divide.hpp
  src/ngraph/runtime/reference/equal.hpp
  src/ngraph/runtime/reference/greater.hpp
  src/ngraph/runtime/reference/greater_eq.hpp
  src/ngraph/runtime/reference/less.hpp
  src/ngraph/runtime/reference/less_eq.hpp
  src/ngraph/runtime/reference/maximum.hpp
  src/ngraph/runtime/reference/mean.hpp
  src/ngraph/runtime/reference/minimum.hpp
  src/ngraph/runtime/reference/multiply.hpp
  src/ngraph/runtime/reference/not_equal.hpp
  src/ngraph/runtime/reference/or.hpp
  src/ngraph/runtime/reference/subtract.hpp
  src/ngraph/runtime/reference/xor.hpp
Labels: Fully Reviewed

#4490 Better performance for graph.huge test. More robust Function validation
  src/ngraph/function.cpp
  test/build_graph.cpp
  test/util.cpp
Labels: Fully Reviewed
