Repository NervanaSystems/ngraph, pull requests merged in 2020-07, with the labels that each got.

#4888 Fix edge-label feature
  src/ngraph/pass/visualize_tree.cpp
Labels: Fully Reviewed

#4890 Enable both MLIR and Codegen with same LLVM version.
  CMakeLists.txt
  cmake/external_llvm.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
  src/ngraph/codegen/execution_engine.cpp
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  src/resource/CMakeLists.txt
  src/resource/main.cpp
Labels: Fully Reviewed

#4891 Remove some auto-GOE elimination code
  src/ngraph/node.hpp
  src/ngraph/node_output.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  test/backend/lstm_cell.in.cpp
  test/cpu_fusion.cpp
  test/cpu_fusion.in.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#4892 Replace some get_argument calls with input_value
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/like_replacement.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.cpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
Labels: Fully Reviewed

#4893 Remove as single output
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/node_output.cpp
  src/ngraph/node_output.hpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/runtime/cpu/builder/quantization.cpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
Labels: Fully Reviewed

#4897 Only allow sanitizers if clang is used since it fails to link otherwise
  CMakeLists.txt
Labels: Fully Reviewed

#4899 Use oneDNN 1.5.1
  cmake/external_onednn.cmake
  cmake/onednn.patch
  python/CMakeLists.txt
  src/contrib/mlir/CMakeLists.txt
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/resource/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#4900 Use oneTBB v2020.2
  CMakeLists.txt
  cmake/external_onetbb.cmake
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
Labels: Fully Reviewed

#4902 Pybind11 use GIT_SHALLOW.
  cmake/external_pybind11.cmake
Labels: Fully Reviewed

#4903 ONNX import: Update external dependencies.
  cmake/external_onnx.cmake
  cmake/external_protobuf.cmake
Labels: Fully Reviewed

#4895 Create a better constructor for Function
  python/src/pyngraph/function.cpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
Labels: Fully Reviewed

#4904 Update Eigen.
  cmake/eigen.patch
  cmake/external_eigen.cmake
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/resource/CMakeLists.txt
  test/backend/gelu.in.cpp
Labels: Fully Reviewed

#4905 Remove AnyOutput match pattern as it is not used
  src/ngraph/CMakeLists.txt
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/pattern/op/any_output.cpp
  src/ngraph/pattern/op/any_output.hpp
Labels: Fully Reviewed

#4372 [MLIR] Introduce op fusion pass
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/pass/ng_op_fusion.cpp
  src/contrib/mlir/core/pass/ng_op_fusion.hpp
  test/mlir/transforms/op_fusion.mlir
Labels: Fully Reviewed, MLIR

#4908 Add test to validate node type info
  src/ngraph/op/mod.hpp
  test/CMakeLists.txt
  test/type_info.cpp
Labels: Fully Reviewed

#4910 Revert MLIR style change because it is too hard to with two styles at once
  src/contrib/mlir/.clang-format
  src/contrib/mlir/backend/analysis/memory_analysis.cpp
  src/contrib/mlir/backend/analysis/memory_analysis.hpp
  src/contrib/mlir/backend/backend.hpp
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/cpu/cpu_backend.hpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.hpp
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/compiler.hpp
  src/contrib/mlir/core/ngraph_dialect/dialect.cpp
  src/contrib/mlir/core/ngraph_dialect/dialect.hpp
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.hpp
  src/contrib/mlir/core/ngraph_dialect/type.cpp
  src/contrib/mlir/core/ngraph_dialect/type.hpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.hpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.hpp
  src/contrib/mlir/core/pass/ng_dialect_fused_ops.cpp
  src/contrib/mlir/core/pass/ng_dialect_fused_ops.hpp
  src/contrib/mlir/core/pass/ng_op_fusion.cpp
  src/contrib/mlir/core/pass/ng_op_fusion.hpp
  src/contrib/mlir/runtime/cpu/callback_utils.hpp
  src/contrib/mlir/runtime/cpu/cpu_callbacks.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.hpp
  src/contrib/mlir/runtime/cpu/memory_manager.cpp
  src/contrib/mlir/runtime/cpu/memory_manager.hpp
  src/contrib/mlir/runtime/runtime.hpp
  src/contrib/mlir/tools/ngraph-opt/ngraph_opt.cpp
  src/contrib/mlir/utils.cpp
  src/contrib/mlir/utils.hpp
Labels: Fully Reviewed

#4913 Fix NGRAPH_CPU_MLIR_ENABLE build issue.
  cmake/external_llvm.cmake
Labels: Bug, Fully Reviewed

#4914 Remove using namespace in header
  src/contrib/mlir/core/pass/ng_dialect_builder.hpp
Labels: Fully Reviewed

#4907 Move external project CMake files.
  CMakeLists.txt
  cmake/external/eigen.cmake
  cmake/external/fetch_gtest.cmake
  cmake/external/gtest.cmake
  cmake/external/json.cmake
  cmake/external/llvm.cmake
  cmake/external/mlir.patch
  cmake/external/onednn.cmake
  cmake/external/onednn.patch
  cmake/external/onetbb.cmake
  cmake/external/onnx.cmake
  cmake/external/protobuf.cmake
  cmake/external/pybind11.cmake
  doc/doxygen/CMakeLists.txt
  doc/doxygen/Doxyfile.in
  doc/sphinx/ngraph.doxyfile
  src/ngraph/codegen/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#4917 Use LLVM archive file to speed up build.
  cmake/external/llvm.cmake
  cmake/external/mlir.patch
Labels: Fully Reviewed

#4916 Remove IE Backend
  CMakeLists.txt
  cmake/Modules/FindCLDNN.cmake
  cmake/external/fetch_gtest.cmake
  src/ngraph/runtime/CMakeLists.txt
  src/ngraph/runtime/ie/CMakeLists.txt
  src/ngraph/runtime/ie/ie_backend.cpp
  src/ngraph/runtime/ie/ie_backend.hpp
  src/ngraph/runtime/ie/ie_backend_visibility.hpp
  src/ngraph/runtime/ie/ie_executable.cpp
  src/ngraph/runtime/ie/ie_executable.hpp
  src/ngraph/runtime/ie/ie_tensor.cpp
  src/ngraph/runtime/ie/ie_tensor.hpp
  src/ngraph/runtime/ie/unit_test.manifest
  test/CMakeLists.txt
Labels: Fully Reviewed

#4919 Revert INTERPRETER to use reference kernels
  python/test/ngraph/test_create_op.py
  src/ngraph/op/clamp.cpp
  src/ngraph/op/clamp.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/eval/unit_test.manifest
  src/ngraph/runtime/gcpu/gcpu_executable.cpp
  src/ngraph/runtime/gcpu/gcpu_executable.hpp
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_backend.hpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/opset_int_tbl.hpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/runtime/mlir/mlir_executable.cpp
  src/ngraph/runtime/mlir/mlir_executable.hpp
  src/ngraph/runtime/mlir/opset_mlir_tbl.hpp
  src/ngraph/runtime/mlir/unit_test.manifest
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/clamp.in.cpp
  test/eval.cpp
Labels: Fully Reviewed

#4921 Remove usage of global CMAKE_CXX_FLAGS.
  CMakeLists.txt
  cmake/clang_flags.cmake
  cmake/external/eigen.cmake
  cmake/external/onednn.cmake
  cmake/external/onetbb.cmake
  src/contrib/mlir/CMakeLists.txt
  src/ngraph/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed

#4922 Simplify MKL fetch.
  cmake/external/eigen.cmake
  cmake/external/json.cmake
  cmake/external/llvm.cmake
  cmake/external/onednn.cmake
  cmake/external/onednn.patch
  cmake/external/onetbb.cmake
  cmake/external/onnx.cmake
  cmake/external/protobuf.cmake
  cmake/external/pybind11.cmake
Labels: Fully Reviewed

#4920 Add missing extern declaration for apply_permutation<CoordinateDiff>
  src/ngraph/util.hpp
Labels: Fully Reviewed

#4923 Ninja: support building python_wheel.
  CMakeLists.txt
  python/CMakeLists.txt
  python/build_wheel.sh.in
  python/setup.py
Labels: Fully Reviewed

#4925 Broadcast to use optimized kernel
  src/ngraph/op/broadcast.cpp
Labels: Fully Reviewed

#4926 Update googletest
  cmake/external/gtest.cmake
  test/all_close_f.cpp
  test/backend/builder_flatten.in.cpp
  test/backend/concat.in.cpp
  test/backend/dyn_replace_slice_reference.in.cpp
  test/backend/graph_comparison.in.cpp
  test/backend/pool.in.cpp
  test/ref_generators/generate_dyn_replace_slice_ref.py
  test/type_prop/broadcast.cpp
  test/type_prop/convolution.cpp
  test/type_prop/dyn_replace_slice.cpp
  test/type_prop/dyn_slice.cpp
  test/type_prop/range.cpp
  test/type_prop/select.cpp
  test/type_prop/top_k.cpp
  test/util/test_control.hpp
Labels: Fully Reviewed
