Repository NervanaSystems/ngraph, pull requests merged in 2020-06, with the labels that each got.

#4818 Remove warnings that are printed to stdout
  src/ngraph/opsets/opset.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#4827 Fix mlir build
  CMakeLists.txt
  cmake/clang_flags.cmake
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  test/CMakeLists.txt
Labels: Fully Reviewed, High Priority

#4829 Better style tools
  CMakeLists.txt
  cmake/Modules/style_apply.cmake
  cmake/Modules/style_check.cmake
  maint/apply-code-format.sh
  maint/check-code-format.sh
Labels: Fully Reviewed

#4833 Fix tests by hiding global objects
  test/backend/auto_broadcast.in.cpp
  test/backend/dyn_slice_reference.in.cpp
  test/backend/range.in.cpp
  test/backend/strided_slice.in.cpp
  test/backend/zero_sized.in.cpp
  test/ref_generators/generate_dyn_slice_ref.py
Labels: Bug, Fully Reviewed

#4814 Add reference implementation for Mod op
  src/ngraph/op/fused/mod.cpp
  src/ngraph/op/fused/mod.hpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/opset_int_tbl.hpp
  src/ngraph/runtime/reference/mod.hpp
  test/CMakeLists.txt
  test/op_eval/mod.cpp
Labels: Fully Reviewed

#4837 Fetch protobuf
  cmake/external_protobuf.cmake
Labels: Fully Reviewed

#4834 [MLIR] add support for unsigned integer comparison
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  test/backend/comparison.in.cpp
  test/backend/fused_op.in.cpp
  test/backend/maximum.in.cpp
  test/backend/minimum.in.cpp
  test/backend/relu.in.cpp
  test/mlir/affine_conversion/core_ops.mlir
  test/util.cpp
Labels: Fully Reviewed, MLIR

#4838 Fix failing codegen unit test
  src/ngraph/runtime/cpu/cpu_external_function.cpp
Labels: Fully Reviewed

#4839 Move test from fused_op.in.cpp to individual files based on op
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/ie/unit_test.manifest
  test/CMakeLists.txt
  test/backend/batch_mat_mul.in.cpp
  test/backend/clamp.in.cpp
  test/backend/conv_bias.in.cpp
  test/backend/cross_entropy.in.cpp
  test/backend/elu.in.cpp
  test/backend/fake_quantize.in.cpp
  test/backend/fused_op.in.cpp
  test/backend/gemm.in.cpp
  test/backend/grn.in.cpp
  test/backend/group_conv.in.cpp
  test/backend/gru_cell.in.cpp
  test/backend/hard_sigmoid.in.cpp
  test/backend/lstm_cell.in.cpp
  test/backend/mvn.in.cpp
  test/backend/normalize.in.cpp
  test/backend/prelu.in.cpp
  test/backend/rnn_cell.in.cpp
  test/backend/scale.in.cpp
  test/backend/shuffle_channels.in.cpp
  test/backend/split.in.cpp
  test/backend/squared_difference.in.cpp
  test/backend/squeeze.in.cpp
  test/backend/stack.in.cpp
  test/backend/transpose.in.cpp
  test/backend/unsqueeze.cpp
  test/type_prop/clamp.cpp
Labels: Fully Reviewed

#4842 Normalize CPU enable flags
  CMakeLists.txt
  doc/sphinx/source/inspection/debug_core.rst
  python/BUILDING.md
Labels: Fully Reviewed

#4847 Remove unused patch files.
  cmake/llvm.patch
  cmake/mkldnn.patch
Labels: Fully Reviewed

#4848 Rename mkldnn build files to onednn.
  CMakeLists.txt
  cmake/external_onednn.cmake
  cmake/onednn.patch
Labels: Fully Reviewed

#4846 Remove GOE from the ONNX frontend
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/supported_ops.md
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.cpp
Labels: Fully Reviewed

#4856 Remove deprecated get_output_tensor*() methods
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/runtime/cpu/cpu_cse.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
  src/ngraph/runtime/cpu/op/convert_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/runtime/gpu/gpu_external_function.cpp
  src/runtime/gpu/gpu_internal_function.cpp
Labels: Fully Reviewed

#4854 Correct style of rt info
  src/ngraph/rt_info.cpp
Labels: Fully Reviewed

#4855 Remove deprecated get input descriptor and get output descriptor methods from Node
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/pass/fused_op_decomposition.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
  src/runtime/gpu/cuda_emitter.cpp
  src/runtime/gpu/cudnn_emitter.cpp
  src/runtime/gpu/gpu_internal_function.cpp
  src/runtime/gpu/gpu_kernel_emitters.cpp
  src/runtime/gpu/pass/gpu_batch_norm_cache.cpp
  src/runtime/gpu/pass/gpu_layout.cpp
  src/runtime/gpu/pass/gpu_rnn_fusion.cpp
  src/runtime/gpu/pass/tensor_memory_reservation.cpp
Labels: Fully Reviewed

#4858 Remove GOE usage
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/op/convert_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#4862 Normalize CPU enable flags in cmake
  CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/runtime/gpu/gpu_external_function.hpp
  test/CMakeLists.txt
Labels: Fully Reviewed

#4861 Remove stray debug statement
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
Labels: Fully Reviewed

#4863 Change placement from enum to an integer
  src/ngraph/CMakeLists.txt
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/placement.cpp
  src/ngraph/placement.hpp
Labels: Fully Reviewed

#4871 Remove obsolete instance object
  src/ngraph/runtime/cpu/cpu_executable.cpp
  src/ngraph/runtime/cpu/cpu_executable.hpp
Labels: Fully Reviewed

#4870 Add match helper for casting root node
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/constant_folding_convert.cpp
  src/ngraph/pass/constant_folding_dyn_broadcast.cpp
  src/ngraph/pass/constant_folding_dyn_slice.cpp
  src/ngraph/pass/constant_folding_one_hot.cpp
  src/ngraph/pass/constant_folding_pad.cpp
  src/ngraph/pass/constant_folding_reverse.cpp
  src/ngraph/pass/constant_folding_slice.cpp
  src/ngraph/pass/constant_folding_split.cpp
  src/ngraph/pass/constant_folding_transpose.cpp
  src/ngraph/pass/constant_folding_variadic_split.cpp
  src/ngraph/pass/convert_fp32_to_fp16.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_elimination_v1.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
Labels: Fully Reviewed

#4867 Add support for Output<Node> to python wrapper
  python/setup.py
  python/src/ngraph/impl/__init__.py
  python/src/pyngraph/function.cpp
  python/src/pyngraph/node.cpp
  python/src/pyngraph/output.cpp
  python/src/pyngraph/output.hpp
  python/src/pyngraph/pyngraph.cpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
Labels: Fully Reviewed

#4868 Fix some awkward use of get_arguments()
  src/runtime/gpu/pass/gpu_rnn_fusion.cpp
  test/build_graph.cpp
  test/pattern.cpp
Labels: Fully Reviewed

#4873 Normalize creating of shared_ptr
  src/ngraph/op/experimental/quantized_conv_bias.cpp
  src/ngraph/op/experimental/quantized_conv_relu.cpp
  src/ngraph/op/quantized_convolution.cpp
  src/ngraph/op/quantized_dot.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/conv_relu.cpp
  src/ngraph/runtime/cpu/op/group_conv_bias.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
Labels: Fully Reviewed

#4869 Replace get_match_root() with get_match_value()
  doc/sphinx/source/core/passes/passes-that-use-matcher.rst
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/pass/constant_folding_convert.cpp
  src/ngraph/pass/constant_folding_dequantize.cpp
  src/ngraph/pass/constant_folding_dyn_broadcast.cpp
  src/ngraph/pass/constant_folding_dyn_reshape.cpp
  src/ngraph/pass/constant_folding_dyn_slice.cpp
  src/ngraph/pass/constant_folding_gather.cpp
  src/ngraph/pass/constant_folding_logical_reduction.cpp
  src/ngraph/pass/constant_folding_one_hot.cpp
  src/ngraph/pass/constant_folding_pad.cpp
  src/ngraph/pass/constant_folding_quantize.cpp
  src/ngraph/pass/constant_folding_reverse.cpp
  src/ngraph/pass/constant_folding_scatter.cpp
  src/ngraph/pass/constant_folding_select.cpp
  src/ngraph/pass/constant_folding_slice.cpp
  src/ngraph/pass/constant_folding_tile.cpp
  src/ngraph/pass/constant_folding_transpose.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pass/reshape_elimination_v1.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/runtime/cpu/cpu_executable.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/runtime/gpu/pass/gpu_rnn_fusion.cpp
  test/pattern.cpp
Labels: Fully Reviewed

#4872 Enable the INTERPRETER's serialize/deserialize check
  python/test/ngraph/test_ops_matmul.py
  python/test/ngraph/test_reduction.py
  src/ngraph/node.hpp
  src/ngraph/op/add.hpp
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/binary_convolution.hpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/experimental/generate_mask.hpp
  src/ngraph/op/max_pool.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/pad.hpp
  src/ngraph/op/reduce_mean.hpp
  src/ngraph/op/reduce_prod.hpp
  src/ngraph/op/reduce_sum.hpp
  src/ngraph/op/reshape.hpp
  src/ngraph/op/reverse.hpp
  src/ngraph/op/softmax.hpp
  src/ngraph/op/strided_slice.hpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/broadcast_base.cpp
  src/ngraph/op/util/broadcast_base.hpp
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/unit_test.manifest
  src/ngraph/serializer.cpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  src/ngraph/util.hpp
  src/runtime/gpu/gpu_emitter.cpp
Labels: Fully Reviewed

#4877 Remove NodePredicate in favor of ValuePredicate
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/pass/concat_fusion.cpp
  src/ngraph/pass/constant_folding_arithmetic_reduction.cpp
  src/ngraph/pass/constant_folding_dequantize.cpp
  src/ngraph/pass/constant_folding_logical_reduction.cpp
  src/ngraph/pass/constant_folding_quantize.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/pass_util.cpp
  src/ngraph/pass/pass_util.hpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pattern/op/any.hpp
  src/ngraph/pattern/op/any_of.hpp
  src/ngraph/pattern/op/label.hpp
  src/ngraph/pattern/op/pattern.cpp
  src/ngraph/pattern/op/pattern.hpp
  src/ngraph/pattern/op/skip.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_horizontal_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  test/cpu_fusion.cpp
  test/pattern.cpp
Labels: Fully Reviewed

#4880 Convert misuse of description() to is_type
  src/ngraph/function.cpp
  src/ngraph/pass/constant_to_broadcast.cpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/runtime/gpu/gpu_backend.cpp
Labels: Fully Reviewed

#4866 Remove GetOutputElement helper functions from Node
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/autobroadcast.hpp
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/op/onehot.cpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/node_output.cpp
  src/ngraph/node_output.hpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/get_output_element.hpp
  src/ngraph/op/gru_cell.cpp
  src/ngraph/op/quantized_convolution.hpp
  src/ngraph/op/quantized_dot.hpp
  src/ngraph/op/rnn_cell.cpp
  src/ngraph/op/util/activation_functions.cpp
  src/ngraph/op/util/activation_functions.hpp
  src/ngraph/op/util/rnn_cell_base.cpp
  src/ngraph/op/util/rnn_cell_base.hpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/implicit_broadcast_elimination.cpp
  src/ngraph/pass/implicit_broadcast_elimination.hpp
  src/ngraph/pass/reshape_elimination.cpp
  src/ngraph/pattern/matcher.cpp
  src/ngraph/pattern/matcher.hpp
  src/ngraph/pattern/op/pattern.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_workspace_insertion.cpp
  src/runtime/gpu/pass/gpu_layout.cpp
  test/builder_autobroadcast.cpp
  test/copy.cpp
  test/cpu_fusion.cpp
  test/pattern.cpp
  test/provenance.cpp
  test/util.cpp
Labels: Fully Reviewed

#4882 Enable multi-tests for CPU variants
  CMakeLists.txt
  src/ngraph/runtime/cpu/unit_test.manifest
  test/CMakeLists.txt
  test/backend/dot.in.cpp
  test/backend/gather.in.cpp
  test/core_fusion.cpp
  test/cpu_core_fusion.in.cpp
  test/cpu_debug_tracer.in.cpp
  test/cpu_debugger.in.cpp
  test/cpu_fusion.cpp
  test/cpu_fusion.in.cpp
  test/cpu_test.in.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#4884 Use Node/Output/ParameterVector instead of vector<shared_ptr<X>> where possible
  python/src/pyngraph/function.cpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/tensor_iterator.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/cse.cpp
  src/ngraph/pass/memory_visualize.cpp
  src/ngraph/pass/memory_visualize.hpp
  src/ngraph/pass/pass.cpp
  src/ngraph/pass/pass.hpp
  src/ngraph/runtime/cpu/cpu_external_function.hpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.hpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/serializer.cpp
  src/ngraph/util.cpp
  src/runtime/gpu/gpu_compiled_function.hpp
  src/runtime/gpu/gpu_runtime_constructor.hpp
  src/runtime/gpu/pass/gpu_rnn_fusion.cpp
  test/backend/autodiff.in.cpp
  test/backend/divide.in.cpp
  test/backend_performance.cpp
  test/cpu_fusion.cpp
  test/eval.cpp
  test/input_output_assign.cpp
  test/onnx/onnx_import.in.cpp
  test/pass_liveness.cpp
  test/pattern.cpp
  test/util.cpp
  test/util/autodiff/backprop_derivative.hpp
  test/util/autodiff/backprop_function.cpp
  test/util/autodiff/numeric_compare.hpp
  test/util/autodiff/numeric_derivative.hpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#4889 Fix compiler warning
  src/ngraph/type/element_type.cpp
Labels: Fully Reviewed
