Repository NervanaSystems/ngraph, pull requests merged in 2020-04, with the labels that each got.

#4505 [ ONNX IMPORTER ] Flatten with axis==1 simplification
  src/ngraph/builder/reshape.cpp
Labels: MaskRCNN

#4499 Removed Threads dependency
  cmake/share/ngraphConfig.cmake.in
  src/ngraph/CMakeLists.txt
  src/tools/nbench/CMakeLists.txt
Labels: Do-not-merge-yet, Fully Reviewed, rov2020.2

#4501 Remove Threads dependency
  cmake/share/ngraphConfig.cmake.in
  src/ngraph/CMakeLists.txt
  src/tools/nbench/CMakeLists.txt
Labels: Fully Reviewed

#4431 [ NonZero ] operator with constant folding and onnx_importer support
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/non_zero.cpp
  src/ngraph/frontend/onnx_import/op/non_zero.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/non_zero.cpp
  src/ngraph/op/non_zero.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset3.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_non_zero.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/constant_folding.cpp
  test/models/onnx/non_zero_1d.prototxt
  test/models/onnx/non_zero_1d_float.prototxt
  test/models/onnx/non_zero_2d_bool.prototxt
  test/models/onnx/non_zero_3d.prototxt
  test/models/onnx/non_zero_scalar.prototxt
  test/onnx/onnx_import.in.cpp
  test/type_prop/non_zero.cpp
Labels: Fully Reviewed, High Priority, MaskRCNN

#4509 Change pad mode to explicit if pad values are set in validation
  src/ngraph/op/convolution.cpp
  test/type_prop/convolution.cpp
Labels: Fully Reviewed

#3958 [nBench] Add support to dump result tensors
  src/tools/nbench/benchmark.cpp
  src/tools/nbench/benchmark.hpp
  src/tools/nbench/nbench.cpp
Labels: Fully Reviewed

#4363 [MLIR] Refactor NG dialect builder
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
Labels: Fully Reviewed, MLIR

#4519 Revert "Stricter checks on padding attributes for v1::Convolution"
  src/ngraph/op/convolution.cpp
  test/type_prop/convolution.cpp
Labels: Fully Reviewed, High Priority

#4504 Add CSE pass description in doxygen documentation
  doc/doxygen/images/add_commutative_postcse.svg
  doc/doxygen/images/add_commutative_precse.svg
  src/ngraph/pass/cse.cpp
  src/ngraph/pass/cse.hpp
Labels: Fully Reviewed

#4451 Squeeze shape inference for dynamic input shape
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/unsqueeze.cpp
  test/type_prop/squeeze.cpp
  test/type_prop/unsqueeze.cpp
Labels: Fully Reviewed, MaskRCNN

#4492 Pretty format for opt_kernels
  src/ngraph/runtime/opt_kernel/broadcast.hpp
  src/ngraph/runtime/opt_kernel/reshape.hpp
Labels: Fully Reviewed

#4496 Test that header files include everything they need
  src/ngraph/op/fused/partial_slice.hpp
  test/CMakeLists.txt
  test/header_standalone.in.cpp
Labels: Fully Reviewed

#4522 Merge rov.2020.2 to master
  cmake/external_protobuf.cmake
  src/ngraph/CMakeLists.txt
  src/ngraph/assertion.cpp
  src/ngraph/assertion.hpp
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/opsets/opset2_tbl.hpp
  src/ngraph/runtime/backend_manager.hpp
Labels: Fully Reviewed, High Priority

#4439 Vanilla RNN Optimization
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_invoke.cpp
  src/ngraph/runtime/cpu/mkldnn_invoke.hpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.hpp
  test/cpu_fusion.cpp
  test/models/tensorflow/rnn/vanilla_rnn_3_time_step.json
Labels: Fully Reviewed

#4523 Use OutputVector in passthrough
  python/pyngraph/ops/passthrough.cpp
  src/ngraph/op/passthrough.cpp
  src/ngraph/op/passthrough.hpp
  test/serialize.cpp
Labels: Fully Reviewed

#4525 Run cpu constant folding with cpu constant folders
  src/ngraph/pass/constant_folding_unary.cpp
  src/ngraph/runtime/cpu/cpu_builder.cpp
  src/ngraph/runtime/cpu/kernel/sqrt.hpp
  test/cpu_test.cpp
Labels: Fully Reviewed

#4527 Fused ops need to defuse
  src/ngraph/CMakeLists.txt
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/fused/split.hpp
  src/ngraph/op/group_conv.cpp
  src/ngraph/op/group_conv.hpp
  src/ngraph/op/split.cpp
  src/ngraph/op/split.hpp
  src/ngraph/op/util/fused_op.hpp
  src/ngraph/ops.hpp
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_split.cpp
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/convolution.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/op/group_conv_bias.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  test/core_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#4526 Expose slice plan
  src/ngraph/slice_plan.hpp
Labels: Fully Reviewed

#4494 Use Squeeze instead of Reshape in interpret_as_scalar
  src/ngraph/frontend/onnx_import/utils/reshape.cpp
Labels: Fully Reviewed, MaskRCNN

#4524 Remove long-deprecated methods
  src/ngraph/op/util/binary_elementwise_arithmetic.cpp
  src/ngraph/op/util/binary_elementwise_arithmetic.hpp
  src/ngraph/op/util/binary_elementwise_comparison.cpp
  src/ngraph/op/util/binary_elementwise_comparison.hpp
  src/ngraph/op/util/binary_elementwise_logical.cpp
  src/ngraph/op/util/binary_elementwise_logical.hpp
  src/ngraph/op/util/fused_op.cpp
  src/ngraph/op/util/fused_op.hpp
  src/ngraph/op/util/index_reduction.cpp
  src/ngraph/op/util/index_reduction.hpp
  src/ngraph/op/util/unary_elementwise_arithmetic.cpp
  src/ngraph/op/util/unary_elementwise_arithmetic.hpp
  test/control_dependencies.cpp
  test/type_prop/compat.cpp
Labels: Fully Reviewed

#4456 [ Gather ] Dynamic Gather value propagation
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_gather.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, MaskRCNN, OV

#4460 [ ConvolutionBackPropData ] Dynamic shape inference
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/group_conv.cpp
  src/ngraph/op/group_conv.hpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/type_prop/convolution.cpp
  test/type_prop/group_convolution_backprop_data.cpp
Labels: Fully Reviewed, MaskRCNN, OV

#4502 [ONNX] Parameter have friendly name set in onnx model
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
Labels: Fully Reviewed, ONNX, OV

#4540 Type hash was using name pointer instead of string contents
  src/ngraph/type.cpp
Labels: Bug, Fully Reviewed, High Priority, OV

#4529 Equality of SlicePlans
  src/ngraph/slice_plan.cpp
  src/ngraph/slice_plan.hpp
Labels: Fully Reviewed, OV

#4455 [ ShapeOf Const Folding ] Dynamic ShapeOf value propagation
  src/ngraph/op/experimental/shape_of.cpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/pass/constant_folding_shape_of.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed, MaskRCNN, OV

#4537 Use Node helpers
  src/ngraph/function.cpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/softmax.cpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/cse.cpp
  src/ngraph/pass/get_output_element_elimination.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/pass/zero_dim_tensor_elimination.cpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/conv_add.hpp
  src/ngraph/runtime/cpu/op/conv_relu.cpp
  src/ngraph/runtime/cpu/op/conv_relu.hpp
  src/ngraph/runtime/cpu/op/group_conv_bias.cpp
  src/ngraph/runtime/cpu/op/group_conv_bias.hpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/gcpu/gcpu_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/tools/nbench/nbench.cpp
  test/pattern.cpp
  test/specialize_function.cpp
Labels: Fully Reviewed

#4459 [ NonMaxSuppression ] Fixed shape inference
  src/ngraph/frontend/onnx_import/op/non_max_suppression.cpp
  src/ngraph/op/non_max_suppression.cpp
  test/type_prop/non_max_suppression.cpp
Labels: Fully Reviewed, MaskRCNN, OV

#4510 Add doxygen description for Validate pass
  src/ngraph/node.hpp
  src/ngraph/pass/manager.hpp
  src/ngraph/pass/validate.hpp
Labels: Fully Reviewed

#4503 Fixes for v1::ConvolutionBackpropData and v1:Convolution ops
  src/ngraph/op/convolution.cpp
  src/ngraph/op/group_conv.cpp
  src/ngraph/validation_util.cpp
Labels: Fully Reviewed, OV

#4528 Add support for option passing to backends in unit test
  src/ngraph/runtime/backend.cpp
  test/CMakeLists.txt
Labels: Fully Reviewed, OV

#4531 [ONNX] Change type of RoiAlign operator atributes to i64 type
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/op/roi_align.cpp
Labels: Fully Reviewed, ONNX, OV

#4441 Update Python API to produce v1 ops
  python/ngraph/__init__.py
  python/ngraph/ops.py
  python/ngraph/utils/broadcasting.py
  python/ngraph/utils/decorators.py
  python/ngraph/utils/node_factory.py
  python/pyngraph/node.cpp
  python/pyngraph/node_factory.cpp
  python/pyngraph/node_factory.hpp
  python/pyngraph/pyngraph.cpp
  python/setup.py
  python/test/ngraph/test_convolution.py
  python/test/ngraph/test_node_factory.py
  python/test/ngraph/test_ops_binary.py
  python/test/ngraph/test_ops_fused.py
  python/test/ngraph/test_ops_matmul.py
  python/test/ngraph/test_ops_multioutput.py
  python/test/ngraph/test_ops_reshape.py
  python/test/ngraph/test_ops_unary.py
  python/test/ngraph/test_pooling.py
  python/test/ngraph/test_reduction.py
  python/test/test_ops.py
  src/ngraph/op/avg_pool.hpp
  src/ngraph/op/fused/matmul.hpp
  src/ngraph/op/topk.hpp
  src/ngraph/pass/opset0_downgrade.cpp
Labels: Fully Reviewed, OV

#4458 [ Broadcast ] Dynamic shape infer
  src/ngraph/op/broadcast.cpp
  test/type_prop/broadcast.cpp
Labels: Fully Reviewed, High Priority, MaskRCNN, OV

#4534 [ONNX] Dynamic builder for Transpose
  src/ngraph/builder/reshape.cpp
  src/ngraph/op/experimental/transpose.cpp
  src/ngraph/op/experimental/transpose.hpp
  test/models/onnx/dynamic_shapes/transpose.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/type_prop/transpose.cpp
Labels: Fully Reviewed, ONNX, OV

#4539 Doxygen documentation for fused op decomposition pass
  doc/doxygen/images/decompose_gelu_post.svg
  doc/doxygen/images/decompose_gelu_pre.svg
  src/ngraph/pass/fused_op_decomposition.hpp
Labels: Fully Reviewed

#4543 [MLIR] Use OutputVector for compiled kernel inputs/outputs
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  src/ngraph/op/experimental/compiled_kernel.cpp
  src/ngraph/op/experimental/compiled_kernel.hpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
Labels: Fully Reviewed, MLIR

#4489 Cyphers/topkconst
  src/ngraph/CMakeLists.txt
  src/ngraph/evaluator.hpp
  src/ngraph/node.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  src/ngraph/type/element_type_traits.hpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/CMakeLists.txt
  test/eval.cpp
Labels: Fully Reviewed, OV

#4546 Remove component manager
  src/ngraph/CMakeLists.txt
  src/ngraph/component_manager.hpp
  src/ngraph/frontend/ATen/operators/test/main.cpp
  src/ngraph/ngraph.hpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_executable.cpp
  src/ngraph/runtime/ie/ie_backend.cpp
  src/ngraph/runtime/interpreter/int_backend.cpp
  src/tools/nbench/nbench.cpp
  test/main.cpp
Labels: Fully Reviewed

#4547 Silence cmake warning about unused flag
  cmake/external_llvm.cmake
Labels: Fully Reviewed

#4550 Adds get_opset3 method
  src/ngraph/opsets/opset.cpp
  src/ngraph/opsets/opset.hpp
  src/ngraph/opsets/opset2_tbl.hpp
Labels: Fully Reviewed, OV

#4548 Use a more sane path to find the test directory
  src/ngraph/frontend/ATen/operators/test/CMakeLists.txt
Labels: Fully Reviewed

#4551 Use configure_file instead of explicit file search/replace
  src/ngraph/runtime/backend_manager.cpp
  src/ngraph/runtime/backend_manager.hpp
  test/CMakeLists.txt
Labels: Fully Reviewed

#4542 Use attribute visitor in serializer
  src/ngraph/serializer.cpp
Labels: OV

#4466 Interval-based dimension
  src/ngraph/CMakeLists.txt
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/evaluator/tensor.cpp
  src/ngraph/evaluator/tensor.hpp
  src/ngraph/interval.cpp
  src/ngraph/interval.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/executable.cpp
  test/CMakeLists.txt
  test/intervals.cpp
  test/partial_shape.cpp
Labels: Dynamic Shape, Fully Reviewed, OV

#4143 Finish off some old deprecations, update some others
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/op.cpp
  src/ngraph/op/op.hpp
  src/ngraph/runtime/gpu/op/batch_norm.cpp
  src/ngraph/runtime/gpu/op/batch_norm.hpp
  src/ngraph/runtime/gpu/op/rnn.cpp
  src/ngraph/runtime/gpu/op/rnn.hpp
Labels: Fully Reviewed

#4541 Constant_folding method
  src/ngraph/CMakeLists.txt
  src/ngraph/node.hpp
  src/ngraph/op/experimental/shape_of.cpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_shape_of.cpp
  src/ngraph/pass/graph_rewrite.cpp
  src/ngraph/pass/graph_rewrite.hpp
Labels: Dynamic Shape, Fully Reviewed, High Priority, OV

#4555 Convert GPU copy_with_new_args
  src/ngraph/runtime/gpu/op/batch_norm.cpp
  src/ngraph/runtime/gpu/op/batch_norm.hpp
  src/ngraph/runtime/gpu/op/rnn.cpp
  src/ngraph/runtime/gpu/op/rnn.hpp
Labels: Fully Reviewed

#4557 Cyphers/fix mac build
  src/ngraph/runtime/ie/ie_backend.cpp
  src/ngraph/runtime/ie/ie_backend.hpp
Labels: Blocker, Fully Reviewed, High Priority, OV

#4556 Update CPU copy_with_new_args
  src/ngraph/runtime/cpu/op/batch_norm_relu.cpp
  src/ngraph/runtime/cpu/op/batch_norm_relu.hpp
  src/ngraph/runtime/cpu/op/bounded_relu.cpp
  src/ngraph/runtime/cpu/op/bounded_relu.hpp
  src/ngraph/runtime/cpu/op/conv_add.cpp
  src/ngraph/runtime/cpu/op/conv_add.hpp
  src/ngraph/runtime/cpu/op/conv_relu.cpp
  src/ngraph/runtime/cpu/op/conv_relu.hpp
  src/ngraph/runtime/cpu/op/convert_layout.cpp
  src/ngraph/runtime/cpu/op/convert_layout.hpp
  src/ngraph/runtime/cpu/op/deconv.cpp
  src/ngraph/runtime/cpu/op/deconv.hpp
  src/ngraph/runtime/cpu/op/dropout.cpp
  src/ngraph/runtime/cpu/op/dropout.hpp
  src/ngraph/runtime/cpu/op/gelu_backprop.cpp
  src/ngraph/runtime/cpu/op/gelu_backprop.hpp
  src/ngraph/runtime/cpu/op/group_conv_bias.cpp
  src/ngraph/runtime/cpu/op/group_conv_bias.hpp
  src/ngraph/runtime/cpu/op/leaky_relu.cpp
  src/ngraph/runtime/cpu/op/leaky_relu.hpp
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/matmul_bias.cpp
  src/ngraph/runtime/cpu/op/matmul_bias.hpp
  src/ngraph/runtime/cpu/op/max_pool_with_indices.cpp
  src/ngraph/runtime/cpu/op/max_pool_with_indices.hpp
  src/ngraph/runtime/cpu/op/quantized_matmul.hpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/op/sigmoid_mul.cpp
  src/ngraph/runtime/cpu/op/sigmoid_mul.hpp
  src/ngraph/runtime/cpu/op/update_slice.cpp
  src/ngraph/runtime/cpu/op/update_slice.hpp
Labels: Fully Reviewed

#4558 Update GCPU to call opt_kernels instead of reference
  src/ngraph/runtime/gcpu/gcpu_executable.hpp
Labels: Fully Reviewed

#4559 Make CPU backend cmake self-contained
  src/ngraph/runtime/CMakeLists.txt
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#4565 Introduced mechanism to propagate rt info attributes through transformations
  src/ngraph/CMakeLists.txt
  src/ngraph/rt_info.cpp
  src/ngraph/rt_info.hpp
  src/ngraph/variant.hpp
Labels: Fully Reviewed

#4549 [ Gather ] Constant Folding for scalar case
  src/ngraph/pass/constant_folding_gather.cpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#4488 [MaskRCNN] ONNX Dynamic Flatten
  src/ngraph/builder/reshape.cpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/dynamic_shapes/flatten_dyn_shape_axis.prototxt
  test/models/onnx/dynamic_shapes/flatten_dyn_shape_axis0.prototxt
  test/models/onnx/dynamic_shapes/flatten_dyn_shape_neg_axis.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
Labels: Fully Reviewed, MaskRCNN, ONNX, OV

#4569 Fixed cmake configuration for Visual Studio
  src/ngraph/runtime/ie/CMakeLists.txt
Labels: Fully Reviewed, High Priority, OV

#4563 Remove support for old version of MKLDNN
  src/ngraph/runtime/cpu/builder/convert_layout.cpp
  src/ngraph/runtime/cpu/builder/lstm.cpp
  src/ngraph/runtime/cpu/builder/rnn.cpp
  src/ngraph/runtime/cpu/cpu_executor.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.cpp
  src/ngraph/runtime/cpu/cpu_layout_descriptor.hpp
  src/ngraph/runtime/cpu/cpu_tensor.cpp
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/mkldnn_invoke.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.cpp
  src/ngraph/runtime/cpu/mkldnn_utils.hpp
  src/ngraph/runtime/cpu/op/lstm.cpp
  src/ngraph/runtime/cpu/op/lstm.hpp
  src/ngraph/runtime/cpu/op/rnn.cpp
  src/ngraph/runtime/cpu/op/rnn.hpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/cpu/pass/cpu_post_layout_optimizations.cpp
  src/ngraph/runtime/cpu/pass/cpu_rnn_fusion.cpp
  test/cpu_fusion.cpp
Labels: Fully Reviewed

#4571 Unit test to check proper conversion of input vector for Constant ctor
  test/constant.cpp
Labels: Fully Reviewed

#4353 [Py] Python wheel building support for Windows
  python/BUILDING.md
  python/CMakeLists.txt
  python/build_wheel.py.in
  python/ngraph/impl/__init__.py
  python/ngraph/impl/onnx_import/__init__.py
  python/ngraph/impl/op/__init__.py
  python/ngraph/impl/op/util/__init__.py
  python/ngraph/impl/passes/__init__.py
  python/ngraph/impl/runtime/__init__.py
  python/pyngraph/util.py
  python/setup.py
Labels: Fully Reviewed, OV

#4533 [DynamicShape] Add dynamic shape support for builder::mean
  src/ngraph/builder/reduce_ops.cpp
  test/CMakeLists.txt
  test/backend/builder_reduce_ops_opset1.in.cpp
Labels: Dynamic Shape, Fully Reviewed, OV

#4562 Remove obsolete cmake
  CMakeLists.txt
  cmake/external_mkldnn.cmake
  src/ngraph/codegen/compiler.cpp
  src/ngraph/runtime/cpu/CMakeLists.txt
Labels: Fully Reviewed

#4560 Cyphers/opmove
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/reshape.cpp
  src/ngraph/op/ctc_greedy_decoder.cpp
  src/ngraph/op/ctc_greedy_decoder.hpp
  src/ngraph/op/detection_output.cpp
  src/ngraph/op/detection_output.hpp
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.hpp
  src/ngraph/op/experimental/layers/detection_output.hpp
  src/ngraph/op/experimental/layers/interpolate.hpp
  src/ngraph/op/experimental/layers/prior_box.hpp
  src/ngraph/op/experimental/layers/prior_box_clustered.hpp
  src/ngraph/op/experimental/layers/proposal.hpp
  src/ngraph/op/experimental/layers/psroi_pooling.hpp
  src/ngraph/op/experimental/layers/region_yolo.hpp
  src/ngraph/op/experimental/layers/reorg_yolo.hpp
  src/ngraph/op/experimental/layers/roi_pooling.hpp
  src/ngraph/op/experimental/range.hpp
  src/ngraph/op/experimental/shape_of.hpp
  src/ngraph/op/experimental/tile.hpp
  src/ngraph/op/experimental/transpose.hpp
  src/ngraph/op/interpolate.cpp
  src/ngraph/op/interpolate.hpp
  src/ngraph/op/prior_box.cpp
  src/ngraph/op/prior_box.hpp
  src/ngraph/op/prior_box_clustered.cpp
  src/ngraph/op/prior_box_clustered.hpp
  src/ngraph/op/proposal.cpp
  src/ngraph/op/proposal.hpp
  src/ngraph/op/psroi_pooling.cpp
  src/ngraph/op/psroi_pooling.hpp
  src/ngraph/op/range.cpp
  src/ngraph/op/range.hpp
  src/ngraph/op/region_yolo.cpp
  src/ngraph/op/region_yolo.hpp
  src/ngraph/op/reorg_yolo.cpp
  src/ngraph/op/reorg_yolo.hpp
  src/ngraph/op/roi_pooling.cpp
  src/ngraph/op/roi_pooling.hpp
  src/ngraph/op/shape_of.cpp
  src/ngraph/op/shape_of.hpp
  src/ngraph/op/tile.cpp
  src/ngraph/op/tile.hpp
  src/ngraph/op/transpose.cpp
  src/ngraph/op/transpose.hpp
  src/ngraph/ops.hpp
  src/ngraph/pass/constant_folding_range.cpp
  src/ngraph/pass/constant_folding_tile.cpp
  src/ngraph/pass/constant_folding_transpose.cpp
  src/ngraph/pass/dyn_elimination.cpp
  src/ngraph/runtime/cpu/builder/tile.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  test/cpu_test.cpp
  test/type_prop/proposal.cpp
  test/type_prop_layers.cpp
Labels: Blocker, Fully Reviewed, OV

#4544 [DynamicShape] Add dynamic shape support for GlobalLpPool
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/norm.hpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/reduce.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/op/fused/grn.cpp
  src/ngraph/op/fused/normalize_l2.cpp
  test/models/onnx/global_lp_pool_dynamic_hw.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/provenance.cpp
Labels: Dynamic Shape, Fully Reviewed, OV

#4433 [ONNX] Add Resize-10 op to ONNX importer
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/resize.cpp
  src/ngraph/frontend/onnx_import/op/resize.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  test/models/onnx/resize_opset10.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, MaskRCNN, ONNX, OV

#4575 Fix unit tests to work if no backends are built
  test/CMakeLists.txt
  test/reshape_elimination.cpp
Labels: Fully Reviewed

#4578 Op constructor for GetOutputElement
  src/ngraph/op/op.hpp
Labels: Fully Reviewed, High Priority, OV

#4536 update nop_elimination pass for openvino use
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/pass/nop_elimination.cpp
  src/ngraph/pass/nop_elimination.hpp
  test/backend/slice.in.cpp
  test/nop_elimination.cpp
Labels: Fully Reviewed, MaskRCNN, OV

#4570 Move prefix from backend name to test name
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_convpool.in.cpp
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/onnx/onnx_import_provenance.in.cpp
  test/onnx/onnx_import_quant.in.cpp
  test/onnx/onnx_import_reshape.in.cpp
  test/onnx/onnx_import_rnn.in.cpp
Labels: Fully Reviewed

#4573 Expand attribute visitor types
  src/ngraph/attribute_adapter.cpp
  src/ngraph/attribute_adapter.hpp
  src/ngraph/attribute_visitor.hpp
  test/attributes.cpp
Labels: Fully Reviewed, OV

#4580 CMake minimum is 3.11. Cleanup outdated code.
  cmake/llvm_fetch.cmake.in
Labels: Fully Reviewed

#4584 Update copy_runtime_info function signature to use NodeVector
  src/ngraph/rt_info.cpp
  src/ngraph/rt_info.hpp
  src/ngraph/variant.hpp
Labels: Fully Reviewed

#4588 Fix location of manifest file for moving backends
  test/CMakeLists.txt
Labels: Fully Reviewed

#4576 [ONNX] Refactor ONNX tests with constant folding
  test/CMakeLists.txt
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_const_folding.in.cpp
Labels: Fully Reviewed, ONNX

#4581 Constant constructor for uniform constant from scalar
  src/ngraph/op/constant.hpp
  test/constant.cpp
Labels: Fully Reviewed

#4587 Add doxygen info for DynElimination pass
  doc/doxygen/images/dyn_broadcast_post_constfld.svg
  doc/doxygen/images/dyn_broadcast_post_dyneliminate.svg
  doc/doxygen/images/dyn_broadcast_pre_constfld.svg
  src/ngraph/pass/dyn_elimination.hpp
Labels: Fully Reviewed

#4470 [ONNX] Add Slice-10 to ONNX importer
  src/ngraph/frontend/onnx_import/op/slice.cpp
  src/ngraph/frontend/onnx_import/op/slice.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/strided_slice.cpp
  test/models/onnx/dynamic_shapes/slice_2d_default_steps_dyn_begin_end.prototxt
  test/models/onnx/dynamic_shapes/slice_2d_input.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input_12_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input_20_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input_neg_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_0231_axes_ends_max.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_2103_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_23_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_23_axes_21_steps.prototxt
  test/models/onnx/dynamic_shapes/slice_default_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_default_steps.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/type_prop/strided_slice.cpp
Labels: Fully Reviewed, MaskRCNN, ONNX, OV

#4567 op::v3::ShapeOf
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/shape_of.cpp
  src/ngraph/op/shape_of.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/interpreter/opset_int_tbl.hpp
  src/ngraph/runtime/reference/shape_of.hpp
  src/runtime/gpu/gpu_emitter.cpp
  test/backend/dynamic.in.cpp
  test/backend/shape_of.in.cpp
  test/constant_folding.cpp
  test/pass_shape_relevance.cpp
  test/type_prop/shape_of.cpp
Labels: Fully Reviewed, OV

#4487 [MaskRCNN] ONNX Dynamic Convolution Transpose
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
  src/ngraph/runtime/cpu/unit_test.manifest
  src/ngraph/runtime/gcpu/unit_test.manifest
  src/ngraph/runtime/interpreter/unit_test.manifest
  test/models/onnx/convtranspose_dyn_data.prototxt
  test/models/onnx/convtranspose_dyn_filters.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
Labels: Fully Reviewed, MaskRCNN, ONNX, OV

#4585 [CMAKE] Exclude ONNX library from target `all` in ngraph
  cmake/external_onnx.cmake
Labels: Fully Reviewed

#4598 ATen frontend removal
  src/ngraph/frontend/ATen/CMakeLists.txt
  src/ngraph/frontend/ATen/README.md
  src/ngraph/frontend/ATen/operators/test/CMakeLists.txt
  src/ngraph/frontend/ATen/operators/test/dummy.cpp
  src/ngraph/frontend/ATen/operators/test/main.cpp
  src/ngraph/frontend/ATen/operators/test/test.manifest
  src/ngraph/frontend/CMakeLists.txt
Labels: Fully Reviewed, OV

#4592 Fixed backend tests for debug configuration
  src/ngraph/CMakeLists.txt
Labels: High Priority

#4604 Add attribute adapters for element::Type, element::Type_t, missing exports
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
  test/attributes.cpp
Labels: Bug, Fully Reviewed, OV

#4605 NGRAPH_API for axis normalization
  src/ngraph/validation_util.hpp
Labels: Fully Reviewed, OV

#4516 oneDNN: Update to 1.4
  cmake/external_mkldnn_v1.cmake
  cmake/mkldnn_v1.patch
  test/backend/sigmoid.in.cpp
Labels: DNNL, Fully Reviewed

#4583 Interpreter/Constant folding with same kernels
  src/ngraph/CMakeLists.txt
  src/ngraph/evaluator.hpp
  src/ngraph/evaluator_tensor.cpp
  src/ngraph/evaluator_tensor.hpp
  src/ngraph/lambda.cpp
  src/ngraph/lambda.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/add.hpp
  src/ngraph/op/constant.cpp
  src/ngraph/op/constant.hpp
  src/ngraph/op/result.cpp
  src/ngraph/op/result.hpp
  src/ngraph/op/shape_of.cpp
  src/ngraph/op/shape_of.hpp
  src/ngraph/op/softmax.cpp
  src/ngraph/op/softmax.hpp
  src/ngraph/partial_shape.cpp
  src/ngraph/partial_shape.hpp
  src/ngraph/pass/constant_folding.cpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/runtime/gcpu/gcpu_executable.cpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/host_tensor.hpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/eval.cpp
Labels: High Priority, OV

#4593 Removed axis normalization for Concat op in Onnx importer.
  src/ngraph/frontend/onnx_import/op/concat.cpp
Labels: Fully Reviewed, OV

#4601 Fix TopK output shape when k is not known
  python/test/ngraph/test_node_factory.py
  src/ngraph/op/topk.cpp
  test/type_prop/top_k.cpp
Labels: Bug, Fully Reviewed, OV

#4545 Update IE backend manifest.
  src/ngraph/runtime/ie/unit_test.manifest
  test/CMakeLists.txt
Labels: Fully Reviewed, OV

#4512 Cyphers/topkmax
  src/ngraph/op/topk.cpp
Labels: Dynamic Shape, Fully Reviewed, OV

#4608 Interpreter cleanup
  src/ngraph/runtime/interpreter/int_executable.hpp
Labels: Fully Reviewed, OV

#4602 add redundant reshape, squeeze, unsqueeze elimination
  src/ngraph/graph_util.cpp
  src/ngraph/pass/nop_elimination.cpp
  test/cpu_fusion.cpp
  test/nop_elimination.cpp
  test/util/all_close.hpp
Labels: Fully Reviewed, MaskRCNN, OV

#4564 Optimize gather
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  test/algebraic_simplification.cpp
Labels: Fully Reviewed, OV

#4577 Adjust NonZero to the new specs
  src/ngraph/frontend/onnx_import/op/non_zero.cpp
  src/ngraph/op/non_zero.cpp
  src/ngraph/op/non_zero.hpp
  src/ngraph/pass/constant_folding_non_zero.cpp
  src/ngraph/serializer.cpp
  test/constant_folding.cpp
  test/type_prop/non_zero.cpp
Labels: Fully Reviewed, OV, SPEC

#4597 Add output_type attribute to NonMaxSuppression for OV opset3
  src/ngraph/op/non_max_suppression.cpp
  src/ngraph/op/non_max_suppression.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/attributes.cpp
  test/type_prop/non_max_suppression.cpp
Labels: Fully Reviewed, OV

#4617 Fix style scripts
  maint/apply-code-format.sh
  maint/check-code-format.sh
Labels: Fully Reviewed

#4616 Import ONNX models directly from ModelProto
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
Labels: Fully Reviewed, ONNX

#4618 Fix some uses of get_argument
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/core_fusion.cpp
  src/ngraph/pass/reshape_sinking.cpp
  src/ngraph/runtime/cpu/builder/broadcast.cpp
  src/ngraph/runtime/cpu/builder/pad.cpp
  src/ngraph/runtime/cpu/builder/reshape.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/mkldnn_emitter.hpp
  src/ngraph/runtime/cpu/pass/cpu_collapse_dims.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/runtime/gpu/pass/gpu_batch_norm_cache.cpp
  test/reshape_sinking.cpp
Labels: Fully Reviewed

#4596 simplify gather->shapeof into shapeof->gather for 0D indices
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/algebraic_simplification.hpp
  src/ngraph/pass/nop_elimination.cpp
  test/algebraic_simplification.cpp
  test/backend/batch_norm.in.cpp
  test/nop_elimination.cpp
Labels: Fully Reviewed, MaskRCNN, OV

#4621 Add EvaluatorTensor functionality into HostTensor
  src/ngraph/descriptor/tensor.cpp
  src/ngraph/descriptor/tensor.hpp
  src/ngraph/evaluator_tensor.hpp
  src/ngraph/op/add.cpp
  src/ngraph/op/shape_of.cpp
  src/ngraph/op/softmax.cpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/host_tensor.hpp
Labels: Blocked, Fully Reviewed, OV

#4535 [MLIR] Convert to MLIR integer type
  src/contrib/mlir/core/ngraph_dialect/dialect.cpp
  src/contrib/mlir/core/ngraph_dialect/ops.cpp
  src/contrib/mlir/core/ngraph_dialect/type.cpp
  src/contrib/mlir/core/ngraph_dialect/type.hpp
  src/contrib/mlir/core/pass/ng_dialect_builder.cpp
  test/mlir/ngraph_dialect/elementwise_binary_ops.mlir
  test/mlir/ngraph_dialect/fused_ops.mlir
  test/mlir/ngraph_dialect/types.mlir
Labels: MLIR

#4611 Alternative style
  src/ngraph/node.hpp
  src/ngraph/op/add.cpp
Labels: Fully Reviewed

#4603 Migrate a few kernels/folders to using methods
  src/ngraph/op/add.cpp
  src/ngraph/op/divide.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/maximum.cpp
  src/ngraph/op/maximum.hpp
  src/ngraph/op/minimum.cpp
  src/ngraph/op/minimum.hpp
  src/ngraph/op/multiply.cpp
  src/ngraph/op/multiply.hpp
  src/ngraph/op/power.cpp
  src/ngraph/op/power.hpp
  src/ngraph/op/shape_of.cpp
  src/ngraph/op/subtract.cpp
  src/ngraph/op/subtract.hpp
  src/ngraph/pass/constant_folding_binary.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/reference/and.hpp
  src/ngraph/runtime/reference/divide.hpp
  src/ngraph/runtime/reference/maximum.hpp
  src/ngraph/runtime/reference/minimum.hpp
  src/ngraph/runtime/reference/multiply.hpp
  src/ngraph/runtime/reference/power.hpp
  src/ngraph/runtime/reference/subtract.hpp
Labels: Fully Reviewed, OV

#4635 Backport of "make install" corrections to rov.2020.3
  cmake/external_onnx.cmake
  src/ngraph/frontend/ATen/CMakeLists.txt
  src/ngraph/frontend/ATen/README.md
  src/ngraph/frontend/ATen/operators/test/CMakeLists.txt
  src/ngraph/frontend/ATen/operators/test/dummy.cpp
  src/ngraph/frontend/ATen/operators/test/main.cpp
  src/ngraph/frontend/ATen/operators/test/test.manifest
  src/ngraph/frontend/CMakeLists.txt
Labels: Fully Reviewed, rov2020.3

#4650 Merge dynamic to master
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/pass/nop_elimination.cpp
  test/algebraic_simplification.cpp
  test/nop_elimination.cpp
Labels: Fully Reviewed, Passed OV CI

#4579 Add support for v3 TopK operator
  python/test/ngraph/test_node_factory.py
  python/test/ngraph/test_reduction.py
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  test/backend/topk.in.cpp
  test/type_prop/top_k.cpp
Labels: Fully Reviewed, OV, SPEC

#4566 [OV] Replace transpose with reshape
  src/ngraph/pass/algebraic_simplification.cpp
  test/algebraic_simplification.cpp
Labels: Fully Reviewed, High Priority, OV

#4638 update softmax evaluate for dynamic shape input
  src/ngraph/op/softmax.cpp
Labels: Fully Reviewed, OV

#4600 Add Broadcast:v3 op
  src/ngraph/CMakeLists.txt
  src/ngraph/attribute_visitor.hpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/broadcast.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/op/util/attr_types.cpp
  src/ngraph/op/util/attr_types.hpp
  src/ngraph/op/util/broadcast_base.cpp
  src/ngraph/op/util/broadcast_base.hpp
  src/ngraph/opsets/opset3_tbl.hpp
  src/ngraph/pass/algebraic_simplification.cpp
  src/ngraph/runtime/dynamic/dynamic_backend.cpp
  test/attributes.cpp
  test/type_prop/broadcast.cpp
Labels: Fully Reviewed, High Priority, OV, SPEC

#4647 Custom ONNX namespace for nGraph
  cmake/external_onnx.cmake
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.cpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/onnx.hpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  test/CMakeLists.txt
  test/onnx/onnx_import_library.in.cpp
Labels: OV, rov2020.3

#4614 [rov.2020.3] Add ONNX Slice-10 operator
  src/ngraph/frontend/onnx_import/op/slice.cpp
  src/ngraph/frontend/onnx_import/op/slice.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/op/strided_slice.cpp
  test/models/onnx/dynamic_shapes/slice_2d_default_steps_dyn_begin_end.prototxt
  test/models/onnx/dynamic_shapes/slice_2d_input.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input_12_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input_20_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_3d_input_neg_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_0231_axes_ends_max.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_2103_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_23_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_4d_input_23_axes_21_steps.prototxt
  test/models/onnx/dynamic_shapes/slice_default_axes.prototxt
  test/models/onnx/dynamic_shapes/slice_default_steps.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/type_prop/strided_slice.cpp
Labels: Fully Reviewed, Passed OV CI, rov2020.3

#4667 Fixed the Transpose to Reshape pass to not use the Node pointer
  src/ngraph/pass/algebraic_simplification.cpp
Labels: Fully Reviewed, High Priority, OV, Passed OV CI

#4271 Introduce customized namespace for ONNX library
  cmake/external_onnx.cmake
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/core/attribute.hpp
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  src/ngraph/frontend/onnx_import/core/model.cpp
  src/ngraph/frontend/onnx_import/core/model.hpp
  src/ngraph/frontend/onnx_import/core/node.cpp
  src/ngraph/frontend/onnx_import/core/node.hpp
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/core/value_info.hpp
  src/ngraph/frontend/onnx_import/onnx.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  test/CMakeLists.txt
  test/onnx/onnx_import_library.in.cpp
Labels: Fully Reviewed, ONNX, OV

#4401 Add get_ops and get_ordered_ops to PyBind wrapper of Function
  python/src/pyngraph/function.cpp
  python/src/pyngraph/node.cpp
  python/test/ngraph/test_basic.py
Labels: Fully Reviewed, OV

#4637 Interpreter: Use reference::copy for Squeeze and Unsqueeze
  src/ngraph/CMakeLists.txt
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/squeeze.hpp
  src/ngraph/op/fused/unsqueeze.cpp
  src/ngraph/op/fused/unsqueeze.hpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_squeeze.cpp
  src/ngraph/pass/constant_folding_unsqueeze.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
  test/backend/fused_op.in.cpp
Labels: Fully Reviewed, OV
