Repository NervanaSystems/ngraph, pull requests merged in 2020-02, with the labels that each got.

#4167 Address warnings generated when compiled with gcc 4.8 and -Wall
  CMakeLists.txt
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/cpu/builder/matmul_bias.cpp
  src/ngraph/runtime/gcpu/gcpu_executable.hpp
Labels: Fully Reviewed, Merge Blocked

#4194 Update broadcasting helpers to use v1 operators.
  src/ngraph/builder/matmul_factory.cpp
  src/ngraph/builder/reshape.cpp
  src/ngraph/builder/reshape.hpp
  src/ngraph/frontend/onnx_import/op/add.cpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/expand.cpp
  src/ngraph/frontend/onnx_import/op/instance_norm.cpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.cpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/fused/lstm_sequence.cpp
  src/ngraph/op/util/broadcasting.cpp
  src/ngraph/op/util/broadcasting.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
Labels: Fully Reviewed, ONNX

#4262 Handle unknown ranks and partial shapes in reduction axes inference f…
  src/ngraph/op/fused/mvn.cpp
  test/type_prop/mvn.cpp
Labels: Fully Reviewed

#4274 Use old version for Windows until compiler errors are resolved.
  cmake/external_json.cmake
Labels: Bug, Fully Reviewed

#4267 Add GPU to codeowners
  CODEOWNERS
Labels: Fully Reviewed

#4268 CODEOWNERS cleanup
  CODEOWNERS
Labels: Fully Reviewed

#4263 Assorted cleanups migrated from GOE removal work
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/util.cpp
  src/ngraph/util.hpp
  test/util/autodiff/backprop_derivative.hpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#4264 Export AttributeAdapter specializations used in Inference Engine
  src/ngraph/partial_shape.hpp
  src/ngraph/type/element_type.cpp
  src/ngraph/type/element_type.hpp
Labels: Fully Reviewed

#4269 Remove Hybrid GPU backend
  CMakeLists.txt
  src/ngraph/runtime/CMakeLists.txt
  src/ngraph/runtime/gpuh/CMakeLists.txt
  src/ngraph/runtime/gpuh/gpuh_backend.cpp
  src/ngraph/runtime/gpuh/gpuh_backend.hpp
  src/ngraph/runtime/gpuh/unit_test.manifest
  test/CMakeLists.txt
Labels: Fully Reviewed

#4207 Convert Function::get_ops/get_ordered_ops to return vector instead of list
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/pass/liveness.cpp
  src/ngraph/pass/memory_visualize.cpp
  src/ngraph/pass/memory_visualize.hpp
  src/ngraph/pass/pass.cpp
  src/ngraph/pass/pass.hpp
  src/ngraph/pass/visualize_tree.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_assignment.hpp
  test/util.cpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed

#4282 Dynamic Clamp shape/data_type propagation
  src/ngraph/op/fused/clamp.cpp
  src/ngraph/op/strided_slice.hpp
Labels: Fully Reviewed

#4260 pybind11 2.4.3
  python/CMakeLists.txt
Labels: Fully Reviewed

#4276 Bug Fix: Codegen - macos system header path is hard wired for mojave.
  src/ngraph/codegen/CMakeLists.txt
  src/ngraph/codegen/compiler.cpp
Labels: Bug, Fully Reviewed

#4273 Divide opset1 tests
  src/ngraph/opsets/opset.hpp
  test/CMakeLists.txt
  test/opset1.cpp
  test/util/backend_utils.hpp
  test/util/unit-test-execution/README.md
  test/util/unit-test-execution/conftest.py
  test/util/unit-test-execution/requirements.txt
  test/util/unit-test-execution/unit_test_executable.py
Labels: Fully Reviewed, High Priority

#4295 Disable NORMALIZE_BOOL in frontend build as a workaround for #4293
  src/ngraph/frontend/CMakeLists.txt
Labels: Bug, Fully Reviewed

#4158 Use GroupConvolutionBackpropData v1 in ONNX ConvTranspose.
  src/ngraph/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/op/fused/group_conv.cpp
  src/ngraph/op/fused/group_conv.hpp
  src/ngraph/op/fused/group_conv_transpose.cpp
  src/ngraph/op/fused/group_conv_transpose.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset0_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  src/ngraph/runtime/interpreter/int_executable.hpp
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/CMakeLists.txt
  test/backend/fused_op.in.cpp
  test/backend/group_convolution.in.cpp
  test/models/onnx/convtranspose_groups_pads_bias.prototxt
  test/models/onnx/convtranspose_groups_w_pads.prototxt
  test/models/onnx/convtranspose_output_shape_auto_pads_same_lower.prototxt
  test/models/onnx/convtranspose_output_shape_auto_pads_same_upper.prototxt
  test/onnx/onnx_import_convpool.in.cpp
  test/op_is.cpp
  test/opset_pass/convolution_opset_pass.cpp
  test/type_prop/group_convolution_backprop_data.cpp
  test/type_prop/group_convolution_transpose.cpp
Labels: Fully Reviewed, ONNX

#4206 Allow topological sort in Function to be replaced
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  test/util.cpp
Labels: Fully Reviewed

#4249 [MLIR] MLIR repo update
  cmake/external_mlir.cmake
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
Labels: Fully Reviewed

#4286 Remove using statement
  src/ngraph/runtime/tensor.hpp
Labels: Fully Reviewed

#4272 Revert "add set_parameters, set_results and serialize types (#4168)"
  src/ngraph/runtime/executable.cpp
  src/ngraph/runtime/executable.hpp
  src/ngraph/serializer.cpp
  src/ngraph/serializer.hpp
  test/serialize.cpp
Labels: Fully Reviewed

#4283 fix reshape_sinking for broadcast & single user swim only
  src/ngraph/pass/reshape_sinking.cpp
Labels: Fully Reviewed

#4297 Fixed warning "control reaches end of non-void function"
  src/ngraph/op/constant.hpp
Labels: Fully Reviewed, High Priority

#4304 Fix Python CI build break
  python/test_requirements.txt
Labels: Fully Reviewed

#4306 Bring the NVIDIA GPU backend up to date with nGraph master
  src/ngraph/runtime/gpu/cudnn_emitter.cpp
  src/ngraph/runtime/gpu/cudnn_emitter.hpp
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_backend.hpp
  src/ngraph/runtime/gpu/gpu_compiled_function.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/gpu_emitter.hpp
  src/ngraph/runtime/gpu/gpu_runtime_constructor.hpp
  src/ngraph/runtime/gpu/op/batch_norm.cpp
  src/ngraph/runtime/gpu/op/batch_norm.hpp
  src/ngraph/runtime/gpu/op/op_tbl.hpp
  src/ngraph/runtime/gpu/op/rnn.cpp
  src/ngraph/runtime/gpu/op/rnn.hpp
Labels: Fully Reviewed

#4308 Remove PlaidML team members from CODEOWNERS
  CODEOWNERS
Labels: Fully Reviewed

#4300 Cleanup headers
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/ngraph/env_util.cpp
  src/ngraph/frontend/onnx_import/op/matmul_integer.cpp
  src/ngraph/frontend/onnx_import/op/qlinear_matmul.cpp
  src/ngraph/log.cpp
  src/ngraph/log.hpp
  src/ngraph/op/allreduce.hpp
  src/ngraph/op/avg_pool.cpp
  src/ngraph/op/batch_norm.cpp
  src/ngraph/op/binary_convolution.cpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/broadcast_distributed.cpp
  src/ngraph/op/concat.cpp
  src/ngraph/op/select.cpp
  src/ngraph/op/util/binary_elementwise_arithmetic.cpp
  src/ngraph/op/util/binary_elementwise_comparison.cpp
  src/ngraph/op/util/binary_elementwise_logical.cpp
  src/ngraph/op/util/index_reduction.cpp
  src/ngraph/pass/batch_fusion.cpp
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/pass_util.cpp
  src/ngraph/pass/propagate_cacheability.cpp
  src/ngraph/placement.hpp
  src/ngraph/runtime/cpu/builder/broadcast_distributed.cpp
  src/ngraph/runtime/cpu/builder/softmax.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_cse.cpp
  src/ngraph/runtime/cpu/cpu_visualize_tree.cpp
  src/ngraph/runtime/cpu/op/deconv.cpp
  src/ngraph/runtime/cpu/pass/cpu_assignment.cpp
  src/ngraph/runtime/cpu/pass/cpu_mat_fusion.cpp
  src/ngraph/runtime/cpu/pass/cpu_memory_optimization.cpp
  src/ngraph/runtime/plaidml/plaidml_pass_explicit_logicals.cpp
  src/ngraph/serializer.cpp
  test/bfloat16.cpp
Labels: Fully Reviewed

#4270 Dynamic Squeeze/Unsqueeze type and rank propagation
  src/ngraph/op/fused/squeeze.cpp
  src/ngraph/op/fused/squeeze.hpp
  src/ngraph/op/fused/unsqueeze.cpp
  test/type_prop/squeeze.cpp
  test/type_prop/unsqueeze.cpp
Labels: Fully Reviewed

#4296 Disable -Werror by default in nGraph build
  CMakeLists.txt
Labels: Fully Reviewed

#4292 [ONNX] Update status of supported ops.
  src/ngraph/frontend/onnx_import/op/supported_ops.md
Labels: Fully Reviewed, ONNX

#4307 Aslepko/test
  src/ngraph/pass/constant_folding_one_hot.cpp
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/onnx/onnx_import_provenance.in.cpp
Labels: Fully Reviewed

#4299 Extend normalize axes helpers to support dynamic shapes
  src/ngraph/frontend/onnx_import/op/concat.cpp
  src/ngraph/frontend/onnx_import/op/dequantize_linear.cpp
  src/ngraph/frontend/onnx_import/op/flatten.cpp
  src/ngraph/frontend/onnx_import/op/gather.hpp
  src/ngraph/frontend/onnx_import/op/hardmax.cpp
  src/ngraph/frontend/onnx_import/op/log_softmax.cpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/frontend/onnx_import/op/mean_variance_normalization.cpp
  src/ngraph/frontend/onnx_import/op/reverse_sequence.cpp
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/op/topk.cpp
  src/ngraph/frontend/onnx_import/op/unsqueeze.cpp
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/op/fused/split.cpp
  src/ngraph/op/reverse_sequence.cpp
  src/ngraph/op/util/arithmetic_reduction.cpp
  src/ngraph/op/util/logical_reduction.cpp
  src/ngraph/op/util/logical_reduction_keep_dims.cpp
  src/ngraph/op/variadic_split.cpp
  src/ngraph/pass/constant_folding_split.cpp
  src/ngraph/pass/constant_folding_variadic_split.cpp
  src/ngraph/validation_util.cpp
  src/ngraph/validation_util.hpp
  test/type_prop/reverse_sequence.cpp
Labels: Dynamic Shape, Fully Reviewed, ONNX

#4305 Move Input/Output from node.?pp to separate files
  src/ngraph/CMakeLists.txt
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/node_input.cpp
  src/ngraph/node_input.hpp
  src/ngraph/node_output.cpp
  src/ngraph/node_output.hpp
Labels: Fully Reviewed

#4301 [ONNX] Inverse hyperbolic functions - dynamic shape support
  src/ngraph/frontend/onnx_import/op/acosh.cpp
  src/ngraph/frontend/onnx_import/op/asinh.cpp
  src/ngraph/frontend/onnx_import/op/atanh.cpp
  test/models/onnx/acosh.prototxt
  test/models/onnx/asinh.prototxt
  test/models/onnx/atanh.prototxt
  test/models/onnx/dynamic_shapes/acosh_dyn_shape.prototxt
  test/models/onnx/dynamic_shapes/asinh_dyn_shape.prototxt
  test/models/onnx/dynamic_shapes/atanh_dyn_shape.prototxt
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_dyn_shapes.in.cpp
Labels: Dynamic Shape, Fully Reviewed, ONNX

#4313 Speed up Validate pass
  src/ngraph/function.cpp
Labels: Fully Reviewed

#4279 Add some attribute visitors
  src/ngraph/attribute_adapter.cpp
  src/ngraph/attribute_adapter.hpp
  src/ngraph/node.hpp
  src/ngraph/op/convert.cpp
  src/ngraph/op/convert.hpp
  src/ngraph/op/convert_like.cpp
  src/ngraph/op/convert_like.hpp
  src/ngraph/op/convolution.cpp
  src/ngraph/op/convolution.hpp
  src/ngraph/op/cos.cpp
  src/ngraph/op/cos.hpp
  src/ngraph/op/cosh.cpp
  src/ngraph/op/cosh.hpp
  src/ngraph/op/deformable_convolution.cpp
  src/ngraph/op/deformable_convolution.hpp
  src/ngraph/op/deformable_psroi_pooling.cpp
  src/ngraph/op/deformable_psroi_pooling.hpp
  src/ngraph/op/divide.cpp
  src/ngraph/op/divide.hpp
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.cpp
  src/ngraph/op/experimental/layers/ctc_greedy_decoder.hpp
  src/ngraph/op/fused/clamp.cpp
  src/ngraph/op/fused/clamp.hpp
  src/ngraph/op/fused/depth_to_space.cpp
  src/ngraph/op/fused/depth_to_space.hpp
Labels: Fully Reviewed

#4312 Remove Event tracing and replace with chrome trace
  src/ngraph/CMakeLists.txt
  src/ngraph/chrome_trace.cpp
  src/ngraph/chrome_trace.hpp
  src/ngraph/event_tracing.cpp
  src/ngraph/event_tracing.hpp
  src/ngraph/runtime/host_tensor.cpp
  src/ngraph/runtime/interpreter/int_executable.cpp
  test/CMakeLists.txt
  test/event_tracing.cpp
Labels: Changes API, Fully Reviewed

#4314 ConvBackPropData dynamic output shape input
  src/ngraph/op/convolution.cpp
  src/ngraph/op/fused/group_conv.cpp
Labels: Fully Reviewed

#4315 Always use control deps in sorting
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/function.cpp
  src/ngraph/function.hpp
  src/ngraph/graph_util.cpp
  src/ngraph/graph_util.hpp
  src/ngraph/node.cpp
  src/ngraph/serializer.cpp
  src/ngraph/util.cpp
  test/provenance.cpp
  test/util.cpp
Labels: Fully Reviewed

#4319 Add GPU visibility and other fixes
  src/ngraph/runtime/gpu/gpu_backend_visibility.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
Labels: Fully Reviewed

#4321 Avoid printing empty NGRAPH_CXX_STANDARD
  CMakeLists.txt
Labels: Fully Reviewed

#4329 Avoid size_t issue in Gather
  src/ngraph/dimension.cpp
  src/ngraph/dimension.hpp
  src/ngraph/op/gather.cpp
  src/ngraph/op/gather.hpp
Labels: Fully Reviewed

#4334 Add refs to DLDT doc and remove PlaidML-related docs
  doc/sphinx/source/backends/index.rst
  doc/sphinx/source/backends/plaidml-ng-api/index.rst
  doc/sphinx/source/buildlb.rst
  doc/sphinx/source/frameworks/quickstart.rst
  doc/sphinx/source/introduction.rst
  doc/sphinx/source/sitemap.rst
Labels: Fully Reviewed

#4324 Change attributes to int64_t
  src/ngraph/op/deformable_convolution.cpp
  src/ngraph/op/deformable_convolution.hpp
Labels: Fully Reviewed

#4104 [MLIR] MatMulBias Fused Op support in MlIR
  src/contrib/mlir/CMakeLists.txt
  src/contrib/mlir/core/compiler.cpp
  src/contrib/mlir/core/compiler.hpp
  src/contrib/mlir/core/ngraph_dialect/fused_ops.td
  src/contrib/mlir/core/pass/fused_ops_pattern.td
  src/contrib/mlir/core/pass/ng_dialect_fused_ops.cpp
  src/contrib/mlir/core/pass/ng_dialect_fused_ops.hpp
  test/cpu_fusion.cpp
  test/mlir/ngraph_dialect/pattern/fused_ops.mlir
Labels: Fully Reviewed, IntelCPU, MLIR

#4294 Fix some warnings
  src/ngraph/op/constant.hpp
  src/ngraph/pass/constant_folding_one_hot.cpp
Labels: Fully Reviewed

#4310 [ONNX] ONNX importer tests refactor
  test/onnx/onnx_import.in.cpp
  test/onnx/onnx_import_convpool.in.cpp
  test/onnx/onnx_import_quant.in.cpp
  test/onnx/onnx_import_reshape.in.cpp
Labels: Fully Reviewed, ONNX

#4338 Fixed memory blob
  test/util/backend_utils.cpp
  test/util/backend_utils.hpp
Labels: Fully Reviewed

#4326 AlgebraicSimplification simplification
  src/ngraph/pass/algebraic_simplification.cpp
  test/algebraic_simplification.cpp
Labels: Fully Reviewed

#4328 Add constant folding for Tile.
  src/ngraph/CMakeLists.txt
  src/ngraph/pass/constant_folding.hpp
  src/ngraph/pass/constant_folding_tile.cpp
  src/ngraph/runtime/reference/tile.hpp
  test/constant_folding.cpp
Labels: Fully Reviewed

#4298 POC enabling Resnet50 with dynamic batch dimension
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/reduce.cpp
  src/ngraph/frontend/onnx_import/op/reshape.cpp
  src/ngraph/frontend/onnx_import/op/shape.cpp
  src/ngraph/frontend/onnx_import/op/softmax.cpp
  src/ngraph/frontend/onnx_import/op/squeeze.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.cpp
  src/ngraph/frontend/onnx_import/utils/reduction.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/dynamic_shapes/conv_with_dynamic_batch.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/type_prop/broadcast.cpp
Labels: Fully Reviewed, ONNX

#4333 Update ONNX OneHot to produce v1 ops only
  src/ngraph/frontend/onnx_import/op/onehot.cpp
Labels: Fully Reviewed, ONNX

#4337 [MLIR] Fix warning: variable used uninitialized.
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
Labels: Fully Reviewed

#4242 Unify (static) auto-broadcasting helpers.
  src/ngraph/CMakeLists.txt
  src/ngraph/builder/autobroadcast.cpp
  src/ngraph/builder/autobroadcast.hpp
  src/ngraph/builder/matmul_factory.cpp
  src/ngraph/frontend/onnx_import/op/add.cpp
  src/ngraph/frontend/onnx_import/op/conv.cpp
  src/ngraph/frontend/onnx_import/op/conv_transpose.cpp
  src/ngraph/frontend/onnx_import/op/div.hpp
  src/ngraph/frontend/onnx_import/op/expand.cpp
  src/ngraph/frontend/onnx_import/op/greater.hpp
  src/ngraph/frontend/onnx_import/op/instance_norm.cpp
  src/ngraph/frontend/onnx_import/op/less.hpp
  src/ngraph/frontend/onnx_import/op/min.hpp
  src/ngraph/frontend/onnx_import/op/mul.hpp
  src/ngraph/frontend/onnx_import/op/pow.hpp
  src/ngraph/frontend/onnx_import/op/softsign.cpp
  src/ngraph/frontend/onnx_import/op/sub.hpp
  src/ngraph/frontend/onnx_import/op/sum.hpp
  src/ngraph/frontend/onnx_import/op/xor.hpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/variadic.hpp
  src/ngraph/op/broadcast.cpp
  src/ngraph/op/fused/crossentropy.cpp
  src/ngraph/op/fused/elu.cpp
  src/ngraph/op/fused/fake_quantize.cpp
  src/ngraph/op/fused/gemm.cpp
  src/ngraph/op/fused/layer_norm.cpp
  src/ngraph/op/fused/lstm_sequence.cpp
  src/ngraph/op/fused/mvn.cpp
  src/ngraph/op/fused/normalize_l2.cpp
  src/ngraph/op/fused/prelu.cpp
  src/ngraph/op/fused/scale_shift.cpp
  src/ngraph/op/fused/softmax_crossentropy.cpp
  src/ngraph/op/fused/squared_difference.cpp
  src/ngraph/op/util/broadcasting.cpp
  src/ngraph/op/util/broadcasting.hpp
  src/ngraph/op/util/rnn_cell_base.cpp
  src/ngraph/pass/implicit_broadcast_elimination.cpp
  src/ngraph/pass/implicit_broadcast_elimination.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/pass/opset1_upgrade.cpp
  test/builder_autobroadcast.cpp
Labels: Fully Reviewed

#4356 MSVC build error in ONNX OneHot
  src/ngraph/frontend/onnx_import/op/onehot.cpp
Labels: Fully Reviewed

#4316 Update MKLDNN to v1.2.
  cmake/external_mkldnn_v1.cmake
  src/ngraph/runtime/cpu/cpu_runtime_context.hpp
  src/ngraph/runtime/cpu/pass/cpu_mkldnn_primitive_build.hpp
Labels: Fully Reviewed

#4303 Add Round op to ONNX importer
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/round.cpp
  src/ngraph/frontend/onnx_import/op/round.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  test/models/onnx/round.prototxt
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#4285 [ONNX] Add dynamic shapes support for pooling ops
  src/ngraph/frontend/onnx_import/op/average_pool.cpp
  src/ngraph/frontend/onnx_import/op/max_pool.cpp
  src/ngraph/frontend/onnx_import/op/pad.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.cpp
  src/ngraph/frontend/onnx_import/utils/convpool.hpp
  src/ngraph/frontend/onnx_import/utils/pooling_factory.cpp
  src/ngraph/frontend/onnx_import/utils/pooling_factory.hpp
  test/models/onnx/dynamic_shapes/average_pool_2d_dyn.prototxt
  test/models/onnx/dynamic_shapes/global_average_pool_dyn.prototxt
  test/models/onnx/dynamic_shapes/global_max_pool_dyn.prototxt
  test/models/onnx/dynamic_shapes/max_pool_2d_dyn.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
Labels: Dynamic Shape, Fully Reviewed, ONNX

#4335 [MLIR] Update MLIR repo
  cmake/external_mlir.cmake
  src/contrib/mlir/backend/analysis/memory_analysis.cpp
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/core/pass/ng_dialect_fused_ops.cpp
  src/contrib/mlir/runtime/cpu/cpu_callbacks.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/tools/ngraph-opt/CMakeLists.txt
  src/contrib/mlir/utils.cpp
  test/mlir/affine_conversion/callback_ops.mlir
Labels: Fully Reviewed

#4351 Fixed matcher
  src/ngraph/pattern/matcher.cpp
Labels: Fully Reviewed, High Priority

#4352 avoid error tautological-constant-out-of-range-compare
  src/ngraph/op/gather.cpp
Labels: DO NOT SQUASH, Fully Reviewed, High Priority, fork

#4311 [ONNX] builder::split used by onnx importer should produce v1 ops
  src/ngraph/builder/split.cpp
  src/ngraph/builder/split.hpp
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/lstm.cpp
  src/ngraph/frontend/onnx_import/op/pad.cpp
  src/ngraph/frontend/onnx_import/op/split.cpp
  src/ngraph/frontend/onnx_import/utils/common.cpp
  src/ngraph/frontend/onnx_import/utils/common.hpp
  src/ngraph/frontend/onnx_import/utils/pooling_factory.hpp
  src/ngraph/runtime/gpu/gpu_compiled_function.cpp
Labels: Fully Reviewed, ONNX

#4336 [MLIR] Enable bare ptr calling convention
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/backend/pass/affine_lowerer.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.cpp
  src/contrib/mlir/runtime/cpu/cpu_runtime.hpp
  test/mlir/affine_conversion/bare_ptr_call_conv.mlir
Labels: Fully Reviewed

#4359 Change ONNX LeakyReLU to use PReLU op
  src/ngraph/frontend/onnx_import/op/leaky_relu.cpp
Labels: Fully Reviewed, ONNX

#4371 If version cannot be determined, set it to v0.0.0
  cmake/Modules/git_tags.cmake
Labels: Bug, Fully Reviewed

#4361 GPU transformer cleanup
  src/ngraph/runtime/gpu/CMakeLists.txt
  src/ngraph/runtime/gpu/gpu_backend.cpp
  src/ngraph/runtime/gpu/gpu_backend.hpp
  src/ngraph/runtime/gpu/gpu_compiled_function.cpp
  src/ngraph/runtime/gpu/gpu_compiled_function.hpp
  src/ngraph/runtime/gpu/gpu_executable.cpp
  src/ngraph/runtime/gpu/gpu_executable.hpp
  src/ngraph/runtime/gpu/gpu_external_function.cpp
  src/ngraph/runtime/gpu/gpu_external_function.hpp
  src/ngraph/runtime/gpu/gpu_internal_function.cpp
  src/ngraph/runtime/gpu/gpu_internal_function.hpp
Labels: Fully Reviewed

#4345 [ONNX] Change constants' target shape to scalar shape
  src/ngraph/frontend/onnx_import/op/leaky_relu.cpp
  src/ngraph/frontend/onnx_import/op/mean.cpp
  src/ngraph/frontend/onnx_import/op/reciprocal.cpp
  src/ngraph/frontend/onnx_import/op/selu.cpp
  src/ngraph/frontend/onnx_import/op/shrink.cpp
  src/ngraph/frontend/onnx_import/op/softplus.cpp
  src/ngraph/frontend/onnx_import/op/softsign.cpp
  src/ngraph/frontend/onnx_import/op/thresholded_relu.cpp
Labels: Fully Reviewed, ONNX

#4245 [ONNX] Add new ConstantOfShape operator
  src/ngraph/frontend/onnx_import/CMakeLists.txt
  src/ngraph/frontend/onnx_import/op/constant_of_shape.cpp
  src/ngraph/frontend/onnx_import/op/constant_of_shape.hpp
  src/ngraph/frontend/onnx_import/ops_bridge.cpp
  src/ngraph/pass/opset0_downgrade.cpp
  test/models/onnx/dynamic_shapes/constant_of_shape_float_zeros.prototxt
  test/models/onnx/dynamic_shapes/constant_of_shape_int_ones.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
Labels: Fully Reviewed, ONNX

#4357 Add friendly names to nGraph nodes generated from ONNX
  src/ngraph/frontend/onnx_import/core/graph.cpp
  src/ngraph/frontend/onnx_import/core/graph.hpp
  test/onnx/onnx_import.in.cpp
Labels: Fully Reviewed, ONNX

#4341 FQ output data type copied from 3,4 input data type
  src/ngraph/op/fused/fake_quantize.cpp
Labels: Fully Reviewed

#4370 Defining opset2
  src/ngraph/opsets/opset.cpp
  src/ngraph/opsets/opset.hpp
  src/ngraph/opsets/opset2.hpp
  src/ngraph/opsets/opset2_tbl.hpp
Labels: Fully Reviewed

#4376 Fix DepthToSpace in op_tbl
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/serializer.cpp
Labels: Fully Reviewed

#4378 Revert "FQ output data type copied from 3,4 input data type"
  src/ngraph/op/fused/fake_quantize.cpp
Labels: Fully Reviewed

#4330 Start finishing cloning with outputs
  src/ngraph/node.cpp
  src/ngraph/node.hpp
  src/ngraph/op/abs.cpp
  src/ngraph/op/abs.hpp
  src/ngraph/op/acos.cpp
  src/ngraph/op/acos.hpp
  src/ngraph/op/get_output_element.cpp
  src/ngraph/op/get_output_element.hpp
  test/copy.cpp
Labels: Fully Reviewed

#4362 [MLIR] Add a flag to control ngraph dialect fusion pass.
  src/contrib/mlir/core/compiler.cpp
Labels: Fully Reviewed, MLIR

#4354 [ONNX] norm builders should produce v1 ops
  src/ngraph/builder/norm.cpp
  src/ngraph/builder/norm.hpp
  src/ngraph/frontend/onnx_import/op/lp_norm.cpp
  src/ngraph/frontend/onnx_import/op/lp_pool.cpp
  src/ngraph/frontend/onnx_import/op/reduce.hpp
  src/ngraph/op/fused/grn.cpp
  src/ngraph/op/fused/normalize_l2.cpp
  test/provenance.cpp
Labels: Fully Reviewed, ONNX

#4373 Add set_config option to python backend
  python/ngraph/runtime.py
  python/pyngraph/runtime/backend.cpp
  python/test/ngraph/test_basic.py
Labels: Fully Reviewed

#4368 [ONNX] Replace arithmetic operators and builders into v1 ops
  src/ngraph/builder/reduce_ops.cpp
  src/ngraph/builder/reduce_ops.hpp
  src/ngraph/frontend/onnx_import/op/instance_norm.cpp
Labels: Fully Reviewed, ONNX

#4379 [ONNX] Add dynamic shapes support for expand op
  src/ngraph/frontend/onnx_import/op/expand.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/dynamic_shapes/expand_dyn.prototxt
  test/models/onnx/dynamic_shapes/expand_uint16_dyn.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
Labels: Dynamic Shape, Fully Reviewed, ONNX

#4382 Remove Fluid helper function.
  CODEOWNERS
  src/ngraph/frontend/CMakeLists.txt
  src/ngraph/frontend/fluid/CMakeLists.txt
  src/ngraph/frontend/fluid/README.md
  src/ngraph/frontend/fluid/operators/layout_converter.cpp
  src/ngraph/frontend/fluid/operators/layout_converter.hpp
  src/ngraph/frontend/fluid/operators/lookup_table.cpp
  src/ngraph/frontend/fluid/operators/lookup_table.hpp
  src/ngraph/frontend/fluid/operators/matmul.cpp
  src/ngraph/frontend/fluid/operators/matmul.hpp
  src/ngraph/frontend/fluid/operators/pool.cpp
  src/ngraph/frontend/fluid/operators/pool.hpp
  src/ngraph/frontend/fluid/operators/reduce_sum.cpp
  src/ngraph/frontend/fluid/operators/reduce_sum.hpp
  src/ngraph/frontend/fluid/operators/test/CMakeLists.txt
  src/ngraph/frontend/fluid/operators/test/lookup_table.cpp
  src/ngraph/frontend/fluid/operators/test/main.cpp
  src/ngraph/frontend/fluid/operators/test/reduce_sum.cpp
  src/ngraph/frontend/fluid/operators/test/test.manifest
Labels: Fully Reviewed

#4383 Becky/dldt custom build
  cmake/Modules/git_tags.cmake
Labels: Fully Reviewed

#4367 [Fused] Add BatchToSpace, SpaceToBatch ops
  src/ngraph/CMakeLists.txt
  src/ngraph/op/fused/batch_to_space.cpp
  src/ngraph/op/fused/batch_to_space.hpp
  src/ngraph/op/fused/space_to_batch.cpp
  src/ngraph/op/fused/space_to_batch.hpp
  src/ngraph/op/op_version_tbl.hpp
  src/ngraph/ops.hpp
  src/ngraph/opsets/opset2_tbl.hpp
  src/ngraph/pass/opset0_downgrade.cpp
  src/ngraph/runtime/gpu/gpu_emitter.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/serializer.cpp
  test/CMakeLists.txt
  test/backend/fused_op.in.cpp
  test/type_prop/batch_to_space.cpp
  test/type_prop/space_to_batch.cpp
Labels: Fully Reviewed, High Priority

#4387 Add attribute visitor to Gelu op
  src/ngraph/op/fused/gelu.cpp
  src/ngraph/op/fused/gelu.hpp
Labels: Fully Reviewed, High Priority

#4291 [SPEC][ONNX] Handle negative axis for TopK:v1, add dynamic shape support for ONNX Arg Min/Max ops
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.cpp
  src/ngraph/frontend/onnx_import/utils/arg_min_max_factory.hpp
  src/ngraph/op/topk.cpp
  src/ngraph/op/topk.hpp
  src/ngraph/runtime/gpu/unit_test.manifest
  src/ngraph/runtime/plaidml/unit_test.manifest
  src/ngraph/serializer.cpp
  test/models/onnx/dynamic_shapes/argmax_dyn.prototxt
  test/models/onnx/dynamic_shapes/argmin_no_keep_dims_dyn.prototxt
  test/onnx/onnx_import_dyn_shapes.in.cpp
  test/type_prop/top_k.cpp
Labels: Dynamic Shape, Fully Reviewed

#4380 Remove distributed implementations
  CMakeLists.txt
  cmake/external_mlsl.cmake
  contrib/docker/build-ngraph-and-test.sh
  doc/examples/mnist_mlp/CMakeLists.txt
  doc/sphinx/source/inspection/debug_core.rst
  src/ngraph/CMakeLists.txt
  src/ngraph/distributed.cpp
  src/ngraph/distributed/mlsl.hpp
  src/ngraph/distributed/open_mpi.hpp
  test/CMakeLists.txt
  test/backend/distributed.in.cpp
Labels: Fully Reviewed

#4355 [ONNX] Enable boolean tensor type
  src/ngraph/frontend/onnx_import/core/tensor.hpp
  src/ngraph/frontend/onnx_import/op/constant.cpp
  src/ngraph/runtime/gpu/unit_test.manifest
  test/models/onnx/bool_const_op.prototxt
  test/models/onnx/bool_init_and.prototxt
  test/models/onnx/bool_init_raw.prototxt
  test/models/onnx/bool_input_or.prototxt
  test/onnx/onnx_import.in.cpp
  test/util/test_case.hpp
  test/util/test_tools.cpp
  test/util/test_tools.hpp
Labels: Fully Reviewed, ONNX

#4365 [MLIR] Use sane utilities to handle environment variables.
  src/contrib/mlir/backend/cpu/cpu_backend.cpp
  src/contrib/mlir/core/pass/mlir_subgraph_extraction.cpp
  src/ngraph/runtime/cache.cpp
  src/ngraph/runtime/cpu/cpu_backend.cpp
  src/ngraph/runtime/cpu/cpu_call_frame.cpp
  src/ngraph/runtime/cpu/cpu_debug_tracer.cpp
  src/ngraph/runtime/cpu/cpu_emitter.cpp
  src/ngraph/runtime/cpu/cpu_executor.cpp
  src/ngraph/runtime/cpu/cpu_external_function.cpp
  src/ngraph/runtime/cpu/cpu_tracing.cpp
  src/ngraph/runtime/cpu/pass/cpu_fusion.hpp
  src/ngraph/runtime/cpu/pass/cpu_layout.cpp
  src/ngraph/runtime/gpu/gpu_internal_function.cpp
Labels: Fully Reviewed

#4392 disable rnn test
  src/ngraph/runtime/cpu/unit_test.manifest
Labels: Fully Reviewed

#4393 Handle negative axis in ArithmeticReductionKeepDims
  src/ngraph/op/util/arithmetic_reductions_keep_dims.cpp
Labels: Fully Reviewed
